// Expo config plugin: wire a release signingConfig into android/app/build.gradle
// at prebuild time, without EAS.
//
// Two release keys exist, and the gradle block picks one by name:
//
//   POLLIS_RELEASE_KEY=upload    (default) the Play upload key. Reads
//                                POLLIS_UPLOAD_STORE_FILE / _STORE_PASSWORD /
//                                _KEY_ALIAS / _KEY_PASSWORD (put them in
//                                ~/.gradle/gradle.properties, see
//                                scripts/generate-upload-keystore.sh) and falls
//                                back to the Expo template's debug keystore when
//                                unset, so CI release builds keep working
//                                unchanged.
//   POLLIS_RELEASE_KEY=sideload  the key the pollis.com APK is signed with
//                                (mobile-apk-release.yml). Reads POLLIS_SIDELOAD_*
//                                and has NO fallback: a sideload build that cannot
//                                find its key fails, rather than quietly shipping
//                                a debug-signed or upload-signed APK.
//
// Each key reads only its own prefix. That matters on a workstation whose
// ~/.gradle/gradle.properties holds POLLIS_UPLOAD_*: gradle properties win over
// environment variables, so a design that reused one set of names for both keys
// would sign a "sideload" build with the upload key there.
const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = 'POLLIS_RELEASE_KEY';

const RELEASE_SIGNING_CONFIG = `        release {
            // Injected by plugins/withReleaseSigning.js. POLLIS_RELEASE_KEY picks
            // the key (upload | sideload); each reads only its own POLLIS_<KEY>_*
            // gradle/env properties. Only the upload key falls back to debug.
            def pollisKey = (project.findProperty('POLLIS_RELEASE_KEY') ?: System.getenv('POLLIS_RELEASE_KEY') ?: 'upload').toString().toUpperCase()
            if (!(pollisKey in ['UPLOAD', 'SIDELOAD'])) {
                throw new GradleException("POLLIS_RELEASE_KEY must be upload or sideload, got " + pollisKey)
            }
            def pollisProp = { String name -> project.findProperty("POLLIS_" + pollisKey + "_" + name) ?: System.getenv("POLLIS_" + pollisKey + "_" + name) }
            def pollisStoreFile = pollisProp('STORE_FILE')
            if (pollisStoreFile) {
                storeFile file(pollisStoreFile)
                storePassword pollisProp('STORE_PASSWORD')
                keyAlias pollisProp('KEY_ALIAS')
                keyPassword pollisProp('KEY_PASSWORD')
            } else if (pollisKey == 'UPLOAD') {
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            } else {
                throw new GradleException("POLLIS_RELEASE_KEY=" + pollisKey.toLowerCase() + " but POLLIS_" + pollisKey + "_STORE_FILE is unset; refusing to fall back to the debug key")
            }
        }
`;

// The block this plugin injected before the sideload key existed. A prebuild
// over an android/ directory generated by that version swaps it for the current
// one instead of inserting a second `release {}` into signingConfigs.
const LEGACY_RELEASE_SIGNING_CONFIG = `        release {
            // Injected by plugins/withReleaseSigning.js (upload keystore from
            // gradle/env properties; debug keystore fallback when unset).
            def pollisStoreFile = project.findProperty('POLLIS_UPLOAD_STORE_FILE') ?: System.getenv('POLLIS_UPLOAD_STORE_FILE')
            if (pollisStoreFile) {
                storeFile file(pollisStoreFile)
                storePassword project.findProperty('POLLIS_UPLOAD_STORE_PASSWORD') ?: System.getenv('POLLIS_UPLOAD_STORE_PASSWORD')
                keyAlias project.findProperty('POLLIS_UPLOAD_KEY_ALIAS') ?: System.getenv('POLLIS_UPLOAD_KEY_ALIAS')
                keyPassword project.findProperty('POLLIS_UPLOAD_KEY_PASSWORD') ?: System.getenv('POLLIS_UPLOAD_KEY_PASSWORD')
            } else {
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }
`;

function addReleaseSigning(gradle) {
  // Idempotency: if the current block is already present, leave the file alone.
  if (gradle.includes(MARKER)) {
    return gradle;
  }
  if (gradle.includes(LEGACY_RELEASE_SIGNING_CONFIG)) {
    return gradle.replace(LEGACY_RELEASE_SIGNING_CONFIG, RELEASE_SIGNING_CONFIG);
  }
  if (gradle.includes('POLLIS_UPLOAD_STORE_FILE')) {
    throw new Error(
      'withReleaseSigning: android/app/build.gradle carries a hand-edited release signing block; run `expo prebuild -p android --clean`'
    );
  }

  // 1. Add a `release` entry inside `signingConfigs { ... }` (inserting it
  //    directly after the opening brace keeps this independent of whatever
  //    else the template puts in there).
  const signingConfigsRe = /(signingConfigs\s*\{\n)/;
  if (!signingConfigsRe.test(gradle)) {
    throw new Error(
      'withReleaseSigning: could not find `signingConfigs {` in android/app/build.gradle'
    );
  }
  let next = gradle.replace(signingConfigsRe, `$1${RELEASE_SIGNING_CONFIG}`);

  // 2. Point buildTypes.release at signingConfigs.release. The Expo template
  //    ships `signingConfig signingConfigs.debug` inside the release build
  //    type; rewrite only the occurrence inside `buildTypes { ... release {`.
  const buildTypesIdx = next.indexOf('buildTypes');
  if (buildTypesIdx === -1) {
    throw new Error(
      'withReleaseSigning: could not find `buildTypes` in android/app/build.gradle'
    );
  }
  const releaseIdx = next.indexOf('release {', buildTypesIdx);
  if (releaseIdx === -1) {
    throw new Error(
      'withReleaseSigning: could not find the release build type in android/app/build.gradle'
    );
  }
  const debugRefIdx = next.indexOf('signingConfig signingConfigs.debug', releaseIdx);
  if (debugRefIdx === -1) {
    // Already pointing somewhere else (e.g. a re-run on a hand-edited file);
    // the signingConfigs.release block above is still in place.
    return next;
  }
  next =
    next.slice(0, debugRefIdx) +
    'signingConfig signingConfigs.release' +
    next.slice(debugRefIdx + 'signingConfig signingConfigs.debug'.length);
  return next;
}

const withReleaseSigning = (config) => {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        'withReleaseSigning: android/app/build.gradle is not groovy — plugin needs updating'
      );
    }
    config.modResults.contents = addReleaseSigning(config.modResults.contents);
    return config;
  });
};

module.exports = withReleaseSigning;
// Exported for unit-style verification without running prebuild.
module.exports.addReleaseSigning = addReleaseSigning;
