/*
 * plugins/withReleaseSigning.js — the release signingConfig injected into the
 * generated android/app/build.gradle at prebuild.
 *
 * Pinned: the block selects its key by POLLIS_RELEASE_KEY and reads only that
 * key's own POLLIS_<KEY>_* names (so a workstation's POLLIS_UPLOAD_* gradle
 * properties can never sign a sideload build), only the upload key may fall back
 * to the debug keystore, re-running prebuild is idempotent, and an android/
 * directory generated by the previous plugin version is migrated rather than
 * given a second `release {}` block.
 *
 *   cd mobile && pnpm test
 */

import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const { addReleaseSigning } = require("../plugins/withReleaseSigning.js");

const TEMPLATE = `android {
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.debug
        }
    }
}
`;

function count(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

test("injects one release signingConfig and points the release build type at it", () => {
  const out = addReleaseSigning(TEMPLATE);
  assert.equal(count(out, "        release {\n            // Injected by plugins/withReleaseSigning.js"), 1);
  assert.equal(count(out, "signingConfig signingConfigs.release"), 1);
  // The debug build type still signs with the debug key.
  assert.equal(count(out, "signingConfig signingConfigs.debug"), 1);
});

test("each key reads only its own prefix, and only the upload key falls back to debug", () => {
  const out = addReleaseSigning(TEMPLATE);
  assert.match(out, /pollisKey in \['UPLOAD', 'SIDELOAD'\]/);
  assert.match(out, /"POLLIS_" \+ pollisKey \+ "_" \+ name/);
  assert.match(out, /else if \(pollisKey == 'UPLOAD'\) \{\n\s+storeFile file\('debug\.keystore'\)/);
  assert.match(out, /refusing to fall back to the debug key/);
  // No hard-coded upload-key property survives that a sideload build could pick up.
  assert.equal(out.includes("POLLIS_UPLOAD_STORE_FILE"), false);
});

test("re-running is a no-op", () => {
  const once = addReleaseSigning(TEMPLATE);
  assert.equal(addReleaseSigning(once), once);
});

test("a build.gradle from the previous plugin version is migrated in place", () => {
  const legacyBlock = `        release {
            // Injected by plugins/withReleaseSigning.js (upload keystore from
            // gradle/env properties; debug keystore fallback when unset).
            def pollisStoreFile = project.findProperty('POLLIS_UPLOAD_STORE_FILE') ?: System.getenv('POLLIS_UPLOAD_STORE_FILE')
            if (pollisStoreFile) {
                storeFile file(pollisStoreFile)
                storePassword project.findProperty('POLLIS_UPLOAD_STORE_PASSWORD') ?: System.getenv('POLLIS_UPLOAD_STORE_PASSWORD')
                keyAlias project.findProperty('POLLIS_UPLOAD_KEY_ALIAS') ?: System.getenv('POLLIS_UPLOAD_KEY_ALIAS')
                keyPassword project.findProperty('POLLIS_UPLOAD_KEY_PASSWORD') ?: System.getenv('POLLIS_UPLOAD_KEY_PASSWORD')
            } else {
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }
`;
  const legacy = TEMPLATE.replace("    signingConfigs {\n", `    signingConfigs {\n${legacyBlock}`).replace(
    "        release {\n            signingConfig signingConfigs.debug",
    "        release {\n            signingConfig signingConfigs.release",
  );
  const out = addReleaseSigning(legacy);
  assert.equal(out, addReleaseSigning(TEMPLATE));
});
