// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Produced by `scripts/generate-emoji-data.py` from the vendored CLDR emoji
// annotations in scripts/emoji-annotations.json (CLDR release-48). To refresh
// the data, or after adding a locale to i18n/languages.ts:
//
//     python3 scripts/generate-emoji-data.py --refresh-annotations
//
// Locale: es — 1581 entries

import type { EmojiAnnotationRow } from "./index";

const ROWS: readonly EmojiAnnotationRow[] = [
  ["©", "copyright", "c|símbolo"],
  ["®", "marca registrada", "r|símbolo de marca registrada"],
  ["🀄", "dragón rojo de mahjong", "dragón rojo|juego|mahjong"],
  ["🃏", "comodín", "joker"],
  ["🅰", "grupo sanguíneo a", "a|grupo|sanguíneo|tipo a"],
  ["🅱", "grupo sanguíneo b", "b|grupo|sanguíneo|tipo b"],
  ["🅾", "grupo sanguíneo tipo o", "grupo sanguíneo|o"],
  ["🅿", "aparcamiento", "p|parking"],
  ["🆎", "grupo sanguíneo ab", "ab|grupo|sanguíneo|tipo ab"],
  ["🆑", "borrar", "símbolo"],
  ["🆒", "botón cool", "botón|cool|mola"],
  ["🆓", "botón free", "gratis|símbolo gratis"],
  ["🆔", "símbolo de identificación", "id|identidad|símbolo identidad"],
  ["🆕", "botón new", "botón|new|nuevo"],
  ["🆖", "botón ng", "botón|ng|nuevo"],
  ["🆗", "botón ok", "botón|ok"],
  ["🆘", "símbolo de socorro", "ayuda|símbolo|socorro|sos"],
  ["🆙", "botón up!", "arriba|información|novedad|símbolo|up"],
  ["🆚", "botón vs", "contra|frente a|símbolo|versus|vs"],
  ["🇦🇩", "bandera: andorra", "bandera"],
  ["🇦🇪", "bandera: emiratos árabes unidos", "bandera"],
  ["🇦🇫", "bandera: afganistán", "bandera"],
  ["🇦🇬", "bandera: antigua y barbuda", "bandera"],
  ["🇦🇮", "bandera: anguila", "bandera"],
  ["🇦🇱", "bandera: albania", "bandera"],
  ["🇦🇲", "bandera: armenia", "bandera"],
  ["🇦🇴", "bandera: angola", "bandera"],
  ["🇦🇶", "bandera: antártida", "bandera"],
  ["🇦🇷", "bandera: argentina", "bandera"],
  ["🇦🇸", "bandera: samoa americana", "bandera"],
  ["🇦🇹", "bandera: austria", "bandera"],
  ["🇦🇺", "bandera: australia", "bandera"],
  ["🇦🇼", "bandera: aruba", "bandera"],
  ["🇦🇽", "bandera: islas aland", "bandera"],
  ["🇦🇿", "bandera: azerbaiyán", "bandera"],
  ["🇧🇦", "bandera: bosnia y herzegovina", "bandera"],
  ["🇧🇧", "bandera: barbados", "bandera"],
  ["🇧🇩", "bandera: bangladés", "bandera"],
  ["🇧🇪", "bandera: bélgica", "bandera"],
  ["🇧🇫", "bandera: burkina faso", "bandera"],
  ["🇧🇬", "bandera: bulgaria", "bandera"],
  ["🇧🇭", "bandera: baréin", "bandera"],
  ["🇧🇮", "bandera: burundi", "bandera"],
  ["🇧🇯", "bandera: benín", "bandera"],
  ["🇧🇱", "bandera: san bartolomé", "bandera"],
  ["🇧🇲", "bandera: bermudas", "bandera"],
  ["🇧🇳", "bandera: brunéi", "bandera"],
  ["🇧🇴", "bandera: bolivia", "bandera"],
  ["🇧🇶", "bandera: caribe neerlandés", "bandera"],
  ["🇧🇷", "bandera: brasil", "bandera"],
  ["🇧🇸", "bandera: bahamas", "bandera"],
  ["🇧🇹", "bandera: bután", "bandera"],
  ["🇧🇻", "bandera: isla bouvet", "bandera"],
  ["🇧🇼", "bandera: botsuana", "bandera"],
  ["🇧🇾", "bandera: bielorrusia", "bandera"],
  ["🇧🇿", "bandera: belice", "bandera"],
  ["🇨🇦", "bandera: canadá", "bandera"],
  ["🇨🇨", "bandera: islas cocos", "bandera"],
  ["🇨🇩", "bandera: república democrática del congo", "bandera"],
  ["🇨🇫", "bandera: república centroafricana", "bandera"],
  ["🇨🇬", "bandera: congo", "bandera"],
  ["🇨🇭", "bandera: suiza", "bandera"],
  ["🇨🇮", "bandera: côte d’ivoire", "bandera"],
  ["🇨🇰", "bandera: islas cook", "bandera"],
  ["🇨🇱", "bandera: chile", "bandera"],
  ["🇨🇲", "bandera: camerún", "bandera"],
  ["🇨🇳", "bandera: china", "bandera"],
  ["🇨🇴", "bandera: colombia", "bandera"],
  ["🇨🇷", "bandera: costa rica", "bandera"],
  ["🇨🇺", "bandera: cuba", "bandera"],
  ["🇨🇻", "bandera: cabo verde", "bandera"],
  ["🇨🇼", "bandera: curazao", "bandera"],
  ["🇨🇽", "bandera: isla de navidad", "bandera"],
  ["🇨🇾", "bandera: chipre", "bandera"],
  ["🇨🇿", "bandera: chequia", "bandera"],
  ["🇩🇪", "bandera: alemania", "bandera"],
  ["🇩🇯", "bandera: yibuti", "bandera"],
  ["🇩🇰", "bandera: dinamarca", "bandera"],
  ["🇩🇲", "bandera: dominica", "bandera"],
  ["🇩🇴", "bandera: república dominicana", "bandera"],
  ["🇩🇿", "bandera: argelia", "bandera"],
  ["🇪🇨", "bandera: ecuador", "bandera"],
  ["🇪🇪", "bandera: estonia", "bandera"],
  ["🇪🇬", "bandera: egipto", "bandera"],
  ["🇪🇭", "bandera: sáhara occidental", "bandera"],
  ["🇪🇷", "bandera: eritrea", "bandera"],
  ["🇪🇸", "bandera: españa", "bandera"],
  ["🇪🇹", "bandera: etiopía", "bandera"],
  ["🇫🇮", "bandera: finlandia", "bandera"],
  ["🇫🇯", "bandera: fiyi", "bandera"],
  ["🇫🇰", "bandera: islas malvinas", "bandera"],
  ["🇫🇲", "bandera: micronesia", "bandera"],
  ["🇫🇴", "bandera: islas feroe", "bandera"],
  ["🇫🇷", "bandera: francia", "bandera"],
  ["🇬🇦", "bandera: gabón", "bandera"],
  ["🇬🇧", "bandera: reino unido", "bandera"],
  ["🇬🇩", "bandera: granada", "bandera"],
  ["🇬🇪", "bandera: georgia", "bandera"],
  ["🇬🇫", "bandera: guayana francesa", "bandera"],
  ["🇬🇬", "bandera: guernesey", "bandera"],
  ["🇬🇭", "bandera: ghana", "bandera"],
  ["🇬🇮", "bandera: gibraltar", "bandera"],
  ["🇬🇱", "bandera: groenlandia", "bandera"],
  ["🇬🇲", "bandera: gambia", "bandera"],
  ["🇬🇳", "bandera: guinea", "bandera"],
  ["🇬🇵", "bandera: guadalupe", "bandera"],
  ["🇬🇶", "bandera: guinea ecuatorial", "bandera"],
  ["🇬🇷", "bandera: grecia", "bandera"],
  ["🇬🇸", "bandera: islas georgia del sur y sandwich del sur", "bandera"],
  ["🇬🇹", "bandera: guatemala", "bandera"],
  ["🇬🇺", "bandera: guam", "bandera"],
  ["🇬🇼", "bandera: guinea-bisáu", "bandera"],
  ["🇬🇾", "bandera: guyana", "bandera"],
  ["🇭🇰", "bandera: rae de hong kong (china)", "bandera"],
  ["🇭🇲", "bandera: islas heard y mcdonald", "bandera"],
  ["🇭🇳", "bandera: honduras", "bandera"],
  ["🇭🇷", "bandera: croacia", "bandera"],
  ["🇭🇹", "bandera: haití", "bandera"],
  ["🇭🇺", "bandera: hungría", "bandera"],
  ["🇮🇩", "bandera: indonesia", "bandera"],
  ["🇮🇪", "bandera: irlanda", "bandera"],
  ["🇮🇱", "bandera: israel", "bandera"],
  ["🇮🇲", "bandera: isla de man", "bandera"],
  ["🇮🇳", "bandera: india", "bandera"],
  ["🇮🇴", "bandera: territorio británico del océano índico", "bandera"],
  ["🇮🇶", "bandera: irak", "bandera"],
  ["🇮🇷", "bandera: irán", "bandera"],
  ["🇮🇸", "bandera: islandia", "bandera"],
  ["🇮🇹", "bandera: italia", "bandera"],
  ["🇯🇪", "bandera: jersey", "bandera"],
  ["🇯🇲", "bandera: jamaica", "bandera"],
  ["🇯🇴", "bandera: jordania", "bandera"],
  ["🇯🇵", "bandera: japón", "bandera"],
  ["🇰🇪", "bandera: kenia", "bandera"],
  ["🇰🇬", "bandera: kirguistán", "bandera"],
  ["🇰🇭", "bandera: camboya", "bandera"],
  ["🇰🇮", "bandera: kiribati", "bandera"],
  ["🇰🇲", "bandera: comoras", "bandera"],
  ["🇰🇳", "bandera: san cristóbal y nieves", "bandera"],
  ["🇰🇵", "bandera: corea del norte", "bandera"],
  ["🇰🇷", "bandera: corea del sur", "bandera"],
  ["🇰🇼", "bandera: kuwait", "bandera"],
  ["🇰🇾", "bandera: islas caimán", "bandera"],
  ["🇰🇿", "bandera: kazajistán", "bandera"],
  ["🇱🇦", "bandera: laos", "bandera"],
  ["🇱🇧", "bandera: líbano", "bandera"],
  ["🇱🇨", "bandera: santa lucía", "bandera"],
  ["🇱🇮", "bandera: liechtenstein", "bandera"],
  ["🇱🇰", "bandera: sri lanka", "bandera"],
  ["🇱🇷", "bandera: liberia", "bandera"],
  ["🇱🇸", "bandera: lesoto", "bandera"],
  ["🇱🇹", "bandera: lituania", "bandera"],
  ["🇱🇺", "bandera: luxemburgo", "bandera"],
  ["🇱🇻", "bandera: letonia", "bandera"],
  ["🇱🇾", "bandera: libia", "bandera"],
  ["🇲🇦", "bandera: marruecos", "bandera"],
  ["🇲🇨", "bandera: mónaco", "bandera"],
  ["🇲🇩", "bandera: moldavia", "bandera"],
  ["🇲🇪", "bandera: montenegro", "bandera"],
  ["🇲🇫", "bandera: san martín", "bandera"],
  ["🇲🇬", "bandera: madagascar", "bandera"],
  ["🇲🇭", "bandera: islas marshall", "bandera"],
  ["🇲🇰", "bandera: macedonia del norte", "bandera"],
  ["🇲🇱", "bandera: mali", "bandera"],
  ["🇲🇲", "bandera: myanmar (birmania)", "bandera"],
  ["🇲🇳", "bandera: mongolia", "bandera"],
  ["🇲🇴", "bandera: rae de macao (china)", "bandera"],
  ["🇲🇵", "bandera: islas marianas del norte", "bandera"],
  ["🇲🇶", "bandera: martinica", "bandera"],
  ["🇲🇷", "bandera: mauritania", "bandera"],
  ["🇲🇸", "bandera: montserrat", "bandera"],
  ["🇲🇹", "bandera: malta", "bandera"],
  ["🇲🇺", "bandera: mauricio", "bandera"],
  ["🇲🇻", "bandera: maldivas", "bandera"],
  ["🇲🇼", "bandera: malaui", "bandera"],
  ["🇲🇽", "bandera: méxico", "bandera"],
  ["🇲🇾", "bandera: malasia", "bandera"],
  ["🇲🇿", "bandera: mozambique", "bandera"],
  ["🇳🇦", "bandera: namibia", "bandera"],
  ["🇳🇨", "bandera: nueva caledonia", "bandera"],
  ["🇳🇪", "bandera: níger", "bandera"],
  ["🇳🇫", "bandera: isla norfolk", "bandera"],
  ["🇳🇬", "bandera: nigeria", "bandera"],
  ["🇳🇮", "bandera: nicaragua", "bandera"],
  ["🇳🇱", "bandera: países bajos", "bandera"],
  ["🇳🇴", "bandera: noruega", "bandera"],
  ["🇳🇵", "bandera: nepal", "bandera"],
  ["🇳🇷", "bandera: nauru", "bandera"],
  ["🇳🇺", "bandera: niue", "bandera"],
  ["🇳🇿", "bandera: nueva zelanda", "bandera"],
  ["🇴🇲", "bandera: omán", "bandera"],
  ["🇵🇦", "bandera: panamá", "bandera"],
  ["🇵🇪", "bandera: perú", "bandera"],
  ["🇵🇫", "bandera: polinesia francesa", "bandera"],
  ["🇵🇬", "bandera: papúa nueva guinea", "bandera"],
  ["🇵🇭", "bandera: filipinas", "bandera"],
  ["🇵🇰", "bandera: pakistán", "bandera"],
  ["🇵🇱", "bandera: polonia", "bandera"],
  ["🇵🇲", "bandera: san pedro y miquelón", "bandera"],
  ["🇵🇳", "bandera: islas pitcairn", "bandera"],
  ["🇵🇷", "bandera: puerto rico", "bandera"],
  ["🇵🇸", "bandera: territorios palestinos", "bandera"],
  ["🇵🇹", "bandera: portugal", "bandera"],
  ["🇵🇼", "bandera: palaos", "bandera"],
  ["🇵🇾", "bandera: paraguay", "bandera"],
  ["🇶🇦", "bandera: catar", "bandera"],
  ["🇷🇪", "bandera: reunión", "bandera"],
  ["🇷🇴", "bandera: rumanía", "bandera"],
  ["🇷🇸", "bandera: serbia", "bandera"],
  ["🇷🇺", "bandera: rusia", "bandera"],
  ["🇷🇼", "bandera: ruanda", "bandera"],
  ["🇸🇦", "bandera: arabia saudí", "bandera"],
  ["🇸🇧", "bandera: islas salomón", "bandera"],
  ["🇸🇨", "bandera: seychelles", "bandera"],
  ["🇸🇩", "bandera: sudán", "bandera"],
  ["🇸🇪", "bandera: suecia", "bandera"],
  ["🇸🇬", "bandera: singapur", "bandera"],
  ["🇸🇭", "bandera: santa elena", "bandera"],
  ["🇸🇮", "bandera: eslovenia", "bandera"],
  ["🇸🇯", "bandera: svalbard y jan mayen", "bandera"],
  ["🇸🇰", "bandera: eslovaquia", "bandera"],
  ["🇸🇱", "bandera: sierra leona", "bandera"],
  ["🇸🇲", "bandera: san marino", "bandera"],
  ["🇸🇳", "bandera: senegal", "bandera"],
  ["🇸🇴", "bandera: somalia", "bandera"],
  ["🇸🇷", "bandera: surinam", "bandera"],
  ["🇸🇸", "bandera: sudán del sur", "bandera"],
  ["🇸🇹", "bandera: santo tomé y príncipe", "bandera"],
  ["🇸🇻", "bandera: el salvador", "bandera"],
  ["🇸🇽", "bandera: sint maarten", "bandera"],
  ["🇸🇾", "bandera: siria", "bandera"],
  ["🇸🇿", "bandera: esuatini", "bandera"],
  ["🇹🇨", "bandera: islas turcas y caicos", "bandera"],
  ["🇹🇩", "bandera: chad", "bandera"],
  ["🇹🇫", "bandera: territorios australes franceses", "bandera"],
  ["🇹🇬", "bandera: togo", "bandera"],
  ["🇹🇭", "bandera: tailandia", "bandera"],
  ["🇹🇯", "bandera: tayikistán", "bandera"],
  ["🇹🇰", "bandera: tokelau", "bandera"],
  ["🇹🇱", "bandera: timor-leste", "bandera"],
  ["🇹🇲", "bandera: turkmenistán", "bandera"],
  ["🇹🇳", "bandera: túnez", "bandera"],
  ["🇹🇴", "bandera: tonga", "bandera"],
  ["🇹🇷", "bandera: turquía", "bandera"],
  ["🇹🇹", "bandera: trinidad y tobago", "bandera"],
  ["🇹🇻", "bandera: tuvalu", "bandera"],
  ["🇹🇼", "bandera: taiwán", "bandera"],
  ["🇹🇿", "bandera: tanzania", "bandera"],
  ["🇺🇦", "bandera: ucrania", "bandera"],
  ["🇺🇬", "bandera: uganda", "bandera"],
  ["🇺🇲", "bandera: islas menores alejadas de ee. uu.", "bandera"],
  ["🇺🇸", "bandera: estados unidos", "bandera"],
  ["🇺🇾", "bandera: uruguay", "bandera"],
  ["🇺🇿", "bandera: uzbekistán", "bandera"],
  ["🇻🇦", "bandera: ciudad del vaticano", "bandera"],
  ["🇻🇨", "bandera: san vicente y las granadinas", "bandera"],
  ["🇻🇪", "bandera: venezuela", "bandera"],
  ["🇻🇬", "bandera: islas vírgenes británicas", "bandera"],
  ["🇻🇮", "bandera: islas vírgenes de ee. uu.", "bandera"],
  ["🇻🇳", "bandera: vietnam", "bandera"],
  ["🇻🇺", "bandera: vanuatu", "bandera"],
  ["🇼🇫", "bandera: wallis y futuna", "bandera"],
  ["🇼🇸", "bandera: samoa", "bandera"],
  ["🇾🇪", "bandera: yemen", "bandera"],
  ["🇾🇹", "bandera: mayotte", "bandera"],
  ["🇿🇦", "bandera: sudáfrica", "bandera"],
  ["🇿🇲", "bandera: zambia", "bandera"],
  ["🇿🇼", "bandera: zimbabue", "bandera"],
  ["🈁", "ideograma japonés para \"aquí\"", "“aquí”|japonés|katakana"],
  ["🈂", "ideograma japonés para \"de cortesía\"", "cortesía|japonés|katakana"],
  ["🈚", "ideograma japonés para \"gratis\"", "gratis|ideograma|japonés|kanji"],
  ["🈯", "ideograma japonés para \"reservado\"", "ideograma|japonés|kanji|reservado"],
  ["🈲", "ideograma japonés para \"prohibido\"", "ideograma|japonés|kanji|prohibido"],
  ["🈳", "ideograma japonés para \"vacante\"", "ideograma|japonés|kanji|vacante"],
  ["🈴", "ideograma japonés para \"aprobado\"", "aprobado|ideograma|japonés|kanji"],
  ["🈵", "ideograma japonés para \"completo\"", "completo|ideograma|japonés|kanji|lleno"],
  ["🈶", "ideograma japonés para \"de pago\"", "“de pago”|ideograma|japonés|kanji"],
  ["🈷", "ideograma japonés para \"cantidad mensual\"", "“cantidad mensual”|ideograma|japonés|kanji"],
  ["🈸", "ideograma japonés para \"aplicación\"", "aplicación|ideograma|japonés|kanji"],
  ["🈹", "ideograma japonés para \"descuento\"", "descuento|ideograma|japonés|kanji"],
  ["🈺", "ideograma japonés para \"abierto\"", "abierto|ideograma|japonés|kanji"],
  ["🉐", "ideograma japonés para \"ganga\"", "ganga|ideograma|japonés|kanji"],
  ["🉑", "ideograma japonés para \"aceptable\"", "aceptable|ideograma|japonés|kanji"],
  ["🌀", "ciclón", "mareo|tifón|tornado"],
  ["🌁", "bruma", "niebla"],
  ["🌂", "paraguas cerrado", "accesorios|lluvia|paraguas"],
  ["🌃", "noche estrellada", "estrellas|noche"],
  ["🌄", "amanecer sobre montañas", "amanecer|montaña|salida|sol"],
  ["🌅", "amanecer", "salida del sol"],
  ["🌆", "ciudad al atardecer", "atardecer|ciudad|edificios|paisaje"],
  ["🌇", "puesta del sol", "edificios"],
  ["🌈", "arcoíris", "colores|lluvia"],
  ["🌉", "puente de noche", "noche|puente"],
  ["🌊", "ola de mar", "mar|océano|ola"],
  ["🌋", "volcán", "erupción|erupción volcánica"],
  ["🌌", "vía láctea", "espacio|galaxia|láctea|vía"],
  ["🌍", "globo terráqueo mostrando europa y áfrica", "áfrica|europa|mundo|planeta|tierra"],
  ["🌎", "globo terráqueo mostrando américa", "américa|globo|mundo|planeta|tierra"],
  ["🌏", "globo terráqueo mostrando asia y australia", "asia|australia|mundo|planeta|tierra"],
  ["🌐", "globo terráqueo con meridianos", "globo|meridianos|mundo|tierra"],
  ["🌑", "luna nueva", "luna|oscuridad"],
  ["🌒", "luna creciente", "creciente|cuarto|espacio|luna"],
  ["🌓", "luna en cuarto creciente", "creciente|cuarto|espacio|luna"],
  ["🌔", "luna gibosa creciente", "creciente|gibosa|luna"],
  ["🌕", "luna llena", "llena|luna|plenilunio"],
  ["🌖", "luna gibosa menguante", "gibosa|luna|menguante"],
  ["🌗", "luna en cuarto menguante", "cuarto|luna|menguante"],
  ["🌘", "luna menguante", "luna|menguante"],
  ["🌙", "luna", "creciente|espacio"],
  ["🌚", "luna nueva con cara", "cara|espacio|luna"],
  ["🌛", "luna de cuarto creciente con cara", "cara|creciente|cuarto|espacio|luna"],
  ["🌜", "luna de cuarto menguante con cara", "cara|creciente|cuarto|espacio|luna"],
  ["🌝", "luna llena con cara", "cara|llena|luna"],
  ["🌞", "sol con cara", "brillante|cara|sol"],
  ["🌟", "estrella brillante", "brillante|estrella|resplandeciente"],
  ["🌠", "estrella fugaz", "estrella|lluvia"],
  ["🌡", "termómetro", "temperatura"],
  ["🌤", "sol detrás de una nube pequeña", "nube|sol"],
  ["🌥", "sol detrás de una nube grande", "nube|sol"],
  ["🌦", "sol detrás de una nube con lluvia", "lluvia|nube|sol"],
  ["🌧", "nube con lluvia", "lluvia|nube"],
  ["🌨", "nube con nieve", "frío|nieve|nube"],
  ["🌩", "nube con rayo", "nube|rayo"],
  ["🌪", "tornado", "nube|torbellino"],
  ["🌫", "niebla", "nube"],
  ["🌬", "cara de viento", "cara|nube|soplar|viento"],
  ["🌭", "perrito caliente", "perrito|salchicha"],
  ["🌮", "taco", "comida|mexicano"],
  ["🌯", "burrito", "comida|mexicano|tex mex|wrap"],
  ["🌰", "castaña", "castaño|fruto seco"],
  ["🌱", "planta joven", "plantón"],
  ["🌲", "árbol de hoja perenne", "árbol|hoja perenne|perenne"],
  ["🌳", "árbol de hoja caduca", "árbol|caducifolio|hoja caduca"],
  ["🌴", "palmera", "árbol|árbol de palma"],
  ["🌵", "cactus", "planta"],
  ["🌶", "chile picante", "chile|picante|planta"],
  ["🌷", "tulipán", "flor"],
  ["🌸", "flor de cerezo", "cerezo|flor"],
  ["🌹", "rosa", "flor"],
  ["🌺", "flor de hibisco", "flor|hibisco"],
  ["🌻", "girasol", "flor|sol"],
  ["🌼", "flor", ""],
  ["🌽", "espiga de maíz", "espiga|maíz|mazorca|mijo"],
  ["🌾", "espiga de arroz", "arroz|espiga|planta"],
  ["🌿", "hierba", "hoja|verde"],
  ["🍀", "trébol de cuatro hojas", "suerte|trébol"],
  ["🍁", "hoja de arce", "arce|hoja"],
  ["🍂", "hojas caídas", "caída|hojas"],
  ["🍃", "hojas revoloteando al viento", "hoja|revolotear|soplar|viento"],
  ["🍄", "champiñón", "hongo|seta"],
  ["🍅", "tomate", "ensalada|fruta|verdura"],
  ["🍆", "berenjena", "fruto|verdura"],
  ["🍇", "uvas", "agracejo|fruta|racimo|uva"],
  ["🍈", "melón", "fruta"],
  ["🍉", "sandía", "fruta"],
  ["🍊", "mandarina", "fruta|naranja"],
  ["🍋", "limón", "cítrico|citrón|fruta"],
  ["🍌", "plátano", "banana|fruta"],
  ["🍍", "piña", "ananás|fruta"],
  ["🍎", "manzana roja", "fruta|manzana|poma|roja"],
  ["🍏", "manzana verde", "fruta|manzana|poma|verde"],
  ["🍐", "pera", "fruta|perilla"],
  ["🍑", "melocotón", "durazno|fruta"],
  ["🍒", "cerezas", "cereza|fruta|guindas"],
  ["🍓", "fresa", "fresón|fruta"],
  ["🍔", "hamburguesa", "burger"],
  ["🍕", "pizza", "porción|restaurante"],
  ["🍖", "carne con hueso", "carne|hueso|restaurante"],
  ["🍗", "muslo de pollo", "muslo|pollo|restaurante"],
  ["🍘", "galleta de arroz", "arroz|galleta"],
  ["🍙", "bola de arroz", "arroz|japonés|onigiri|restaurante"],
  ["🍚", "arroz cocido", "arroz|restaurante"],
  ["🍛", "arroz con curry", "arroz|curry|restaurante"],
  ["🍜", "tazón de fideos", "fideos calientes|fideos chinos|fideos ramen|ramen"],
  ["🍝", "espagueti", "pasta|restaurante"],
  ["🍞", "pan de molde", "pan|rebanada|tostada"],
  ["🍟", "patatas fritas", "papas fritas|patatas|restaurante"],
  ["🍠", "patata asada", "asada|papa asada|patata|restaurante"],
  ["🍡", "dango", "japonés|pincho|postre|restaurante"],
  ["🍢", "brocheta", "japonés|marisco|oden|pincho"],
  ["🍣", "sushi", "restaurante"],
  ["🍤", "gamba frita", "frito|gamba|restaurante"],
  ["🍥", "pastel de pescado japonés", "comida japonesa|pastel|pescado"],
  ["🍦", "cucurucho de helado", "cucurucho|dulce|helado|helado de cucurucho|restaurante"],
  ["🍧", "granizado hawaiano", "helado|hielo|postre|raspado"],
  ["🍨", "helado", "postre|sorbete"],
  ["🍩", "dónut", "berlina|pastel|rosquilla"],
  ["🍪", "galleta", "dulce|pasta|postre"],
  ["🍫", "tableta de chocolate", "barra|chocolate|restaurante|tableta"],
  ["🍬", "caramelo", "chuche|chuchería|dulce|golosina"],
  ["🍭", "piruleta", "chuche|chuchería|dulce|golosina"],
  ["🍮", "flan", "dulce|postre|pudding"],
  ["🍯", "tarro de miel", "dulce|miel|tarro"],
  ["🍰", "trozo de tarta", "pedazo de tarta|restaurante|tarta"],
  ["🍱", "caja de bento", "bento|caja|comida|restaurante"],
  ["🍲", "olla de comida", "comida de olla|puchero|restaurante"],
  ["🍳", "cocinar", "freír|huevo|sartén"],
  ["🍴", "tenedor y cuchillo", "cuchillo|restaurante|tenedor"],
  ["🍵", "tazón de té", "bebida|taza|té"],
  ["🍶", "sake", "bar|bebida|botella|restaurante|tazón"],
  ["🍷", "copa de vino", "bar|bebida|copa|vaso|vino"],
  ["🍸", "copa de cóctel", "bar|cóctel|copa|restaurante"],
  ["🍹", "bebida tropical", "bar|bebida|restaurante|tropical"],
  ["🍺", "jarra de cerveza", "bar|cerveza|jarra|restaurante"],
  ["🍻", "jarras de cerveza brindando", "bar|cerveza|jarra|jarras|restaurante"],
  ["🍼", "biberón", "bebé|bibe|bibi|botella|leche"],
  ["🍽", "cuchillo y tenedor con un plato", "cuchillo|plato|restaurante|tenedor"],
  ["🍾", "botella descorchada", "bar|beber|botella|cava|corcho"],
  ["🍿", "palomitas", "maíz"],
  ["🎀", "lazo", "celebración"],
  ["🎁", "regalo", "celebración|envoltorio|presente|regalo envuelto"],
  ["🎂", "tarta de cumpleaños", "celebración|cumpleaños|tarta"],
  ["🎃", "calabaza de halloween", "calabaza|celebración|halloween|linterna"],
  ["🎄", "árbol de navidad", "abeto de navidad|árbol|celebración|navidad"],
  ["🎅", "papá noel", "celebración|claus|cuento|fantasía|feliz|fiestas|navidad|padre|santa"],
  ["🎆", "fuegos artificiales", "celebración"],
  ["🎇", "bengala", "celebración|fuegos artificiales"],
  ["🎈", "globo", "celebración"],
  ["🎉", "cañón de confeti", "celebración|confeti|fiesta"],
  ["🎊", "bola de confeti", "celebración|confeti"],
  ["🎋", "árbol de tanabata", "árbol|celebración|festividad|tanabata"],
  ["🎌", "banderas cruzadas", "banderas|celebración|japón"],
  ["🎍", "decoración de pino", "año nuevo japonés|bambú|celebración|decoración|kadomatsu"],
  ["🎎", "muñecas japonesas", "celebración|festival|hinamatsuri|muñecas"],
  ["🎏", "banderín de carpas", "banderín|carpa|celebración|koinobori"],
  ["🎐", "campanilla de viento", "campanilla|furin|viento"],
  ["🎑", "ceremonia de contemplación de la luna", "celebración|contemplación|luna|tsukimi"],
  ["🎒", "mochila escolar", "colegio|mochila"],
  ["🎓", "birrete", "celebración|gorro|graduación"],
  ["🎖", "medalla militar", "celebración|medalla|militar"],
  ["🎗", "lazo conmemorativo", "conmemorativo|lazo"],
  ["🎙", "micrófono de estudio", "estudio|micrófono|música"],
  ["🎚", "control de volumen", "control|fader|volumen"],
  ["🎛", "ruedas de control", "control|diales|música|potenciómetros|ruedas"],
  ["🎞", "fotograma de película", "cine|fotograma|película"],
  ["🎟", "entradas", "acceso|admisión|entrada|evento"],
  ["🎠", "caballo de tiovivo", "caballo|entretenimiento|tiovivo"],
  ["🎡", "noria de feria", "atracciones|entretenimiento|feria|noria"],
  ["🎢", "montaña rusa", "atracciones|entretenimiento|feria|parque"],
  ["🎣", "caña de pescar", "caña|entretenimiento|esparcimiento|pesca|pez"],
  ["🎤", "micrófono", "entretenimiento|karaoke|micro"],
  ["🎥", "cámara de cine", "cámara|cine|entretenimiento|película"],
  ["🎦", "cine", "entretenimiento|película"],
  ["🎧", "auricular", "cascos"],
  ["🎨", "paleta de pintor", "arte|artista|paleta|pintura"],
  ["🎩", "sombrero de copa", "chistera|copa|ropa|sombrero"],
  ["🎪", "carpa de circo", "carpa|circo|entretenimiento"],
  ["🎫", "tique", "acceso|admisión"],
  ["🎬", "claqueta", "cine|claqueta de cine|entretenimiento|película"],
  ["🎭", "máscaras de teatro", "actuación|arte|artes escénicas|entretenimiento"],
  ["🎮", "mando de videoconsola", "juego|mando|videojuego"],
  ["🎯", "diana", "blanco|en el blanco|juego"],
  ["🎰", "máquina tragaperras", "juego|máquina"],
  ["🎱", "bola negra de billar", "8|billar|bola ocho|juego"],
  ["🎲", "dado", "juego"],
  ["🎳", "bolos", "bola|bola de bolos|juego"],
  ["🎴", "cartas de flores", "carta|flor|hanafuda|naipe japonés"],
  ["🎵", "nota musical", "música|nota"],
  ["🎶", "notas musicales", "música|notas"],
  ["🎷", "saxofón", "instrumento|instrumento musical|música|saxo"],
  ["🎸", "guitarra", "instrumento|instrumento musical|música"],
  ["🎹", "teclado musical", "instrumento|instrumento musical|música|piano|teclado"],
  ["🎺", "trompeta", "instrumento|instrumento musical|música"],
  ["🎻", "violín", "instrumento|instrumento musical|música"],
  ["🎼", "pentagrama", "música|partitura"],
  ["🎽", "camiseta sin mangas", "banda|camiseta con banda|camiseta de correr|deporte"],
  ["🎾", "pelota de tenis", "deporte|pelota|tenis"],
  ["🎿", "esquís", "esquí|esquíes|nieve"],
  ["🏀", "balón de baloncesto", "balón|canasta|deporte"],
  ["🏁", "bandera de cuadros", "bandera|carreras|cuadros|deporte|motor"],
  ["🏂", "practicante de snowboard", "nieve|snowboard"],
  ["🏃", "persona corriendo", "carrera|deporte|maratón"],
  ["🏄", "persona haciendo surf", "surf|surfear"],
  ["🏅", "medalla deportiva", "medalla|premio"],
  ["🏆", "trofeo", "premio"],
  ["🏇", "carrera de caballos", "caballo|caballo de carreras|carreras|jinete"],
  ["🏈", "balón de fútbol americano", "balón|deporte|fútbol americano"],
  ["🏉", "balón de rugby", "balón|deporte|rugby"],
  ["🏊", "persona nadando", "nadar|natación"],
  ["🏋", "persona levantando pesas", "halterofilia|levantador|pesas|peso"],
  ["🏌", "persona jugando al golf", "golf|golfista|pelota"],
  ["🏍", "moto", "carreras|motocicleta|vehículo"],
  ["🏎", "coche de carreras", "carreras|coche"],
  ["🏏", "críquet", "juego|pelota"],
  ["🏐", "pelota de voleibol", "balón|juego|pelota|voleibol"],
  ["🏑", "hockey sobre hierba", "hierba|hockey|juego|palo|pelota"],
  ["🏒", "hockey sobre hielo", "disco|hielo|hockey|palo"],
  ["🏓", "tenis de mesa", "juego|mesa|pelota|ping pong"],
  ["🏔", "montaña con nieve", "frío|montaña|nieve"],
  ["🏕", "camping", "acampada|campamento|vacaciones"],
  ["🏖", "playa y sombrilla", "playa|sombrilla"],
  ["🏗", "construcción", "edificio|obra"],
  ["🏘", "casas", "edificio|urbanización"],
  ["🏙", "paisaje urbano", "ciudad|edificio|paisaje"],
  ["🏚", "casa abandonada", "abandonada|casa|deshabitada|inhabitada|vacía"],
  ["🏛", "edificio clásico", "clásico|edificio"],
  ["🏜", "desierto", "arena"],
  ["🏝", "isla desierta", "desierta|isla"],
  ["🏞", "parque nacional", "nacional|parque"],
  ["🏟", "estadio", ""],
  ["🏠", "casa", "vivienda"],
  ["🏡", "casa con jardín", "casa|construcción|jardín|vivienda"],
  ["🏢", "edificio de oficinas", "construcción|edificio|oficinas"],
  ["🏣", "oficina de correos japonesa", "correos|edificio|japón|oficina de correos"],
  ["🏤", "oficina de correos europea", "correos|edificio|europa|oficina de correos"],
  ["🏥", "hospital", "doctor|edificio|medicina|médico"],
  ["🏦", "banco", "banca|edificio"],
  ["🏧", "señal de cajero automático", "atm|banco|cajero"],
  ["🏨", "hotel", "alojamiento|edificio|turismo"],
  ["🏩", "hotel del amor", "amor|edificio|hotel"],
  ["🏪", "tienda 24 horas", "edificio|establecimiento|tienda de comestibles"],
  ["🏫", "colegio", "edificio|escuela"],
  ["🏬", "grandes almacenes", "comercio"],
  ["🏭", "fábrica", "edificio|industria"],
  ["🏮", "lámpara japonesa", "izakaya|lámpara roja|linterna izakaya|linterna japonesa|restaurante"],
  ["🏯", "castillo japonés", "castillo|construcción"],
  ["🏰", "castillo europeo", "castillo|construcción"],
  ["🏵", "roseta", "flor|planta"],
  ["🏷", "etiqueta", ""],
  ["🏸", "bádminton", "pluma|raqueta|volante"],
  ["🏹", "arco y flecha", "arco|arquero|flecha|sagitario|zodiaco"],
  ["🏺", "ánfora", "acuario|beber|jarra|zodiaco"],
  ["🐀", "rata", "roedor"],
  ["🐁", "ratón", "roedor"],
  ["🐂", "buey", "cabestro|tauro|zodiaco"],
  ["🐃", "búfalo de agua", "agua|búfalo"],
  ["🐄", "vaca", "bovino|res"],
  ["🐅", "tigre", "felino"],
  ["🐆", "leopardo", "felino"],
  ["🐇", "conejo", "conejito|gazapo"],
  ["🐈", "gato", "gatete|minino"],
  ["🐉", "dragón", "cuento|fantasía"],
  ["🐊", "cocodrilo", "caimán"],
  ["🐋", "ballena", "cachalote|cetáceo"],
  ["🐌", "caracol", "caracola|molusco"],
  ["🐍", "serpiente", "culebra|reptil|víbora"],
  ["🐎", "caballo", "caballo de carreras|carreras de caballos|ecuestre"],
  ["🐏", "carnero", "aries|morueco|zodiaco"],
  ["🐐", "cabra", "capricornio|caprino|chivo|zodiaco"],
  ["🐑", "oveja", "borrego|cordero|ovino"],
  ["🐒", "mono", "macaco|simio"],
  ["🐓", "gallo", "ave|gallina|gallinácea|pollo"],
  ["🐔", "gallina", "ave|gallinácea|pollo"],
  ["🐕", "perro", "cachorro|perrete|perrito"],
  ["🐖", "cerdo", "cochino|gorrino|puerco"],
  ["🐗", "jabalí", "cerdo salvaje"],
  ["🐘", "elefante", "paquidermo"],
  ["🐙", "pulpo", "cefalópodo|octópodo"],
  ["🐚", "caracola", "concha|espiral"],
  ["🐛", "bicho", "gusano|insecto"],
  ["🐜", "hormiga", "antenas|insecto"],
  ["🐝", "abeja", "insecto|miel"],
  ["🐞", "mariquita", "cochinilla|insecto"],
  ["🐟", "pez", "pececillo|pescado|piscis|zodiaco"],
  ["🐠", "pez tropical", "pez|tropical"],
  ["🐡", "pez globo", "globo|pez"],
  ["🐢", "tortuga", "galápago"],
  ["🐣", "pollito rompiendo el cascarón", "ave|huevo|pollito|pollo"],
  ["🐤", "pollito", "ave|pollo|polluelo"],
  ["🐥", "pollito de frente", "ave|pollito|pollo"],
  ["🐦", "pájaro", "ave|pajarillo"],
  ["🐧", "pingüino", "ave"],
  ["🐨", "koala", "cara|marsupial"],
  ["🐩", "caniche", "perrito|perro"],
  ["🐪", "dromedario", "camello|desierto|joroba"],
  ["🐫", "camello", "bactriano|desierto|dromedario|jorobas"],
  ["🐬", "delfín", "cetáceo"],
  ["🐭", "cara de ratón", "cara|ratón"],
  ["🐮", "cara de vaca", "cara|vaca"],
  ["🐯", "cara de tigre", "cara|tigre"],
  ["🐰", "cara de conejo", "cara|conejo|mascota"],
  ["🐱", "cara de gato", "cara|gato|mascota"],
  ["🐲", "cara de dragón", "cara|cuento|dragón|fantasía"],
  ["🐳", "ballena soltando un chorro", "ballena|chorro de agua"],
  ["🐴", "cara de caballo", "caballo|cara"],
  ["🐵", "cara de mono", "cara|mono"],
  ["🐶", "cara de perro", "cara|mascota|perro"],
  ["🐷", "cara de cerdo", "cara|cerdo|gorrino"],
  ["🐸", "rana", "cara"],
  ["🐹", "hámster", "cara|mascota"],
  ["🐺", "lobo", "cara"],
  ["🐻", "oso", "cara"],
  ["🐼", "panda", "cara|oso panda"],
  ["🐽", "nariz de cerdo", "cara|cerdo|morro|nariz"],
  ["🐾", "huellas de pezuñas", "huellas|pezuñas"],
  ["🐿", "ardilla", ""],
  ["👀", "ojos", "cara"],
  ["👁", "ojo", "cuerpo"],
  ["👂", "oreja", "cuerpo"],
  ["👃", "nariz", "cuerpo"],
  ["👄", "boca", "labios"],
  ["👅", "lengua", "cuerpo"],
  ["👆", "dorso de mano con índice hacia arriba", "apuntar|arriba|dedo|mano"],
  ["👇", "dorso de mano con índice hacia abajo", "abajo|apuntar|dedo|mano"],
  ["👈", "dorso de mano con índice a la izquierda", "dedo|índice|izquierda|mano"],
  ["👉", "dorso de mano con índice a la derecha", "dedo|derecha|índice|mano"],
  ["👊", "puño cerrado", "puñetazo|puño"],
  ["👋", "mano saludando", "agitar|mano|saludar|saludo"],
  ["👌", "señal de aprobación con la mano", "aprobación|mano|ok"],
  ["👍", "pulgar hacia arriba", "arriba|mano|pulgar|señal"],
  ["👎", "pulgar hacia abajo", "abajo|mano|pulgar|señal"],
  ["👏", "manos aplaudiendo", "aplaudir|manos|palmas|señal"],
  ["👐", "manos abiertas", "abiertas|manos"],
  ["👑", "corona", "accesorios|complementos|reina|rey"],
  ["👒", "sombrero de mujer", "accesorio|mujer|ropa|sombrero"],
  ["👓", "gafas", "accesorios|ojo|ropa"],
  ["👔", "corbata", "accesorio|ropa"],
  ["👕", "camiseta", "ropa"],
  ["👖", "vaqueros", "pantalones|ropa"],
  ["👗", "vestido", "mujer|ropa"],
  ["👘", "kimono", "japonés|ropa"],
  ["👙", "bikini", "baño|playa|ropa"],
  ["👚", "ropa de mujer", "blusa|camisa|femenina|ropa"],
  ["👛", "monedero", "accesorios|cartera|complementos"],
  ["👜", "bolso", "accesorios|complementos"],
  ["👝", "bolso de mano", "accesorios|bolso|cartera|complementos"],
  ["👞", "zapato de hombre", "calzado|hombre|ropa|zapato"],
  ["👟", "zapatilla deportiva", "calzado|correr|ropa|tenis"],
  ["👠", "zapato de tacón", "mujer|tacón|zapato"],
  ["👡", "sandalia de mujer", "calzado|mujer|ropa|sandalia"],
  ["👢", "bota de mujer", "bota|calzado|mujer|ropa"],
  ["👣", "huellas de pies", "huellas|pies"],
  ["👤", "silueta de busto", "busto|silueta"],
  ["👥", "dos siluetas de bustos", "bustos|siluetas"],
  ["👦", "niño", "joven"],
  ["👧", "niña", "chica|joven"],
  ["👨", "hombre", "adulto"],
  ["👩", "mujer", "adulta"],
  ["👪", "familia", ""],
  ["👫", "mujer y hombre de la mano", "hombre|hombre y mujer de la mano|mujer|novios|pareja"],
  ["👬", "hombres de la mano", "gays|hombres|novios|pareja"],
  ["👭", "mujeres de la mano", "lesbianas|mujeres|novias|pareja"],
  ["👮", "agente de policía", "agente|personas|policía"],
  ["👯", "personas con orejas de conejo", "bailar|fiesta|orejas de conejo|personas"],
  ["👰", "persona con velo", "boda|novia|persona|velo"],
  ["👱", "persona adulta rubia", "rubia|rubias|rubio|rubios"],
  ["👲", "persona con gorro chino", "gorro|gua|gua pi mao|mao|persona"],
  ["👳", "persona con turbante", "turbante"],
  ["👴", "anciano", "hombre|mayor"],
  ["👵", "anciana", "mayor|mujer"],
  ["👶", "bebé", "joven|niño"],
  ["👷", "profesional de la construcción", "casco|construcción|obrero|trabajador"],
  ["👸", "princesa", "cuento|fantasía|hadas"],
  ["👹", "demonio japonés oni", "cara|cuento|cuernos|sonrisa"],
  ["👺", "demonio japonés tengu", "cara|cuento|fantasía|monstruo|tengu"],
  ["👻", "fantasma", "cara|criatura|cuento|monstruo"],
  ["👼", "bebé ángel", "ángel|bebé|cara|cuento"],
  ["👽", "alienígena", "alien|cara|criatura|extraterrestre|ovni"],
  ["👾", "monstruo alienígena", "alien|cara|criatura|extraterrestre|ovni"],
  ["👿", "cara enfadada con cuernos", "cara|cuernos|demonio|diablo"],
  ["💀", "calavera", "cara|cuento|monstruo|muerte"],
  ["💁", "persona de mostrador de información", "información|mano|mostrador|persona"],
  ["💂", "guardia", "guardia real británica"],
  ["💃", "mujer bailando", "bailar|mujer"],
  ["💄", "pintalabios", "barra|cosmética|labios|maquillaje"],
  ["💅", "pintarse las uñas", "cosmética|esmalte|manicura|uñas"],
  ["💆", "persona recibiendo masaje", "cara|facial|masaje|salón"],
  ["💇", "persona cortándose el pelo", "belleza|corte|pelo|peluquero"],
  ["💈", "poste de barbero", "barbería|barbero|peluquero|poste"],
  ["💉", "jeringuilla", "aguja|jeringa|medicina|médico"],
  ["💊", "píldora", "comprimido|medicina|médico|pastilla"],
  ["💋", "marca de beso", "beso|labios|romance"],
  ["💌", "carta de amor", "amor|carta|corazón|correo"],
  ["💍", "anillo", "diamante"],
  ["💎", "piedra preciosa", "diamante|gema|joya|piedra|preciosa"],
  ["💏", "beso", "personas|romance"],
  ["💐", "ramo de flores", "bouquet|flores|ramo"],
  ["💑", "pareja enamorada", "amor|pareja|personas enamoradas"],
  ["💒", "iglesia celebrando boda", "boda|iglesia|romance"],
  ["💓", "corazón latiendo", "amor|corazón|emoción|latido"],
  ["💔", "corazón roto", "corazón|emoción|partido|roto"],
  ["💕", "dos corazones", "amantes|amor|corazón"],
  ["💖", "corazón brillante", "amor|brillante|emoción"],
  ["💗", "corazón creciente", "corazón|creciente|emocionado|latido|nervioso"],
  ["💘", "corazón con flecha", "amor|corazón|emoción|flecha"],
  ["💙", "corazón azul", "azul|corazón|emoción"],
  ["💚", "corazón verde", "corazón|emoción|verde"],
  ["💛", "corazón amarillo", "amarillo|corazón|emoción"],
  ["💜", "corazón morado", "corazón|emoción|morado"],
  ["💝", "corazón con lazo", "corazón|emoción|lazo|san valentín"],
  ["💞", "corazones giratorios", "corazón|giratorio"],
  ["💟", "adorno de corazón", "corazón"],
  ["💠", "rombo con pétalo", "flor|geometría|rombo"],
  ["💡", "bombilla", "cómic|electricidad|idea|luz"],
  ["💢", "símbolo de enfado", "cómic|enfadado|enfado"],
  ["💣", "bomba", "cómic|emoción"],
  ["💤", "símbolo de sueño", "cómic|dormir|sueño|zzz"],
  ["💥", "colisión", "cómic"],
  ["💦", "gotas de sudor", "cómic|emoción|sudor"],
  ["💧", "gota", "agua|cómic|sudor"],
  ["💨", "salir corriendo", "carrera|cómic|correr|humo"],
  ["💩", "caca con ojos", "caca|cómic|mierda|mojón"],
  ["💪", "bíceps flexionado", "bíceps|cómic|flexionado|fuerte|músculo"],
  ["💫", "símbolo de mareo", "cómic|emoción|estrella|mareo"],
  ["💬", "bocadillo de diálogo", "bocadillo|cómic|conversación|diálogo"],
  ["💭", "bocadillo de pensamiento", "bocadillo|burbuja|cómic|pensamiento"],
  ["💮", "flor blanca", "blanca|flor"],
  ["💯", "cien puntos", "100|pleno|puntos"],
  ["💰", "bolsa de dinero", "bolsa|bolsa de dólares|dinero"],
  ["💱", "cambio de divisas", "cambio|dinero|divisa|moneda"],
  ["💲", "símbolo de dólar", "dinero|dólar|símbolo"],
  ["💳", "tarjeta de crédito", "crédito|tarjeta"],
  ["💴", "billete de yen", "billete|billete de banco|dinero|yen"],
  ["💵", "billete de dólar", "billete|billete de banco|dinero|dólar"],
  ["💶", "billete de euro", "billete|billete de banco|dinero|euro"],
  ["💷", "billete de libra", "billete de banco|dinero|libra"],
  ["💸", "billete con alas", "billete|billete de banco|dinero|dinero con alas"],
  ["💹", "mercado al alza", "alza|mercado|mercado alcista|tabla"],
  ["💺", "asiento de transporte", "asiento|plaza|silla"],
  ["💻", "ordenador portátil", "ordenador|pc|personal"],
  ["💼", "maletín", "cartera|documentos"],
  ["💽", "minidisc", "disco|md"],
  ["💾", "disquete", "disco|disco de 3 1/2"],
  ["💿", "disco óptico", "cd|disco"],
  ["📀", "disco dvd", "disco|dvd"],
  ["📁", "carpeta de archivos", "archivo|carpeta"],
  ["📂", "carpeta de archivos abierta", "abierta|archivo|carpeta"],
  ["📃", "página doblada", "documento|página"],
  ["📄", "página hacia arriba", "anverso|documento|página"],
  ["📅", "calendario", "fecha"],
  ["📆", "calendario recortable", "calendario|fecha"],
  ["📇", "organizador de fichas", "cartera|ficha|organizador|tarjetas"],
  ["📈", "gráfica de evolución ascendente", "ascendente|gráfica|gráfico|tendencia ascendente"],
  ["📉", "gráfica de evolución descendente", "descendente|gráfica|gráfico|tendencia descendente"],
  ["📊", "gráfico de barras", "barras|gráfico"],
  ["📋", "portapapeles", "papeles|pinza|tabla"],
  ["📌", "chincheta", "tachuela"],
  ["📍", "chincheta redonda", "chincheta"],
  ["📎", "clip", ""],
  ["📏", "regla", ""],
  ["📐", "escuadra", "regla|regla triangular|triángulo"],
  ["📑", "marcadores", "pestañas"],
  ["📒", "libro de contabilidad", "cuaderno"],
  ["📓", "cuaderno", "libreta"],
  ["📔", "cuaderno con tapa decorativa", "cuaderno|decoración|tapa"],
  ["📕", "libro cerrado", "cerrado|libro"],
  ["📖", "libro abierto", "abierto|libro"],
  ["📗", "libro verde", "libro|verde"],
  ["📘", "libro azul", "azul|libro"],
  ["📙", "libro naranja", "libro|naranja"],
  ["📚", "libros", "libro"],
  ["📛", "etiqueta identificativa", "etiqueta|nombre"],
  ["📜", "pergamino", "pergamino de papel"],
  ["📝", "cuaderno de notas", "comunicación"],
  ["📞", "auricular de teléfono", "comunicación|teléfono"],
  ["📟", "busca", "comunicación|localizador"],
  ["📠", "máquina de fax", "comunicación|fax"],
  ["📡", "antena de satélite", "antena|comunicación|satélite"],
  ["📢", "altavoz de mano", "altavoz|comunicación"],
  ["📣", "megáfono", "comunicación"],
  ["📤", "bandeja de salida", "bandeja|comunicación|correo|enviado|salida"],
  ["📥", "bandeja de entrada", "bandeja|comunicación|correo|entrada|recibido"],
  ["📦", "paquete", "caja"],
  ["📧", "correo electrónico", "comunicación|correo|sobre"],
  ["📨", "sobre entrante", "carta|comunicación|correo|correo electrónico|sobre"],
  ["📩", "sobre con flecha", "carta|comunicación|correo|correo electrónico|sobre"],
  ["📪", "buzón cerrado con la bandera bajada", "bandera|buzón|buzón cerrado|vacío"],
  ["📫", "buzón cerrado con la bandera levantada", "bandera|buzón|buzón cerrado|con contenido"],
  ["📬", "buzón abierto con la bandera levantada", "bandera|buzón|buzón abierto|con contenido"],
  ["📭", "buzón abierto con la bandera bajada", "bandera|buzón|buzón abierto|vacío"],
  ["📮", "buzón", "cartas|correo"],
  ["📯", "corneta de posta", "corneta|posta"],
  ["📰", "periódico", "diario"],
  ["📱", "teléfono móvil", "celular|móvil|teléfono"],
  ["📲", "móvil con una flecha", "flecha|llamada|móvil|recibir|teléfono"],
  ["📳", "modo vibración", "móvil|teléfono|teléfono celular|vibración"],
  ["📴", "teléfono móvil apagado", "apagado|móvil|teléfono|teléfono celular"],
  ["📵", "prohibido el uso de móviles", "móvil|no hacer llamadas|prohibido|teléfono"],
  ["📶", "barras de cobertura", "antena|celular|móvil|señal|teléfono"],
  ["📷", "cámara de fotos", "cámara"],
  ["📸", "cámara con flash", "cámara|flash"],
  ["📹", "videocámara", "cámara|vídeo"],
  ["📺", "televisión", "tv"],
  ["📻", "radio", ""],
  ["📼", "cinta de vídeo", "cinta"],
  ["📽", "proyector de cine", "cine|película|proyector"],
  ["📿", "rosario", "collar|cuentas|religión"],
  ["🔀", "reproducción aleatoria", "cruzado|flechas|flechas entrecruzadas"],
  ["🔁", "repetir", "flechas|repetición"],
  ["🔂", "repetir una vez", "flechas|repetición|uno"],
  ["🔃", "flechas verticales en sentido horario", "flechas|flechas verticales sentido horario|horario|señal de recarga"],
  ["🔄", "flechas en sentido antihorario", "dirección|flechas|señal de recarga|sentido antihorario"],
  ["🔅", "brillo bajo", "bajo|brillo|señal de brillo bajo|tenue"],
  ["🔆", "brillo alto", "alto|brillante|brillo|señal de brillo alto"],
  ["🔇", "altavoz silenciado", "altavoz|altavoz con marca de cancelación|mute|silencio"],
  ["🔈", "altavoz a volumen bajo", "volumen bajo"],
  ["🔉", "altavoz a volumen medio", "altavoz con volumen medio|medio|volumen medio"],
  ["🔊", "altavoz a volumen alto", "altavoz|alto|volumen alto"],
  ["🔋", "pila", "batería"],
  ["🔌", "enchufe eléctrico", "corriente|electricidad|eléctrico|enchufe"],
  ["🔍", "lupa orientada hacia la izquierda", "buscar|lupa"],
  ["🔎", "lupa orientada hacia la derecha", "buscar|lupa"],
  ["🔏", "candado con pluma estilográfica", "candado|cerrado|estilográfica|pluma|privacidad"],
  ["🔐", "candado cerrado y llave", "candado|cerrado|llave|seguro"],
  ["🔑", "llave", "contraseña"],
  ["🔒", "candado cerrado", "candado|cerrado|cerrar"],
  ["🔓", "candado abierto", "abierto|abrir|candado"],
  ["🔔", "campana", ""],
  ["🔕", "campana con signo de cancelación", "campana|cancelación|ruido"],
  ["🔖", "marcapáginas", "marcador"],
  ["🔗", "eslabón", ""],
  ["🔘", "botón de opción", "botón|opción"],
  ["🔙", "flecha back", "atrás|atrás con flecha izquierda|back|flecha|flecha a la izquierda"],
  ["🔚", "flecha end", "final|final con flecha izquierda|flecha|flecha a la izquierda"],
  ["🔛", "flecha on!", "flecha|flecha de doble punta con la palabra \"on\" encima|on|señal"],
  ["🔜", "flecha soon", "flecha|soon|soon con flecha a la derecha"],
  ["🔝", "flecha top", "arriba|flecha hacia arriba|top|top con flecha hacia arriba"],
  ["🔞", "prohibido para menos de 18 años", "18|no apto para menores|prohibido|prohibido para menores de 18 años"],
  ["🔟", "teclas: 10", "teclas"],
  ["🔠", "letras latinas mayúsculas", "abcd|letras|mayúsculas"],
  ["🔡", "letras latinas minúsculas", "abcd|letras|minúsculas"],
  ["🔢", "números", "1234|dígitos"],
  ["🔣", "símbolos", "〒♪&%"],
  ["🔤", "alfabeto latino", "abc|latino"],
  ["🔥", "fuego", "llama"],
  ["🔦", "linterna", "luz"],
  ["🔧", "llave inglesa", "herramienta"],
  ["🔨", "martillo", "herramienta"],
  ["🔩", "tornillo y tuerca", "herramienta|tornillo|tuerca"],
  ["🔪", "cuchillo de cocina", "arma|cocinar|cuchillo"],
  ["🔫", "pistola de agua", "agua|juguete|pistola|verano"],
  ["🔬", "microscopio", "instrumento|laboratorio"],
  ["🔭", "telescopio", "astronomía|instrumento"],
  ["🔮", "bola de cristal", "adivinación|bola|buena fortuna|cristal"],
  ["🔯", "estrella de seis puntas", "adivinación|buena fortuna|estrella|seis puntas"],
  ["🔰", "símbolo japonés para principiante", "amarillo|japonés|principiante|verde"],
  ["🔱", "emblema de tridente", "ancla|emblema|tridente"],
  ["🔲", "botón cuadrado con borde negro", "botón|cuadrado"],
  ["🔳", "botón cuadrado con borde blanco", "botón|cuadrado"],
  ["🔴", "círculo rojo", "círculo|geometría|rojo"],
  ["🔵", "círculo azul", "azul|círculo|geometría"],
  ["🔶", "rombo naranja grande", "geometría|naranja|rombo"],
  ["🔷", "rombo azul grande", "azul|geometría|rombo"],
  ["🔸", "rombo naranja pequeño", "geometría|naranja|rombo"],
  ["🔹", "rombo azul pequeño", "azul|geometría|rombo"],
  ["🔺", "triángulo rojo hacia arriba", "geometría|rojo|triángulo|triángulo hacia arriba rojo"],
  ["🔻", "triángulo rojo hacia abajo", "geometría|rojo|triángulo|triángulo hacia abajo rojo"],
  ["🔼", "triángulo hacia arriba", "arriba|botón|botón triángulo hacia arriba|triángulo"],
  ["🔽", "triángulo hacia abajo", "abajo|botón|botón triángulo hacia abajo|triángulo"],
  ["🕐", "1 en punto", "1:00|reloj|una"],
  ["🕑", "2 en punto", "2:00|dos|reloj"],
  ["🕒", "3 en punto", "3:00|reloj|tres"],
  ["🕓", "4 en punto", "4:00|cuatro|reloj"],
  ["🕔", "5 en punto", "5:00|cinco|reloj"],
  ["🕕", "6 en punto", "6:00|reloj|seis"],
  ["🕖", "7 en punto", "7:00|reloj|siete"],
  ["🕗", "8 en punto", "8:00|ocho|reloj"],
  ["🕘", "9 en punto", "9:00|nueve|reloj"],
  ["🕙", "10 en punto", "10:00|diez|reloj"],
  ["🕚", "11 en punto", "11:00|once|reloj"],
  ["🕛", "12 en punto", "12:00|doce|reloj"],
  ["🕜", "una y media", "1:30|reloj"],
  ["🕝", "dos y media", "2:30|reloj"],
  ["🕞", "tres y media", "3:30|reloj"],
  ["🕟", "cuatro y media", "4:30|reloj"],
  ["🕠", "cinco y media", "5:30|reloj"],
  ["🕡", "seis y media", "6:30|reloj"],
  ["🕢", "siete y media", "7:30|reloj"],
  ["🕣", "ocho y media", "8:30|reloj"],
  ["🕤", "nueve y media", "9:30|reloj"],
  ["🕥", "diez y media", "10:30|reloj"],
  ["🕦", "once y media", "11:30|reloj"],
  ["🕧", "doce y media", "12:30|reloj"],
  ["🕯", "vela", "luz"],
  ["🕰", "reloj de sobremesa", "reloj|sobremesa"],
  ["🕴", "persona trajeada levitando", "levitar|negocios|persona|traje"],
  ["🕵", "detective", "cara|espía"],
  ["🕶", "gafas de sol", "gafas|ojo|oscuras|sol"],
  ["🕷", "araña", "insecto"],
  ["🕸", "tela de araña", "araña|tela|telaraña"],
  ["🕹", "joystick", "juego|mando|palanca|videojuego"],
  ["🕺", "hombre bailando", "bailar|hombre"],
  ["🖇", "clips unidos", "clips|unidos|unión"],
  ["🖊", "bolígrafo", "boli|escribir"],
  ["🖋", "estilográfica", "bolígrafo|escribir|pluma|tinta"],
  ["🖌", "pincel", "pintar"],
  ["🖍", "lápiz de cera", "cera|lápiz"],
  ["🖐", "mano abierta", "abierta|dedo|mano"],
  ["🖕", "dedo corazón hacia arriba", "corazón|dedo|mano|peineta"],
  ["🖖", "saludo vulcano", "mano|saludo|spock|vulcano"],
  ["🖤", "corazón negro", "corazón|negro"],
  ["🖥", "ordenador de sobremesa", "ordenador|sobremesa"],
  ["🖨", "impresora", "ordenador"],
  ["🖱", "ratón de ordenador", "ordenador|ratón"],
  ["🖲", "bola de desplazamiento", "ordenador|trackball"],
  ["🖼", "cuadro enmarcado", "marco|museo"],
  ["🗂", "separador de fichas", "fichas|fichero|separador"],
  ["🗃", "archivador de tarjetas", "archivador|archivo|caja"],
  ["🗄", "archivador", "archivos|oficina|organizador"],
  ["🗑", "papelera", "basura|cubo"],
  ["🗒", "bloc de notas de espiral", "bloc|cuaderno|espiral|notas"],
  ["🗓", "calendario de espiral", "calendario|espiral"],
  ["🗜", "tornillo de banco", "herramienta|tornillo"],
  ["🗝", "llave antigua", "antigua|llave"],
  ["🗞", "periódico enrollado", "noticias|papel|periódico"],
  ["🗡", "puñal", "arma|cuchillo|daga"],
  ["🗣", "cabeza parlante", "cabeza|cara|hablar|silueta"],
  ["🗨", "bocadillo de diálogo por la izquierda", "bocadillo|burbuja|conversación|diálogo"],
  ["🗯", "bocadillo de enfado por la derecha", "bocadillo|cabreo|enfado|rabia"],
  ["🗳", "urna con papeleta", "papeleta|urna|voto"],
  ["🗺", "mapa mundial", "mapa|mapamundi|mundo"],
  ["🗻", "monte fuji", "fuji|montaña|monte|naturaleza"],
  ["🗼", "torre de tokio", "tokio|torre"],
  ["🗽", "estatua de la libertad", "estatua|libertad|nueva|ny|nyc|york"],
  ["🗾", "mapa de japón", "japón|mapa"],
  ["🗿", "estatua moái", "estatua|moái|pascua"],
  ["😀", "cara sonriendo", "cara|divertido|feliz|sonrisa"],
  ["😁", "cara radiante con ojos sonrientes", "cara|ojo|risa|sonrisa"],
  ["😂", "cara llorando de risa", "cara|felicidad|lágrima|risa"],
  ["😃", "cara sonriendo con ojos grandes", "cara|divertido|risa|sonriendo"],
  ["😄", "cara sonriendo con ojos sonrientes", "abierta|cara|ojo|sonrisa"],
  ["😅", "cara sonriendo con sudor frío", "cara|frío|risa|sudor"],
  ["😆", "cara sonriendo con los ojos cerrados", "abierta|boca|cara|risa"],
  ["😇", "cara sonriendo con aureola", "ángel|cara|halo|sonrisa"],
  ["😈", "cara sonriendo con cuernos", "cara|cuernos|demonio|sonrisa"],
  ["😉", "cara guiñando el ojo", "cara|guiño"],
  ["😊", "cara feliz con ojos sonrientes", "cara|ojo|rubor|sonrisa"],
  ["😋", "cara saboreando comida", "cara|delicioso|hambre|rico"],
  ["😌", "cara de alivio", "aliviado|cara"],
  ["😍", "cara sonriendo con ojos de corazón", "amor|cara|corazón|sonrisa"],
  ["😎", "cara sonriendo con gafas de sol", "cara|gafas|guay|sol"],
  ["😏", "cara sonriendo con superioridad", "cara|listillo|superioridad"],
  ["😐", "cara neutral", "cara|inexpresivo|neutral"],
  ["😑", "cara sin expresión", "cara|inexpresión|inexpresiva|inexpresivo"],
  ["😒", "cara de desaprobación", "cara|insatisfacción|rechazo"],
  ["😓", "cara con sudor frío", "cara|frío|sudor"],
  ["😔", "cara desanimada", "alicaído|cara|desanimado|pensativo"],
  ["😕", "cara de confusión", "cara|confuso"],
  ["😖", "cara de frustración", "cara|frustrado"],
  ["😗", "cara besando", "beso|cara"],
  ["😘", "cara lanzando un beso", "beso|cara"],
  ["😙", "cara besando con ojos sonrientes", "beso|cara|ojo|sonrisa"],
  ["😚", "cara besando con los ojos cerrados", "beso|cara|cerrado|ojo"],
  ["😛", "cara sacando la lengua", "cara|lengua"],
  ["😜", "cara sacando la lengua y guiñando un ojo", "cara|guiño|lengua|ojo"],
  ["😝", "cara con ojos cerrados y lengua fuera", "cara|lengua|ojo|sabor"],
  ["😞", "cara decepcionada", "cara|decepción|decepcionado"],
  ["😟", "cara preocupada", "cara|preocupación|preocupado"],
  ["😠", "cara enfadada", "cara|enfadado|histérico"],
  ["😡", "cara cabreada", "cabreo|cara|enfadado|furia"],
  ["😢", "cara llorando", "cara|lágrima|llorar|triste"],
  ["😣", "cara desesperada", "cara|desesperación|frustración"],
  ["😤", "cara resoplando", "cabreo|cara|enfado"],
  ["😥", "cara triste pero aliviada", "aliviado|cara|decepcionado|menos mal"],
  ["😦", "cara con el ceño fruncido y la boca abierta", "boca abierta|cara|ceño fruncido con boca abierta"],
  ["😧", "cara angustiada", "angustia|angustiado|cara"],
  ["😨", "cara asustada", "asustado|cara|miedo|miedoso"],
  ["😩", "cara agotada", "agotado|cansado|cara"],
  ["😪", "cara de sueño", "cara|dormir|sueño"],
  ["😫", "cara cansada", "cansado|cara"],
  ["😬", "cara haciendo una mueca", "cara|mueca"],
  ["😭", "cara llorando fuerte", "cara|lágrima|llorar|triste"],
  ["😮", "cara con la boca abierta", "boca|cara"],
  ["😯", "cara estupefacta", "alucinado|cara|estupefacto|sorprendido"],
  ["😰", "cara con ansiedad y sudor", "ansiedad|cara|frío|sudor"],
  ["😱", "cara gritando de miedo", "asustado|cara|miedo|pánico"],
  ["😲", "cara asombrada", "alucinado|asombrado|cara|pasmado"],
  ["😳", "cara sonrojada", "cara|colorado|sonrojado"],
  ["😴", "cara durmiendo", "cara|dormido|sueño|zzz"],
  ["😵", "cara mareada", "cara|mareo"],
  ["😶", "cara sin boca", "boca|callado|cara|silencio"],
  ["😷", "cara con mascarilla médica", "cara|enfermo|malo|máscara"],
  ["😸", "gato sonriendo con ojos sonrientes", "cara|gato|ojos|sonriente|sonrisa"],
  ["😹", "gato llorando de risa", "cara|gato|lágrima|risa"],
  ["😺", "gato sonriendo", "cara|feliz|gato alegre|gato feliz|sonrisa"],
  ["😻", "gato sonriendo con ojos de corazón", "cara|corazón|enamorado|gato"],
  ["😼", "gato haciendo una mueca", "cara|gato|irónico|sonrisa"],
  ["😽", "gato besando", "beso|cara|cariñoso|gato"],
  ["😾", "gato enfadado", "cara|enfadado|gato"],
  ["😿", "gato llorando", "cara|gato|lágrima|pena|triste"],
  ["🙀", "gato asustado", "cara|gato|pánico|preocupación|sorpresa"],
  ["🙁", "cara con el ceño ligeramente fruncido", "cara|ceño|fruncido"],
  ["🙂", "cara sonriendo ligeramente", "cara|sonrisa"],
  ["🙃", "cara al revés", "cara|revés"],
  ["🙄", "cara con ojos en blanco", "cara|frustración|ojos|vueltos"],
  ["🙅", "persona haciendo el gesto de \"no\"", "gesto|mano|no|prohibido"],
  ["🙆", "persona haciendo el gesto de \"de acuerdo\"", "gesto|mano|ok|vale"],
  ["🙇", "persona haciendo una reverencia", "disculpa|gesto|perdón|reverencia"],
  ["🙈", "mono con los ojos tapados", "cara|mal|mono|prohibido"],
  ["🙉", "mono con los oídos tapados", "cara|mal|mono|prohibido"],
  ["🙊", "mono con la boca tapada", "cara|mal|mono|prohibido"],
  ["🙋", "persona con la mano levantada", "feliz|gesto|levantar|mano"],
  ["🙌", "manos levantadas celebrando", "celebración|gesto|hurra|mano"],
  ["🙍", "persona frunciendo el ceño", "ceño|fruncido|gesto|persona"],
  ["🙎", "persona haciendo pucheros", "gesto|persona|pucheros"],
  ["🙏", "manos en oración", "gracias|mano|oración|orar|por favor|rezar"],
  ["🚀", "cohete", "espacio|vehículo"],
  ["🚁", "helicóptero", "aspas|rotores|vehículo|volar"],
  ["🚂", "locomotora de vapor", "locomotora|tren|vehículo"],
  ["🚃", "vagón", "ferrocarril|tranvía|tren eléctrico|vehículo"],
  ["🚄", "tren de alta velocidad", "ave|ferrocarril|rápido|tren|velocidad"],
  ["🚅", "tren bala", "bala|shinkansen|tren|vehículo|velocidad"],
  ["🚆", "tren", "ferrocarril|vehículo"],
  ["🚇", "metro", "subterráneo|suburbano|transporte"],
  ["🚈", "tren ligero", "ferrocarril|transporte|tren"],
  ["🚉", "estación de tren", "estación|tren"],
  ["🚊", "tranvía", "transporte|trolebús"],
  ["🚋", "vagón de tranvía", "tranvía|vagón|vehículo"],
  ["🚌", "autobús", "bus|transporte"],
  ["🚍", "autobús próximo", "autobús|próximo|vehículo"],
  ["🚎", "trolebús", "transporte|tranvía"],
  ["🚏", "parada de autobús", "autobús|parada"],
  ["🚐", "minibús", "autobús|bus|transporte"],
  ["🚑", "ambulancia", "asistencia médica|transporte|vehículo"],
  ["🚒", "coche de bomberos", "camión|camión de bomberos|fuego|vehículo"],
  ["🚓", "coche de policía", "coche patrulla|policía|vehículo"],
  ["🚔", "coche de policía próximo", "coche patrulla|policía|próximo|vehículo"],
  ["🚕", "taxi", "coche|vehículo"],
  ["🚖", "taxi próximo", "taxi|vehículo"],
  ["🚗", "coche", "automóvil|vehículo"],
  ["🚘", "coche próximo", "automóvil|coche|próximo|vehículo"],
  ["🚙", "vehículo deportivo utilitario", "camping|caravana|furgoneta|vacaciones|vehículo"],
  ["🚚", "camión de reparto", "mercancías|reparto|transporte|vehículo"],
  ["🚛", "camión articulado", "camión|tráiler|vehículo"],
  ["🚜", "tractor", "agricultura|vehículo"],
  ["🚝", "monorraíl", "ferrocarril|monocarril|transporte|tren"],
  ["🚞", "ferrocarril de montaña", "ferrocarril|montaña|vehículo"],
  ["🚟", "ferrocarril de suspensión", "ferrocarril|suspensión|vehículo"],
  ["🚠", "teleférico de montaña", "cable|funicular|montaña|teleférico|vehículo"],
  ["🚡", "teleférico", "aéreo|tranvía|vehículo"],
  ["🚢", "barco", "vehículo"],
  ["🚣", "persona remando en un bote", "barca|bote|remo"],
  ["🚤", "lancha motora", "barco|vehículo"],
  ["🚥", "semáforo horizontal", "luz|señales de tráfico|tráfico"],
  ["🚦", "semáforo", "luz|semáforo vertical|señales de tráfico|tráfico"],
  ["🚧", "obras", "construcción|señal|señal de obras"],
  ["🚨", "luces de policía", "coche de policía|luces|policía"],
  ["🚩", "bandera triangular", "bandera|bandera de localización triangular|bandera informativa de localización|localización"],
  ["🚪", "puerta", ""],
  ["🚫", "prohibido", "entrar|no|pasar|prohibición"],
  ["🚬", "cigarrillo", "cigarro|fumar"],
  ["🚭", "prohibido fumar", "fumar|no|prohibido|señal"],
  ["🚮", "señal de usar papelera", "basura|papelera|señal|tirar la basura en la papelera"],
  ["🚯", "prohibido tirar basura", "basura|prohibido|señal|señal de no tirar basura"],
  ["🚰", "agua potable", "agua|potable"],
  ["🚱", "agua no potable", "agua|no potable"],
  ["🚲", "bicicleta", "bici|vehículo"],
  ["🚳", "bicicletas prohibidas", "bicicleta|prohibido|vehículo"],
  ["🚴", "persona en bicicleta", "bicicleta|ciclismo|ciclista"],
  ["🚵", "persona en bicicleta de montaña", "bicicleta|ciclista|montaña|mountain bike"],
  ["🚶", "persona caminando", "andar|caminando|caminar"],
  ["🚷", "prohibido el paso de peatones", "peatón|peatones|prohibido|señal"],
  ["🚸", "niños cruzando", "cruzando|niños|señal"],
  ["🚹", "aseo para hombres", "aseo de caballeros|baño|señal|señal con un hombre|servicio"],
  ["🚺", "señal de aseo para mujeres", "aseo de señoras|baño|señal|señal con una mujer|servicio"],
  ["🚻", "señal de aseos", "aseos|servicios|wc"],
  ["🚼", "señal de bebé", "bebé|cambiar|lactancia"],
  ["🚽", "inodoro", "baño|váter|wc"],
  ["🚾", "aseos", "lavabo|servicios|wc"],
  ["🚿", "ducha", "agua|baño"],
  ["🛀", "persona en la bañera", "bañera|baño|persona"],
  ["🛁", "bañera", "baño"],
  ["🛂", "control de pasaportes", "control|pasaportes"],
  ["🛃", "aduana", ""],
  ["🛄", "recogida de equipajes", "equipaje|maleta"],
  ["🛅", "consigna", "depósito|equipaje|servicio de equipaje en depósito"],
  ["🛌", "persona en la cama", "dormir|hotel"],
  ["🛐", "lugar de culto", "culto|religión"],
  ["🛑", "señal de stop", "octágono|parada|señal|stop"],
  ["🛒", "carrito de la compra", "carrito|carro|compra|supermercado"],
  ["🛕", "templo hindú", "hindú|templo"],
  ["🛖", "cabaña", "casa|yurta"],
  ["🛗", "ascensor", "accesibilidad|elevador|montacargas"],
  ["🛜", "wifi", "conexión|inalámbrica|internet|red|wi-fi"],
  ["🛝", "tobogán", "jugar|parque|parque de atracciones"],
  ["🛞", "rueda", "círculo|girar|neumático|rodar"],
  ["🛟", "salvavidas", "flotador|rescate|seguridad|socorrista"],
  ["🛠", "martillo y llave inglesa", "herramienta|llave inglesa|martillo"],
  ["🛡", "escudo", "defensa"],
  ["🛢", "barril de petróleo", "barril|bidón|petróleo"],
  ["🛣", "autopista", "carretera"],
  ["🛤", "vía de tren", "tren|vía"],
  ["🛥", "barco a motor", "barco|motor|vehículo"],
  ["🛩", "avioneta", "avión"],
  ["🛫", "avión despegando", "aeroplano|avión|salida"],
  ["🛬", "avión aterrizando", "aeroplano|avión|llegada"],
  ["🛰", "satélite", "espacio|vehículo"],
  ["🛳", "barco de pasajeros", "barco|pasajeros|vehículo"],
  ["🛴", "patinete", ""],
  ["🛵", "scooter", "escúter|moto"],
  ["🛶", "canoa", "barca|barco|piragua"],
  ["🛷", "trineo", ""],
  ["🛸", "platillo volante", "ovni"],
  ["🛹", "monopatín", "skateboard|tabla"],
  ["🛺", "mototaxi", "rickshaw|tuk tuk"],
  ["🛻", "camioneta", "pickup|ranchera"],
  ["🛼", "patines", "patín|patín de 4 ruedas|patín de cuatro ruedas"],
  ["🟠", "círculo naranja", "círculo|naranja"],
  ["🟡", "círculo amarillo", "amarillo|círculo"],
  ["🟢", "círculo verde", "círculo|verde"],
  ["🟣", "círculo morado", "círculo|lila|morado|púrpura"],
  ["🟤", "círculo marrón", "círculo|marrón"],
  ["🟥", "cuadrado rojo", "cuadrado|rojo"],
  ["🟦", "cuadrado azul", "azul|cuadrado"],
  ["🟧", "cuadrado naranja", "cuadrado|naranja"],
  ["🟨", "cuadrado amarillo", "amarillo|cuadrado"],
  ["🟩", "cuadrado verde", "cuadrado|verde"],
  ["🟪", "cuadrado morado", "cuadrado|lila|morado|púrpura"],
  ["🟫", "cuadrado marrón", "cuadrado|marrón"],
  ["🟰", "signo igual grueso", "equivalencia|igualdad|matemáticas|mates"],
  ["🤌", "dedos juntos apuntando hacia arriba", "dedos|gesto|italia|italiano|mano|sarcasmo"],
  ["🤍", "corazón blanco", "blanco|corazón|emoción"],
  ["🤎", "corazón marrón", "corazón|emoción|marrón"],
  ["🤏", "mano pellizcando", "pellizco|poco|poquito"],
  ["🤘", "mano haciendo el signo de cuernos", "cuernos|dedo|mano|rock"],
  ["🤙", "mano haciendo el gesto de llamar", "llamar|mano|meñique|pulgar"],
  ["🤚", "dorso de la mano", "dorso|levantado|mano"],
  ["🤛", "puño hacia la izquierda", "izquierda|puño"],
  ["🤜", "puño hacia la derecha", "derecha|puño"],
  ["🤝", "apretón de manos", "acuerdo|apretón|manos"],
  ["🤞", "dedos cruzados", "cruzar|dedos|mano|suerte"],
  ["🤟", "gesto de te quiero", "mano|quiero"],
  ["🤠", "cara con sombrero de vaquero", "cara|sombrero|vaquera|vaquero"],
  ["🤡", "cara de payaso", "cara|payaso"],
  ["🤢", "cara de náuseas", "cara|náuseas|vomitar"],
  ["🤣", "cara revolviéndose de la risa", "cara|carcajada|ojos cerrados|risa"],
  ["🤤", "cara babeando", "baba|babeando|cara"],
  ["🤥", "cara de mentiroso", "cara|mentiroso|nariz|pinocho"],
  ["🤦", "persona con la mano en la frente", "facepalm|frente|incredulidad|mano"],
  ["🤧", "cara estornudando", "cara|estornudar|estornudo|pañuelo"],
  ["🤨", "cara con ceja alzada", "desconfiado|escéptico"],
  ["🤩", "cara sonriendo con estrellas", "cara|estrellas|sonrisa"],
  ["🤪", "cara de loco", "grande|ojo|pequeño"],
  ["🤫", "cara pidiendo silencio", "callado|silencio"],
  ["🤬", "cara con símbolos en la boca", "maldecir|palabrota|símbolo"],
  ["🤭", "cara con mano sobre la boca", "ostras|uy|vaya"],
  ["🤮", "cara vomitando", "enfermo|malo|vomitar"],
  ["🤯", "cabeza explotando", "cabeza|explosión"],
  ["🤰", "mujer embarazada", "embarazada|mujer"],
  ["🤱", "lactancia materna", "amamantar|bebé|dar pecho|pecho"],
  ["🤲", "palmas hacia arriba juntas", "oración"],
  ["🤳", "selfi", "autofoto|cámara|selfie|teléfono"],
  ["🤴", "príncipe", "corona"],
  ["🤵", "persona con esmoquin", "esmoquin|novio|persona"],
  ["🤶", "mamá noel", "celebración|claus|cuento|fantasía|feliz|fiestas|madre|navidad|santa"],
  ["🤷", "persona encogida de hombros", "duda|encogerse|hombros|indiferencia"],
  ["🤸", "persona haciendo voltereta lateral", "acrobacia|gimnasia|pirueta|rueda|voltereta"],
  ["🤹", "persona haciendo malabares", "equilibrio|malabares|malabarismo|malabarista"],
  ["🤺", "persona haciendo esgrima", "esgrima|esgrimista|espada"],
  ["🤼", "personas luchando", "lucha|luchador"],
  ["🤽", "persona jugando al waterpolo", "waterpolista|waterpolo"],
  ["🤾", "persona jugando al balonmano", "balonmanista|balonmano"],
  ["🥂", "copas brindando", "bebida|brindar|brindis|celebración|copa"],
  ["🥃", "vaso de whisky", "chupito|copa|licor|vaso|whisky"],
  ["🥄", "cuchara", "cubiertos|cucharilla"],
  ["🥅", "portería", "deporte|red"],
  ["🥇", "medalla de oro", "medalla|oro|primero"],
  ["🥈", "medalla de plata", "medalla|plata|segundo"],
  ["🥉", "medalla de bronce", "bronce|medalla|tercero"],
  ["🥊", "guante de boxeo", "boxeo|deporte|guante"],
  ["🥋", "uniforme de artes marciales", "artes marciales|judo|kárate|taekwondo"],
  ["🥌", "piedra de curling", "juego|roca"],
  ["🥐", "cruasán", "bollo|comida|croissant|francés"],
  ["🥑", "aguacate", "comida|fruta"],
  ["🥒", "pepino", "comida|pepinillo|verdura"],
  ["🥓", "beicon", "bacon|carne|comida|panceta"],
  ["🥔", "patata", "comida|papa|verdura"],
  ["🥕", "zanahoria", "comida|verdura"],
  ["🥖", "baguete", "baguette|barra|comida|francés|pan"],
  ["🥗", "ensalada", "bol|comida|verde"],
  ["🥘", "paella", "arroz|comida"],
  ["🥙", "pan relleno", "comida|durum|falafel|kebab|pan de pita"],
  ["🥚", "huevo", "comida"],
  ["🥛", "vaso de leche", "bebida|leche|vaso"],
  ["🥜", "cacahuetes", "cacahuete|comida|fruto seco|verdura"],
  ["🥝", "kiwi", "comida|fruta"],
  ["🥞", "tortitas", "comida|dulce|pancakes|postre|tortita"],
  ["🥟", "dumpling", "comida|gyōza|jiaozi|masa"],
  ["🥠", "galleta de la fortuna", "adivinación|profecía|superstición"],
  ["🥡", "caja para llevar", "recipiente para llevar|restaurante"],
  ["🥢", "palillos", "cubiertos|hashi"],
  ["🥣", "cuenco con cuchara", "cereal|desayuno"],
  ["🥤", "vaso con pajita", "refresco|zumo"],
  ["🥥", "coco", "palmera|piña colada"],
  ["🥦", "brócoli", "col|repollo"],
  ["🥧", "pastel", "masa|relleno"],
  ["🥨", "bretzel", "galleta salada|pretzel"],
  ["🥩", "corte de carne", "carne|chuleta|filete"],
  ["🥪", "sándwich", "bocadillo|bocata|emparedado"],
  ["🥫", "comida enlatada", "conserva|lata"],
  ["🥬", "verdura de hoja verde", "bok choy|col|kale|lechuga|pak choi"],
  ["🥭", "mango", "fruta|tropical"],
  ["🥮", "pastel de luna", "festival|luna|otoño|yuebing"],
  ["🥯", "bagel", "bocadillo|pan|panadería"],
  ["🥰", "cara sonriendo con corazones", "adorar|amor|corazones|enamorada|enamorado"],
  ["🥱", "cara de bostezo", "aburrido|bostezo|cansado|dormido|sueño"],
  ["🥲", "cara sonriente con lágrima", "agradecido|aliviado|emocionado|lágrima|orgulloso|sonrisa"],
  ["🥳", "cara de fiesta", "capirote|celebración|fiesta|gorro|matasuegras"],
  ["🥴", "cara de grogui", "atontado|entonado|grogui|intoxicado|mareado"],
  ["🥵", "cara con calor", "calor|cara roja|fiebre|golpe de calor|sudor"],
  ["🥶", "cara con frío", "cara congelada|congelado|frío|helado"],
  ["🥷", "ninja", "furtivo|guerrero|luchador|oculto|sigilo"],
  ["🥸", "cara disfrazada", "careta|disfraz|disimulo|gafas|incógnito|nariz"],
  ["🥹", "cara aguantándose las lágrimas", "emoción|emocionado|llorar|orgulloso|resistir|triste"],
  ["🥺", "cara suplicante", "implorar|ojos adorables|piedad|por favor"],
  ["🥻", "sari", "prenda|ropa|vestido"],
  ["🥼", "bata de laboratorio", "científico|doctor|experimento|médico"],
  ["🥽", "gafas de protección", "gafas|nadar|protección ocular|soldar"],
  ["🥾", "bota de senderismo", "bota|camping|mochilero|senderismo"],
  ["🥿", "bailarina", "calzado|zapato"],
  ["🦀", "cangrejo", "animal|cáncer|zodiaco"],
  ["🦁", "león", "cara|leo|zodiaco"],
  ["🦂", "escorpión", "escorpio|zodiaco"],
  ["🦃", "pavo", "ave"],
  ["🦄", "unicornio", "cara"],
  ["🦅", "águila", "ave"],
  ["🦆", "pato", "ave"],
  ["🦇", "murciélago", "vampiro"],
  ["🦈", "tiburón", "pez"],
  ["🦉", "búho", "ave|lechuza|pájaro"],
  ["🦊", "zorro", "cara"],
  ["🦋", "mariposa", "bonito|insecto"],
  ["🦌", "ciervo", "bambi|cervatillo"],
  ["🦍", "gorila", "primate|simio"],
  ["🦎", "lagarto", "lagartija|reptil"],
  ["🦏", "rinoceronte", "paquidermo"],
  ["🦐", "gamba", "camarón|comida|langostino|marisco"],
  ["🦑", "calamar", "comida|molusco"],
  ["🦒", "jirafa", "manchas"],
  ["🦓", "cebra", "raya"],
  ["🦔", "erizo", "espinas|púas"],
  ["🦕", "saurópodo", "braquiosaurio|brontosaurio|diplodocus"],
  ["🦖", "t-rex", "tiranosaurio|tiranosaurio rex"],
  ["🦗", "grillo", "saltamontes"],
  ["🦘", "canguro", "marsupial|saltar|salto"],
  ["🦙", "llama", "alpaca|guanaco|lana|vicuña"],
  ["🦚", "pavo real", "ave|orgulloso|pavo|plumas"],
  ["🦛", "hipopótamo", "paquidermo"],
  ["🦜", "loro", "ave|hablar|papagayo|pirata"],
  ["🦝", "mapache", "astuto|curioso|ladino|maquillaje|ojeras"],
  ["🦞", "bogavante", "langosta|marisco|pinzas"],
  ["🦟", "mosquito", "fiebre|insecto|malaria|virus"],
  ["🦠", "microbio", "ameba|bacteria|germen|virus"],
  ["🦡", "tejón", "ratel|tejón de la miel|tejón melero"],
  ["🦢", "cisne", "ave|patito feo"],
  ["🦣", "mamut", "colmillo|extinguido|lanudo"],
  ["🦤", "dodo", "ave|dronte|extinguido|mauricio|pájaro"],
  ["🦥", "perezoso", "gandul|lento|vago"],
  ["🦦", "nutria", "bromista|juguetón|pesca"],
  ["🦧", "orangután", "mono|primate|simio"],
  ["🦨", "mofeta", "apestar|hedor|mal olor|peste|tufo"],
  ["🦩", "flamenco", "extravangante|ostentoso|tropical"],
  ["🦪", "ostra", "buceo|perla"],
  ["🦫", "castor", "roedor"],
  ["🦬", "bisonte", "búfalo|cíbolo"],
  ["🦭", "foca", "león marino"],
  ["🦮", "perro guía", "accesibilidad|ciego|guía|invidente|lazarillo"],
  ["🦯", "bastón", "accesibilidad|ceguera|ciega|ciego|invidente"],
  ["🦰", "pelo pelirrojo", "pelirrojo|pelo|rojizo|rojo"],
  ["🦱", "pelo rizado", "afro|bucle|rizado|rizo|tirabuzón"],
  ["🦲", "sin pelo", "afeitado|bola de billar|calvo|quimioterapia"],
  ["🦳", "pelo blanco", "blanco|cana|gris|pelo|viejo"],
  ["🦴", "hueso", "esqueleto"],
  ["🦵", "pierna", "extremidad|patada"],
  ["🦶", "pie", "patada|pisotón"],
  ["🦷", "diente", "dentista|molar|muela"],
  ["🦸", "personaje de superhéroe", "bien|héroe|heroína|superhéroe|superheroína|superpoder"],
  ["🦹", "personaje de supervillano", "mal|superpoder|supervillana|supervillano|villana|villano"],
  ["🦻", "oreja con audífono", "accesibilidad|audífono|prótesis auditiva|sordo"],
  ["🦼", "silla de ruedas eléctrica", "accesibilidad"],
  ["🦽", "silla de ruedas manual", "accesibilidad"],
  ["🦾", "brazo mecánico", "accesibilidad|ortopedia|prótesis"],
  ["🦿", "pierna mecánica", "accesibilidad|ortopedia|prótesis"],
  ["🧀", "cuña de queso", "cuña|queso|trozo"],
  ["🧁", "magdalena", "cupcake|dulce|repostería"],
  ["🧂", "sal", "condimento|salero"],
  ["🧃", "tetrabrik", "brick|cartón|envase|zumo"],
  ["🧄", "ajo", "condimento|vampiro"],
  ["🧅", "cebolla", "condimento|llorar"],
  ["🧆", "falafel", "albóndiga|garbanzo"],
  ["🧇", "gofre", "waffle"],
  ["🧈", "mantequilla", "lácteo"],
  ["🧉", "mate", "bebida|infusión"],
  ["🧊", "cubito de hielo", "frío|iceberg"],
  ["🧋", "té de burbujas", "boba|bubble tea|burbuja|leche|perla|té"],
  ["🧍", "persona de pie", "de pie|levantada|levantado|levantarse"],
  ["🧎", "persona de rodillas", "arrodillada|arrodillado|arrodillarse|de rodillas"],
  ["🧏", "persona sorda", "accesibilidad|escuchar|oído|oír|sordera"],
  ["🧐", "cara con monóculo", "aristocrático|estirado"],
  ["🧑", "persona adulta", "género|neutro"],
  ["🧒", "infante", "crío|género|joven|neutro"],
  ["🧓", "persona mayor", "adulto|género neutro|género no especificado|maduro|mayor"],
  ["🧔", "persona con barba", "barbas|barbudo|persona"],
  ["🧕", "mujer con hiyab", "hiyab|pañuelo"],
  ["🧖", "persona en una sauna", "sauna|vapor"],
  ["🧗", "persona escalando", "alpinista|escalador"],
  ["🧘", "persona en posición de loto", "meditación|yoga"],
  ["🧙", "persona maga", "bruja|brujo|hechicera|hechicero"],
  ["🧚", "hada", "campanilla|oberón|puck|titania"],
  ["🧛", "vampiro", "drácula|muerto viviente|no muerto"],
  ["🧜", "persona sirena", "sirena|tritón"],
  ["🧝", "elfo", "mágico"],
  ["🧞", "genio", "lámpara"],
  ["🧟", "zombi", "muerto viviente|no muerto"],
  ["🧠", "cerebro", "inteligente"],
  ["🧡", "corazón naranja", "corazón|emoción|naranja"],
  ["🧢", "gorra con visera", "béisbol|gorra|visera"],
  ["🧣", "bufanda", "abrigo|cuello"],
  ["🧤", "guantes", "mano"],
  ["🧥", "abrigo", "chaquetón"],
  ["🧦", "calcetines", "pies|ropa"],
  ["🧧", "sobre rojo", "buena suerte|hóngbāo|lai see|regalo"],
  ["🧨", "petardo", "dinamita|explosivo|fuegos artificiales"],
  ["🧩", "pieza de puzle", "conectar|pieza|pista|puzle|rompecabezas"],
  ["🧪", "tubo de ensayo", "ciencia|experimento|laboratorio|química|químico"],
  ["🧫", "placa de petri", "bacterias|biología|biólogo|cultivo|laboratorio"],
  ["🧬", "adn", "biólogo|evolución|gen|genética|vida"],
  ["🧭", "brújula", "compás|magnético|navegación|orientación"],
  ["🧮", "ábaco", "cálculo|contar|matemáticas"],
  ["🧯", "extintor", "apagar|extinguir|incendio"],
  ["🧰", "caja de herramientas", "armario|herramienta|mecánico"],
  ["🧱", "ladrillo", "arcilla|cemento|muro|pared"],
  ["🧲", "imán", "atracción|herradura|magnético"],
  ["🧳", "equipaje", "maleta|viajar"],
  ["🧴", "bote de crema", "champú|crema|hidratante|protector solar"],
  ["🧵", "hilo", "aguja|carrete|coser|costura"],
  ["🧶", "ovillo", "bola|croché|punto|tejer"],
  ["🧷", "imperdible", "pañal|punk rock"],
  ["🧸", "osito de peluche", "juguete|oso|peluche"],
  ["🧹", "escoba", "barrer|bruja|fregar"],
  ["🧺", "cesta", "colada|cosecha|pícnic"],
  ["🧻", "rollo de papel", "papel absorbente|papel higiénico"],
  ["🧼", "jabón", "bañarse|enjabonarse|jabonera|lavarse|pastilla"],
  ["🧽", "esponja", "absorbente|limpiar|poroso"],
  ["🧾", "recibo", "contabilidad|prueba|teneduría de libros|testimonio"],
  ["🧿", "ojo turco", "amuleto|mal de ojo|nazar|talismán"],
  ["🩰", "zapatillas de ballet", "bailar|balé|ballet|danza"],
  ["🩱", "traje de baño de una pieza", "bañador"],
  ["🩲", "ropa interior", "bañador|bragas|braguitas|calzoncillos|slip"],
  ["🩳", "pantalones cortos", "bañador|bermudas|calzoncillos|ropa interior|shorts"],
  ["🩴", "chancla", "chancla de dedo|chancleta|chinela|sandalia"],
  ["🩵", "corazón azul claro", "azul|celeste|cián|claro|corazón"],
  ["🩶", "corazón gris", "corazón|gris|pizarra|plata"],
  ["🩷", "corazón rosa", "amor|bonito|corazón|gustar|rosa"],
  ["🩸", "gota de sangre", "donación de sangre|donar sangre|herida|medicina|sangre"],
  ["🩹", "tirita", "apósito"],
  ["🩺", "estetoscopio", "corazón|doctor|fonendoscopio|latido|medicina|médico"],
  ["🩻", "radiografía", "doctor|doctora|esqueleto|huesos|médico|rayos"],
  ["🩼", "muleta", "ayuda para la movilidad|bastón|discapacidad|lesión|palo"],
  ["🪀", "yoyó", "dieta|efecto|fluctuar|juguete"],
  ["🪁", "cometa", "juguete|planear|viento|volar"],
  ["🪂", "paracaídas", "ala delta|paracaidismo|paravela|volar"],
  ["🪃", "bumerán", "boomerang|rebotar"],
  ["🪄", "varita mágica", "bruja|hechicero|magia|mago|prestidigitación|varita"],
  ["🪅", "piñata", "caballito|celebración|fiesta"],
  ["🪆", "muñeca rusa", "babushka|mamushka|matrioska|rusia"],
  ["🪇", "maracas", "agitar|brasil|instrumento|movimiento|música|percusión"],
  ["🪈", "flauta", "flautín|instrumento|instrumento de viento madera|música"],
  ["🪉", "arpa", "amor|cupido|harpa|instrumento|música|orquesta"],
  ["🪐", "planeta con anillos", "saturnino|saturno"],
  ["🪑", "silla", "asiento|sentarse"],
  ["🪒", "cuchilla de afeitar", "afeitado|afeitar|afilado|barbero|navaja"],
  ["🪓", "hacha", "cortar|dividir|hachuela|madera|talar"],
  ["🪔", "lámpara de aceite", "aceite|diya|lámpara"],
  ["🪕", "banjo", "banyo|cuerda|instrumento|música"],
  ["🪖", "casco militar", "casco|ejército|guerra|guerrero|soldado"],
  ["🪗", "acordeón", "concertina"],
  ["🪘", "tamboril", "conga|ritmo|tambor"],
  ["🪙", "moneda", "dinero|metal|oro|plata|tesoro"],
  ["🪚", "sierra de carpintería", "carpintería|carpintero|herramienta|sierra|talar"],
  ["🪛", "destornillador", "atornillador|herramienta|tornillo"],
  ["🪜", "escalera", "escalar|escalerilla|escalón|peldaño"],
  ["🪝", "gancho", "agarrar|anzuelo|atrapar|garfio"],
  ["🪞", "espejo", "espéculo|reflector|reflejo"],
  ["🪟", "ventana", "abertura|apertura|cristal|marco|transparente|vista"],
  ["🪠", "desatascador", "fontanero|retrete|servicio|succión"],
  ["🪡", "aguja de coser", "aguja|bordado|coser|hilar|punto|tejer"],
  ["🪢", "nudo", "anudar|atar|enredar|trenzar"],
  ["🪣", "cubo", "balde|barreño|cuba|cubeta"],
  ["🪤", "trampa de ratones", "cebo|cepo|engañar|ratón|ratonera|trampa"],
  ["🪥", "cepillo de dientes", "cepillo|dental|higiene|limpio|servicio"],
  ["🪦", "lápida", "cementario|estela|sepulcro|tumba"],
  ["🪧", "letrero", "anuncio|aviso|cartel|pancarta|poste"],
  ["🪨", "piedra", "pedrusco|peña|peñasco|roca"],
  ["🪩", "bola de espejos", "bailar|brillar|disco|discoteca|fiesta"],
  ["🪪", "carné de identidad", "carné de conducir|credenciales|identificación|permiso|seguridad"],
  ["🪫", "batería baja", "batería|carga baja|electrónico|energía baja|pila"],
  ["🪬", "hamsa", "amuleto|fátima|jamsa|mano|maría|miriam"],
  ["🪭", "abanico abierto", "abanico|airear|bailar|calor|feria|flamenco"],
  ["🪮", "peineta", "afro|peine|pelo"],
  ["🪯", "khanda", "religión|sij|sijismo|sikh"],
  ["🪰", "mosca", "basura|bicho|mal olor|podrido"],
  ["🪱", "gusano", "lombriz|oruga|parásito"],
  ["🪲", "escarabajo", "bicho|insecto"],
  ["🪳", "cucaracha", "alimaña|bicho|insecto|plaga"],
  ["🪴", "planta de maceta", "crecer|maceta|planta|tiesto"],
  ["🪵", "madera", "hoguera|leña|madero|palos|tronco"],
  ["🪶", "pluma", "ave|ligero|pájaro|plumaje"],
  ["🪷", "loto", "budismo|flor|hinduismo|pureza"],
  ["🪸", "coral", "arrecife|océano"],
  ["🪹", "nido vacío", "anidación|anidamiento|anidar"],
  ["🪺", "nido con huevos", "anidación|anidamiento|anidar"],
  ["🪻", "campanilla", "boca de dragón|flor|jacinto|lavanda|lila|lupino"],
  ["🪼", "medusa", "invertebrado|marino|picadura|picar"],
  ["🪽", "ala", "ángel|angelical|ave|mitología|pájaro|volar"],
  ["🪾", "árbol sin hojas", "árbol|deshojado|estéril|invierno|madera|muerto|ramas|sequía|sin hojas|tronco"],
  ["🪿", "oca", "ave|ganso|graznar|pájaro"],
  ["🫀", "corazón humano", "anatomía|cardiología|corazón|latido|órgano|pulso"],
  ["🫁", "pulmones", "exhalar|inhalar|órgano|respiración|respirar"],
  ["🫂", "personas abrazándose", "abrazo|adiós|despedida|gracias|saludo"],
  ["🫃", "hombre embarazado", "barriga|embarazado|hinchado|hinchazón|inflado|lleno"],
  ["🫄", "persona embarazada", "barriga|embarazo|gestación|hinchazón"],
  ["🫅", "persona con corona", "majestad|monarca|monarquía|noble|real|realeza"],
  ["🫐", "arándanos", "arándano|azul|baya|frutos del bosque|mirtilo"],
  ["🫑", "pimiento", "ají|chile|morrón|rojo|verdura"],
  ["🫒", "aceituna", "aperitivo|comida|oliva"],
  ["🫓", "pan sin levadura", "arepa|naan|pita|tortilla"],
  ["🫔", "tamal", "mejicano|mexicano|wrap"],
  ["🫕", "fondue", "chocolate|olla|queso|suizo"],
  ["🫖", "tetera", "bebida|infusión|té"],
  ["🫗", "líquido derramándose", "bebida|derramar|vacío|vaso|verter"],
  ["🫘", "alubias", "comida|habichuela roja|habichuelas|judía roja|judías|legumbre"],
  ["🫙", "tarro", "almacenar|condimento|frasco|recipiente|salsa|vacío"],
  ["🫚", "raíz de jengibre", "cerveza|especia|garganta|raíz"],
  ["🫛", "vaina", "edamame|guisante|judías|legumbre|soja|verdura"],
  ["🫜", "túberculo comestible", "chirivía|comida|ensalada|huerto|nabo|rábano|raíz|remolacha|vegetariano|verdura"],
  ["🫰", "mano con dedo índice y pulgar cruzados", "amor|caro|chasquido|corazón|dinero"],
  ["🫱", "mano hacia la derecha", "a la derecha|derecha|mano"],
  ["🫲", "mano hacia la izquierda", "a la izquierda|izquierda|mano"],
  ["🫳", "mano con la palma hacia abajo", "bajar|descartar|fuera|no|quita|rechazar"],
  ["🫴", "mano con la palma hacia arriba", "acércate|dame|ofrecer|trae|ven"],
  ["🫵", "dedo índice apuntándote a ti", "apuntar|ti|tú"],
  ["🫶", "manos formando un corazón", "amor"],
  ["🫷", "mano empujando hacia la izquierda", "a la izquierda|choca esos cinco|detener|empujar|rechazar|stop"],
  ["🫸", "mano empujando hacia la derecha", "a la derecha|choca esos cinco|detener|empujar|rechazar|stop"],
  ["‼", "exclamación doble", "!!|exclamación|puntuación|sorpresa"],
  ["⁉", "exclamación e interrogación", "!|!?|?|exclamación|interrogación"],
  ["™", "símbolo de marca comercial", "marca comercial"],
  ["ℹ", "información", "i"],
  ["↔", "flecha izquierda y derecha", "derecha|dirección|flecha|izquierda"],
  ["↕", "flecha arriba y abajo", "abajo|arriba|dirección|flecha"],
  ["↖", "flecha hacia la esquina superior izquierda", "arriba|dirección|flecha|izquierda|noroeste"],
  ["↗", "flecha hacia la esquina superior derecha", "arriba|derecha|dirección|flecha|noreste"],
  ["↘", "flecha hacia la esquina inferior derecha", "abajo|derecha|dirección|flecha|sudeste"],
  ["↙", "flecha hacia la esquina inferior izquierda", "abajo|dirección|flecha|izquierda|suroeste"],
  ["↩", "flecha derecha curvándose a la izquierda", "curva|dirección|flecha|izquierda"],
  ["↪", "flecha izquierda curvándose a la derecha", "curva|derecha|dirección|flecha"],
  ["⌚", "reloj", ""],
  ["⌛", "reloj de arena sin tiempo", "arena|reloj|temporizador"],
  ["⌨", "teclado", "ordenador"],
  ["⏏", "expulsar", "botón"],
  ["⏩", "avance rápido", "avanzar|doble|flecha"],
  ["⏪", "retroceso rápido", "flecha|flecha doble a la izquierda|izquierda|rebobinado|rebobinar"],
  ["⏫", "triángulo doble hacia arriba", "arriba|flecha"],
  ["⏬", "triángulo doble hacia abajo", "triángulo|triángulo doble abajo"],
  ["⏭", "pista siguiente", "raya vertical|siguiente|triángulos"],
  ["⏮", "pista anterior", "atrás|escena anterior|triángulo"],
  ["⏯", "reproducir o pausa", "pausa|reproducir|triángulo"],
  ["⏰", "reloj despertador", "alarma|despertador|reloj"],
  ["⏱", "cronómetro", "reloj"],
  ["⏲", "temporizador", "reloj"],
  ["⏳", "reloj de arena con tiempo", "reloj con arena cayendo|temporizador"],
  ["⏸", "pausa", "barras|botón|vertical"],
  ["⏹", "detener", "botón|cuadrado|parar"],
  ["⏺", "grabar", "botón|círculo"],
  ["Ⓜ", "m en círculo", "círculo|m"],
  ["▪", "cuadrado negro pequeño", "cuadrado|geometría|negro"],
  ["▫", "cuadrado blanco pequeño", "blanco|cuadrado|geometría"],
  ["▶", "reproducir", "botón de reproducción|flecha|triángulo"],
  ["◀", "retroceso", "izquierda|triángulo"],
  ["◻", "cuadrado blanco mediano", "blanco|cuadrado|geometría"],
  ["◼", "cuadrado negro mediano", "cuadrado|geometría|negro"],
  ["◽", "cuadrado blanco mediano-pequeño", "blanco|cuadrado|geometría"],
  ["◾", "cuadrado negro mediano-pequeño", "cuadrado|geometría|negro"],
  ["☀", "sol", "espacio|rayos|soleado"],
  ["☁", "nube", "tiempo"],
  ["☂", "paraguas", "lluvia|paraguas abierto"],
  ["☃", "muñeco de nieve con nieve", "nieve"],
  ["☄", "meteorito", "cometa|espacio"],
  ["☎", "teléfono", ""],
  ["☑", "casilla con marca de verificación", "✓|casilla|marca|selección|verificación"],
  ["☔", "paraguas con gotas de lluvia", "gotas|lluvia|paraguas"],
  ["☕", "bebida caliente", "bebida|café|caliente|té"],
  ["☝", "dedo índice hacia arriba", "apuntar|arriba|dedo|mano"],
  ["☦", "cruz ortodoxa", "cruz|religión"],
  ["☪", "media luna y estrella", "estrella|islam|luna|religión"],
  ["☮", "símbolo de la paz", "paz"],
  ["☯", "yin yang", "religión|taoísmo|yang|yin"],
  ["☸", "rueda del dharma", "budismo|dharma|religión|rueda"],
  ["☹", "cara con el ceño fruncido", "cara|ceño|fruncido"],
  ["☺", "cara sonriente", "cara|contorno|relajado|sonrisa"],
  ["♈", "aries", "carnero|horóscopo|zodiaco"],
  ["♉", "tauro", "buey|horóscopo|toro|zodiaco"],
  ["♊", "géminis", "gemelos|horóscopo|zodiaco"],
  ["♋", "cáncer", "cangrejo|horóscopo|zodiaco"],
  ["♌", "leo", "horóscopo|león|zodiaco"],
  ["♍", "virgo", "horóscopo|zodiaco"],
  ["♎", "libra", "balanza|escala|horóscopo|justicia|zodiaco"],
  ["♏", "escorpio", "escorpión|horóscopo|zodiaco"],
  ["♐", "sagitario", "arquero|horóscopo|zodiaco"],
  ["♑", "capricornio", "cabra|horóscopo|zodiaco"],
  ["♒", "acuario", "agua|horóscopo|zodiaco"],
  ["♓", "piscis", "horóscopo|pescado|pez|zodiaco"],
  ["♟", "peón de ajedrez", "ajedrez|peón"],
  ["♻", "símbolo de reciclaje", "reciclaje|reciclar|señal|símbolo universal de reciclaje sólido|universal"],
  ["♾", "infinito", "ilimitado|siempre|universal"],
  ["♿", "símbolo de silla de ruedas", "acceso|señal|silla|silla de ruedas|símbolo"],
  ["⚒", "martillo y pico", "herramienta|martillo|pico"],
  ["⚔", "espadas cruzadas", "arma|cruzadas|espadas"],
  ["⚕", "símbolo de medicina", "asclepio|esculapio|medicina|serpiente"],
  ["⚖", "balanza", "justicia|libra|peso|zodiaco"],
  ["⚗", "alambique", "herramienta|química"],
  ["⚙", "engranaje", "herramienta"],
  ["⚛", "símbolo de átomo", "átomo|símbolo"],
  ["⚜", "flor de lis", "flor|lis"],
  ["⚠", "advertencia", "cuidado|señal"],
  ["⚡", "alto voltaje", "electricidad|peligro|peligro de alto voltaje|señal de alto voltaje|voltaje"],
  ["⚧", "símbolo de transgénero", "transgénero"],
  ["⚪", "círculo blanco", "círculo|geometría"],
  ["⚫", "círculo negro", "círculo|geometría"],
  ["⚰", "ataúd", "muerte"],
  ["⚱", "urna funeraria", "funeraria|muerte|urna"],
  ["⚽", "balón de fútbol", "balón|fútbol"],
  ["⚾", "béisbol", "balón|baseball|pelota"],
  ["⛄", "muñeco de nieve", "muñeco de nieve sin nieve|nieve"],
  ["⛅", "sol detrás de una nube", "nube|sol|sol con nubes"],
  ["⛈", "nube con rayo y lluvia", "lluvia|nube|trueno"],
  ["⛎", "ofiuco", "horóscopo|portador|serpiente|zodiaco"],
  ["⛏", "pico", "herramienta|mina"],
  ["⛑", "casco con una cruz blanca", "ayuda|cara|casco|cruz"],
  ["⛓", "cadenas", "cadena"],
  ["⛔", "dirección prohibida", "no|prohibido|señal|señal de dirección prohibida"],
  ["⛩", "santuario sintoísta", "japón|religión|santuario|sintoísmo"],
  ["⛪", "iglesia", "cristianismo|cruz|edificio|religión"],
  ["⛰", "montaña", "monte"],
  ["⛱", "sombrilla en la arena", "arena|sol|sombrilla"],
  ["⛲", "fuente", ""],
  ["⛳", "banderín en hoyo", "banderín|golf|hoyo"],
  ["⛴", "ferri", "barco|ferry"],
  ["⛵", "velero", "barco|barco de vela|yate"],
  ["⛷", "persona esquiando", "esquí|esquiador|nieve"],
  ["⛸", "patín de hielo", "hielo|patín"],
  ["⛹", "persona botando un balón", "balón|botar|pelota"],
  ["⛺", "tienda de campaña", "campaña|camping|tienda|vacaciones"],
  ["⛽", "surtidor de gasolina", "bomba de gasolina|combustible|gasolina|surtidor"],
  ["✂", "tijeras", "cortar|herramienta"],
  ["✅", "botón de marca de verificación", "✓|botón|marca|selección|verificación"],
  ["✈", "avión", "aeroplano"],
  ["✉", "sobre", "carta|correo"],
  ["✊", "puño en alto", "cerrado|mano|puñetazo|puño"],
  ["✋", "mano levantada", "choca esos cinco|levantada|mano"],
  ["✌", "mano con señal de victoria", "mano|señal de victoria|victoria"],
  ["✍", "mano escribiendo", "escribir|lápiz|mano"],
  ["✏", "lápiz", "escolar|escribir|lapicero"],
  ["✒", "pluma negra", "bolígrafo|escribir|pluma|tinta"],
  ["✔", "marca de verificación", "✓|marca|selección|verificación"],
  ["✖", "multiplicación", "×|cancelar|marca|prohibido|signo de multiplicación|x"],
  ["✝", "cruz latina", "cristianismo|cruz|religión"],
  ["✡", "estrella de david", "david|estrella|judaísmo|judío|religión"],
  ["✨", "chispas", "*|bengala|estrellas"],
  ["✳", "asterisco de ocho puntas", "*|asterisco"],
  ["✴", "estrella de ocho puntas", "*|estrella"],
  ["❄", "copo de nieve", "frío|nieve"],
  ["❇", "chispa", "*"],
  ["❌", "marca de cruz", "×|cancelar|cruz|marca de tachado|tachar|x"],
  ["❎", "botón con marca de cruz", "×|casilla|cruz|marca|x"],
  ["❓", "interrogación roja", "?|interrogación|pregunta|puntuación|signo de interrogación"],
  ["❔", "interrogación blanca", "?|interrogación|pregunta|puntuación"],
  ["❕", "exclamación blanca", "!|exclamación|puntuación"],
  ["❗", "exclamación roja", "!|exclamación|puntuación|signo de exclamación"],
  ["❣", "exclamación de corazón", "corazón|exclamación|puntuación"],
  ["❤", "corazón rojo", "corazón|emoción|rojo"],
  ["➕", "más", "+|signo|suma"],
  ["➖", "menos", "-|−|resta|signo"],
  ["➗", "división", "÷|signo|signo de división"],
  ["➡", "flecha hacia la derecha", "derecha|dirección|este|flecha"],
  ["➰", "bucle", "giro|tirabuzón"],
  ["➿", "bucle doble", "bucle|doble"],
  ["⤴", "flecha derecha curvándose hacia arriba", "arriba|curva|dirección|flecha"],
  ["⤵", "flecha derecha curvándose hacia abajo", "abajo|curva|dirección|flecha"],
  ["⬅", "flecha hacia la izquierda", "flecha|izquierda|oeste"],
  ["⬆", "flecha hacia arriba", "dirección|flecha|flecha arriba|norte"],
  ["⬇", "flecha hacia abajo", "abajo|dirección|flecha|sur"],
  ["⬛", "cuadrado negro grande", "cuadrado|geometría|negro"],
  ["⬜", "cuadrado blanco grande", "blanco|cuadrado|geometría"],
  ["⭐", "estrella", "estelar"],
  ["⭕", "círculo rojo hueco", "aro|círculo|o|rojo"],
  ["〰", "guion ondulado", "guion|marca de sonido largo|ondulado"],
  ["〽", "marca de alternancia", "alternancia|marca"],
  ["㊗", "ideograma japonés para \"enhorabuena\"", "enhorabuena|ideograma|japonés|kanji"],
  ["㊙", "ideograma japonés para \"secreto\"", "ideograma|japonés|kanji|secreto"],
];

export default ROWS;
