// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Produced by `scripts/generate-emoji-data.py` from the vendored CLDR emoji
// annotations in scripts/emoji-annotations.json (CLDR release-48). To refresh
// the data, or after adding a locale to i18n/languages.ts:
//
//     python3 scripts/generate-emoji-data.py --refresh-annotations
//
// Locale: en — 1581 entries

import type { EmojiAnnotationRow } from "./index";

const ROWS: readonly EmojiAnnotationRow[] = [
  ["©", "copyright", "c"],
  ["®", "registered", "r"],
  ["🀄", "mahjong red dragon", "dragon|game|mahjong|red"],
  ["🃏", "joker", "card|game|wildcard"],
  ["🅰", "a button (blood type)", "blood|button|type"],
  ["🅱", "b button (blood type)", "b|blood|button|type"],
  ["🅾", "o button (blood type)", "blood|button|o|type"],
  ["🅿", "p button", "button|p|parking"],
  ["🆎", "ab button (blood type)", "ab|blood|button|type"],
  ["🆑", "cl button", "button|cl"],
  ["🆒", "cool button", "button|cool"],
  ["🆓", "free button", "button|free"],
  ["🆔", "id button", "button|id|identity"],
  ["🆕", "new button", "button|new"],
  ["🆖", "ng button", "button|ng"],
  ["🆗", "ok button", "button|ok|okay"],
  ["🆘", "sos button", "button|help|sos"],
  ["🆙", "up! button", "button|mark|up|up!"],
  ["🆚", "vs button", "button|versus|vs"],
  ["🇦🇩", "flag: andorra", "flag"],
  ["🇦🇪", "flag: united arab emirates", "flag"],
  ["🇦🇫", "flag: afghanistan", "flag"],
  ["🇦🇬", "flag: antigua & barbuda", "flag"],
  ["🇦🇮", "flag: anguilla", "flag"],
  ["🇦🇱", "flag: albania", "flag"],
  ["🇦🇲", "flag: armenia", "flag"],
  ["🇦🇴", "flag: angola", "flag"],
  ["🇦🇶", "flag: antarctica", "flag"],
  ["🇦🇷", "flag: argentina", "flag"],
  ["🇦🇸", "flag: american samoa", "flag"],
  ["🇦🇹", "flag: austria", "flag"],
  ["🇦🇺", "flag: australia", "flag"],
  ["🇦🇼", "flag: aruba", "flag"],
  ["🇦🇽", "flag: åland islands", "flag"],
  ["🇦🇿", "flag: azerbaijan", "flag"],
  ["🇧🇦", "flag: bosnia & herzegovina", "flag"],
  ["🇧🇧", "flag: barbados", "flag"],
  ["🇧🇩", "flag: bangladesh", "flag"],
  ["🇧🇪", "flag: belgium", "flag"],
  ["🇧🇫", "flag: burkina faso", "flag"],
  ["🇧🇬", "flag: bulgaria", "flag"],
  ["🇧🇭", "flag: bahrain", "flag"],
  ["🇧🇮", "flag: burundi", "flag"],
  ["🇧🇯", "flag: benin", "flag"],
  ["🇧🇱", "flag: st. barthélemy", "flag"],
  ["🇧🇲", "flag: bermuda", "flag"],
  ["🇧🇳", "flag: brunei", "flag"],
  ["🇧🇴", "flag: bolivia", "flag"],
  ["🇧🇶", "flag: caribbean netherlands", "flag"],
  ["🇧🇷", "flag: brazil", "flag"],
  ["🇧🇸", "flag: bahamas", "flag"],
  ["🇧🇹", "flag: bhutan", "flag"],
  ["🇧🇻", "flag: bouvet island", "flag"],
  ["🇧🇼", "flag: botswana", "flag"],
  ["🇧🇾", "flag: belarus", "flag"],
  ["🇧🇿", "flag: belize", "flag"],
  ["🇨🇦", "flag: canada", "flag"],
  ["🇨🇨", "flag: cocos (keeling) islands", "flag"],
  ["🇨🇩", "flag: congo - kinshasa", "flag"],
  ["🇨🇫", "flag: central african republic", "flag"],
  ["🇨🇬", "flag: congo - brazzaville", "flag"],
  ["🇨🇭", "flag: switzerland", "flag"],
  ["🇨🇮", "flag: côte d’ivoire", "flag"],
  ["🇨🇰", "flag: cook islands", "flag"],
  ["🇨🇱", "flag: chile", "flag"],
  ["🇨🇲", "flag: cameroon", "flag"],
  ["🇨🇳", "flag: china", "flag"],
  ["🇨🇴", "flag: colombia", "flag"],
  ["🇨🇷", "flag: costa rica", "flag"],
  ["🇨🇺", "flag: cuba", "flag"],
  ["🇨🇻", "flag: cape verde", "flag"],
  ["🇨🇼", "flag: curaçao", "flag"],
  ["🇨🇽", "flag: christmas island", "flag"],
  ["🇨🇾", "flag: cyprus", "flag"],
  ["🇨🇿", "flag: czechia", "flag"],
  ["🇩🇪", "flag: germany", "flag"],
  ["🇩🇯", "flag: djibouti", "flag"],
  ["🇩🇰", "flag: denmark", "flag"],
  ["🇩🇲", "flag: dominica", "flag"],
  ["🇩🇴", "flag: dominican republic", "flag"],
  ["🇩🇿", "flag: algeria", "flag"],
  ["🇪🇨", "flag: ecuador", "flag"],
  ["🇪🇪", "flag: estonia", "flag"],
  ["🇪🇬", "flag: egypt", "flag"],
  ["🇪🇭", "flag: western sahara", "flag"],
  ["🇪🇷", "flag: eritrea", "flag"],
  ["🇪🇸", "flag: spain", "flag"],
  ["🇪🇹", "flag: ethiopia", "flag"],
  ["🇫🇮", "flag: finland", "flag"],
  ["🇫🇯", "flag: fiji", "flag"],
  ["🇫🇰", "flag: falkland islands", "flag"],
  ["🇫🇲", "flag: micronesia", "flag"],
  ["🇫🇴", "flag: faroe islands", "flag"],
  ["🇫🇷", "flag: france", "flag"],
  ["🇬🇦", "flag: gabon", "flag"],
  ["🇬🇧", "flag: united kingdom", "flag"],
  ["🇬🇩", "flag: grenada", "flag"],
  ["🇬🇪", "flag: georgia", "flag"],
  ["🇬🇫", "flag: french guiana", "flag"],
  ["🇬🇬", "flag: guernsey", "flag"],
  ["🇬🇭", "flag: ghana", "flag"],
  ["🇬🇮", "flag: gibraltar", "flag"],
  ["🇬🇱", "flag: greenland", "flag"],
  ["🇬🇲", "flag: gambia", "flag"],
  ["🇬🇳", "flag: guinea", "flag"],
  ["🇬🇵", "flag: guadeloupe", "flag"],
  ["🇬🇶", "flag: equatorial guinea", "flag"],
  ["🇬🇷", "flag: greece", "flag"],
  ["🇬🇸", "flag: south georgia & south sandwich islands", "flag"],
  ["🇬🇹", "flag: guatemala", "flag"],
  ["🇬🇺", "flag: guam", "flag"],
  ["🇬🇼", "flag: guinea-bissau", "flag"],
  ["🇬🇾", "flag: guyana", "flag"],
  ["🇭🇰", "flag: hong kong sar china", "flag"],
  ["🇭🇲", "flag: heard & mcdonald islands", "flag"],
  ["🇭🇳", "flag: honduras", "flag"],
  ["🇭🇷", "flag: croatia", "flag"],
  ["🇭🇹", "flag: haiti", "flag"],
  ["🇭🇺", "flag: hungary", "flag"],
  ["🇮🇩", "flag: indonesia", "flag"],
  ["🇮🇪", "flag: ireland", "flag"],
  ["🇮🇱", "flag: israel", "flag"],
  ["🇮🇲", "flag: isle of man", "flag"],
  ["🇮🇳", "flag: india", "flag"],
  ["🇮🇴", "flag: british indian ocean territory", "flag"],
  ["🇮🇶", "flag: iraq", "flag"],
  ["🇮🇷", "flag: iran", "flag"],
  ["🇮🇸", "flag: iceland", "flag"],
  ["🇮🇹", "flag: italy", "flag"],
  ["🇯🇪", "flag: jersey", "flag"],
  ["🇯🇲", "flag: jamaica", "flag"],
  ["🇯🇴", "flag: jordan", "flag"],
  ["🇯🇵", "flag: japan", "flag"],
  ["🇰🇪", "flag: kenya", "flag"],
  ["🇰🇬", "flag: kyrgyzstan", "flag"],
  ["🇰🇭", "flag: cambodia", "flag"],
  ["🇰🇮", "flag: kiribati", "flag"],
  ["🇰🇲", "flag: comoros", "flag"],
  ["🇰🇳", "flag: st. kitts & nevis", "flag"],
  ["🇰🇵", "flag: north korea", "flag"],
  ["🇰🇷", "flag: south korea", "flag"],
  ["🇰🇼", "flag: kuwait", "flag"],
  ["🇰🇾", "flag: cayman islands", "flag"],
  ["🇰🇿", "flag: kazakhstan", "flag"],
  ["🇱🇦", "flag: laos", "flag"],
  ["🇱🇧", "flag: lebanon", "flag"],
  ["🇱🇨", "flag: st. lucia", "flag"],
  ["🇱🇮", "flag: liechtenstein", "flag"],
  ["🇱🇰", "flag: sri lanka", "flag"],
  ["🇱🇷", "flag: liberia", "flag"],
  ["🇱🇸", "flag: lesotho", "flag"],
  ["🇱🇹", "flag: lithuania", "flag"],
  ["🇱🇺", "flag: luxembourg", "flag"],
  ["🇱🇻", "flag: latvia", "flag"],
  ["🇱🇾", "flag: libya", "flag"],
  ["🇲🇦", "flag: morocco", "flag"],
  ["🇲🇨", "flag: monaco", "flag"],
  ["🇲🇩", "flag: moldova", "flag"],
  ["🇲🇪", "flag: montenegro", "flag"],
  ["🇲🇫", "flag: st. martin", "flag"],
  ["🇲🇬", "flag: madagascar", "flag"],
  ["🇲🇭", "flag: marshall islands", "flag"],
  ["🇲🇰", "flag: north macedonia", "flag"],
  ["🇲🇱", "flag: mali", "flag"],
  ["🇲🇲", "flag: myanmar (burma)", "flag"],
  ["🇲🇳", "flag: mongolia", "flag"],
  ["🇲🇴", "flag: macao sar china", "flag"],
  ["🇲🇵", "flag: northern mariana islands", "flag"],
  ["🇲🇶", "flag: martinique", "flag"],
  ["🇲🇷", "flag: mauritania", "flag"],
  ["🇲🇸", "flag: montserrat", "flag"],
  ["🇲🇹", "flag: malta", "flag"],
  ["🇲🇺", "flag: mauritius", "flag"],
  ["🇲🇻", "flag: maldives", "flag"],
  ["🇲🇼", "flag: malawi", "flag"],
  ["🇲🇽", "flag: mexico", "flag"],
  ["🇲🇾", "flag: malaysia", "flag"],
  ["🇲🇿", "flag: mozambique", "flag"],
  ["🇳🇦", "flag: namibia", "flag"],
  ["🇳🇨", "flag: new caledonia", "flag"],
  ["🇳🇪", "flag: niger", "flag"],
  ["🇳🇫", "flag: norfolk island", "flag"],
  ["🇳🇬", "flag: nigeria", "flag"],
  ["🇳🇮", "flag: nicaragua", "flag"],
  ["🇳🇱", "flag: netherlands", "flag"],
  ["🇳🇴", "flag: norway", "flag"],
  ["🇳🇵", "flag: nepal", "flag"],
  ["🇳🇷", "flag: nauru", "flag"],
  ["🇳🇺", "flag: niue", "flag"],
  ["🇳🇿", "flag: new zealand", "flag"],
  ["🇴🇲", "flag: oman", "flag"],
  ["🇵🇦", "flag: panama", "flag"],
  ["🇵🇪", "flag: peru", "flag"],
  ["🇵🇫", "flag: french polynesia", "flag"],
  ["🇵🇬", "flag: papua new guinea", "flag"],
  ["🇵🇭", "flag: philippines", "flag"],
  ["🇵🇰", "flag: pakistan", "flag"],
  ["🇵🇱", "flag: poland", "flag"],
  ["🇵🇲", "flag: st. pierre & miquelon", "flag"],
  ["🇵🇳", "flag: pitcairn islands", "flag"],
  ["🇵🇷", "flag: puerto rico", "flag"],
  ["🇵🇸", "flag: palestinian territories", "flag"],
  ["🇵🇹", "flag: portugal", "flag"],
  ["🇵🇼", "flag: palau", "flag"],
  ["🇵🇾", "flag: paraguay", "flag"],
  ["🇶🇦", "flag: qatar", "flag"],
  ["🇷🇪", "flag: réunion", "flag"],
  ["🇷🇴", "flag: romania", "flag"],
  ["🇷🇸", "flag: serbia", "flag"],
  ["🇷🇺", "flag: russia", "flag"],
  ["🇷🇼", "flag: rwanda", "flag"],
  ["🇸🇦", "flag: saudi arabia", "flag"],
  ["🇸🇧", "flag: solomon islands", "flag"],
  ["🇸🇨", "flag: seychelles", "flag"],
  ["🇸🇩", "flag: sudan", "flag"],
  ["🇸🇪", "flag: sweden", "flag"],
  ["🇸🇬", "flag: singapore", "flag"],
  ["🇸🇭", "flag: st. helena", "flag"],
  ["🇸🇮", "flag: slovenia", "flag"],
  ["🇸🇯", "flag: svalbard & jan mayen", "flag"],
  ["🇸🇰", "flag: slovakia", "flag"],
  ["🇸🇱", "flag: sierra leone", "flag"],
  ["🇸🇲", "flag: san marino", "flag"],
  ["🇸🇳", "flag: senegal", "flag"],
  ["🇸🇴", "flag: somalia", "flag"],
  ["🇸🇷", "flag: suriname", "flag"],
  ["🇸🇸", "flag: south sudan", "flag"],
  ["🇸🇹", "flag: são tomé & príncipe", "flag"],
  ["🇸🇻", "flag: el salvador", "flag"],
  ["🇸🇽", "flag: sint maarten", "flag"],
  ["🇸🇾", "flag: syria", "flag"],
  ["🇸🇿", "flag: eswatini", "flag"],
  ["🇹🇨", "flag: turks & caicos islands", "flag"],
  ["🇹🇩", "flag: chad", "flag"],
  ["🇹🇫", "flag: french southern territories", "flag"],
  ["🇹🇬", "flag: togo", "flag"],
  ["🇹🇭", "flag: thailand", "flag"],
  ["🇹🇯", "flag: tajikistan", "flag"],
  ["🇹🇰", "flag: tokelau", "flag"],
  ["🇹🇱", "flag: timor-leste", "flag"],
  ["🇹🇲", "flag: turkmenistan", "flag"],
  ["🇹🇳", "flag: tunisia", "flag"],
  ["🇹🇴", "flag: tonga", "flag"],
  ["🇹🇷", "flag: türkiye", "flag"],
  ["🇹🇹", "flag: trinidad & tobago", "flag"],
  ["🇹🇻", "flag: tuvalu", "flag"],
  ["🇹🇼", "flag: taiwan", "flag"],
  ["🇹🇿", "flag: tanzania", "flag"],
  ["🇺🇦", "flag: ukraine", "flag"],
  ["🇺🇬", "flag: uganda", "flag"],
  ["🇺🇲", "flag: u.s. outlying islands", "flag"],
  ["🇺🇸", "flag: united states", "flag"],
  ["🇺🇾", "flag: uruguay", "flag"],
  ["🇺🇿", "flag: uzbekistan", "flag"],
  ["🇻🇦", "flag: vatican city", "flag"],
  ["🇻🇨", "flag: st. vincent & grenadines", "flag"],
  ["🇻🇪", "flag: venezuela", "flag"],
  ["🇻🇬", "flag: british virgin islands", "flag"],
  ["🇻🇮", "flag: u.s. virgin islands", "flag"],
  ["🇻🇳", "flag: vietnam", "flag"],
  ["🇻🇺", "flag: vanuatu", "flag"],
  ["🇼🇫", "flag: wallis & futuna", "flag"],
  ["🇼🇸", "flag: samoa", "flag"],
  ["🇾🇪", "flag: yemen", "flag"],
  ["🇾🇹", "flag: mayotte", "flag"],
  ["🇿🇦", "flag: south africa", "flag"],
  ["🇿🇲", "flag: zambia", "flag"],
  ["🇿🇼", "flag: zimbabwe", "flag"],
  ["🈁", "japanese “here” button", "button|here|japanese|katakana"],
  ["🈂", "japanese “service charge” button", "button|charge|japanese|katakana|service"],
  ["🈚", "japanese “free of charge” button", "button|charge|free|ideograph|japanese"],
  ["🈯", "japanese “reserved” button", "button|ideograph|japanese|reserved"],
  ["🈲", "japanese “prohibited” button", "button|ideograph|japanese|prohibited"],
  ["🈳", "japanese “vacancy” button", "button|ideograph|japanese|vacancy"],
  ["🈴", "japanese “passing grade” button", "button|grade|ideograph|japanese|passing"],
  ["🈵", "japanese “no vacancy” button", "button|ideograph|japanese|no|vacancy"],
  ["🈶", "japanese “not free of charge” button", "button|charge|free|ideograph|japanese|not"],
  ["🈷", "japanese “monthly amount” button", "amount|button|ideograph|japanese|monthly"],
  ["🈸", "japanese “application” button", "application|button|ideograph|japanese"],
  ["🈹", "japanese “discount” button", "button|discount|ideograph|japanese"],
  ["🈺", "japanese “open for business” button", "business|button|ideograph|japanese|open"],
  ["🉐", "japanese “bargain” button", "bargain|button|ideograph|japanese"],
  ["🉑", "japanese “acceptable” button", "acceptable|button|ideograph|japanese"],
  ["🌀", "cyclone", "dizzy|hurricane|twister|typhoon|weather"],
  ["🌁", "foggy", "fog"],
  ["🌂", "closed umbrella", "closed|clothing|rain|umbrella"],
  ["🌃", "night with stars", "night|star|stars"],
  ["🌄", "sunrise over mountains", "morning|mountains|over|sun|sunrise"],
  ["🌅", "sunrise", "morning|nature|sun"],
  ["🌆", "cityscape at dusk", "at|building|city|cityscape|dusk|evening|landscape|sun|sunset"],
  ["🌇", "sunset", "building|dusk|sun"],
  ["🌈", "rainbow", "gay|genderqueer|glbt|glbtq|lesbian|lgbt|lgbtq|lgbtqia|nature|pride|queer|rain|trans|transgender|weather"],
  ["🌉", "bridge at night", "at|bridge|night"],
  ["🌊", "water wave", "nature|ocean|surf|surfer|surfing|water|wave"],
  ["🌋", "volcano", "eruption|mountain|nature"],
  ["🌌", "milky way", "milky|space|way"],
  ["🌍", "globe showing europe-africa", "africa|earth|europe|europe-africa|globe|showing|world"],
  ["🌎", "globe showing americas", "americas|earth|globe|showing|world"],
  ["🌏", "globe showing asia-australia", "asia|asia-australia|australia|earth|globe|showing|world"],
  ["🌐", "globe with meridians", "earth|globe|internet|meridians|web|world|worldwide"],
  ["🌑", "new moon", "dark|moon|new|space"],
  ["🌒", "waxing crescent moon", "crescent|dreams|moon|space|waxing"],
  ["🌓", "first quarter moon", "first|moon|quarter|space"],
  ["🌔", "waxing gibbous moon", "gibbous|moon|space|waxing"],
  ["🌕", "full moon", "full|moon|space"],
  ["🌖", "waning gibbous moon", "gibbous|moon|space|waning"],
  ["🌗", "last quarter moon", "last|moon|quarter|space"],
  ["🌘", "waning crescent moon", "crescent|moon|space|waning"],
  ["🌙", "crescent moon", "crescent|moon|ramadan|space"],
  ["🌚", "new moon face", "face|moon|new|space"],
  ["🌛", "first quarter moon face", "face|first|moon|quarter|space"],
  ["🌜", "last quarter moon face", "dreams|face|last|moon|quarter"],
  ["🌝", "full moon face", "bright|face|full|moon"],
  ["🌞", "sun with face", "beach|bright|day|face|heat|shine|sun|sunny|sunshine|weather"],
  ["🌟", "glowing star", "glittery|glow|glowing|night|shining|sparkle|star|win"],
  ["🌠", "shooting star", "falling|night|shooting|space|star"],
  ["🌡", "thermometer", "weather"],
  ["🌤", "sun behind small cloud", "behind|cloud|sun|weather"],
  ["🌥", "sun behind large cloud", "behind|cloud|sun|weather"],
  ["🌦", "sun behind rain cloud", "behind|cloud|rain|sun|weather"],
  ["🌧", "cloud with rain", "cloud|rain|weather"],
  ["🌨", "cloud with snow", "cloud|cold|snow|weather"],
  ["🌩", "cloud with lightning", "cloud|lightning|weather"],
  ["🌪", "tornado", "cloud|weather|whirlwind"],
  ["🌫", "fog", "cloud|weather"],
  ["🌬", "wind face", "blow|cloud|face|wind"],
  ["🌭", "hot dog", "dog|frankfurter|hot|hotdog|sausage"],
  ["🌮", "taco", "mexican"],
  ["🌯", "burrito", "mexican|wrap"],
  ["🌰", "chestnut", "almond|plant"],
  ["🌱", "seedling", "plant|sapling|sprout|young"],
  ["🌲", "evergreen tree", "christmas|evergreen|forest|pine|tree"],
  ["🌳", "deciduous tree", "deciduous|forest|green|habitat|shedding|tree"],
  ["🌴", "palm tree", "beach|palm|plant|tree|tropical"],
  ["🌵", "cactus", "desert|drought|nature|plant"],
  ["🌶", "hot pepper", "hot|pepper"],
  ["🌷", "tulip", "blossom|flower|growth|plant"],
  ["🌸", "cherry blossom", "blossom|cherry|flower|plant|spring|springtime"],
  ["🌹", "rose", "beauty|elegant|flower|love|plant|red|valentine"],
  ["🌺", "hibiscus", "flower|plant"],
  ["🌻", "sunflower", "flower|outdoors|plant|sun"],
  ["🌼", "blossom", "buttercup|dandelion|flower|plant"],
  ["🌽", "ear of corn", "corn|crops|ear|farm|maize|maze"],
  ["🌾", "sheaf of rice", "ear|grain|grains|plant|rice|sheaf"],
  ["🌿", "herb", "leaf|plant"],
  ["🍀", "four leaf clover", "4|clover|four|four-leaf|irish|leaf|lucky|plant"],
  ["🍁", "maple leaf", "falling|leaf|maple"],
  ["🍂", "fallen leaf", "autumn|fall|fallen|falling|leaf"],
  ["🍃", "leaf fluttering in wind", "blow|flutter|fluttering|leaf|wind"],
  ["🍄", "mushroom", "fungus|toadstool"],
  ["🍅", "tomato", "food|fruit|vegetable"],
  ["🍆", "eggplant", "aubergine|vegetable"],
  ["🍇", "grapes", "dionysus|fruit|grape"],
  ["🍈", "melon", "cantaloupe|fruit"],
  ["🍉", "watermelon", "fruit"],
  ["🍊", "tangerine", "c|citrus|fruit|nectarine|orange|vitamin"],
  ["🍋", "lemon", "citrus|fruit|sour"],
  ["🍌", "banana", "fruit|potassium"],
  ["🍍", "pineapple", "colada|fruit|pina|tropical"],
  ["🍎", "red apple", "apple|diet|food|fruit|health|red|ripe"],
  ["🍏", "green apple", "apple|fruit|green"],
  ["🍐", "pear", "fruit"],
  ["🍑", "peach", "fruit"],
  ["🍒", "cherries", "berries|cherry|fruit|red"],
  ["🍓", "strawberry", "berry|fruit"],
  ["🍔", "hamburger", "burger|eat|fast|food|hungry"],
  ["🍕", "pizza", "cheese|food|hungry|pepperoni|slice"],
  ["🍖", "meat on bone", "bone|meat"],
  ["🍗", "poultry leg", "bone|chicken|drumstick|hungry|leg|poultry|turkey"],
  ["🍘", "rice cracker", "cracker|food|rice"],
  ["🍙", "rice ball", "ball|food|japanese|rice"],
  ["🍚", "cooked rice", "cooked|food|rice"],
  ["🍛", "curry rice", "curry|food|rice"],
  ["🍜", "steaming bowl", "bowl|chopsticks|food|noodle|pho|ramen|soup|steaming"],
  ["🍝", "spaghetti", "food|meatballs|pasta|restaurant"],
  ["🍞", "bread", "carbs|food|grain|loaf|restaurant|toast|wheat"],
  ["🍟", "french fries", "fast|food|french|fries"],
  ["🍠", "roasted sweet potato", "food|potato|roasted|sweet"],
  ["🍡", "dango", "dessert|japanese|skewer|stick|sweet"],
  ["🍢", "oden", "food|kebab|restaurant|seafood|skewer|stick"],
  ["🍣", "sushi", "food"],
  ["🍤", "fried shrimp", "fried|prawn|shrimp|tempura"],
  ["🍥", "fish cake with swirl", "cake|fish|food|pastry|restaurant|swirl"],
  ["🍦", "soft ice cream", "cream|dessert|food|ice|icecream|restaurant|serve|soft|sweet"],
  ["🍧", "shaved ice", "dessert|ice|restaurant|shaved|sweet"],
  ["🍨", "ice cream", "cream|dessert|food|ice|restaurant|sweet"],
  ["🍩", "doughnut", "breakfast|dessert|donut|food|sweet"],
  ["🍪", "cookie", "chip|chocolate|dessert|sweet"],
  ["🍫", "chocolate bar", "bar|candy|chocolate|dessert|halloween|sweet|tooth"],
  ["🍬", "candy", "cavities|dessert|halloween|restaurant|sweet|tooth|wrapper"],
  ["🍭", "lollipop", "candy|dessert|food|restaurant|sweet"],
  ["🍮", "custard", "dessert|pudding|sweet"],
  ["🍯", "honey pot", "barrel|bear|food|honey|honeypot|jar|pot|sweet"],
  ["🍰", "shortcake", "cake|dessert|pastry|slice|sweet"],
  ["🍱", "bento box", "bento|box|food"],
  ["🍲", "pot of food", "food|pot|soup|stew"],
  ["🍳", "cooking", "breakfast|easy|egg|fry|frying|over|pan|restaurant|side|sunny|up"],
  ["🍴", "fork and knife", "breakfast|breaky|cooking|cutlery|delicious|dinner|eat|feed|food|fork|hungry|knife|lunch|restaurant|yum|yummy"],
  ["🍵", "teacup without handle", "beverage|cup|drink|handle|oolong|tea|teacup"],
  ["🍶", "sake", "bar|beverage|bottle|cup|drink|restaurant"],
  ["🍷", "wine glass", "alcohol|bar|beverage|booze|club|drink|drinking|drinks|glass|restaurant|wine"],
  ["🍸", "cocktail glass", "alcohol|bar|booze|club|cocktail|drink|drinking|drinks|glass|mad|martini|men"],
  ["🍹", "tropical drink", "alcohol|bar|booze|club|cocktail|drink|drinking|drinks|drunk|mai|party|tai|tropical|tropics"],
  ["🍺", "beer mug", "alcohol|ale|bar|beer|booze|drink|drinking|drinks|mug|octoberfest|oktoberfest|pint|stein|summer"],
  ["🍻", "clinking beer mugs", "alcohol|bar|beer|booze|bottoms|cheers|clink|clinking|drinking|drinks|mugs"],
  ["🍼", "baby bottle", "babies|baby|birth|born|bottle|drink|infant|milk|newborn"],
  ["🍽", "fork and knife with plate", "cooking|dinner|eat|fork|knife|plate"],
  ["🍾", "bottle with popping cork", "bar|bottle|cork|drink|popping"],
  ["🍿", "popcorn", "corn|movie|pop"],
  ["🎀", "ribbon", "celebration"],
  ["🎁", "wrapped gift", "birthday|bow|box|celebration|christmas|gift|present|surprise|wrapped"],
  ["🎂", "birthday cake", "bday|birthday|cake|celebration|dessert|happy|pastry|sweet"],
  ["🎃", "jack-o-lantern", "celebration|halloween|jack|lantern|pumpkin"],
  ["🎄", "christmas tree", "celebration|christmas|tree"],
  ["🎅", "santa claus", "celebration|christmas|claus|fairy|fantasy|father|holiday|merry|santa|tale|xmas"],
  ["🎆", "fireworks", "boom|celebration|entertainment|yolo"],
  ["🎇", "sparkler", "boom|celebration|fireworks|sparkle"],
  ["🎈", "balloon", "birthday|celebrate|celebration"],
  ["🎉", "party popper", "awesome|birthday|celebrate|celebration|excited|hooray|party|popper|tada|woohoo"],
  ["🎊", "confetti ball", "ball|celebrate|celebration|confetti|party|woohoo"],
  ["🎋", "tanabata tree", "banner|celebration|japanese|tanabata|tree"],
  ["🎌", "crossed flags", "celebration|cross|crossed|flags|japanese"],
  ["🎍", "pine decoration", "bamboo|celebration|decoration|japanese|pine|plant"],
  ["🎎", "japanese dolls", "celebration|doll|dolls|festival|japanese"],
  ["🎏", "carp streamer", "carp|celebration|streamer"],
  ["🎐", "wind chime", "bell|celebration|chime|wind"],
  ["🎑", "moon viewing ceremony", "celebration|ceremony|moon|viewing"],
  ["🎒", "backpack", "backpacking|bag|bookbag|education|rucksack|satchel|school"],
  ["🎓", "graduation cap", "cap|celebration|clothing|education|graduation|hat|scholar"],
  ["🎖", "military medal", "award|celebration|medal|military"],
  ["🎗", "reminder ribbon", "celebration|reminder|ribbon"],
  ["🎙", "studio microphone", "mic|microphone|music|studio"],
  ["🎚", "level slider", "level|music|slider"],
  ["🎛", "control knobs", "control|knobs|music"],
  ["🎞", "film frames", "cinema|film|frames|movie"],
  ["🎟", "admission tickets", "admission|ticket|tickets"],
  ["🎠", "carousel horse", "carousel|entertainment|horse"],
  ["🎡", "ferris wheel", "amusement|ferris|park|theme|wheel"],
  ["🎢", "roller coaster", "amusement|coaster|park|roller|theme"],
  ["🎣", "fishing pole", "entertainment|fish|fishing|pole|sport"],
  ["🎤", "microphone", "karaoke|mic|music|sing|sound"],
  ["🎥", "movie camera", "bollywood|camera|cinema|film|hollywood|movie|record"],
  ["🎦", "cinema", "camera|film|movie"],
  ["🎧", "headphone", "earbud|sound"],
  ["🎨", "artist palette", "art|artist|artsy|arty|colorful|creative|entertainment|museum|painter|painting|palette"],
  ["🎩", "top hat", "clothes|clothing|fancy|formal|hat|magic|top|tophat"],
  ["🎪", "circus tent", "circus|tent"],
  ["🎫", "ticket", "admission|stub"],
  ["🎬", "clapper board", "action|board|clapper|movie"],
  ["🎭", "performing arts", "actor|actress|art|arts|entertainment|mask|performing|theater|theatre|thespian"],
  ["🎮", "video game", "controller|entertainment|game|video"],
  ["🎯", "bullseye", "bull|dart|direct|entertainment|game|hit|target"],
  ["🎰", "slot machine", "casino|gamble|gambling|game|machine|slot|slots"],
  ["🎱", "pool 8 ball", "8|8ball|ball|billiard|eight|game|pool"],
  ["🎲", "game die", "dice|die|entertainment|game"],
  ["🎳", "bowling", "ball|game|sport|strike"],
  ["🎴", "flower playing cards", "card|cards|flower|game|japanese|playing"],
  ["🎵", "musical note", "music|musical|note|sound"],
  ["🎶", "musical notes", "music|musical|note|notes|sound"],
  ["🎷", "saxophone", "instrument|music|sax"],
  ["🎸", "guitar", "instrument|music|strat"],
  ["🎹", "musical keyboard", "instrument|keyboard|music|musical|piano"],
  ["🎺", "trumpet", "instrument|music"],
  ["🎻", "violin", "instrument|music"],
  ["🎼", "musical score", "music|musical|note|score"],
  ["🎽", "running shirt", "athletics|running|sash|shirt"],
  ["🎾", "tennis", "ball|racquet|sport"],
  ["🎿", "skis", "ski|snow|sport"],
  ["🏀", "basketball", "ball|hoop|sport"],
  ["🏁", "chequered flag", "checkered|chequered|finish|flag|flags|game|race|racing|sport|win"],
  ["🏂", "snowboarder", "ski|snow|snowboard|sport"],
  ["🏃", "person running", "fast|hurry|marathon|move|person|quick|race|racing|run|rush|speed"],
  ["🏄", "person surfing", "beach|ocean|person|sport|surf|surfer|surfing|swell|waves"],
  ["🏅", "sports medal", "award|gold|medal|sports|winner"],
  ["🏆", "trophy", "champion|champs|prize|slay|sport|victory|win|winning"],
  ["🏇", "horse racing", "horse|jockey|racehorse|racing|riding|sport"],
  ["🏈", "american football", "american|ball|bowl|football|sport|super"],
  ["🏉", "rugby football", "ball|football|rugby|sport"],
  ["🏊", "person swimming", "freestyle|person|sport|swim|swimmer|swimming|triathlon"],
  ["🏋", "person lifting weights", "barbell|bodybuilder|deadlift|lifter|lifting|person|powerlifting|weight|weightlifter|weights|workout"],
  ["🏌", "person golfing", "ball|birdie|caddy|driving|golf|golfing|green|person|pga|putt|range|tee"],
  ["🏍", "motorcycle", "racing"],
  ["🏎", "racing car", "car|racing|zoom"],
  ["🏏", "cricket game", "ball|bat|cricket|game"],
  ["🏐", "volleyball", "ball|game"],
  ["🏑", "field hockey", "ball|field|game|hockey|stick"],
  ["🏒", "ice hockey", "game|hockey|ice|puck|stick"],
  ["🏓", "ping pong", "ball|bat|game|paddle|ping|pingpong|pong|table|tennis"],
  ["🏔", "snow-capped mountain", "cold|mountain|snow|snow-capped"],
  ["🏕", "camping", ""],
  ["🏖", "beach with umbrella", "beach|umbrella"],
  ["🏗", "building construction", "building|construction|crane"],
  ["🏘", "houses", "house"],
  ["🏙", "cityscape", "city"],
  ["🏚", "derelict house", "derelict|home|house"],
  ["🏛", "classical building", "building|classical"],
  ["🏜", "desert", ""],
  ["🏝", "desert island", "desert|island"],
  ["🏞", "national park", "national|park"],
  ["🏟", "stadium", ""],
  ["🏠", "house", "building|country|heart|home|ranch|settle|simple|suburban|suburbia|where"],
  ["🏡", "house with garden", "building|country|garden|heart|home|house|ranch|settle|simple|suburban|suburbia|where"],
  ["🏢", "office building", "building|city|cubical|job|office"],
  ["🏣", "japanese post office", "building|japanese|office|post"],
  ["🏤", "post office", "building|european|office|post"],
  ["🏥", "hospital", "building|doctor|medicine"],
  ["🏦", "bank", "building"],
  ["🏧", "atm sign", "atm|automated|bank|cash|money|sign|teller"],
  ["🏨", "hotel", "building"],
  ["🏩", "love hotel", "building|hotel|love"],
  ["🏪", "convenience store", "24|building|convenience|hours|store"],
  ["🏫", "school", "building"],
  ["🏬", "department store", "building|department|store"],
  ["🏭", "factory", "building"],
  ["🏮", "red paper lantern", "bar|lantern|light|paper|red|restaurant"],
  ["🏯", "japanese castle", "building|castle|japanese"],
  ["🏰", "castle", "building|european"],
  ["🏵", "rosette", "plant"],
  ["🏷", "label", "tag"],
  ["🏸", "badminton", "birdie|game|racquet|shuttlecock"],
  ["🏹", "bow and arrow", "archer|archery|arrow|bow|sagittarius|tool|weapon|zodiac"],
  ["🏺", "amphora", "aquarius|cooking|drink|jug|tool|weapon|zodiac"],
  ["🐀", "rat", "animal"],
  ["🐁", "mouse", "animal|animals"],
  ["🐂", "ox", "animal|animals|bull|farm|taurus|zodiac"],
  ["🐃", "water buffalo", "animal|buffalo|water|zoo"],
  ["🐄", "cow", "animal|animals|farm|milk|moo"],
  ["🐅", "tiger", "animal|big|cat|predator|zoo"],
  ["🐆", "leopard", "animal|big|cat|predator|zoo"],
  ["🐇", "rabbit", "animal|bunny|pet"],
  ["🐈", "cat", "animal|animals|cats|kitten|pet"],
  ["🐉", "dragon", "animal|fairy|fairytale|knights|tale"],
  ["🐊", "crocodile", "animal|zoo"],
  ["🐋", "whale", "animal|beach|ocean"],
  ["🐌", "snail", "animal|escargot|garden|nature|slug"],
  ["🐍", "snake", "animal|bearer|ophiuchus|serpent|zodiac"],
  ["🐎", "horse", "animal|equestrian|farm|racehorse|racing"],
  ["🐏", "ram", "animal|aries|horns|male|sheep|zodiac|zoo"],
  ["🐐", "goat", "animal|capricorn|farm|milk|zodiac"],
  ["🐑", "ewe", "animal|baa|farm|female|fluffy|lamb|sheep|wool"],
  ["🐒", "monkey", "animal|banana"],
  ["🐓", "rooster", "animal|bird|ornithology"],
  ["🐔", "chicken", "animal|bird|ornithology"],
  ["🐕", "dog", "animal|animals|dogs|pet"],
  ["🐖", "pig", "animal|bacon|farm|pork|sow"],
  ["🐗", "boar", "animal|pig"],
  ["🐘", "elephant", "animal"],
  ["🐙", "octopus", "animal|creature|ocean"],
  ["🐚", "spiral shell", "animal|beach|conch|sea|shell|spiral"],
  ["🐛", "bug", "animal|garden|insect"],
  ["🐜", "ant", "animal|garden|insect"],
  ["🐝", "honeybee", "animal|bee|bumblebee|honey|insect|nature|spring"],
  ["🐞", "lady beetle", "animal|beetle|garden|insect|lady|ladybird|ladybug|nature"],
  ["🐟", "fish", "animal|dinner|fishes|fishing|pisces|zodiac"],
  ["🐠", "tropical fish", "animal|fish|fishes|tropical"],
  ["🐡", "blowfish", "animal|fish"],
  ["🐢", "turtle", "animal|terrapin|tortoise"],
  ["🐣", "hatching chick", "animal|baby|bird|chick|egg|hatching"],
  ["🐤", "baby chick", "animal|baby|bird|chick|ornithology"],
  ["🐥", "front-facing baby chick", "animal|baby|bird|chick|front-facing|newborn|ornithology"],
  ["🐦", "bird", "animal|ornithology"],
  ["🐧", "penguin", "animal|antarctica|bird|ornithology"],
  ["🐨", "koala", "animal|australia|bear|down|face|marsupial|under"],
  ["🐩", "poodle", "animal|dog|fluffy"],
  ["🐪", "camel", "animal|desert|dromedary|hump|one"],
  ["🐫", "two-hump camel", "animal|bactrian|camel|desert|hump|two|two-hump"],
  ["🐬", "dolphin", "animal|beach|flipper|ocean"],
  ["🐭", "mouse face", "animal|face|mouse"],
  ["🐮", "cow face", "animal|cow|face|farm|milk|moo"],
  ["🐯", "tiger face", "animal|big|cat|face|predator|tiger"],
  ["🐰", "rabbit face", "animal|bunny|face|pet|rabbit"],
  ["🐱", "cat face", "animal|cat|face|kitten|kitty|pet"],
  ["🐲", "dragon face", "animal|dragon|face|fairy|fairytale|tale"],
  ["🐳", "spouting whale", "animal|beach|face|ocean|spouting|whale"],
  ["🐴", "horse face", "animal|dressage|equine|face|farm|horse|horses"],
  ["🐵", "monkey face", "animal|banana|face|monkey"],
  ["🐶", "dog face", "adorbs|animal|dog|face|pet|puppies|puppy"],
  ["🐷", "pig face", "animal|bacon|face|farm|pig|pork"],
  ["🐸", "frog", "animal|face"],
  ["🐹", "hamster", "animal|face|pet"],
  ["🐺", "wolf", "animal|face"],
  ["🐻", "bear", "animal|face|grizzly|growl|honey"],
  ["🐼", "panda", "animal|bamboo|face"],
  ["🐽", "pig nose", "animal|face|farm|nose|pig|smell|snout"],
  ["🐾", "paw prints", "feet|paw|paws|print|prints"],
  ["🐿", "chipmunk", "animal|squirrel"],
  ["👀", "eyes", "body|eye|face|googly|look|looking|omg|peep|see|seeing"],
  ["👁", "eye", "1|body|one"],
  ["👂", "ear", "body|ears|hear|hearing|listen|listening|sound"],
  ["👃", "nose", "body|noses|nosey|odor|smell|smells"],
  ["👄", "mouth", "beauty|body|kiss|kissing|lips|lipstick"],
  ["👅", "tongue", "body|lick|slurp"],
  ["👆", "backhand index pointing up", "backhand|finger|hand|index|point|pointing|up"],
  ["👇", "backhand index pointing down", "backhand|down|finger|hand|index|point|pointing"],
  ["👈", "backhand index pointing left", "backhand|finger|hand|index|left|point|pointing"],
  ["👉", "backhand index pointing right", "backhand|finger|hand|index|point|pointing|right"],
  ["👊", "oncoming fist", "absolutely|agree|boom|bro|bruh|bump|clenched|correct|fist|hand|knuckle|oncoming|pound|punch|rock|ttyl"],
  ["👋", "waving hand", "bye|cya|g2g|greetings|gtg|hand|hello|hey|hi|later|outtie|ttfn|ttyl|wave|yo|you"],
  ["👌", "ok hand", "awesome|bet|dope|fleek|fosho|got|gotcha|hand|legit|ok|okay|pinch|rad|sure|sweet|three"],
  ["👍", "thumbs up", "+1|good|hand|like|thumb|up|yes"],
  ["👎", "thumbs down", "-1|bad|dislike|down|good|hand|no|nope|thumb|thumbs"],
  ["👏", "clapping hands", "applause|approval|awesome|clap|congrats|congratulations|excited|good|great|hand|homie|job|nice|prayed|well|yay"],
  ["👐", "open hands", "hand|hands|hug|jazz|open|swerve"],
  ["👑", "crown", "clothing|family|king|medieval|queen|royal|royalty|win"],
  ["👒", "woman’s hat", "clothes|clothing|garden|hat|hats|party|woman|woman’s"],
  ["👓", "glasses", "clothing|eye|eyeglasses|eyewear"],
  ["👔", "necktie", "clothing|employed|serious|shirt|tie"],
  ["👕", "t-shirt", "blue|casual|clothes|clothing|collar|dressed|shirt|shopping|tshirt|weekend"],
  ["👖", "jeans", "blue|casual|clothes|clothing|denim|dressed|pants|shopping|trousers|weekend"],
  ["👗", "dress", "clothes|clothing|dressed|fancy|shopping"],
  ["👘", "kimono", "clothing|comfortable"],
  ["👙", "bikini", "bathing|beach|clothing|pool|suit|swim"],
  ["👚", "woman’s clothes", "blouse|clothes|clothing|collar|dress|dressed|lady|shirt|shopping|woman|woman’s"],
  ["👛", "purse", "clothes|clothing|coin|dress|fancy|handbag|shopping"],
  ["👜", "handbag", "bag|clothes|clothing|dress|lady|purse|shopping"],
  ["👝", "clutch bag", "bag|clothes|clothing|clutch|dress|handbag|pouch|purse"],
  ["👞", "man’s shoe", "brown|clothes|clothing|feet|foot|kick|man|man’s|shoe|shoes|shopping"],
  ["👟", "running shoe", "athletic|clothes|clothing|fast|kick|running|shoe|shoes|shopping|sneaker|tennis"],
  ["👠", "high-heeled shoe", "clothes|clothing|dress|fashion|heel|heels|high-heeled|shoe|shoes|shopping|stiletto|woman"],
  ["👡", "woman’s sandal", "clothing|sandal|shoe|woman|woman’s"],
  ["👢", "woman’s boot", "boot|clothes|clothing|dress|shoe|shoes|shopping|woman|woman’s"],
  ["👣", "footprints", "barefoot|clothing|footprint|omw|print|walk"],
  ["👤", "bust in silhouette", "bust|mysterious|shadow|silhouette"],
  ["👥", "busts in silhouette", "bff|bust|busts|everyone|friend|friends|people|silhouette"],
  ["👦", "boy", "bright-eyed|child|grandson|kid|son|young|younger"],
  ["👧", "girl", "bright-eyed|child|daughter|granddaughter|kid|virgo|young|younger|zodiac"],
  ["👨", "man", "adult|bro"],
  ["👩", "woman", "adult|lady"],
  ["👪", "family", "child"],
  ["👫", "woman and man holding hands", "bae|bestie|bff|couple|dating|flirt|friends|hand|hold|man|twins|woman"],
  ["👬", "men holding hands", "bae|bestie|bff|boys|brothers|couple|dating|flirt|friends|hand|hold|men|twins"],
  ["👭", "women holding hands", "bae|bestie|bff|couple|dating|flirt|friends|girls|hand|hold|sisters|twins|women"],
  ["👮", "police officer", "apprehend|arrest|citation|cop|law|officer|over|police|pulled|undercover"],
  ["👯", "people with bunny ears", "bestie|bff|bunny|counterpart|dancer|double|ear|identical|pair|party|partying|people|soulmate|twin|twinsies"],
  ["👰", "person with veil", "person|veil|wedding"],
  ["👱", "person: blond hair", "blond|blond-haired|human|person"],
  ["👲", "person with skullcap", "cap|chinese|gua|guapi|hat|mao|person|pi|skullcap"],
  ["👳", "person wearing turban", "person|turban|wearing"],
  ["👴", "old man", "adult|bald|elderly|gramps|grandfather|grandpa|man|old|wise"],
  ["👵", "old woman", "adult|elderly|grandma|grandmother|granny|lady|old|wise|woman"],
  ["👶", "baby", "babies|children|goo|infant|newborn|pregnant|young"],
  ["👷", "construction worker", "build|construction|fix|hardhat|hat|man|person|rebuild|remodel|repair|work|worker"],
  ["👸", "princess", "crown|fairy|fairytale|fantasy|queen|royal|royalty|tale"],
  ["👹", "ogre", "creature|devil|face|fairy|fairytale|fantasy|mask|monster|scary|tale"],
  ["👺", "goblin", "angry|creature|face|fairy|fairytale|fantasy|mask|mean|monster|tale"],
  ["👻", "ghost", "boo|creature|excited|face|fairy|fairytale|fantasy|halloween|haunting|monster|scary|silly|tale"],
  ["👼", "baby angel", "angel|baby|church|face|fairy|fairytale|fantasy|tale"],
  ["👽", "alien", "creature|extraterrestrial|face|fairy|fairytale|fantasy|monster|space|tale|ufo"],
  ["👾", "alien monster", "alien|creature|extraterrestrial|face|fairy|fairytale|fantasy|game|gamer|games|monster|pixelated|space|tale|ufo"],
  ["👿", "angry face with horns", "angry|demon|devil|evil|face|fairy|fairytale|fantasy|horns|imp|mischievous|purple|shade|tale"],
  ["💀", "skull", "body|dead|death|face|fairy|fairytale|i’m|lmao|monster|tale|yolo"],
  ["💁", "person tipping hand", "fetch|flick|flip|gossip|hand|person|sarcasm|sarcastic|sassy|seriously|tipping|whatever"],
  ["💂", "guard", "buckingham|helmet|london|palace"],
  ["💃", "woman dancing", "dance|dancer|dancing|elegant|festive|flair|flamenco|groove|let’s|salsa|tango|woman"],
  ["💄", "lipstick", "cosmetics|date|makeup"],
  ["💅", "nail polish", "bored|care|cosmetics|done|makeup|manicure|nail|polish|whatever"],
  ["💆", "person getting massage", "face|getting|headache|massage|person|relax|relaxing|salon|soothe|spa|tension|therapy|treatment"],
  ["💇", "person getting haircut", "barber|beauty|chop|cosmetology|cut|groom|hair|haircut|parlor|person|shears|style"],
  ["💈", "barber pole", "barber|cut|fresh|haircut|pole|shave"],
  ["💉", "syringe", "doctor|flu|medicine|needle|shot|sick|tool|vaccination"],
  ["💊", "pill", "doctor|drugs|medicated|medicine|pills|sick|vitamin"],
  ["💋", "kiss mark", "dating|emotion|heart|kiss|kissing|lips|mark|romance|sexy"],
  ["💌", "love letter", "heart|letter|love|mail|romance|valentine"],
  ["💍", "ring", "diamond|engaged|engagement|married|romance|shiny|sparkling|wedding"],
  ["💎", "gem stone", "diamond|engagement|gem|jewel|money|romance|stone|wedding"],
  ["💏", "kiss", "anniversary|babe|bae|couple|date|dating|heart|love|mwah|person|romance|together|xoxo"],
  ["💐", "bouquet", "anniversary|birthday|date|flower|love|plant|romance"],
  ["💑", "couple with heart", "anniversary|babe|bae|couple|dating|heart|kiss|love|person|relationship|romance|together|you"],
  ["💒", "wedding", "chapel|hitched|nuptials|romance"],
  ["💓", "beating heart", "143|beating|cardio|emotion|heart|heartbeat|ily|love|pulsating|pulse"],
  ["💔", "broken heart", "break|broken|crushed|emotion|heart|heartbroken|lonely|sad"],
  ["💕", "two hearts", "143|anniversary|date|dating|emotion|heart|hearts|ily|kisses|love|loving|two|xoxo"],
  ["💖", "sparkling heart", "143|emotion|excited|good|heart|ily|kisses|morning|night|sparkle|sparkling|xoxo"],
  ["💗", "growing heart", "143|emotion|excited|growing|heart|heartpulse|ily|kisses|muah|nervous|pulse|xoxo"],
  ["💘", "heart with arrow", "143|adorbs|arrow|cupid|date|emotion|heart|ily|love|romance|valentine"],
  ["💙", "blue heart", "143|blue|emotion|heart|ily|love|romance"],
  ["💚", "green heart", "143|emotion|green|heart|ily|love|romantic"],
  ["💛", "yellow heart", "143|cardiac|emotion|heart|ily|love|yellow"],
  ["💜", "purple heart", "143|bestest|emotion|heart|ily|love|purple"],
  ["💝", "heart with ribbon", "143|anniversary|emotion|heart|ily|kisses|ribbon|valentine|xoxo"],
  ["💞", "revolving hearts", "143|adorbs|anniversary|emotion|heart|hearts|revolving"],
  ["💟", "heart decoration", "143|decoration|emotion|heart|hearth|purple|white"],
  ["💠", "diamond with a dot", "comic|diamond|dot|geometric"],
  ["💡", "light bulb", "bulb|comic|electric|idea|light"],
  ["💢", "anger symbol", "anger|angry|comic|mad|symbol|upset"],
  ["💣", "bomb", "boom|comic|dangerous|explosion|hot"],
  ["💤", "zzz", "comic|good|goodnight|night|sleep|sleeping|sleepy|tired"],
  ["💥", "collision", "bomb|boom|collide|comic|explode"],
  ["💦", "sweat droplets", "comic|drip|droplet|droplets|drops|splashing|squirt|sweat|water|wet|work|workout"],
  ["💧", "droplet", "cold|comic|drop|nature|sad|sweat|tear|water|weather"],
  ["💨", "dashing away", "away|cloud|comic|dash|dashing|fart|fast|go|gone|gotta|running|smoke"],
  ["💩", "pile of poo", "bs|comic|doo|dung|face|fml|monster|pile|poo|poop|smelly|smh|stink|stinks|stinky|turd"],
  ["💪", "flexed biceps", "arm|beast|bench|biceps|bodybuilder|bro|curls|flex|gains|gym|jacked|muscle|press|ripped|strong|weightlift"],
  ["💫", "dizzy", "comic|shining|shooting|star|stars"],
  ["💬", "speech balloon", "balloon|bubble|comic|dialog|message|sms|speech|talk|text|typing"],
  ["💭", "thought balloon", "balloon|bubble|cartoon|cloud|comic|daydream|decisions|dream|idea|invent|invention|realize|think|thoughts|wonder"],
  ["💮", "white flower", "flower|white"],
  ["💯", "hundred points", "100|a+|agree|clearly|definitely|faithful|fleek|full|hundred|keep|perfect|point|score|true|truth|yup"],
  ["💰", "money bag", "bag|bank|bet|billion|cash|cost|dollar|gold|million|money|moneybag|paid|paying|pot|rich|win"],
  ["💱", "currency exchange", "bank|currency|exchange|money"],
  ["💲", "heavy dollar sign", "billion|cash|charge|currency|dollar|heavy|million|money|pay|sign"],
  ["💳", "credit card", "bank|card|cash|charge|credit|money|pay"],
  ["💴", "yen banknote", "bank|banknote|bill|currency|money|note|yen"],
  ["💵", "dollar banknote", "bank|banknote|bill|currency|dollar|money|note"],
  ["💶", "euro banknote", "100|bank|banknote|bill|currency|euro|money|note|rich"],
  ["💷", "pound banknote", "bank|banknote|bill|billion|cash|currency|money|note|pound|pounds"],
  ["💸", "money with wings", "bank|banknote|bill|billion|cash|dollar|fly|million|money|note|pay|wings"],
  ["💹", "chart increasing with yen", "bank|chart|currency|graph|growth|increasing|market|money|rise|trend|upward|yen"],
  ["💺", "seat", "chair"],
  ["💻", "laptop", "computer|office|pc|personal"],
  ["💼", "briefcase", "office"],
  ["💽", "computer disk", "computer|disk|minidisk|optical"],
  ["💾", "floppy disk", "computer|disk|floppy"],
  ["💿", "optical disk", "blu-ray|cd|computer|disk|dvd|optical"],
  ["📀", "dvd", "blu-ray|cd|computer|disk|optical"],
  ["📁", "file folder", "file|folder"],
  ["📂", "open file folder", "file|folder|open"],
  ["📃", "page with curl", "curl|document|page|paper"],
  ["📄", "page facing up", "document|facing|page|paper|up"],
  ["📅", "calendar", "date"],
  ["📆", "tear-off calendar", "calendar|tear-off"],
  ["📇", "card index", "card|index|old|rolodex|school"],
  ["📈", "chart increasing", "chart|data|graph|growth|increasing|right|trend|up|upward"],
  ["📉", "chart decreasing", "chart|data|decreasing|down|downward|graph|negative|trend"],
  ["📊", "bar chart", "bar|chart|data|graph"],
  ["📋", "clipboard", "do|list|notes"],
  ["📌", "pushpin", "collage|pin"],
  ["📍", "round pushpin", "location|map|pin|pushpin|round"],
  ["📎", "paperclip", ""],
  ["📏", "straight ruler", "angle|edge|math|ruler|straight|straightedge"],
  ["📐", "triangular ruler", "angle|math|rule|ruler|set|slide|triangle|triangular"],
  ["📑", "bookmark tabs", "bookmark|mark|marker|tabs"],
  ["📒", "ledger", "notebook"],
  ["📓", "notebook", ""],
  ["📔", "notebook with decorative cover", "book|cover|decorated|decorative|education|notebook|school|writing"],
  ["📕", "closed book", "book|closed|education"],
  ["📖", "open book", "book|education|fantasy|knowledge|library|novels|open|reading"],
  ["📗", "green book", "book|education|fantasy|green|library|reading"],
  ["📘", "blue book", "blue|book|education|fantasy|library|reading"],
  ["📙", "orange book", "book|education|fantasy|library|orange|reading"],
  ["📚", "books", "book|education|fantasy|knowledge|library|novels|reading|school|study"],
  ["📛", "name badge", "badge|name"],
  ["📜", "scroll", "paper"],
  ["📝", "memo", "communication|media|notes|pencil"],
  ["📞", "telephone receiver", "communication|phone|receiver|telephone|voip"],
  ["📟", "pager", "communication"],
  ["📠", "fax machine", "communication|fax|machine"],
  ["📡", "satellite antenna", "aliens|antenna|contact|dish|satellite|science"],
  ["📢", "loudspeaker", "address|communication|loud|public|sound"],
  ["📣", "megaphone", "cheering|sound"],
  ["📤", "outbox tray", "box|email|letter|mail|outbox|sent|tray"],
  ["📥", "inbox tray", "box|email|inbox|letter|mail|receive|tray|zero"],
  ["📦", "package", "box|communication|delivery|parcel|shipping"],
  ["📧", "e-mail", "email|letter|mail"],
  ["📨", "incoming envelope", "delivering|e-mail|email|envelope|incoming|letter|mail|receive|sent"],
  ["📩", "envelope with arrow", "arrow|communication|down|e-mail|email|envelope|letter|mail|outgoing|send|sent"],
  ["📪", "closed mailbox with lowered flag", "closed|flag|lowered|mail|mailbox|postbox"],
  ["📫", "closed mailbox with raised flag", "closed|communication|flag|mail|mailbox|postbox|raised"],
  ["📬", "open mailbox with raised flag", "flag|mail|mailbox|open|postbox|raised"],
  ["📭", "open mailbox with lowered flag", "flag|lowered|mail|mailbox|open|postbox"],
  ["📮", "postbox", "mail|mailbox"],
  ["📯", "postal horn", "horn|post|postal"],
  ["📰", "newspaper", "communication|news|paper"],
  ["📱", "mobile phone", "cell|communication|mobile|phone|telephone"],
  ["📲", "mobile phone with arrow", "arrow|build|call|cell|communication|mobile|phone|receive|telephone"],
  ["📳", "vibration mode", "cell|communication|mobile|mode|phone|telephone|vibration"],
  ["📴", "mobile phone off", "cell|mobile|off|phone|telephone"],
  ["📵", "no mobile phones", "cell|forbidden|mobile|no|not|phone|phones|prohibited|telephone"],
  ["📶", "antenna bars", "antenna|bar|bars|cell|communication|mobile|phone|signal|telephone"],
  ["📷", "camera", "photo|selfie|snap|tbt|trip|video"],
  ["📸", "camera with flash", "camera|flash|video"],
  ["📹", "video camera", "camcorder|camera|tbt|video"],
  ["📺", "television", "tv|video"],
  ["📻", "radio", "entertainment|tbt|video"],
  ["📼", "videocassette", "old|school|tape|vcr|vhs|video"],
  ["📽", "film projector", "cinema|film|movie|projector|video"],
  ["📿", "prayer beads", "beads|clothing|necklace|prayer|religion"],
  ["🔀", "shuffle tracks button", "arrow|button|crossed|shuffle|tracks"],
  ["🔁", "repeat button", "arrow|button|clockwise|repeat"],
  ["🔂", "repeat single button", "arrow|button|clockwise|once|repeat|single"],
  ["🔃", "clockwise vertical arrows", "arrow|arrows|clockwise|refresh|reload|vertical"],
  ["🔄", "counterclockwise arrows button", "again|anticlockwise|arrow|arrows|button|counterclockwise|deja|refresh|rewindershins|vu"],
  ["🔅", "dim button", "brightness|button|dim|low"],
  ["🔆", "bright button", "bright|brightness|button|light"],
  ["🔇", "muted speaker", "mute|muted|quiet|silent|sound|speaker"],
  ["🔈", "speaker low volume", "low|soft|sound|speaker|volume"],
  ["🔉", "speaker medium volume", "medium|sound|speaker|volume"],
  ["🔊", "speaker high volume", "high|loud|music|sound|speaker|volume"],
  ["🔋", "battery", ""],
  ["🔌", "electric plug", "electric|electricity|plug"],
  ["🔍", "magnifying glass tilted left", "glass|lab|left|left-pointing|magnifying|science|search|tilted|tool"],
  ["🔎", "magnifying glass tilted right", "contact|glass|lab|magnifying|right|right-pointing|science|search|tilted|tool"],
  ["🔏", "locked with pen", "ink|lock|locked|nib|pen|privacy"],
  ["🔐", "locked with key", "bike|closed|key|lock|locked|secure"],
  ["🔑", "key", "keys|lock|major|password|unlock"],
  ["🔒", "locked", "closed|lock|private"],
  ["🔓", "unlocked", "cracked|lock|open|unlock"],
  ["🔔", "bell", "break|church|sound"],
  ["🔕", "bell with slash", "bell|forbidden|mute|no|not|prohibited|quiet|silent|slash|sound"],
  ["🔖", "bookmark", "mark"],
  ["🔗", "link", "links"],
  ["🔘", "radio button", "button|geometric|radio"],
  ["🔙", "back arrow", "arrow|back"],
  ["🔚", "end arrow", "arrow|end"],
  ["🔛", "on! arrow", "arrow|mark|on!"],
  ["🔜", "soon arrow", "arrow|brb|omw|soon"],
  ["🔝", "top arrow", "arrow|homie|top|up"],
  ["🔞", "no one under eighteen", "18|age|eighteen|forbidden|no|not|one|prohibited|restriction|underage"],
  ["🔟", "keycap: 10", "keycap"],
  ["🔠", "input latin uppercase", "abcd|input|latin|letters|uppercase"],
  ["🔡", "input latin lowercase", "abcd|input|latin|letters|lowercase"],
  ["🔢", "input numbers", "1234|input|numbers"],
  ["🔣", "input symbols", "&|%|♪|〒|input|symbols"],
  ["🔤", "input latin letters", "abc|alphabet|input|latin|letters"],
  ["🔥", "fire", "af|burn|flame|hot|lit|litaf|tool"],
  ["🔦", "flashlight", "electric|light|tool|torch"],
  ["🔧", "wrench", "home|improvement|spanner|tool"],
  ["🔨", "hammer", "home|improvement|repairs|tool"],
  ["🔩", "nut and bolt", "bolt|home|improvement|nut|tool"],
  ["🔪", "kitchen knife", "chef|cooking|hocho|kitchen|knife|tool|weapon"],
  ["🔫", "water pistol", "gun|handgun|pistol|revolver|tool|water|weapon"],
  ["🔬", "microscope", "experiment|lab|science|tool"],
  ["🔭", "telescope", "contact|extraterrestrial|science|tool"],
  ["🔮", "crystal ball", "ball|crystal|fairy|fairytale|fantasy|fortune|future|magic|tale|tool"],
  ["🔯", "dotted six-pointed star", "dotted|fortune|jewish|judaism|six-pointed|star"],
  ["🔰", "japanese symbol for beginner", "beginner|chevron|green|japanese|leaf|symbol|tool|yellow"],
  ["🔱", "trident emblem", "anchor|emblem|poseidon|ship|tool|trident"],
  ["🔲", "black square button", "black|button|geometric|square"],
  ["🔳", "white square button", "button|geometric|outlined|square|white"],
  ["🔴", "red circle", "circle|geometric|red"],
  ["🔵", "blue circle", "blue|circle|geometric"],
  ["🔶", "large orange diamond", "diamond|geometric|large|orange"],
  ["🔷", "large blue diamond", "blue|diamond|geometric|large"],
  ["🔸", "small orange diamond", "diamond|geometric|orange|small"],
  ["🔹", "small blue diamond", "blue|diamond|geometric|small"],
  ["🔺", "red triangle pointed up", "geometric|pointed|red|triangle|up"],
  ["🔻", "red triangle pointed down", "down|geometric|pointed|red|triangle"],
  ["🔼", "upwards button", "arrow|button|red|up|upwards"],
  ["🔽", "downwards button", "arrow|button|down|downwards|red"],
  ["🕐", "one o’clock", "1|1:00|clock|o’clock|one|time"],
  ["🕑", "two o’clock", "2|2:00|clock|o’clock|time|two"],
  ["🕒", "three o’clock", "3|3:00|clock|o’clock|three|time"],
  ["🕓", "four o’clock", "4|4:00|clock|four|o’clock|time"],
  ["🕔", "five o’clock", "5|5:00|clock|five|o’clock|time"],
  ["🕕", "six o’clock", "6|6:00|clock|o’clock|six|time"],
  ["🕖", "seven o’clock", "0|7|7:00|clock|o’clock|seven"],
  ["🕗", "eight o’clock", "8|8:00|clock|eight|o’clock|time"],
  ["🕘", "nine o’clock", "9|9:00|clock|nine|o’clock|time"],
  ["🕙", "ten o’clock", "0|10|10:00|clock|o’clock|ten"],
  ["🕚", "eleven o’clock", "11|11:00|clock|eleven|o’clock|time"],
  ["🕛", "twelve o’clock", "12|12:00|clock|o’clock|time|twelve"],
  ["🕜", "one-thirty", "1|1:30|30|clock|one|thirty|time"],
  ["🕝", "two-thirty", "2|2:30|30|clock|thirty|time|two"],
  ["🕞", "three-thirty", "3|3:30|30|clock|thirty|three|time"],
  ["🕟", "four-thirty", "30|4|4:30|clock|four|thirty|time"],
  ["🕠", "five-thirty", "30|5|5:30|clock|five|thirty|time"],
  ["🕡", "six-thirty", "30|6|6:30|clock|six|thirty"],
  ["🕢", "seven-thirty", "30|7|7:30|clock|seven|thirty"],
  ["🕣", "eight-thirty", "30|8|8:30|clock|eight|thirty|time"],
  ["🕤", "nine-thirty", "30|9|9:30|clock|nine|thirty|time"],
  ["🕥", "ten-thirty", "10|10:30|30|clock|ten|thirty|time"],
  ["🕦", "eleven-thirty", "11|11:30|30|clock|eleven|thirty|time"],
  ["🕧", "twelve-thirty", "12|12:30|30|clock|thirty|time|twelve"],
  ["🕯", "candle", "light"],
  ["🕰", "mantelpiece clock", "clock|mantelpiece|time"],
  ["🕴", "person in suit levitating", "business|levitating|person|suit"],
  ["🕵", "detective", "sleuth|spy"],
  ["🕶", "sunglasses", "dark|eye|eyewear|glasses"],
  ["🕷", "spider", "animal|insect"],
  ["🕸", "spider web", "spider|web"],
  ["🕹", "joystick", "game|video|videogame"],
  ["🕺", "man dancing", "dance|dancer|dancing|elegant|festive|flair|flamenco|groove|let’s|man|salsa|tango"],
  ["🖇", "linked paperclips", "link|linked|paperclip|paperclips"],
  ["🖊", "pen", "ballpoint"],
  ["🖋", "fountain pen", "fountain|pen"],
  ["🖌", "paintbrush", "painting"],
  ["🖍", "crayon", ""],
  ["🖐", "hand with fingers splayed", "finger|fingers|hand|raised|splayed|stop"],
  ["🖕", "middle finger", "finger|hand|middle"],
  ["🖖", "vulcan salute", "finger|hand|hands|salute|vulcan"],
  ["🖤", "black heart", "black|evil|heart|wicked"],
  ["🖥", "desktop computer", "computer|desktop|monitor"],
  ["🖨", "printer", "computer"],
  ["🖱", "computer mouse", "computer|mouse"],
  ["🖲", "trackball", "computer"],
  ["🖼", "framed picture", "art|frame|framed|museum|painting|picture"],
  ["🗂", "card index dividers", "card|dividers|index"],
  ["🗃", "card file box", "box|card|file"],
  ["🗄", "file cabinet", "cabinet|file|filing|paper"],
  ["🗑", "wastebasket", "can|garbage|trash|waste"],
  ["🗒", "spiral notepad", "note|notepad|pad|spiral"],
  ["🗓", "spiral calendar", "calendar|pad|spiral"],
  ["🗜", "clamp", "compress|tool|vice"],
  ["🗝", "old key", "clue|key|lock|old"],
  ["🗞", "rolled-up newspaper", "news|newspaper|paper|rolled|rolled-up"],
  ["🗡", "dagger", "knife|weapon"],
  ["🗣", "speaking head", "face|head|silhouette|speak|speaking"],
  ["🗨", "left speech bubble", "balloon|bubble|dialog|left|speech"],
  ["🗯", "right anger bubble", "anger|angry|balloon|bubble|mad|right"],
  ["🗳", "ballot box with ballot", "ballot|box"],
  ["🗺", "world map", "map|world"],
  ["🗻", "mount fuji", "fuji|mount|mountain|nature"],
  ["🗼", "tokyo tower", "tokyo|tower"],
  ["🗽", "statue of liberty", "liberty|new|ny|nyc|statue|york"],
  ["🗾", "map of japan", "japan|map"],
  ["🗿", "moai", "face|moyai|statue|stoneface|travel"],
  ["😀", "grinning face", "cheerful|cheery|face|grin|grinning|happy|laugh|nice|smile|smiling|teeth"],
  ["😁", "beaming face with smiling eyes", "beaming|eye|eyes|face|grin|grinning|happy|nice|smile|smiling|teeth"],
  ["😂", "face with tears of joy", "crying|face|feels|funny|haha|happy|hehe|hilarious|joy|laugh|lmao|lol|rofl|roflmao|tear"],
  ["😃", "grinning face with big eyes", "awesome|big|eyes|face|grin|grinning|happy|mouth|open|smile|smiling|teeth|yay"],
  ["😄", "grinning face with smiling eyes", "eye|eyes|face|grin|grinning|happy|laugh|lol|mouth|open|smile|smiling"],
  ["😅", "grinning face with sweat", "cold|dejected|excited|face|grinning|mouth|nervous|open|smile|smiling|stress|stressed|sweat"],
  ["😆", "grinning squinting face", "closed|eyes|face|grinning|haha|hahaha|happy|laugh|lol|mouth|open|rofl|smile|smiling|squinting"],
  ["😇", "smiling face with halo", "angel|angelic|angels|blessed|face|fairy|fairytale|fantasy|halo|happy|innocent|peaceful|smile|smiling|spirit|tale"],
  ["😈", "smiling face with horns", "demon|devil|evil|face|fairy|fairytale|fantasy|horns|purple|shade|smile|smiling|tale"],
  ["😉", "winking face", "face|flirt|heartbreaker|sexy|slide|tease|wink|winking|winks"],
  ["😊", "smiling face with smiling eyes", "blush|eye|eyes|face|glad|satisfied|smile|smiling"],
  ["😋", "face savoring food", "delicious|eat|face|food|full|hungry|savor|smile|smiling|tasty|um|yum|yummy"],
  ["😌", "relieved face", "calm|face|peace|relief|relieved|zen"],
  ["😍", "smiling face with heart-eyes", "143|bae|eye|face|feels|heart-eyes|hearts|ily|kisses|love|romance|romantic|smile|xoxo"],
  ["😎", "smiling face with sunglasses", "awesome|beach|bright|bro|chilling|cool|face|rad|relaxed|shades|slay|smile|style|sunglasses|swag|win"],
  ["😏", "smirking face", "boss|dapper|face|flirt|homie|kidding|leer|shade|slick|sly|smirk|smug|snicker|suave|suspicious|swag"],
  ["😐", "neutral face", "awkward|blank|deadpan|expressionless|face|fine|jealous|meh|neutral|oh|shade|straight|unamused|unhappy|unimpressed|whatever"],
  ["😑", "expressionless face", "awkward|dead|expressionless|face|fine|inexpressive|jealous|meh|not|oh|omg|straight|uh|unhappy|unimpressed|whatever"],
  ["😒", "unamused face", "...|bored|face|fine|jealous|jel|jelly|pissed|smh|ugh|uhh|unamused|unhappy|weird|whatever"],
  ["😓", "downcast face with sweat", "close|cold|downcast|face|feels|headache|nervous|sad|scared|sweat|yikes"],
  ["😔", "pensive face", "awful|bored|dejected|died|disappointed|face|losing|lost|pensive|sad|sucks"],
  ["😕", "confused face", "befuddled|confused|confusing|dunno|face|frown|hm|meh|not|sad|sorry|sure"],
  ["😖", "confounded face", "annoyed|confounded|confused|cringe|distraught|face|feels|frustrated|mad|sad"],
  ["😗", "kissing face", "143|date|dating|face|flirt|ily|kiss|love|smooch|smooches|xoxo|you"],
  ["😘", "face blowing a kiss", "adorbs|bae|blowing|face|flirt|heart|ily|kiss|love|lover|miss|muah|romantic|smooch|xoxo|you"],
  ["😙", "kissing face with smiling eyes", "143|closed|date|dating|eye|eyes|face|flirt|ily|kiss|kisses|kissing|love|night|smile|smiling"],
  ["😚", "kissing face with closed eyes", "143|bae|blush|closed|date|dating|eye|eyes|face|flirt|ily|kisses|kissing|smooches|xoxo"],
  ["😛", "face with tongue", "awesome|cool|face|nice|party|stuck-out|sweet|tongue"],
  ["😜", "winking face with tongue", "crazy|epic|eye|face|funny|joke|loopy|nutty|party|stuck-out|tongue|wacky|weirdo|wink|winking|yolo"],
  ["😝", "squinting face with tongue", "closed|eye|eyes|face|gross|horrible|omg|squinting|stuck-out|taste|tongue|whatever|yolo"],
  ["😞", "disappointed face", "awful|blame|dejected|disappointed|face|fail|losing|sad|unhappy"],
  ["😟", "worried face", "anxious|butterflies|face|nerves|nervous|sad|stress|stressed|surprised|worried|worry"],
  ["😠", "angry face", "anger|angry|blame|face|feels|frustrated|mad|maddening|rage|shade|unhappy|upset"],
  ["😡", "enraged face", "anger|angry|enraged|face|feels|mad|maddening|pouting|rage|red|shade|unhappy|upset"],
  ["😢", "crying face", "awful|cry|crying|face|feels|miss|sad|tear|triste|unhappy"],
  ["😣", "persevering face", "concentrate|concentration|face|focus|headache|persevere|persevering"],
  ["😤", "face with steam from nose", "anger|angry|face|feels|fume|fuming|furious|fury|mad|nose|steam|triumph|unhappy|won"],
  ["😥", "sad but relieved face", "anxious|call|close|complicated|disappointed|face|not|relieved|sad|sweat|time|whew"],
  ["😦", "frowning face with open mouth", "caught|face|frown|frowning|guard|mouth|open|scared|scary|surprise|what|wow"],
  ["😧", "anguished face", "anguished|face|forgot|scared|scary|stressed|surprise|unhappy|what|wow"],
  ["😨", "fearful face", "afraid|anxious|blame|face|fear|fearful|scared|worried"],
  ["😩", "weary face", "crying|face|fail|feels|hungry|mad|nooo|sad|sleepy|tired|unhappy|weary"],
  ["😪", "sleepy face", "crying|face|good|night|sad|sleep|sleeping|sleepy|tired"],
  ["😫", "tired face", "cost|face|feels|nap|sad|sneeze|tired"],
  ["😬", "grimacing face", "awk|awkward|dentist|face|grimace|grimacing|grinning|smile|smiling"],
  ["😭", "loudly crying face", "bawling|cry|crying|face|loudly|sad|sob|tear|tears|unhappy"],
  ["😮", "face with open mouth", "believe|face|forgot|mouth|omg|open|shocked|surprised|sympathy|unbelievable|unreal|whoa|wow|you"],
  ["😯", "hushed face", "epic|face|hushed|omg|stunned|surprised|whoa|woah"],
  ["😰", "anxious face with sweat", "anxious|blue|cold|eek|face|mouth|nervous|open|rushed|scared|sweat|yikes"],
  ["😱", "face screaming in fear", "epic|face|fear|fearful|munch|scared|scream|screamer|screaming|shocked|surprised|woah"],
  ["😲", "astonished face", "astonished|cost|face|no|omg|shocked|totally|way"],
  ["😳", "flushed face", "amazed|awkward|crazy|dazed|dead|disbelief|embarrassed|face|flushed|geez|heat|hot|impressed|jeez|what|wow"],
  ["😴", "sleeping face", "bed|bedtime|face|good|goodnight|nap|night|sleep|sleeping|tired|whatever|yawn|zzz"],
  ["😵", "face with crossed-out eyes", "crossed-out|dead|dizzy|eyes|face|feels|knocked|out|sick|tired"],
  ["😶", "face without mouth", "awkward|blank|expressionless|face|mouth|mouthless|mute|quiet|secret|silence|silent|speechless"],
  ["😷", "face with medical mask", "cold|dentist|dermatologist|doctor|dr|face|germs|mask|medical|medicine|sick"],
  ["😸", "grinning cat with smiling eyes", "animal|cat|eye|eyes|face|grin|grinning|smile|smiling"],
  ["😹", "cat with tears of joy", "animal|cat|face|joy|laugh|laughing|lol|tear|tears"],
  ["😺", "grinning cat", "animal|cat|face|grinning|mouth|open|smile|smiling"],
  ["😻", "smiling cat with heart-eyes", "animal|cat|eye|face|heart|heart-eyes|love|smile|smiling"],
  ["😼", "cat with wry smile", "animal|cat|face|ironic|smile|wry"],
  ["😽", "kissing cat", "animal|cat|closed|eye|eyes|face|kiss|kissing"],
  ["😾", "pouting cat", "animal|cat|face|pouting"],
  ["😿", "crying cat", "animal|cat|cry|crying|face|sad|tear"],
  ["🙀", "weary cat", "animal|cat|face|oh|surprised|weary"],
  ["🙁", "slightly frowning face", "face|frown|frowning|sad|slightly"],
  ["🙂", "slightly smiling face", "face|happy|slightly|smile|smiling"],
  ["🙃", "upside-down face", "face|hehe|smile|upside-down"],
  ["🙄", "face with rolling eyes", "eyeroll|eyes|face|rolling|shade|ugh|whatever"],
  ["🙅", "person gesturing no", "forbidden|gesture|hand|no|not|person|prohibit"],
  ["🙆", "person gesturing ok", "exercise|gesture|gesturing|hand|ok|omg|person"],
  ["🙇", "person bowing", "apology|ask|beg|bow|bowing|favor|forgive|gesture|meditate|meditation|person|pity|regret|sorry"],
  ["🙈", "see-no-evil monkey", "embarrassed|evil|face|forbidden|forgot|gesture|hide|monkey|no|omg|prohibited|scared|secret|smh|watch"],
  ["🙉", "hear-no-evil monkey", "animal|ears|evil|face|forbidden|gesture|hear|listen|monkey|no|not|prohibited|secret|shh|tmi"],
  ["🙊", "speak-no-evil monkey", "animal|evil|face|forbidden|gesture|monkey|no|not|oops|prohibited|quiet|secret|speak|stealth"],
  ["🙋", "person raising hand", "gesture|hand|here|know|me|person|pick|question|raise|raising"],
  ["🙌", "raising hands", "celebration|gesture|hand|hands|hooray|praise|raised|raising"],
  ["🙍", "person frowning", "annoyed|disappointed|disgruntled|disturbed|frown|frowning|frustrated|gesture|irritated|person|upset"],
  ["🙎", "person pouting", "disappointed|downtrodden|frown|grimace|person|pouting|scowl|sulk|upset|whine"],
  ["🙏", "folded hands", "appreciate|ask|beg|blessed|bow|cmon|five|folded|gesture|hand|high|please|pray|thanks|thx"],
  ["🚀", "rocket", "launch|rockets|space|travel"],
  ["🚁", "helicopter", "copter|roflcopter|travel|vehicle"],
  ["🚂", "locomotive", "caboose|engine|railway|steam|train|trains|travel"],
  ["🚃", "railway car", "car|electric|railway|train|tram|travel|trolleybus"],
  ["🚄", "high-speed train", "high-speed|railway|shinkansen|speed|train"],
  ["🚅", "bullet train", "bullet|high-speed|nose|railway|shinkansen|speed|train|travel"],
  ["🚆", "train", "arrived|choo|railway"],
  ["🚇", "metro", "subway|travel"],
  ["🚈", "light rail", "arrived|light|monorail|rail|railway"],
  ["🚉", "station", "railway|train"],
  ["🚊", "tram", "trolleybus"],
  ["🚋", "tram car", "bus|car|tram|trolley|trolleybus"],
  ["🚌", "bus", "school|vehicle"],
  ["🚍", "oncoming bus", "bus|cars|oncoming"],
  ["🚎", "trolleybus", "bus|tram|trolley"],
  ["🚏", "bus stop", "bus|busstop|stop"],
  ["🚐", "minibus", "bus|drive|van|vehicle"],
  ["🚑", "ambulance", "emergency|vehicle"],
  ["🚒", "fire engine", "engine|fire|truck"],
  ["🚓", "police car", "5–0|car|cops|patrol|police"],
  ["🚔", "oncoming police car", "car|oncoming|police"],
  ["🚕", "taxi", "cab|cabbie|car|drive|vehicle|yellow"],
  ["🚖", "oncoming taxi", "cab|cabbie|cars|drove|hail|oncoming|taxi|yellow"],
  ["🚗", "automobile", "car|driving|vehicle"],
  ["🚘", "oncoming automobile", "automobile|car|cars|drove|oncoming|vehicle"],
  ["🚙", "sport utility vehicle", "car|drive|recreational|sport|sportutility|utility|vehicle"],
  ["🚚", "delivery truck", "car|delivery|drive|truck|vehicle"],
  ["🚛", "articulated lorry", "articulated|car|drive|lorry|move|semi|truck|vehicle"],
  ["🚜", "tractor", "vehicle"],
  ["🚝", "monorail", "vehicle"],
  ["🚞", "mountain railway", "car|mountain|railway|trip"],
  ["🚟", "suspension railway", "railway|suspension"],
  ["🚠", "mountain cableway", "cable|cableway|gondola|lift|mountain|ski"],
  ["🚡", "aerial tramway", "aerial|cable|car|gondola|ropeway|tramway"],
  ["🚢", "ship", "boat|passenger|travel"],
  ["🚣", "person rowing boat", "boat|canoe|cruise|fishing|lake|oar|paddle|person|raft|river|row|rowboat|rowing"],
  ["🚤", "speedboat", "billionaire|boat|lake|luxury|millionaire|summer|travel"],
  ["🚥", "horizontal traffic light", "horizontal|intersection|light|signal|stop|stoplight|traffic"],
  ["🚦", "vertical traffic light", "drove|intersection|light|signal|stop|stoplight|traffic|vertical"],
  ["🚧", "construction", "barrier"],
  ["🚨", "police car light", "alarm|alert|beacon|car|emergency|light|police|revolving|siren"],
  ["🚩", "triangular flag", "construction|flag|golf|post|triangular"],
  ["🚪", "door", "back|closet|front"],
  ["🚫", "prohibited", "entry|forbidden|no|not|smoke"],
  ["🚬", "cigarette", "smoking"],
  ["🚭", "no smoking", "forbidden|no|not|prohibited|smoke|smoking"],
  ["🚮", "litter in bin sign", "bin|litter|litterbin|sign"],
  ["🚯", "no littering", "forbidden|litter|littering|no|not|prohibited"],
  ["🚰", "potable water", "drinking|potable|water"],
  ["🚱", "non-potable water", "dry|non-drinking|non-potable|prohibited|water"],
  ["🚲", "bicycle", "bike|class|cycle|cycling|cyclist|gang|ride|spin|spinning"],
  ["🚳", "no bicycles", "bicycle|bicycles|bike|forbidden|no|not|prohibited"],
  ["🚴", "person biking", "bicycle|bicyclist|bike|biking|cycle|cyclist|person|riding|sport"],
  ["🚵", "person mountain biking", "bicycle|bicyclist|bike|biking|cycle|cyclist|mountain|person|riding|sport"],
  ["🚶", "person walking", "amble|gait|hike|man|pace|pedestrian|person|stride|stroll|walk|walking"],
  ["🚷", "no pedestrians", "forbidden|no|not|pedestrian|pedestrians|prohibited"],
  ["🚸", "children crossing", "child|children|crossing|pedestrian|traffic"],
  ["🚹", "men’s room", "bathroom|lavatory|man|men’s|restroom|room|toilet|wc"],
  ["🚺", "women’s room", "bathroom|lavatory|restroom|room|toilet|wc|woman|women’s"],
  ["🚻", "restroom", "bathroom|lavatory|toilet|wc"],
  ["🚼", "baby symbol", "baby|changing|symbol"],
  ["🚽", "toilet", "bathroom"],
  ["🚾", "water closet", "bathroom|closet|lavatory|restroom|toilet|water|wc"],
  ["🚿", "shower", "water"],
  ["🛀", "person taking bath", "bath|bathtub|person|taking|tub"],
  ["🛁", "bathtub", "bath"],
  ["🛂", "passport control", "control|passport"],
  ["🛃", "customs", "packing"],
  ["🛄", "baggage claim", "arrived|baggage|bags|case|checked|claim|journey|packing|plane|ready|travel|trip"],
  ["🛅", "left luggage", "baggage|case|left|locker|luggage"],
  ["🛌", "person in bed", "bed|bedtime|good|goodnight|hotel|nap|night|person|sleep|tired|zzz"],
  ["🛐", "place of worship", "place|pray|religion|worship"],
  ["🛑", "stop sign", "octagonal|sign|stop"],
  ["🛒", "shopping cart", "cart|shopping|trolley"],
  ["🛕", "hindu temple", "hindu|temple"],
  ["🛖", "hut", "home|house|roundhouse|shelter|yurt"],
  ["🛗", "elevator", "accessibility|hoist|lift"],
  ["🛜", "wireless", "broadband|computer|connectivity|hotspot|internet|network|router|smartphone|wi-fi|wifi|wlan"],
  ["🛝", "playground slide", "amusement|park|play|playground|playing|slide|sliding|theme"],
  ["🛞", "wheel", "car|circle|tire|turn|vehicle"],
  ["🛟", "ring buoy", "buoy|float|life|lifesaver|preserver|rescue|ring|safety|save|saver|swim"],
  ["🛠", "hammer and wrench", "hammer|spanner|tool|wrench"],
  ["🛡", "shield", "weapon"],
  ["🛢", "oil drum", "drum|oil"],
  ["🛣", "motorway", "highway|road"],
  ["🛤", "railway track", "railway|track|train"],
  ["🛥", "motor boat", "boat|motor|motorboat"],
  ["🛩", "small airplane", "aeroplane|airplane|plane|small"],
  ["🛫", "airplane departure", "aeroplane|airplane|check-in|departure|departures|plane"],
  ["🛬", "airplane arrival", "aeroplane|airplane|arrival|arrivals|arriving|landing|plane"],
  ["🛰", "satellite", "space"],
  ["🛳", "passenger ship", "passenger|ship"],
  ["🛴", "kick scooter", "kick|scooter"],
  ["🛵", "motor scooter", "motor|scooter"],
  ["🛶", "canoe", "boat"],
  ["🛷", "sled", "luge|sledge|sleigh|snow|toboggan"],
  ["🛸", "flying saucer", "aliens|extra|flying|saucer|terrestrial|ufo"],
  ["🛹", "skateboard", "board|skate|skater|wheels"],
  ["🛺", "auto rickshaw", "auto|rickshaw|tuk"],
  ["🛻", "pickup truck", "automobile|car|flatbed|pick-up|pickup|transportation|truck"],
  ["🛼", "roller skate", "blades|roller|skate|skates|sport"],
  ["🟠", "orange circle", "circle|orange"],
  ["🟡", "yellow circle", "circle|yellow"],
  ["🟢", "green circle", "circle|green"],
  ["🟣", "purple circle", "circle|purple"],
  ["🟤", "brown circle", "brown|circle"],
  ["🟥", "red square", "card|penalty|red|square"],
  ["🟦", "blue square", "blue|square"],
  ["🟧", "orange square", "orange|square"],
  ["🟨", "yellow square", "card|penalty|square|yellow"],
  ["🟩", "green square", "green|square"],
  ["🟪", "purple square", "purple|square"],
  ["🟫", "brown square", "brown|square"],
  ["🟰", "heavy equals sign", "answer|equal|equality|equals|heavy|math|sign"],
  ["🤌", "pinched fingers", "fingers|gesture|hand|hold|huh|interrogation|patience|pinched|relax|sarcastic|ugh|what|zip"],
  ["🤍", "white heart", "143|heart|white"],
  ["🤎", "brown heart", "143|brown|heart"],
  ["🤏", "pinching hand", "amount|bit|fingers|hand|little|pinching|small|sort"],
  ["🤘", "sign of the horns", "finger|hand|horns|rock-on|sign"],
  ["🤙", "call me hand", "call|hand|hang|loose|me|shaka"],
  ["🤚", "raised back of hand", "back|backhand|hand|raised"],
  ["🤛", "left-facing fist", "fist|left-facing|leftwards"],
  ["🤜", "right-facing fist", "fist|right-facing|rightwards"],
  ["🤝", "handshake", "agreement|deal|hand|meeting|shake"],
  ["🤞", "crossed fingers", "cross|crossed|finger|fingers|hand|luck"],
  ["🤟", "love-you gesture", "fingers|gesture|hand|ily|love|love-you|three|you"],
  ["🤠", "cowboy hat face", "cowboy|cowgirl|face|hat"],
  ["🤡", "clown face", "clown|face"],
  ["🤢", "nauseated face", "face|gross|nasty|nauseated|sick|vomit"],
  ["🤣", "rolling on the floor laughing", "crying|face|floor|funny|haha|happy|hehe|hilarious|joy|laugh|lmao|lol|rofl|roflmao|rolling|tear"],
  ["🤤", "drooling face", "drooling|face"],
  ["🤥", "lying face", "face|liar|lie|lying|pinocchio"],
  ["🤦", "person facepalming", "again|bewilder|disbelief|exasperation|facepalm|no|not|oh|omg|person|shock|smh"],
  ["🤧", "sneezing face", "face|fever|flu|gesundheit|sick|sneeze|sneezing"],
  ["🤨", "face with raised eyebrow", "disapproval|disbelief|distrust|emoji|eyebrow|face|hmm|mild|raised|skeptic|skeptical|skepticism|surprise|what"],
  ["🤩", "star-struck", "excited|eyes|face|grinning|smile|star|starry-eyed|wow"],
  ["🤪", "zany face", "crazy|eye|eyes|face|goofy|large|small|zany"],
  ["🤫", "shushing face", "face|quiet|shh|shush|shushing"],
  ["🤬", "face with symbols on mouth", "censor|cursing|cussing|face|mad|mouth|pissed|swearing|symbols"],
  ["🤭", "face with hand over mouth", "face|giggle|giggling|hand|mouth|oops|realization|secret|shock|sudden|surprise|whoops"],
  ["🤮", "face vomiting", "barf|ew|face|gross|puke|sick|spew|throw|up|vomit|vomiting"],
  ["🤯", "exploding head", "blown|explode|exploding|head|mind|mindblown|no|shocked|way"],
  ["🤰", "pregnant woman", "pregnant|woman"],
  ["🤱", "breast-feeding", "baby|breast|feeding|mom|mother|nursing|woman"],
  ["🤲", "palms up together", "cupped|dua|hands|palms|pray|prayer|together|up|wish"],
  ["🤳", "selfie", "camera|phone"],
  ["🤴", "prince", "crown|fairy|fairytale|fantasy|king|royal|royalty|tale"],
  ["🤵", "person in tuxedo", "formal|person|tuxedo|wedding"],
  ["🤶", "mrs. claus", "celebration|christmas|claus|fairy|fantasy|holiday|merry|mother|mrs|santa|tale|xmas"],
  ["🤷", "person shrugging", "doubt|dunno|guess|idk|ignorance|indifference|knows|maybe|person|shrug|shrugging|whatever|who"],
  ["🤸", "person cartwheeling", "active|cartwheel|cartwheeling|excited|flip|gymnastics|happy|person|somersault"],
  ["🤹", "person juggling", "act|balance|balancing|handle|juggle|juggling|manage|multitask|person|skill"],
  ["🤺", "person fencing", "fencer|fencing|person|sword"],
  ["🤼", "people wrestling", "combat|duel|grapple|people|ring|tournament|wrestle|wrestling"],
  ["🤽", "person playing water polo", "person|playing|polo|sport|swimming|water|waterpolo"],
  ["🤾", "person playing handball", "athletics|ball|catch|chuck|handball|hurl|lob|person|pitch|playing|sport|throw|toss"],
  ["🥂", "clinking glasses", "celebrate|clink|clinking|drink|glass|glasses"],
  ["🥃", "tumbler glass", "glass|liquor|scotch|shot|tumbler|whiskey|whisky"],
  ["🥄", "spoon", "eat|tableware"],
  ["🥅", "goal net", "goal|net"],
  ["🥇", "1st place medal", "1st|first|gold|medal|place"],
  ["🥈", "2nd place medal", "2nd|medal|place|second|silver"],
  ["🥉", "3rd place medal", "3rd|bronze|medal|place|third"],
  ["🥊", "boxing glove", "boxing|glove"],
  ["🥋", "martial arts uniform", "arts|judo|karate|martial|taekwondo|uniform"],
  ["🥌", "curling stone", "curling|game|rock|stone"],
  ["🥐", "croissant", "bread|breakfast|crescent|food|french|roll"],
  ["🥑", "avocado", "food|fruit"],
  ["🥒", "cucumber", "food|pickle|vegetable"],
  ["🥓", "bacon", "breakfast|food|meat"],
  ["🥔", "potato", "food|vegetable"],
  ["🥕", "carrot", "food|vegetable"],
  ["🥖", "baguette bread", "baguette|bread|food|french"],
  ["🥗", "green salad", "food|green|salad"],
  ["🥘", "shallow pan of food", "casserole|food|paella|pan|shallow"],
  ["🥙", "stuffed flatbread", "falafel|flatbread|food|gyro|kebab|stuffed"],
  ["🥚", "egg", "breakfast|food"],
  ["🥛", "glass of milk", "drink|glass|milk"],
  ["🥜", "peanuts", "food|nut|peanut|vegetable"],
  ["🥝", "kiwi fruit", "food|fruit|kiwi"],
  ["🥞", "pancakes", "breakfast|crêpe|food|hotcake|pancake"],
  ["🥟", "dumpling", "empanada|gyōza|jiaozi|pierogi|potsticker"],
  ["🥠", "fortune cookie", "cookie|fortune|prophecy"],
  ["🥡", "takeout box", "box|chopsticks|delivery|food|oyster|pail|takeout"],
  ["🥢", "chopsticks", "hashi|jeotgarak|kuaizi"],
  ["🥣", "bowl with spoon", "bowl|breakfast|cereal|congee|oatmeal|porridge|spoon"],
  ["🥤", "cup with straw", "cup|drink|juice|malt|soda|soft|straw|water"],
  ["🥥", "coconut", "colada|palm|piña"],
  ["🥦", "broccoli", "cabbage|wild"],
  ["🥧", "pie", "apple|filling|fruit|meat|pastry|pumpkin|slice"],
  ["🥨", "pretzel", "convoluted|twisted"],
  ["🥩", "cut of meat", "chop|cut|lambchop|meat|porkchop|red|steak"],
  ["🥪", "sandwich", "bread"],
  ["🥫", "canned food", "can|canned|food"],
  ["🥬", "leafy green", "bok|burgers|cabbage|choy|green|kale|leafy|lettuce|salad"],
  ["🥭", "mango", "food|fruit|tropical"],
  ["🥮", "moon cake", "autumn|cake|festival|moon|yuèbǐng"],
  ["🥯", "bagel", "bakery|bread|breakfast|schmear"],
  ["🥰", "smiling face with hearts", "3|adore|crush|face|heart|hearts|ily|love|romance|smile|smiling|you"],
  ["🥱", "yawning face", "bedtime|bored|face|goodnight|nap|night|sleep|sleepy|tired|whatever|yawn|yawning|zzz"],
  ["🥲", "smiling face with tear", "face|glad|grateful|happy|joy|pain|proud|relieved|smile|smiley|smiling|tear|touched"],
  ["🥳", "partying face", "bday|birthday|celebrate|celebration|excited|face|happy|hat|hooray|horn|party|partying"],
  ["🥴", "woozy face", "dizzy|drunk|eyes|face|intoxicated|mouth|tipsy|uneven|wavy|woozy"],
  ["🥵", "hot face", "dying|face|feverish|heat|hot|panting|red-faced|stroke|sweating|tongue"],
  ["🥶", "cold face", "blue|blue-faced|cold|face|freezing|frostbite|icicles|subzero|teeth"],
  ["🥷", "ninja", "assassin|fight|fighter|hidden|person|secret|skills|sly|soldier|stealth|war"],
  ["🥸", "disguised face", "disguise|eyebrow|face|glasses|incognito|moustache|mustache|nose|person|spy|tache|tash"],
  ["🥹", "face holding back tears", "admiration|aww|back|cry|embarrassed|face|feelings|grateful|gratitude|holding|joy|please|proud|resist|sad|tears"],
  ["🥺", "pleading face", "begging|big|eyes|face|mercy|not|pleading|please|pretty|puppy|sad|why"],
  ["🥻", "sari", "clothing|dress"],
  ["🥼", "lab coat", "clothes|coat|doctor|dr|experiment|jacket|lab|scientist|white"],
  ["🥽", "goggles", "dive|eye|protection|scuba|swimming|welding"],
  ["🥾", "hiking boot", "backpacking|boot|brown|camping|hiking|outdoors|shoe"],
  ["🥿", "flat shoe", "ballet|comfy|flat|flats|shoe|slip-on|slipper"],
  ["🦀", "crab", "cancer|zodiac"],
  ["🦁", "lion", "alpha|animal|face|leo|mane|order|rawr|roar|safari|strong|zodiac"],
  ["🦂", "scorpion", "scorpio|scorpius|zodiac"],
  ["🦃", "turkey", "bird|gobble|thanksgiving"],
  ["🦄", "unicorn", "face"],
  ["🦅", "eagle", "animal|bird|ornithology"],
  ["🦆", "duck", "animal|bird|ornithology"],
  ["🦇", "bat", "animal|vampire"],
  ["🦈", "shark", "animal|fish"],
  ["🦉", "owl", "animal|bird|ornithology|wise"],
  ["🦊", "fox", "animal|face"],
  ["🦋", "butterfly", "insect|pretty"],
  ["🦌", "deer", "animal"],
  ["🦍", "gorilla", "animal"],
  ["🦎", "lizard", "animal|reptile"],
  ["🦏", "rhinoceros", "animal"],
  ["🦐", "shrimp", "food|shellfish|small"],
  ["🦑", "squid", "animal|food|mollusk"],
  ["🦒", "giraffe", "animal|spots"],
  ["🦓", "zebra", "animal|stripe"],
  ["🦔", "hedgehog", "animal|spiny"],
  ["🦕", "sauropod", "brachiosaurus|brontosaurus|dinosaur|diplodocus"],
  ["🦖", "t-rex", "dinosaur|rex|t|tyrannosaurus"],
  ["🦗", "cricket", "animal|bug|grasshopper|insect|orthoptera"],
  ["🦘", "kangaroo", "animal|joey|jump|marsupial"],
  ["🦙", "llama", "alpaca|animal|guanaco|vicuña|wool"],
  ["🦚", "peacock", "animal|bird|colorful|ornithology|ostentatious|peahen|pretty|proud"],
  ["🦛", "hippopotamus", "animal|hippo"],
  ["🦜", "parrot", "animal|bird|ornithology|pirate|talk"],
  ["🦝", "raccoon", "animal|curious|sly"],
  ["🦞", "lobster", "animal|bisque|claws|seafood"],
  ["🦟", "mosquito", "bite|disease|fever|insect|malaria|pest|virus"],
  ["🦠", "microbe", "amoeba|bacteria|science|virus"],
  ["🦡", "badger", "animal|honey|pester"],
  ["🦢", "swan", "animal|bird|cygnet|duckling|ornithology|ugly"],
  ["🦣", "mammoth", "animal|extinction|large|tusk|wooly"],
  ["🦤", "dodo", "animal|bird|extinction|large|ornithology"],
  ["🦥", "sloth", "lazy|slow"],
  ["🦦", "otter", "animal|fishing|playful"],
  ["🦧", "orangutan", "animal|ape|monkey"],
  ["🦨", "skunk", "animal|stink"],
  ["🦩", "flamingo", "animal|bird|flamboyant|ornithology|tropical"],
  ["🦪", "oyster", "diving|pearl"],
  ["🦫", "beaver", "animal|dam|teeth"],
  ["🦬", "bison", "animal|buffalo|herd|wisent"],
  ["🦭", "seal", "animal|lion|ocean|sea"],
  ["🦮", "guide dog", "accessibility|animal|blind|dog|guide"],
  ["🦯", "white cane", "accessibility|blind|cane|probing|white"],
  ["🦰", "red hair", "ginger|hair|red|redhead"],
  ["🦱", "curly hair", "afro|curly|hair|ringlets"],
  ["🦲", "bald", "chemotherapy|hair|hairless|no|shaven"],
  ["🦳", "white hair", "gray|hair|old|white"],
  ["🦴", "bone", "bones|dog|skeleton|wishbone"],
  ["🦵", "leg", "bent|foot|kick|knee|limb"],
  ["🦶", "foot", "ankle|feet|kick|stomp"],
  ["🦷", "tooth", "dentist|pearly|teeth|white"],
  ["🦸", "superhero", "good|hero|superpower"],
  ["🦹", "supervillain", "bad|criminal|evil|superpower|villain"],
  ["🦻", "ear with hearing aid", "accessibility|aid|ear|hard|hearing"],
  ["🦼", "motorized wheelchair", "accessibility|motorized|wheelchair"],
  ["🦽", "manual wheelchair", "accessibility|manual|wheelchair"],
  ["🦾", "mechanical arm", "accessibility|arm|mechanical|prosthetic"],
  ["🦿", "mechanical leg", "accessibility|leg|mechanical|prosthetic"],
  ["🧀", "cheese wedge", "cheese|wedge"],
  ["🧁", "cupcake", "bakery|dessert|sprinkles|sugar|sweet|treat"],
  ["🧂", "salt", "condiment|flavor|mad|salty|shaker|taste|upset"],
  ["🧃", "beverage box", "beverage|box|juice|straw|sweet"],
  ["🧄", "garlic", "flavoring"],
  ["🧅", "onion", "flavoring"],
  ["🧆", "falafel", "chickpea|meatball"],
  ["🧇", "waffle", "breakfast|indecisive|iron"],
  ["🧈", "butter", "dairy"],
  ["🧉", "mate", "drink"],
  ["🧊", "ice", "cold|cube|iceberg"],
  ["🧋", "bubble tea", "boba|bubble|food|milk|pearl|tea"],
  ["🧍", "person standing", "person|stand|standing"],
  ["🧎", "person kneeling", "kneel|kneeling|knees|person"],
  ["🧏", "deaf person", "accessibility|deaf|ear|gesture|hear|person"],
  ["🧐", "face with monocle", "classy|face|fancy|monocle|rich|stuffy|wealthy"],
  ["🧑", "person", "adult"],
  ["🧒", "child", "bright-eyed|grandchild|kid|young|younger"],
  ["🧓", "older person", "adult|elderly|grandparent|old|person|wise"],
  ["🧔", "person: beard", "beard|bearded|person|whiskers"],
  ["🧕", "woman with headscarf", "bandana|head|headscarf|hijab|kerchief|mantilla|tichel|woman"],
  ["🧖", "person in steamy room", "day|luxurious|pamper|person|relax|room|sauna|spa|steam|steambath|unwind"],
  ["🧗", "person climbing", "climb|climber|climbing|mountain|person|rock|scale|up"],
  ["🧘", "person in lotus position", "cross|legged|legs|lotus|meditation|peace|person|position|relax|serenity|yoga|yogi|zen"],
  ["🧙", "mage", "fantasy|magic|play|sorcerer|sorceress|sorcery|spell|summon|witch|wizard"],
  ["🧚", "fairy", "fairytale|fantasy|myth|person|pixie|tale|wings"],
  ["🧛", "vampire", "blood|dracula|fangs|halloween|scary|supernatural|teeth|undead"],
  ["🧜", "merperson", "creature|fairytale|folklore|ocean|sea|siren|trident"],
  ["🧝", "elf", "elves|enchantment|fantasy|folklore|magic|magical|myth"],
  ["🧞", "genie", "djinn|fantasy|jinn|lamp|myth|rub|wishes"],
  ["🧟", "zombie", "apocalypse|dead|halloween|horror|scary|undead|walking"],
  ["🧠", "brain", "intelligent|smart"],
  ["🧡", "orange heart", "143|heart|orange"],
  ["🧢", "billed cap", "baseball|bent|billed|cap|dad|hat"],
  ["🧣", "scarf", "bundle|cold|neck|up"],
  ["🧤", "gloves", "hand"],
  ["🧥", "coat", "brr|bundle|cold|jacket|up"],
  ["🧦", "socks", "stocking"],
  ["🧧", "red envelope", "envelope|gift|good|hóngbāo|lai|luck|money|red|see"],
  ["🧨", "firecracker", "dynamite|explosive|fire|fireworks|light|pop|popping|spark"],
  ["🧩", "puzzle piece", "clue|interlocking|jigsaw|piece|puzzle"],
  ["🧪", "test tube", "chemist|chemistry|experiment|lab|science|test|tube"],
  ["🧫", "petri dish", "bacteria|biologist|biology|culture|dish|lab|petri"],
  ["🧬", "dna", "biologist|evolution|gene|genetics|life"],
  ["🧭", "compass", "direction|magnetic|navigation|orienteering"],
  ["🧮", "abacus", "calculation|calculator"],
  ["🧯", "fire extinguisher", "extinguish|extinguisher|fire|quench"],
  ["🧰", "toolbox", "box|chest|mechanic|red|tool"],
  ["🧱", "brick", "bricks|clay|mortar|wall"],
  ["🧲", "magnet", "attraction|horseshoe|magnetic|negative|positive|shape|u"],
  ["🧳", "luggage", "bag|packing|roller|suitcase|travel"],
  ["🧴", "lotion bottle", "bottle|lotion|moisturizer|shampoo|sunscreen"],
  ["🧵", "thread", "needle|sewing|spool|string"],
  ["🧶", "yarn", "ball|crochet|knit"],
  ["🧷", "safety pin", "diaper|pin|punk|rock|safety"],
  ["🧸", "teddy bear", "bear|plaything|plush|stuffed|teddy|toy"],
  ["🧹", "broom", "cleaning|sweeping|witch"],
  ["🧺", "basket", "farming|laundry|picnic"],
  ["🧻", "roll of paper", "paper|roll|toilet|towels"],
  ["🧼", "soap", "bar|bathing|clean|cleaning|lather|soapdish"],
  ["🧽", "sponge", "absorbing|cleaning|porous|soak"],
  ["🧾", "receipt", "accounting|bookkeeping|evidence|invoice|proof"],
  ["🧿", "nazar amulet", "amulet|bead|blue|charm|evil-eye|nazar|talisman"],
  ["🩰", "ballet shoes", "ballet|dance|shoes"],
  ["🩱", "one-piece swimsuit", "bathing|one-piece|suit|swimsuit"],
  ["🩲", "briefs", "bathing|one-piece|suit|swimsuit|underwear"],
  ["🩳", "shorts", "bathing|pants|suit|swimsuit|underwear"],
  ["🩴", "thong sandal", "beach|flip|flop|sandal|sandals|shoe|thong|thongs|zōri"],
  ["🩵", "light blue heart", "143|blue|cute|cyan|emotion|heart|ily|light|like|love|sky|special|teal"],
  ["🩶", "grey heart", "143|emotion|gray|grey|heart|ily|love|silver|slate|special"],
  ["🩷", "pink heart", "143|adorable|cute|emotion|heart|ily|like|love|pink|special|sweet"],
  ["🩸", "drop of blood", "bleed|blood|donation|drop|injury|medicine|menstruation"],
  ["🩹", "adhesive bandage", "adhesive|bandage"],
  ["🩺", "stethoscope", "doctor|heart|medicine"],
  ["🩻", "x-ray", "bones|doctor|medical|skeleton|skull|xray"],
  ["🩼", "crutch", "aid|cane|disability|help|hurt|injured|mobility|stick"],
  ["🪀", "yo-yo", "fluctuate|toy"],
  ["🪁", "kite", "fly|soar"],
  ["🪂", "parachute", "hang-glide|parasail|skydive"],
  ["🪃", "boomerang", "rebound|repercussion|weapon"],
  ["🪄", "magic wand", "magic|magician|wand|witch|wizard"],
  ["🪅", "piñata", "candy|celebrate|celebration|cinco|de|festive|mayo|party|pinada|pinata"],
  ["🪆", "nesting dolls", "babooshka|baboushka|babushka|doll|dolls|matryoshka|nesting|russia"],
  ["🪇", "maracas", "cha|dance|instrument|music|party|percussion|rattle|shake|shaker"],
  ["🪈", "flute", "band|fife|flautist|instrument|marching|music|orchestra|piccolo|pipe|recorder|woodwind"],
  ["🪉", "harp", "cupid|instrument|love|music|orchestra"],
  ["🪐", "ringed planet", "planet|ringed|saturn|saturnine"],
  ["🪑", "chair", "seat|sit"],
  ["🪒", "razor", "sharp|shave"],
  ["🪓", "axe", "ax|chop|hatchet|split|wood"],
  ["🪔", "diya lamp", "diya|lamp|light|oil"],
  ["🪕", "banjo", "music|stringed"],
  ["🪖", "military helmet", "army|helmet|military|soldier|war|warrior"],
  ["🪗", "accordion", "box|concertina|instrument|music|squeeze|squeezebox"],
  ["🪘", "long drum", "beat|conga|drum|instrument|long|rhythm"],
  ["🪙", "coin", "dollar|euro|gold|metal|money|rich|silver|treasure"],
  ["🪚", "carpentry saw", "carpenter|carpentry|cut|lumber|saw|tool|trim"],
  ["🪛", "screwdriver", "flathead|handy|screw|tool"],
  ["🪜", "ladder", "climb|rung|step"],
  ["🪝", "hook", "catch|crook|curve|ensnare|point|selling"],
  ["🪞", "mirror", "makeup|reflection|reflector|speculum"],
  ["🪟", "window", "air|frame|fresh|opening|transparent|view"],
  ["🪠", "plunger", "cup|force|plumber|poop|suction|toilet"],
  ["🪡", "sewing needle", "embroidery|needle|sew|sewing|stitches|sutures|tailoring|thread"],
  ["🪢", "knot", "cord|rope|tangled|tie|twine|twist"],
  ["🪣", "bucket", "cask|pail|vat"],
  ["🪤", "mouse trap", "bait|cheese|lure|mouse|mousetrap|snare|trap"],
  ["🪥", "toothbrush", "bathroom|brush|clean|dental|hygiene|teeth|toiletry"],
  ["🪦", "headstone", "cemetery|dead|grave|graveyard|memorial|rip|tomb|tombstone"],
  ["🪧", "placard", "card|demonstration|notice|picket|plaque|protest|sign"],
  ["🪨", "rock", "boulder|heavy|solid|stone|tough"],
  ["🪩", "mirror ball", "ball|dance|disco|glitter|mirror|party"],
  ["🪪", "identification card", "card|credentials|document|id|identification|license|security"],
  ["🪫", "low battery", "battery|drained|electronic|energy|low|power"],
  ["🪬", "hamsa", "amulet|fatima|fortune|guide|hand|mary|miriam|palm|protect|protection"],
  ["🪭", "folding hand fan", "clack|clap|cool|cooling|dance|fan|flirt|flutter|folding|hand|hot|shy"],
  ["🪮", "hair pick", "afro|comb|groom|hair|pick"],
  ["🪯", "khanda", "deg|fateh|khalsa|religion|sikh|sikhism|tegh"],
  ["🪰", "fly", "animal|disease|insect|maggot|pest|rotting"],
  ["🪱", "worm", "animal|annelid|earthworm|parasite"],
  ["🪲", "beetle", "animal|bug|insect"],
  ["🪳", "cockroach", "animal|insect|pest|roach"],
  ["🪴", "potted plant", "decor|grow|house|nurturing|plant|pot|potted"],
  ["🪵", "wood", "log|lumber|timber"],
  ["🪶", "feather", "bird|flight|light|plumage"],
  ["🪷", "lotus", "beauty|buddhism|calm|flower|hinduism|peace|purity|serenity"],
  ["🪸", "coral", "change|climate|ocean|reef|sea"],
  ["🪹", "empty nest", "branch|empty|home|nest|nesting"],
  ["🪺", "nest with eggs", "bird|branch|egg|eggs|nest|nesting"],
  ["🪻", "hyacinth", "bloom|bluebonnet|flower|indigo|lavender|lilac|lupine|plant|purple|shrub|snapdragon|spring|violet"],
  ["🪼", "jellyfish", "animal|aquarium|burn|invertebrate|jelly|life|marine|ocean|ouch|plankton|sea|sting|stinger|tentacles"],
  ["🪽", "wing", "angelic|ascend|aviation|bird|fly|flying|heavenly|mythology|soar"],
  ["🪾", "leafless tree", "bare|barren|branches|dead|drought|leafless|tree|trunk|winter|wood"],
  ["🪿", "goose", "animal|bird|duck|flock|fowl|gaggle|gander|geese|honk|ornithology|silly"],
  ["🫀", "anatomical heart", "anatomical|beat|cardiology|heart|heartbeat|organ|pulse|real|red"],
  ["🫁", "lungs", "breath|breathe|exhalation|inhalation|lung|organ|respiration"],
  ["🫂", "people hugging", "comfort|embrace|farewell|friendship|goodbye|hello|hug|hugging|love|people|thanks"],
  ["🫃", "pregnant man", "belly|bloated|full|man|overeat|pregnant"],
  ["🫄", "pregnant person", "belly|bloated|full|overeat|person|pregnant|stuffed"],
  ["🫅", "person with crown", "crown|monarch|noble|person|regal|royal|royalty"],
  ["🫐", "blueberries", "berries|berry|bilberry|blue|blueberry|food|fruit"],
  ["🫑", "bell pepper", "bell|capsicum|food|pepper|vegetable"],
  ["🫒", "olive", "food"],
  ["🫓", "flatbread", "arepa|bread|food|gordita|lavash|naan|pita"],
  ["🫔", "tamale", "food|mexican|pamonha|wrapped"],
  ["🫕", "fondue", "cheese|chocolate|food|melted|pot|ski"],
  ["🫖", "teapot", "brew|drink|food|pot|tea"],
  ["🫗", "pouring liquid", "accident|drink|empty|glass|liquid|oops|pour|pouring|spill|water"],
  ["🫘", "beans", "food|kidney|legume|small"],
  ["🫙", "jar", "condiment|container|empty|nothing|sauce|store"],
  ["🫚", "ginger root", "beer|ginger|health|herb|natural|root|spice"],
  ["🫛", "pea pod", "beans|beanstalk|edamame|legume|pea|pod|soybean|vegetable|veggie"],
  ["🫜", "root vegetable", "beet|food|garden|radish|root|salad|turnip|vegetable|vegetarian"],
  ["🫰", "hand with index finger and thumb crossed", "<3|crossed|expensive|finger|hand|heart|index|love|money|snap|thumb"],
  ["🫱", "rightwards hand", "hand|handshake|hold|reach|right|rightward|rightwards|shake"],
  ["🫲", "leftwards hand", "hand|handshake|hold|left|leftward|leftwards|reach|shake"],
  ["🫳", "palm down hand", "dismiss|down|drop|dropped|hand|palm|pick|shoo|up"],
  ["🫴", "palm up hand", "beckon|catch|come|hand|hold|know|lift|me|offer|palm|tell"],
  ["🫵", "index pointing at the viewer", "at|finger|hand|index|pointing|poke|viewer|you"],
  ["🫶", "heart hands", "<3|hands|heart|love|you"],
  ["🫷", "leftwards pushing hand", "block|five|halt|hand|high|hold|leftward|leftwards|pause|push|pushing|refuse|slap|stop|wait"],
  ["🫸", "rightwards pushing hand", "block|five|halt|hand|high|hold|pause|push|pushing|refuse|rightward|rightwards|slap|stop|wait"],
  ["‼", "double exclamation mark", "!|!!|bangbang|double|exclamation|mark|punctuation"],
  ["⁉", "exclamation question mark", "!|!?|?|exclamation|interrobang|mark|punctuation|question"],
  ["™", "trade mark", "mark|tm|trade|trademark"],
  ["ℹ", "information", "i"],
  ["↔", "left-right arrow", "arrow|left-right"],
  ["↕", "up-down arrow", "arrow|up-down"],
  ["↖", "up-left arrow", "arrow|direction|intercardinal|northwest|up-left"],
  ["↗", "up-right arrow", "arrow|direction|intercardinal|northeast|up-right"],
  ["↘", "down-right arrow", "arrow|direction|down-right|intercardinal|southeast"],
  ["↙", "down-left arrow", "arrow|direction|down-left|intercardinal|southwest"],
  ["↩", "right arrow curving left", "arrow|curving|left|right"],
  ["↪", "left arrow curving right", "arrow|curving|left|right"],
  ["⌚", "watch", "clock|time"],
  ["⌛", "hourglass done", "done|hourglass|sand|time|timer"],
  ["⌨", "keyboard", "computer"],
  ["⏏", "eject button", "button|eject"],
  ["⏩", "fast-forward button", "arrow|button|double|fast|fast-forward|forward"],
  ["⏪", "fast reverse button", "arrow|button|double|fast|reverse|rewind"],
  ["⏫", "fast up button", "arrow|button|double|fast|up"],
  ["⏬", "fast down button", "arrow|button|double|down|fast"],
  ["⏭", "next track button", "arrow|button|next|scene|track|triangle"],
  ["⏮", "last track button", "arrow|button|last|previous|scene|track|triangle"],
  ["⏯", "play or pause button", "arrow|button|pause|play|right|triangle"],
  ["⏰", "alarm clock", "alarm|clock|hours|hrs|late|time|waiting"],
  ["⏱", "stopwatch", "clock|time"],
  ["⏲", "timer clock", "clock|timer"],
  ["⏳", "hourglass not done", "done|flowing|hourglass|hours|not|sand|timer|waiting|yolo"],
  ["⏸", "pause button", "bar|button|double|pause|vertical"],
  ["⏹", "stop button", "button|square|stop"],
  ["⏺", "record button", "button|circle|record"],
  ["Ⓜ", "circled m", "circle|circled|m"],
  ["▪", "black small square", "black|geometric|small|square"],
  ["▫", "white small square", "geometric|small|square|white"],
  ["▶", "play button", "arrow|button|play|right|triangle"],
  ["◀", "reverse button", "arrow|button|left|reverse|triangle"],
  ["◻", "white medium square", "geometric|medium|square|white"],
  ["◼", "black medium square", "black|geometric|medium|square"],
  ["◽", "white medium-small square", "geometric|medium-small|square|white"],
  ["◾", "black medium-small square", "black|geometric|medium-small|square"],
  ["☀", "sun", "bright|rays|space|sunny|weather"],
  ["☁", "cloud", "weather"],
  ["☂", "umbrella", "clothing|rain"],
  ["☃", "snowman", "cold|man|snow"],
  ["☄", "comet", "space"],
  ["☎", "telephone", "phone"],
  ["☑", "check box with check", "✓|ballot|box|check|checked|done|off|tick"],
  ["☔", "umbrella with rain drops", "clothing|drop|drops|rain|umbrella|weather"],
  ["☕", "hot beverage", "beverage|cafe|caffeine|chai|coffee|drink|hot|morning|steaming|tea"],
  ["☝", "index pointing up", "finger|hand|index|point|pointing|this|up"],
  ["☦", "orthodox cross", "christian|cross|orthodox|religion"],
  ["☪", "star and crescent", "crescent|islam|muslim|ramadan|religion|star"],
  ["☮", "peace symbol", "healing|peace|peaceful|symbol"],
  ["☯", "yin yang", "difficult|lives|religion|tao|taoist|total|yang|yin|yinyang"],
  ["☸", "wheel of dharma", "buddhist|dharma|religion|wheel"],
  ["☹", "frowning face", "face|frown|frowning|sad"],
  ["☺", "smiling face", "face|happy|outlined|relaxed|smile|smiling"],
  ["♈", "aries", "horoscope|ram|zodiac"],
  ["♉", "taurus", "bull|horoscope|ox|zodiac"],
  ["♊", "gemini", "horoscope|twins|zodiac"],
  ["♋", "cancer", "crab|horoscope|zodiac"],
  ["♌", "leo", "horoscope|lion|zodiac"],
  ["♍", "virgo", "horoscope|zodiac"],
  ["♎", "libra", "balance|horoscope|justice|scales|zodiac"],
  ["♏", "scorpio", "horoscope|scorpion|scorpius|zodiac"],
  ["♐", "sagittarius", "archer|horoscope|zodiac"],
  ["♑", "capricorn", "goat|horoscope|zodiac"],
  ["♒", "aquarius", "bearer|horoscope|water|zodiac"],
  ["♓", "pisces", "fish|horoscope|zodiac"],
  ["♟", "chess pawn", "chess|dupe|expendable|pawn"],
  ["♻", "recycling symbol", "recycle|recycling|symbol"],
  ["♾", "infinity", "forever|unbounded|universal"],
  ["♿", "wheelchair symbol", "access|handicap|symbol|wheelchair"],
  ["⚒", "hammer and pick", "hammer|pick|tool"],
  ["⚔", "crossed swords", "crossed|swords|weapon"],
  ["⚕", "medical symbol", "aesculapius|medical|medicine|staff|symbol"],
  ["⚖", "balance scale", "balance|justice|libra|scale|scales|tool|weight|zodiac"],
  ["⚗", "alembic", "chemistry|tool"],
  ["⚙", "gear", "cog|cogwheel|tool"],
  ["⚛", "atom symbol", "atheist|atom|symbol"],
  ["⚜", "fleur-de-lis", "knights"],
  ["⚠", "warning", "caution"],
  ["⚡", "high voltage", "danger|electric|electricity|high|lightning|nature|thunder|thunderbolt|voltage|zap"],
  ["⚧", "transgender symbol", "symbol|transgender"],
  ["⚪", "white circle", "circle|geometric|white"],
  ["⚫", "black circle", "black|circle|geometric"],
  ["⚰", "coffin", "dead|death|vampire"],
  ["⚱", "funeral urn", "ashes|death|funeral|urn"],
  ["⚽", "soccer ball", "ball|football|futbol|soccer|sport"],
  ["⚾", "baseball", "ball|sport"],
  ["⛄", "snowman without snow", "cold|man|snow|snowman"],
  ["⛅", "sun behind cloud", "behind|cloud|cloudy|sun|weather"],
  ["⛈", "cloud with lightning and rain", "cloud|lightning|rain|thunder|thunderstorm"],
  ["⛎", "ophiuchus", "bearer|serpent|snake|zodiac"],
  ["⛏", "pick", "hammer|mining|tool"],
  ["⛑", "rescue worker’s helmet", "aid|cross|face|hat|helmet|rescue|worker’s"],
  ["⛓", "chains", "chain"],
  ["⛔", "no entry", "do|entry|fail|forbidden|no|not|pass|prohibited|traffic"],
  ["⛩", "shinto shrine", "religion|shinto|shrine"],
  ["⛪", "church", "bless|chapel|christian|cross|religion"],
  ["⛰", "mountain", ""],
  ["⛱", "umbrella on ground", "ground|rain|sun|umbrella"],
  ["⛲", "fountain", ""],
  ["⛳", "flag in hole", "flag|golf|hole|sport"],
  ["⛴", "ferry", "boat|passenger"],
  ["⛵", "sailboat", "boat|resort|sailing|sea|yacht"],
  ["⛷", "skier", "ski|snow"],
  ["⛸", "ice skate", "ice|skate|skating"],
  ["⛹", "person bouncing ball", "athletic|ball|basketball|bouncing|championship|dribble|net|person|player|throw"],
  ["⛺", "tent", "camping"],
  ["⛽", "fuel pump", "diesel|fuel|fuelpump|gas|gasoline|pump|station"],
  ["✂", "scissors", "cut|cutting|paper|tool"],
  ["✅", "check mark button", "✓|button|check|checked|checkmark|complete|completed|done|fixed|mark|tick"],
  ["✈", "airplane", "aeroplane|fly|flying|jet|plane|travel"],
  ["✉", "envelope", "e-mail|email|letter"],
  ["✊", "raised fist", "clenched|fist|hand|punch|raised|solidarity"],
  ["✋", "raised hand", "5|five|hand|high|raised|stop"],
  ["✌", "victory hand", "hand|peace|v|victory"],
  ["✍", "writing hand", "hand|write|writing"],
  ["✏", "pencil", ""],
  ["✒", "black nib", "black|nib|pen"],
  ["✔", "check mark", "✓|check|checked|checkmark|done|heavy|mark|tick"],
  ["✖", "multiply", "×|cancel|multiplication|sign|x"],
  ["✝", "latin cross", "christ|christian|cross|latin|religion"],
  ["✡", "star of david", "david|jew|jewish|judaism|religion|star"],
  ["✨", "sparkles", "*|magic|sparkle|star"],
  ["✳", "eight-spoked asterisk", "*|asterisk|eight-spoked"],
  ["✴", "eight-pointed star", "*|eight-pointed|star"],
  ["❄", "snowflake", "cold|snow|weather"],
  ["❇", "sparkle", "*"],
  ["❌", "cross mark", "×|cancel|cross|mark|multiplication|multiply|x"],
  ["❎", "cross mark button", "×|button|cross|mark|multiplication|multiply|square|x"],
  ["❓", "red question mark", "?|mark|punctuation|question|red"],
  ["❔", "white question mark", "?|mark|outlined|punctuation|question|white"],
  ["❕", "white exclamation mark", "!|exclamation|mark|outlined|punctuation|white"],
  ["❗", "red exclamation mark", "!|exclamation|mark|punctuation|red"],
  ["❣", "heart exclamation", "exclamation|heart|heavy|mark|punctuation"],
  ["❤", "red heart", "emotion|heart|love|red"],
  ["➕", "plus", "+"],
  ["➖", "minus", "-|−|heavy|math|sign"],
  ["➗", "divide", "÷|division|heavy|math|sign"],
  ["➡", "right arrow", "arrow|cardinal|direction|east|right"],
  ["➰", "curly loop", "curl|curly|loop"],
  ["➿", "double curly loop", "curl|curly|double|loop"],
  ["⤴", "right arrow curving up", "arrow|curving|right|up"],
  ["⤵", "right arrow curving down", "arrow|curving|down|right"],
  ["⬅", "left arrow", "arrow|cardinal|direction|left|west"],
  ["⬆", "up arrow", "arrow|cardinal|direction|north|up"],
  ["⬇", "down arrow", "arrow|cardinal|direction|down|south"],
  ["⬛", "black large square", "black|geometric|large|square"],
  ["⬜", "white large square", "geometric|large|square|white"],
  ["⭐", "star", "astronomy|medium|stars|white"],
  ["⭕", "hollow red circle", "circle|heavy|hollow|large|o|red"],
  ["〰", "wavy dash", "dash|punctuation|wavy"],
  ["〽", "part alternation mark", "alternation|mark|part"],
  ["㊗", "japanese “congratulations” button", "button|congratulations|ideograph|japanese"],
  ["㊙", "japanese “secret” button", "button|ideograph|japanese|secret"],
];

export default ROWS;
