// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Produced by `scripts/generate-emoji-data.py`. To regenerate:
//
//     python3 scripts/generate-emoji-data.py
//
// Unicode data version: 16.0.0
// Country names from:   /usr/share/zoneinfo/iso3166.tab
// Entries:              1581 (people 298, nature 149, food 128, activity 78, travel 214, objects 258, symbols 207, flags 249)
//
// Names come straight from `unicodedata.name()`, lowercased, and double as
// the search keywords — there is deliberately no separate keyword field.
// Categories approximate the CLDR groups; see the generator's docstring for
// the exact ranges and the known approximation limits.

export type EmojiCategoryId =
  | "people"
  | "nature"
  | "food"
  | "activity"
  | "travel"
  | "objects"
  | "symbols"
  | "flags";

export interface EmojiCategory {
  readonly id: EmojiCategoryId;
  readonly label: string;
}

export interface StandardEmoji {
  /** The emoji character itself. */
  readonly char: string;
  /** Human-readable name, lowercase (e.g. "grinning face"). */
  readonly name: string;
  readonly category: EmojiCategoryId;
  /** True when this base emoji accepts a Fitzpatrick skin-tone modifier. */
  readonly tonable: boolean;
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  { id: "people", label: "People" },
  { id: "nature", label: "Nature" },
  { id: "food", label: "Food" },
  { id: "activity", label: "Activities" },
  { id: "travel", label: "Travel" },
  { id: "objects", label: "Objects" },
  { id: "symbols", label: "Symbols" },
  { id: "flags", label: "Flags" },
];

/** The five Fitzpatrick modifiers, in Discord's order (index 0 = default/none). */
export const SKIN_TONES: readonly string[] = ["", "\u{1F3FB}", "\u{1F3FC}", "\u{1F3FD}", "\u{1F3FE}", "\u{1F3FF}"];

// The table is emitted as positional rows rather than object literals: at this
// size a literal array of 1500+ distinct object types makes tsc give up with
// "union type that is too complex to represent" (TS2590). Rows are contextually
// typed against the single EmojiRow tuple type, so there is no union to widen,
// and the file stays one entry per line for readable diffs.
type EmojiRow = readonly [
  char: string,
  name: string,
  category: EmojiCategoryId,
  tonable: 0 | 1,
];

const EMOJI_ROWS: readonly EmojiRow[] = [
  ["☝", "white up pointing index", "people", 1],
  ["☹", "white frowning face", "people", 0],
  ["☺", "white smiling face", "people", 0],
  ["⛹", "person with ball", "people", 1],
  ["✊", "raised fist", "people", 1],
  ["✋", "raised hand", "people", 1],
  ["✌", "victory hand", "people", 1],
  ["✍", "writing hand", "people", 1],
  ["❣", "heavy heart exclamation mark ornament", "people", 0],
  ["❤", "heavy black heart", "people", 0],
  ["🎅", "father christmas", "people", 1],
  ["🏂", "snowboarder", "people", 1],
  ["🏃", "runner", "people", 1],
  ["🏄", "surfer", "people", 1],
  ["🏇", "horse racing", "people", 1],
  ["🏊", "swimmer", "people", 1],
  ["🏋", "weight lifter", "people", 1],
  ["🏌", "golfer", "people", 1],
  ["👀", "eyes", "people", 0],
  ["👁", "eye", "people", 0],
  ["👂", "ear", "people", 1],
  ["👃", "nose", "people", 1],
  ["👄", "mouth", "people", 0],
  ["👅", "tongue", "people", 0],
  ["👆", "white up pointing backhand index", "people", 1],
  ["👇", "white down pointing backhand index", "people", 1],
  ["👈", "white left pointing backhand index", "people", 1],
  ["👉", "white right pointing backhand index", "people", 1],
  ["👊", "fisted hand sign", "people", 1],
  ["👋", "waving hand sign", "people", 1],
  ["👌", "ok hand sign", "people", 1],
  ["👍", "thumbs up sign", "people", 1],
  ["👎", "thumbs down sign", "people", 1],
  ["👏", "clapping hands sign", "people", 1],
  ["👐", "open hands sign", "people", 1],
  ["👣", "footprints", "people", 0],
  ["👤", "bust in silhouette", "people", 0],
  ["👥", "busts in silhouette", "people", 0],
  ["👦", "boy", "people", 1],
  ["👧", "girl", "people", 1],
  ["👨", "man", "people", 1],
  ["👩", "woman", "people", 1],
  ["👪", "family", "people", 1],
  ["👫", "man and woman holding hands", "people", 1],
  ["👬", "two men holding hands", "people", 1],
  ["👭", "two women holding hands", "people", 1],
  ["👮", "police officer", "people", 1],
  ["👯", "woman with bunny ears", "people", 1],
  ["👰", "bride with veil", "people", 1],
  ["👱", "person with blond hair", "people", 1],
  ["👲", "man with gua pi mao", "people", 1],
  ["👳", "man with turban", "people", 1],
  ["👴", "older man", "people", 1],
  ["👵", "older woman", "people", 1],
  ["👶", "baby", "people", 1],
  ["👷", "construction worker", "people", 1],
  ["👸", "princess", "people", 1],
  ["👹", "japanese ogre", "people", 0],
  ["👺", "japanese goblin", "people", 0],
  ["👻", "ghost", "people", 0],
  ["👼", "baby angel", "people", 1],
  ["👽", "extraterrestrial alien", "people", 0],
  ["👾", "alien monster", "people", 0],
  ["👿", "imp", "people", 0],
  ["💀", "skull", "people", 0],
  ["💁", "information desk person", "people", 1],
  ["💂", "guardsman", "people", 1],
  ["💃", "dancer", "people", 1],
  ["💄", "lipstick", "people", 0],
  ["💅", "nail polish", "people", 1],
  ["💆", "face massage", "people", 1],
  ["💇", "haircut", "people", 1],
  ["💋", "kiss mark", "people", 0],
  ["💌", "love letter", "people", 0],
  ["💏", "kiss", "people", 1],
  ["💑", "couple with heart", "people", 1],
  ["💓", "beating heart", "people", 0],
  ["💔", "broken heart", "people", 0],
  ["💕", "two hearts", "people", 0],
  ["💖", "sparkling heart", "people", 0],
  ["💗", "growing heart", "people", 0],
  ["💘", "heart with arrow", "people", 0],
  ["💙", "blue heart", "people", 0],
  ["💚", "green heart", "people", 0],
  ["💛", "yellow heart", "people", 0],
  ["💜", "purple heart", "people", 0],
  ["💝", "heart with ribbon", "people", 0],
  ["💞", "revolving hearts", "people", 0],
  ["💟", "heart decoration", "people", 0],
  ["💢", "anger symbol", "people", 0],
  ["💣", "bomb", "people", 0],
  ["💤", "sleeping symbol", "people", 0],
  ["💥", "collision symbol", "people", 0],
  ["💦", "splashing sweat symbol", "people", 0],
  ["💧", "droplet", "people", 0],
  ["💨", "dash symbol", "people", 0],
  ["💩", "pile of poo", "people", 0],
  ["💪", "flexed biceps", "people", 1],
  ["💫", "dizzy symbol", "people", 0],
  ["💬", "speech balloon", "people", 0],
  ["💭", "thought balloon", "people", 0],
  ["🕴", "man in business suit levitating", "people", 1],
  ["🕵", "sleuth or spy", "people", 1],
  ["🕺", "man dancing", "people", 1],
  ["🖐", "raised hand with fingers splayed", "people", 1],
  ["🖕", "reversed hand with middle finger extended", "people", 1],
  ["🖖", "raised hand with part between middle and ring fingers", "people", 1],
  ["🖤", "black heart", "people", 0],
  ["🗣", "speaking head in silhouette", "people", 0],
  ["🗨", "left speech bubble", "people", 0],
  ["🗯", "right anger bubble", "people", 0],
  ["😀", "grinning face", "people", 0],
  ["😁", "grinning face with smiling eyes", "people", 0],
  ["😂", "face with tears of joy", "people", 0],
  ["😃", "smiling face with open mouth", "people", 0],
  ["😄", "smiling face with open mouth and smiling eyes", "people", 0],
  ["😅", "smiling face with open mouth and cold sweat", "people", 0],
  ["😆", "smiling face with open mouth and tightly closed eyes", "people", 0],
  ["😇", "smiling face with halo", "people", 0],
  ["😈", "smiling face with horns", "people", 0],
  ["😉", "winking face", "people", 0],
  ["😊", "smiling face with smiling eyes", "people", 0],
  ["😋", "face savouring delicious food", "people", 0],
  ["😌", "relieved face", "people", 0],
  ["😍", "smiling face with heart shaped eyes", "people", 0],
  ["😎", "smiling face with sunglasses", "people", 0],
  ["😏", "smirking face", "people", 0],
  ["😐", "neutral face", "people", 0],
  ["😑", "expressionless face", "people", 0],
  ["😒", "unamused face", "people", 0],
  ["😓", "face with cold sweat", "people", 0],
  ["😔", "pensive face", "people", 0],
  ["😕", "confused face", "people", 0],
  ["😖", "confounded face", "people", 0],
  ["😗", "kissing face", "people", 0],
  ["😘", "face throwing a kiss", "people", 0],
  ["😙", "kissing face with smiling eyes", "people", 0],
  ["😚", "kissing face with closed eyes", "people", 0],
  ["😛", "face with stuck out tongue", "people", 0],
  ["😜", "face with stuck out tongue and winking eye", "people", 0],
  ["😝", "face with stuck out tongue and tightly closed eyes", "people", 0],
  ["😞", "disappointed face", "people", 0],
  ["😟", "worried face", "people", 0],
  ["😠", "angry face", "people", 0],
  ["😡", "pouting face", "people", 0],
  ["😢", "crying face", "people", 0],
  ["😣", "persevering face", "people", 0],
  ["😤", "face with look of triumph", "people", 0],
  ["😥", "disappointed but relieved face", "people", 0],
  ["😦", "frowning face with open mouth", "people", 0],
  ["😧", "anguished face", "people", 0],
  ["😨", "fearful face", "people", 0],
  ["😩", "weary face", "people", 0],
  ["😪", "sleepy face", "people", 0],
  ["😫", "tired face", "people", 0],
  ["😬", "grimacing face", "people", 0],
  ["😭", "loudly crying face", "people", 0],
  ["😮", "face with open mouth", "people", 0],
  ["😯", "hushed face", "people", 0],
  ["😰", "face with open mouth and cold sweat", "people", 0],
  ["😱", "face screaming in fear", "people", 0],
  ["😲", "astonished face", "people", 0],
  ["😳", "flushed face", "people", 0],
  ["😴", "sleeping face", "people", 0],
  ["😵", "dizzy face", "people", 0],
  ["😶", "face without mouth", "people", 0],
  ["😷", "face with medical mask", "people", 0],
  ["😸", "grinning cat face with smiling eyes", "people", 0],
  ["😹", "cat face with tears of joy", "people", 0],
  ["😺", "smiling cat face with open mouth", "people", 0],
  ["😻", "smiling cat face with heart shaped eyes", "people", 0],
  ["😼", "cat face with wry smile", "people", 0],
  ["😽", "kissing cat face with closed eyes", "people", 0],
  ["😾", "pouting cat face", "people", 0],
  ["😿", "crying cat face", "people", 0],
  ["🙀", "weary cat face", "people", 0],
  ["🙁", "slightly frowning face", "people", 0],
  ["🙂", "slightly smiling face", "people", 0],
  ["🙃", "upside down face", "people", 0],
  ["🙄", "face with rolling eyes", "people", 0],
  ["🙅", "face with no good gesture", "people", 1],
  ["🙆", "face with ok gesture", "people", 1],
  ["🙇", "person bowing deeply", "people", 1],
  ["🙈", "see no evil monkey", "people", 0],
  ["🙉", "hear no evil monkey", "people", 0],
  ["🙊", "speak no evil monkey", "people", 0],
  ["🙋", "happy person raising one hand", "people", 1],
  ["🙌", "person raising both hands in celebration", "people", 1],
  ["🙍", "person frowning", "people", 1],
  ["🙎", "person with pouting face", "people", 1],
  ["🙏", "person with folded hands", "people", 1],
  ["🚣", "rowboat", "people", 1],
  ["🚴", "bicyclist", "people", 1],
  ["🚵", "mountain bicyclist", "people", 1],
  ["🚶", "pedestrian", "people", 1],
  ["🛀", "bath", "people", 1],
  ["🛌", "sleeping accommodation", "people", 1],
  ["🤌", "pinched fingers", "people", 1],
  ["🤍", "white heart", "people", 0],
  ["🤎", "brown heart", "people", 0],
  ["🤏", "pinching hand", "people", 1],
  ["🤘", "sign of the horns", "people", 1],
  ["🤙", "call me hand", "people", 1],
  ["🤚", "raised back of hand", "people", 1],
  ["🤛", "left facing fist", "people", 1],
  ["🤜", "right facing fist", "people", 1],
  ["🤝", "handshake", "people", 1],
  ["🤞", "hand with index and middle fingers crossed", "people", 1],
  ["🤟", "i love you hand sign", "people", 1],
  ["🤠", "face with cowboy hat", "people", 0],
  ["🤡", "clown face", "people", 0],
  ["🤢", "nauseated face", "people", 0],
  ["🤣", "rolling on the floor laughing", "people", 0],
  ["🤤", "drooling face", "people", 0],
  ["🤥", "lying face", "people", 0],
  ["🤦", "face palm", "people", 1],
  ["🤧", "sneezing face", "people", 0],
  ["🤨", "face with one eyebrow raised", "people", 0],
  ["🤩", "grinning face with star eyes", "people", 0],
  ["🤪", "grinning face with one large and one small eye", "people", 0],
  ["🤫", "face with finger covering closed lips", "people", 0],
  ["🤬", "serious face with symbols covering mouth", "people", 0],
  ["🤭", "smiling face with smiling eyes and hand covering mouth", "people", 0],
  ["🤮", "face with open mouth vomiting", "people", 0],
  ["🤯", "shocked face with exploding head", "people", 0],
  ["🤰", "pregnant woman", "people", 1],
  ["🤱", "breast feeding", "people", 1],
  ["🤲", "palms up together", "people", 1],
  ["🤳", "selfie", "people", 1],
  ["🤴", "prince", "people", 1],
  ["🤵", "man in tuxedo", "people", 1],
  ["🤶", "mother christmas", "people", 1],
  ["🤷", "shrug", "people", 1],
  ["🤸", "person doing cartwheel", "people", 1],
  ["🤹", "juggling", "people", 1],
  ["🤼", "wrestlers", "people", 1],
  ["🤽", "water polo", "people", 1],
  ["🤾", "handball", "people", 1],
  ["🥰", "smiling face with smiling eyes and three hearts", "people", 0],
  ["🥱", "yawning face", "people", 0],
  ["🥲", "smiling face with tear", "people", 0],
  ["🥳", "face with party horn and party hat", "people", 0],
  ["🥴", "face with uneven eyes and wavy mouth", "people", 0],
  ["🥵", "overheated face", "people", 0],
  ["🥶", "freezing face", "people", 0],
  ["🥷", "ninja", "people", 1],
  ["🥸", "disguised face", "people", 0],
  ["🥹", "face holding back tears", "people", 0],
  ["🥺", "face with pleading eyes", "people", 0],
  ["🦰", "emoji component red hair", "people", 0],
  ["🦱", "emoji component curly hair", "people", 0],
  ["🦲", "emoji component bald", "people", 0],
  ["🦳", "emoji component white hair", "people", 0],
  ["🦴", "bone", "people", 0],
  ["🦵", "leg", "people", 1],
  ["🦶", "foot", "people", 1],
  ["🦷", "tooth", "people", 0],
  ["🦸", "superhero", "people", 1],
  ["🦹", "supervillain", "people", 1],
  ["🦻", "ear with hearing aid", "people", 1],
  ["🦾", "mechanical arm", "people", 0],
  ["🦿", "mechanical leg", "people", 0],
  ["🧍", "standing person", "people", 1],
  ["🧎", "kneeling person", "people", 1],
  ["🧏", "deaf person", "people", 1],
  ["🧐", "face with monocle", "people", 1],
  ["🧑", "adult", "people", 1],
  ["🧒", "child", "people", 1],
  ["🧓", "older adult", "people", 1],
  ["🧔", "bearded person", "people", 1],
  ["🧕", "person with headscarf", "people", 1],
  ["🧖", "person in steamy room", "people", 1],
  ["🧗", "person climbing", "people", 1],
  ["🧘", "person in lotus position", "people", 1],
  ["🧙", "mage", "people", 1],
  ["🧚", "fairy", "people", 1],
  ["🧛", "vampire", "people", 1],
  ["🧜", "merperson", "people", 1],
  ["🧝", "elf", "people", 1],
  ["🧞", "genie", "people", 1],
  ["🧟", "zombie", "people", 1],
  ["🧠", "brain", "people", 0],
  ["🧡", "orange heart", "people", 0],
  ["🫀", "anatomical heart", "people", 0],
  ["🫁", "lungs", "people", 0],
  ["🫂", "people hugging", "people", 0],
  ["🫃", "pregnant man", "people", 1],
  ["🫄", "pregnant person", "people", 1],
  ["🫅", "person with crown", "people", 1],
  ["🫰", "hand with index finger and thumb crossed", "people", 1],
  ["🫱", "rightwards hand", "people", 1],
  ["🫲", "leftwards hand", "people", 1],
  ["🫳", "palm down hand", "people", 1],
  ["🫴", "palm up hand", "people", 1],
  ["🫵", "index pointing at the viewer", "people", 1],
  ["🫶", "heart hands", "people", 1],
  ["🫷", "leftwards pushing hand", "people", 1],
  ["🫸", "rightwards pushing hand", "people", 1],
  ["🌱", "seedling", "nature", 0],
  ["🌲", "evergreen tree", "nature", 0],
  ["🌳", "deciduous tree", "nature", 0],
  ["🌴", "palm tree", "nature", 0],
  ["🌵", "cactus", "nature", 0],
  ["🌷", "tulip", "nature", 0],
  ["🌸", "cherry blossom", "nature", 0],
  ["🌹", "rose", "nature", 0],
  ["🌺", "hibiscus", "nature", 0],
  ["🌻", "sunflower", "nature", 0],
  ["🌼", "blossom", "nature", 0],
  ["🌾", "ear of rice", "nature", 0],
  ["🌿", "herb", "nature", 0],
  ["🍀", "four leaf clover", "nature", 0],
  ["🍁", "maple leaf", "nature", 0],
  ["🍂", "fallen leaf", "nature", 0],
  ["🍃", "leaf fluttering in wind", "nature", 0],
  ["🐀", "rat", "nature", 0],
  ["🐁", "mouse", "nature", 0],
  ["🐂", "ox", "nature", 0],
  ["🐃", "water buffalo", "nature", 0],
  ["🐄", "cow", "nature", 0],
  ["🐅", "tiger", "nature", 0],
  ["🐆", "leopard", "nature", 0],
  ["🐇", "rabbit", "nature", 0],
  ["🐈", "cat", "nature", 0],
  ["🐉", "dragon", "nature", 0],
  ["🐊", "crocodile", "nature", 0],
  ["🐋", "whale", "nature", 0],
  ["🐌", "snail", "nature", 0],
  ["🐍", "snake", "nature", 0],
  ["🐎", "horse", "nature", 0],
  ["🐏", "ram", "nature", 0],
  ["🐐", "goat", "nature", 0],
  ["🐑", "sheep", "nature", 0],
  ["🐒", "monkey", "nature", 0],
  ["🐓", "rooster", "nature", 0],
  ["🐔", "chicken", "nature", 0],
  ["🐕", "dog", "nature", 0],
  ["🐖", "pig", "nature", 0],
  ["🐗", "boar", "nature", 0],
  ["🐘", "elephant", "nature", 0],
  ["🐙", "octopus", "nature", 0],
  ["🐚", "spiral shell", "nature", 0],
  ["🐛", "bug", "nature", 0],
  ["🐜", "ant", "nature", 0],
  ["🐝", "honeybee", "nature", 0],
  ["🐞", "lady beetle", "nature", 0],
  ["🐟", "fish", "nature", 0],
  ["🐠", "tropical fish", "nature", 0],
  ["🐡", "blowfish", "nature", 0],
  ["🐢", "turtle", "nature", 0],
  ["🐣", "hatching chick", "nature", 0],
  ["🐤", "baby chick", "nature", 0],
  ["🐥", "front facing baby chick", "nature", 0],
  ["🐦", "bird", "nature", 0],
  ["🐧", "penguin", "nature", 0],
  ["🐨", "koala", "nature", 0],
  ["🐩", "poodle", "nature", 0],
  ["🐪", "dromedary camel", "nature", 0],
  ["🐫", "bactrian camel", "nature", 0],
  ["🐬", "dolphin", "nature", 0],
  ["🐭", "mouse face", "nature", 0],
  ["🐮", "cow face", "nature", 0],
  ["🐯", "tiger face", "nature", 0],
  ["🐰", "rabbit face", "nature", 0],
  ["🐱", "cat face", "nature", 0],
  ["🐲", "dragon face", "nature", 0],
  ["🐳", "spouting whale", "nature", 0],
  ["🐴", "horse face", "nature", 0],
  ["🐵", "monkey face", "nature", 0],
  ["🐶", "dog face", "nature", 0],
  ["🐷", "pig face", "nature", 0],
  ["🐸", "frog face", "nature", 0],
  ["🐹", "hamster face", "nature", 0],
  ["🐺", "wolf face", "nature", 0],
  ["🐻", "bear face", "nature", 0],
  ["🐼", "panda face", "nature", 0],
  ["🐽", "pig nose", "nature", 0],
  ["🐾", "paw prints", "nature", 0],
  ["🐿", "chipmunk", "nature", 0],
  ["💐", "bouquet", "nature", 0],
  ["💮", "white flower", "nature", 0],
  ["🕷", "spider", "nature", 0],
  ["🕸", "spider web", "nature", 0],
  ["🦀", "crab", "nature", 0],
  ["🦁", "lion face", "nature", 0],
  ["🦂", "scorpion", "nature", 0],
  ["🦃", "turkey", "nature", 0],
  ["🦄", "unicorn face", "nature", 0],
  ["🦅", "eagle", "nature", 0],
  ["🦆", "duck", "nature", 0],
  ["🦇", "bat", "nature", 0],
  ["🦈", "shark", "nature", 0],
  ["🦉", "owl", "nature", 0],
  ["🦊", "fox face", "nature", 0],
  ["🦋", "butterfly", "nature", 0],
  ["🦌", "deer", "nature", 0],
  ["🦍", "gorilla", "nature", 0],
  ["🦎", "lizard", "nature", 0],
  ["🦏", "rhinoceros", "nature", 0],
  ["🦐", "shrimp", "nature", 0],
  ["🦑", "squid", "nature", 0],
  ["🦒", "giraffe face", "nature", 0],
  ["🦓", "zebra face", "nature", 0],
  ["🦔", "hedgehog", "nature", 0],
  ["🦕", "sauropod", "nature", 0],
  ["🦖", "t rex", "nature", 0],
  ["🦗", "cricket", "nature", 0],
  ["🦘", "kangaroo", "nature", 0],
  ["🦙", "llama", "nature", 0],
  ["🦚", "peacock", "nature", 0],
  ["🦛", "hippopotamus", "nature", 0],
  ["🦜", "parrot", "nature", 0],
  ["🦝", "raccoon", "nature", 0],
  ["🦞", "lobster", "nature", 0],
  ["🦟", "mosquito", "nature", 0],
  ["🦠", "microbe", "nature", 0],
  ["🦡", "badger", "nature", 0],
  ["🦢", "swan", "nature", 0],
  ["🦣", "mammoth", "nature", 0],
  ["🦤", "dodo", "nature", 0],
  ["🦥", "sloth", "nature", 0],
  ["🦦", "otter", "nature", 0],
  ["🦧", "orangutan", "nature", 0],
  ["🦨", "skunk", "nature", 0],
  ["🦩", "flamingo", "nature", 0],
  ["🦪", "oyster", "nature", 0],
  ["🦫", "beaver", "nature", 0],
  ["🦬", "bison", "nature", 0],
  ["🦭", "seal", "nature", 0],
  ["🦮", "guide dog", "nature", 0],
  ["🪨", "rock", "nature", 0],
  ["🪰", "fly", "nature", 0],
  ["🪱", "worm", "nature", 0],
  ["🪲", "beetle", "nature", 0],
  ["🪳", "cockroach", "nature", 0],
  ["🪴", "potted plant", "nature", 0],
  ["🪵", "wood", "nature", 0],
  ["🪶", "feather", "nature", 0],
  ["🪷", "lotus", "nature", 0],
  ["🪸", "coral", "nature", 0],
  ["🪹", "empty nest", "nature", 0],
  ["🪺", "nest with eggs", "nature", 0],
  ["🪻", "hyacinth", "nature", 0],
  ["🪼", "jellyfish", "nature", 0],
  ["🪽", "wing", "nature", 0],
  ["🪾", "leafless tree", "nature", 0],
  ["🪿", "goose", "nature", 0],
  ["☕", "hot beverage", "food", 0],
  ["🌭", "hot dog", "food", 0],
  ["🌮", "taco", "food", 0],
  ["🌯", "burrito", "food", 0],
  ["🌰", "chestnut", "food", 0],
  ["🌶", "hot pepper", "food", 0],
  ["🌽", "ear of maize", "food", 0],
  ["🍄", "mushroom", "food", 0],
  ["🍅", "tomato", "food", 0],
  ["🍆", "aubergine", "food", 0],
  ["🍇", "grapes", "food", 0],
  ["🍈", "melon", "food", 0],
  ["🍉", "watermelon", "food", 0],
  ["🍊", "tangerine", "food", 0],
  ["🍋", "lemon", "food", 0],
  ["🍌", "banana", "food", 0],
  ["🍍", "pineapple", "food", 0],
  ["🍎", "red apple", "food", 0],
  ["🍏", "green apple", "food", 0],
  ["🍐", "pear", "food", 0],
  ["🍑", "peach", "food", 0],
  ["🍒", "cherries", "food", 0],
  ["🍓", "strawberry", "food", 0],
  ["🍔", "hamburger", "food", 0],
  ["🍕", "slice of pizza", "food", 0],
  ["🍖", "meat on bone", "food", 0],
  ["🍗", "poultry leg", "food", 0],
  ["🍘", "rice cracker", "food", 0],
  ["🍙", "rice ball", "food", 0],
  ["🍚", "cooked rice", "food", 0],
  ["🍛", "curry and rice", "food", 0],
  ["🍜", "steaming bowl", "food", 0],
  ["🍝", "spaghetti", "food", 0],
  ["🍞", "bread", "food", 0],
  ["🍟", "french fries", "food", 0],
  ["🍠", "roasted sweet potato", "food", 0],
  ["🍡", "dango", "food", 0],
  ["🍢", "oden", "food", 0],
  ["🍣", "sushi", "food", 0],
  ["🍤", "fried shrimp", "food", 0],
  ["🍥", "fish cake with swirl design", "food", 0],
  ["🍦", "soft ice cream", "food", 0],
  ["🍧", "shaved ice", "food", 0],
  ["🍨", "ice cream", "food", 0],
  ["🍩", "doughnut", "food", 0],
  ["🍪", "cookie", "food", 0],
  ["🍫", "chocolate bar", "food", 0],
  ["🍬", "candy", "food", 0],
  ["🍭", "lollipop", "food", 0],
  ["🍮", "custard", "food", 0],
  ["🍯", "honey pot", "food", 0],
  ["🍰", "shortcake", "food", 0],
  ["🍱", "bento box", "food", 0],
  ["🍲", "pot of food", "food", 0],
  ["🍳", "cooking", "food", 0],
  ["🍴", "fork and knife", "food", 0],
  ["🍵", "teacup without handle", "food", 0],
  ["🍶", "sake bottle and cup", "food", 0],
  ["🍷", "wine glass", "food", 0],
  ["🍸", "cocktail glass", "food", 0],
  ["🍹", "tropical drink", "food", 0],
  ["🍺", "beer mug", "food", 0],
  ["🍻", "clinking beer mugs", "food", 0],
  ["🍼", "baby bottle", "food", 0],
  ["🍽", "fork and knife with plate", "food", 0],
  ["🍾", "bottle with popping cork", "food", 0],
  ["🍿", "popcorn", "food", 0],
  ["🎂", "birthday cake", "food", 0],
  ["🥂", "clinking glasses", "food", 0],
  ["🥃", "tumbler glass", "food", 0],
  ["🥄", "spoon", "food", 0],
  ["🥐", "croissant", "food", 0],
  ["🥑", "avocado", "food", 0],
  ["🥒", "cucumber", "food", 0],
  ["🥓", "bacon", "food", 0],
  ["🥔", "potato", "food", 0],
  ["🥕", "carrot", "food", 0],
  ["🥖", "baguette bread", "food", 0],
  ["🥗", "green salad", "food", 0],
  ["🥘", "shallow pan of food", "food", 0],
  ["🥙", "stuffed flatbread", "food", 0],
  ["🥚", "egg", "food", 0],
  ["🥛", "glass of milk", "food", 0],
  ["🥜", "peanuts", "food", 0],
  ["🥝", "kiwifruit", "food", 0],
  ["🥞", "pancakes", "food", 0],
  ["🥟", "dumpling", "food", 0],
  ["🥠", "fortune cookie", "food", 0],
  ["🥡", "takeout box", "food", 0],
  ["🥢", "chopsticks", "food", 0],
  ["🥣", "bowl with spoon", "food", 0],
  ["🥤", "cup with straw", "food", 0],
  ["🥥", "coconut", "food", 0],
  ["🥦", "broccoli", "food", 0],
  ["🥧", "pie", "food", 0],
  ["🥨", "pretzel", "food", 0],
  ["🥩", "cut of meat", "food", 0],
  ["🥪", "sandwich", "food", 0],
  ["🥫", "canned food", "food", 0],
  ["🥬", "leafy green", "food", 0],
  ["🥭", "mango", "food", 0],
  ["🥮", "moon cake", "food", 0],
  ["🥯", "bagel", "food", 0],
  ["🧀", "cheese wedge", "food", 0],
  ["🧁", "cupcake", "food", 0],
  ["🧂", "salt shaker", "food", 0],
  ["🧃", "beverage box", "food", 0],
  ["🧄", "garlic", "food", 0],
  ["🧅", "onion", "food", 0],
  ["🧆", "falafel", "food", 0],
  ["🧇", "waffle", "food", 0],
  ["🧈", "butter", "food", 0],
  ["🧉", "mate drink", "food", 0],
  ["🧊", "ice cube", "food", 0],
  ["🧋", "bubble tea", "food", 0],
  ["🫐", "blueberries", "food", 0],
  ["🫑", "bell pepper", "food", 0],
  ["🫒", "olive", "food", 0],
  ["🫓", "flatbread", "food", 0],
  ["🫔", "tamale", "food", 0],
  ["🫕", "fondue", "food", 0],
  ["🫖", "teapot", "food", 0],
  ["🫗", "pouring liquid", "food", 0],
  ["🫘", "beans", "food", 0],
  ["🫙", "jar", "food", 0],
  ["🫚", "ginger root", "food", 0],
  ["🫛", "pea pod", "food", 0],
  ["🫜", "root vegetable", "food", 0],
  ["♟", "black chess pawn", "activity", 0],
  ["⚽", "soccer ball", "activity", 0],
  ["⚾", "baseball", "activity", 0],
  ["⛳", "flag in hole", "activity", 0],
  ["⛷", "skier", "activity", 0],
  ["⛸", "ice skate", "activity", 0],
  ["🀄", "mahjong tile red dragon", "activity", 0],
  ["🃏", "playing card black joker", "activity", 0],
  ["🎀", "ribbon", "activity", 0],
  ["🎁", "wrapped present", "activity", 0],
  ["🎃", "jack o lantern", "activity", 0],
  ["🎄", "christmas tree", "activity", 0],
  ["🎆", "fireworks", "activity", 0],
  ["🎇", "firework sparkler", "activity", 0],
  ["🎈", "balloon", "activity", 0],
  ["🎉", "party popper", "activity", 0],
  ["🎊", "confetti ball", "activity", 0],
  ["🎋", "tanabata tree", "activity", 0],
  ["🎌", "crossed flags", "activity", 0],
  ["🎍", "pine decoration", "activity", 0],
  ["🎎", "japanese dolls", "activity", 0],
  ["🎏", "carp streamer", "activity", 0],
  ["🎐", "wind chime", "activity", 0],
  ["🎑", "moon viewing ceremony", "activity", 0],
  ["🎒", "school satchel", "activity", 0],
  ["🎓", "graduation cap", "activity", 0],
  ["🎖", "military medal", "activity", 0],
  ["🎗", "reminder ribbon", "activity", 0],
  ["🎣", "fishing pole and fish", "activity", 0],
  ["🎨", "artist palette", "activity", 0],
  ["🎪", "circus tent", "activity", 0],
  ["🎫", "ticket", "activity", 0],
  ["🎭", "performing arts", "activity", 0],
  ["🎮", "video game", "activity", 0],
  ["🎯", "direct hit", "activity", 0],
  ["🎰", "slot machine", "activity", 0],
  ["🎱", "billiards", "activity", 0],
  ["🎲", "game die", "activity", 0],
  ["🎳", "bowling", "activity", 0],
  ["🎴", "flower playing cards", "activity", 0],
  ["🎽", "running shirt with sash", "activity", 0],
  ["🎾", "tennis racquet and ball", "activity", 0],
  ["🎿", "ski and ski boot", "activity", 0],
  ["🏀", "basketball and hoop", "activity", 0],
  ["🏁", "chequered flag", "activity", 0],
  ["🏅", "sports medal", "activity", 0],
  ["🏆", "trophy", "activity", 0],
  ["🏈", "american football", "activity", 0],
  ["🏉", "rugby football", "activity", 0],
  ["🏏", "cricket bat and ball", "activity", 0],
  ["🏐", "volleyball", "activity", 0],
  ["🏑", "field hockey stick and ball", "activity", 0],
  ["🏒", "ice hockey stick and puck", "activity", 0],
  ["🏓", "table tennis paddle and ball", "activity", 0],
  ["🏵", "rosette", "activity", 0],
  ["🏸", "badminton racquet and shuttlecock", "activity", 0],
  ["🏹", "bow and arrow", "activity", 0],
  ["🔮", "crystal ball", "activity", 0],
  ["🕹", "joystick", "activity", 0],
  ["🛝", "playground slide", "activity", 0],
  ["🤺", "fencer", "activity", 0],
  ["🥅", "goal net", "activity", 0],
  ["🥇", "first place medal", "activity", 0],
  ["🥈", "second place medal", "activity", 0],
  ["🥉", "third place medal", "activity", 0],
  ["🥊", "boxing glove", "activity", 0],
  ["🥋", "martial arts uniform", "activity", 0],
  ["🥌", "curling stone", "activity", 0],
  ["🧧", "red gift envelope", "activity", 0],
  ["🧨", "firecracker", "activity", 0],
  ["🧩", "jigsaw puzzle piece", "activity", 0],
  ["🪀", "yo yo", "activity", 0],
  ["🪁", "kite", "activity", 0],
  ["🪂", "parachute", "activity", 0],
  ["🪃", "boomerang", "activity", 0],
  ["🪄", "magic wand", "activity", 0],
  ["🪅", "pinata", "activity", 0],
  ["🪆", "nesting dolls", "activity", 0],
  ["⌚", "watch", "travel", 0],
  ["⌛", "hourglass", "travel", 0],
  ["⏰", "alarm clock", "travel", 0],
  ["⏱", "stopwatch", "travel", 0],
  ["⏲", "timer clock", "travel", 0],
  ["⏳", "hourglass with flowing sand", "travel", 0],
  ["☀", "black sun with rays", "travel", 0],
  ["☁", "cloud", "travel", 0],
  ["☂", "umbrella", "travel", 0],
  ["☃", "snowman", "travel", 0],
  ["☄", "comet", "travel", 0],
  ["☔", "umbrella with rain drops", "travel", 0],
  ["⛄", "snowman without snow", "travel", 0],
  ["⛅", "sun behind cloud", "travel", 0],
  ["⛈", "thunder cloud and rain", "travel", 0],
  ["⛩", "shinto shrine", "travel", 0],
  ["⛪", "church", "travel", 0],
  ["⛰", "mountain", "travel", 0],
  ["⛱", "umbrella on ground", "travel", 0],
  ["⛲", "fountain", "travel", 0],
  ["⛴", "ferry", "travel", 0],
  ["⛵", "sailboat", "travel", 0],
  ["⛺", "tent", "travel", 0],
  ["⛽", "fuel pump", "travel", 0],
  ["✈", "airplane", "travel", 0],
  ["🌀", "cyclone", "travel", 0],
  ["🌁", "foggy", "travel", 0],
  ["🌂", "closed umbrella", "travel", 0],
  ["🌃", "night with stars", "travel", 0],
  ["🌄", "sunrise over mountains", "travel", 0],
  ["🌅", "sunrise", "travel", 0],
  ["🌆", "cityscape at dusk", "travel", 0],
  ["🌇", "sunset over buildings", "travel", 0],
  ["🌈", "rainbow", "travel", 0],
  ["🌉", "bridge at night", "travel", 0],
  ["🌊", "water wave", "travel", 0],
  ["🌋", "volcano", "travel", 0],
  ["🌌", "milky way", "travel", 0],
  ["🌍", "earth globe europe africa", "travel", 0],
  ["🌎", "earth globe americas", "travel", 0],
  ["🌏", "earth globe asia australia", "travel", 0],
  ["🌐", "globe with meridians", "travel", 0],
  ["🌑", "new moon symbol", "travel", 0],
  ["🌒", "waxing crescent moon symbol", "travel", 0],
  ["🌓", "first quarter moon symbol", "travel", 0],
  ["🌔", "waxing gibbous moon symbol", "travel", 0],
  ["🌕", "full moon symbol", "travel", 0],
  ["🌖", "waning gibbous moon symbol", "travel", 0],
  ["🌗", "last quarter moon symbol", "travel", 0],
  ["🌘", "waning crescent moon symbol", "travel", 0],
  ["🌙", "crescent moon", "travel", 0],
  ["🌚", "new moon with face", "travel", 0],
  ["🌛", "first quarter moon with face", "travel", 0],
  ["🌜", "last quarter moon with face", "travel", 0],
  ["🌝", "full moon with face", "travel", 0],
  ["🌞", "sun with face", "travel", 0],
  ["🌟", "glowing star", "travel", 0],
  ["🌠", "shooting star", "travel", 0],
  ["🌡", "thermometer", "travel", 0],
  ["🌤", "white sun with small cloud", "travel", 0],
  ["🌥", "white sun behind cloud", "travel", 0],
  ["🌦", "white sun behind cloud with rain", "travel", 0],
  ["🌧", "cloud with rain", "travel", 0],
  ["🌨", "cloud with snow", "travel", 0],
  ["🌩", "cloud with lightning", "travel", 0],
  ["🌪", "cloud with tornado", "travel", 0],
  ["🌫", "fog", "travel", 0],
  ["🌬", "wind blowing face", "travel", 0],
  ["🎠", "carousel horse", "travel", 0],
  ["🎡", "ferris wheel", "travel", 0],
  ["🎢", "roller coaster", "travel", 0],
  ["🏍", "racing motorcycle", "travel", 0],
  ["🏎", "racing car", "travel", 0],
  ["🏔", "snow capped mountain", "travel", 0],
  ["🏕", "camping", "travel", 0],
  ["🏖", "beach with umbrella", "travel", 0],
  ["🏗", "building construction", "travel", 0],
  ["🏘", "house buildings", "travel", 0],
  ["🏙", "cityscape", "travel", 0],
  ["🏚", "derelict house building", "travel", 0],
  ["🏛", "classical building", "travel", 0],
  ["🏜", "desert", "travel", 0],
  ["🏝", "desert island", "travel", 0],
  ["🏞", "national park", "travel", 0],
  ["🏟", "stadium", "travel", 0],
  ["🏠", "house building", "travel", 0],
  ["🏡", "house with garden", "travel", 0],
  ["🏢", "office building", "travel", 0],
  ["🏣", "japanese post office", "travel", 0],
  ["🏤", "european post office", "travel", 0],
  ["🏥", "hospital", "travel", 0],
  ["🏦", "bank", "travel", 0],
  ["🏧", "automated teller machine", "travel", 0],
  ["🏨", "hotel", "travel", 0],
  ["🏩", "love hotel", "travel", 0],
  ["🏪", "convenience store", "travel", 0],
  ["🏫", "school", "travel", 0],
  ["🏬", "department store", "travel", 0],
  ["🏭", "factory", "travel", 0],
  ["🏮", "izakaya lantern", "travel", 0],
  ["🏯", "japanese castle", "travel", 0],
  ["🏰", "european castle", "travel", 0],
  ["💒", "wedding", "travel", 0],
  ["💺", "seat", "travel", 0],
  ["🕐", "clock face one oclock", "travel", 0],
  ["🕑", "clock face two oclock", "travel", 0],
  ["🕒", "clock face three oclock", "travel", 0],
  ["🕓", "clock face four oclock", "travel", 0],
  ["🕔", "clock face five oclock", "travel", 0],
  ["🕕", "clock face six oclock", "travel", 0],
  ["🕖", "clock face seven oclock", "travel", 0],
  ["🕗", "clock face eight oclock", "travel", 0],
  ["🕘", "clock face nine oclock", "travel", 0],
  ["🕙", "clock face ten oclock", "travel", 0],
  ["🕚", "clock face eleven oclock", "travel", 0],
  ["🕛", "clock face twelve oclock", "travel", 0],
  ["🕜", "clock face one thirty", "travel", 0],
  ["🕝", "clock face two thirty", "travel", 0],
  ["🕞", "clock face three thirty", "travel", 0],
  ["🕟", "clock face four thirty", "travel", 0],
  ["🕠", "clock face five thirty", "travel", 0],
  ["🕡", "clock face six thirty", "travel", 0],
  ["🕢", "clock face seven thirty", "travel", 0],
  ["🕣", "clock face eight thirty", "travel", 0],
  ["🕤", "clock face nine thirty", "travel", 0],
  ["🕥", "clock face ten thirty", "travel", 0],
  ["🕦", "clock face eleven thirty", "travel", 0],
  ["🕧", "clock face twelve thirty", "travel", 0],
  ["🕰", "mantelpiece clock", "travel", 0],
  ["🗺", "world map", "travel", 0],
  ["🗻", "mount fuji", "travel", 0],
  ["🗼", "tokyo tower", "travel", 0],
  ["🗽", "statue of liberty", "travel", 0],
  ["🗾", "silhouette of japan", "travel", 0],
  ["🗿", "moyai", "travel", 0],
  ["🚀", "rocket", "travel", 0],
  ["🚁", "helicopter", "travel", 0],
  ["🚂", "steam locomotive", "travel", 0],
  ["🚃", "railway car", "travel", 0],
  ["🚄", "high speed train", "travel", 0],
  ["🚅", "high speed train with bullet nose", "travel", 0],
  ["🚆", "train", "travel", 0],
  ["🚇", "metro", "travel", 0],
  ["🚈", "light rail", "travel", 0],
  ["🚉", "station", "travel", 0],
  ["🚊", "tram", "travel", 0],
  ["🚋", "tram car", "travel", 0],
  ["🚌", "bus", "travel", 0],
  ["🚍", "oncoming bus", "travel", 0],
  ["🚎", "trolleybus", "travel", 0],
  ["🚏", "bus stop", "travel", 0],
  ["🚐", "minibus", "travel", 0],
  ["🚑", "ambulance", "travel", 0],
  ["🚒", "fire engine", "travel", 0],
  ["🚓", "police car", "travel", 0],
  ["🚔", "oncoming police car", "travel", 0],
  ["🚕", "taxi", "travel", 0],
  ["🚖", "oncoming taxi", "travel", 0],
  ["🚗", "automobile", "travel", 0],
  ["🚘", "oncoming automobile", "travel", 0],
  ["🚙", "recreational vehicle", "travel", 0],
  ["🚚", "delivery truck", "travel", 0],
  ["🚛", "articulated lorry", "travel", 0],
  ["🚜", "tractor", "travel", 0],
  ["🚝", "monorail", "travel", 0],
  ["🚞", "mountain railway", "travel", 0],
  ["🚟", "suspension railway", "travel", 0],
  ["🚠", "mountain cableway", "travel", 0],
  ["🚡", "aerial tramway", "travel", 0],
  ["🚢", "ship", "travel", 0],
  ["🚤", "speedboat", "travel", 0],
  ["🚥", "horizontal traffic light", "travel", 0],
  ["🚦", "vertical traffic light", "travel", 0],
  ["🚧", "construction sign", "travel", 0],
  ["🚨", "police cars revolving light", "travel", 0],
  ["🚩", "triangular flag on post", "travel", 0],
  ["🚫", "no entry sign", "travel", 0],
  ["🚬", "smoking symbol", "travel", 0],
  ["🚭", "no smoking symbol", "travel", 0],
  ["🚮", "put litter in its place symbol", "travel", 0],
  ["🚯", "do not litter symbol", "travel", 0],
  ["🚰", "potable water symbol", "travel", 0],
  ["🚱", "non potable water symbol", "travel", 0],
  ["🚲", "bicycle", "travel", 0],
  ["🚳", "no bicycles", "travel", 0],
  ["🚷", "no pedestrians", "travel", 0],
  ["🚸", "children crossing", "travel", 0],
  ["🛑", "octagonal sign", "travel", 0],
  ["🛕", "hindu temple", "travel", 0],
  ["🛖", "hut", "travel", 0],
  ["🛞", "wheel", "travel", 0],
  ["🛟", "ring buoy", "travel", 0],
  ["🛠", "hammer and wrench", "travel", 0],
  ["🛡", "shield", "travel", 0],
  ["🛢", "oil drum", "travel", 0],
  ["🛣", "motorway", "travel", 0],
  ["🛤", "railway track", "travel", 0],
  ["🛥", "motor boat", "travel", 0],
  ["🛩", "small airplane", "travel", 0],
  ["🛫", "airplane departure", "travel", 0],
  ["🛬", "airplane arriving", "travel", 0],
  ["🛰", "satellite", "travel", 0],
  ["🛳", "passenger ship", "travel", 0],
  ["🛴", "scooter", "travel", 0],
  ["🛵", "motor scooter", "travel", 0],
  ["🛶", "canoe", "travel", 0],
  ["🛷", "sled", "travel", 0],
  ["🛸", "flying saucer", "travel", 0],
  ["🛹", "skateboard", "travel", 0],
  ["🛺", "auto rickshaw", "travel", 0],
  ["🛻", "pickup truck", "travel", 0],
  ["🛼", "roller skate", "travel", 0],
  ["🧳", "luggage", "travel", 0],
  ["🪐", "ringed planet", "travel", 0],
  ["⌨", "keyboard", "objects", 0],
  ["☎", "black telephone", "objects", 0],
  ["⚒", "hammer and pick", "objects", 0],
  ["⚔", "crossed swords", "objects", 0],
  ["⚖", "scales", "objects", 0],
  ["⚗", "alembic", "objects", 0],
  ["⚙", "gear", "objects", 0],
  ["⚰", "coffin", "objects", 0],
  ["⚱", "funeral urn", "objects", 0],
  ["⛏", "pick", "objects", 0],
  ["⛑", "helmet with white cross", "objects", 0],
  ["⛓", "chains", "objects", 0],
  ["✂", "black scissors", "objects", 0],
  ["✉", "envelope", "objects", 0],
  ["✏", "pencil", "objects", 0],
  ["✒", "black nib", "objects", 0],
  ["🎙", "studio microphone", "objects", 0],
  ["🎚", "level slider", "objects", 0],
  ["🎛", "control knobs", "objects", 0],
  ["🎞", "film frames", "objects", 0],
  ["🎟", "admission tickets", "objects", 0],
  ["🎤", "microphone", "objects", 0],
  ["🎥", "movie camera", "objects", 0],
  ["🎦", "cinema", "objects", 0],
  ["🎧", "headphone", "objects", 0],
  ["🎩", "top hat", "objects", 0],
  ["🎬", "clapper board", "objects", 0],
  ["🎵", "musical note", "objects", 0],
  ["🎶", "multiple musical notes", "objects", 0],
  ["🎷", "saxophone", "objects", 0],
  ["🎸", "guitar", "objects", 0],
  ["🎹", "musical keyboard", "objects", 0],
  ["🎺", "trumpet", "objects", 0],
  ["🎻", "violin", "objects", 0],
  ["🎼", "musical score", "objects", 0],
  ["🏷", "label", "objects", 0],
  ["🏺", "amphora", "objects", 0],
  ["👑", "crown", "objects", 0],
  ["👒", "womans hat", "objects", 0],
  ["👓", "eyeglasses", "objects", 0],
  ["👔", "necktie", "objects", 0],
  ["👕", "t shirt", "objects", 0],
  ["👖", "jeans", "objects", 0],
  ["👗", "dress", "objects", 0],
  ["👘", "kimono", "objects", 0],
  ["👙", "bikini", "objects", 0],
  ["👚", "womans clothes", "objects", 0],
  ["👛", "purse", "objects", 0],
  ["👜", "handbag", "objects", 0],
  ["👝", "pouch", "objects", 0],
  ["👞", "mans shoe", "objects", 0],
  ["👟", "athletic shoe", "objects", 0],
  ["👠", "high heeled shoe", "objects", 0],
  ["👡", "womans sandal", "objects", 0],
  ["👢", "womans boots", "objects", 0],
  ["💈", "barber pole", "objects", 0],
  ["💉", "syringe", "objects", 0],
  ["💊", "pill", "objects", 0],
  ["💍", "ring", "objects", 0],
  ["💎", "gem stone", "objects", 0],
  ["💡", "electric light bulb", "objects", 0],
  ["💰", "money bag", "objects", 0],
  ["💱", "currency exchange", "objects", 0],
  ["💲", "heavy dollar sign", "objects", 0],
  ["💳", "credit card", "objects", 0],
  ["💴", "banknote with yen sign", "objects", 0],
  ["💵", "banknote with dollar sign", "objects", 0],
  ["💶", "banknote with euro sign", "objects", 0],
  ["💷", "banknote with pound sign", "objects", 0],
  ["💸", "money with wings", "objects", 0],
  ["💹", "chart with upwards trend and yen sign", "objects", 0],
  ["💻", "personal computer", "objects", 0],
  ["💼", "briefcase", "objects", 0],
  ["💽", "minidisc", "objects", 0],
  ["💾", "floppy disk", "objects", 0],
  ["💿", "optical disc", "objects", 0],
  ["📀", "dvd", "objects", 0],
  ["📁", "file folder", "objects", 0],
  ["📂", "open file folder", "objects", 0],
  ["📃", "page with curl", "objects", 0],
  ["📄", "page facing up", "objects", 0],
  ["📅", "calendar", "objects", 0],
  ["📆", "tear off calendar", "objects", 0],
  ["📇", "card index", "objects", 0],
  ["📈", "chart with upwards trend", "objects", 0],
  ["📉", "chart with downwards trend", "objects", 0],
  ["📊", "bar chart", "objects", 0],
  ["📋", "clipboard", "objects", 0],
  ["📌", "pushpin", "objects", 0],
  ["📍", "round pushpin", "objects", 0],
  ["📎", "paperclip", "objects", 0],
  ["📏", "straight ruler", "objects", 0],
  ["📐", "triangular ruler", "objects", 0],
  ["📑", "bookmark tabs", "objects", 0],
  ["📒", "ledger", "objects", 0],
  ["📓", "notebook", "objects", 0],
  ["📔", "notebook with decorative cover", "objects", 0],
  ["📕", "closed book", "objects", 0],
  ["📖", "open book", "objects", 0],
  ["📗", "green book", "objects", 0],
  ["📘", "blue book", "objects", 0],
  ["📙", "orange book", "objects", 0],
  ["📚", "books", "objects", 0],
  ["📛", "name badge", "objects", 0],
  ["📜", "scroll", "objects", 0],
  ["📝", "memo", "objects", 0],
  ["📞", "telephone receiver", "objects", 0],
  ["📟", "pager", "objects", 0],
  ["📠", "fax machine", "objects", 0],
  ["📡", "satellite antenna", "objects", 0],
  ["📢", "public address loudspeaker", "objects", 0],
  ["📣", "cheering megaphone", "objects", 0],
  ["📤", "outbox tray", "objects", 0],
  ["📥", "inbox tray", "objects", 0],
  ["📦", "package", "objects", 0],
  ["📧", "e mail symbol", "objects", 0],
  ["📨", "incoming envelope", "objects", 0],
  ["📩", "envelope with downwards arrow above", "objects", 0],
  ["📪", "closed mailbox with lowered flag", "objects", 0],
  ["📫", "closed mailbox with raised flag", "objects", 0],
  ["📬", "open mailbox with raised flag", "objects", 0],
  ["📭", "open mailbox with lowered flag", "objects", 0],
  ["📮", "postbox", "objects", 0],
  ["📯", "postal horn", "objects", 0],
  ["📰", "newspaper", "objects", 0],
  ["📱", "mobile phone", "objects", 0],
  ["📲", "mobile phone with rightwards arrow at left", "objects", 0],
  ["📳", "vibration mode", "objects", 0],
  ["📴", "mobile phone off", "objects", 0],
  ["📵", "no mobile phones", "objects", 0],
  ["📶", "antenna with bars", "objects", 0],
  ["📷", "camera", "objects", 0],
  ["📸", "camera with flash", "objects", 0],
  ["📹", "video camera", "objects", 0],
  ["📺", "television", "objects", 0],
  ["📻", "radio", "objects", 0],
  ["📼", "videocassette", "objects", 0],
  ["📽", "film projector", "objects", 0],
  ["📿", "prayer beads", "objects", 0],
  ["🔥", "fire", "objects", 0],
  ["🔦", "electric torch", "objects", 0],
  ["🔧", "wrench", "objects", 0],
  ["🔨", "hammer", "objects", 0],
  ["🔩", "nut and bolt", "objects", 0],
  ["🔪", "hocho", "objects", 0],
  ["🔫", "pistol", "objects", 0],
  ["🔬", "microscope", "objects", 0],
  ["🔭", "telescope", "objects", 0],
  ["🕯", "candle", "objects", 0],
  ["🕶", "dark sunglasses", "objects", 0],
  ["🖇", "linked paperclips", "objects", 0],
  ["🖊", "lower left ballpoint pen", "objects", 0],
  ["🖋", "lower left fountain pen", "objects", 0],
  ["🖌", "lower left paintbrush", "objects", 0],
  ["🖍", "lower left crayon", "objects", 0],
  ["🖥", "desktop computer", "objects", 0],
  ["🖨", "printer", "objects", 0],
  ["🖱", "three button mouse", "objects", 0],
  ["🖲", "trackball", "objects", 0],
  ["🖼", "frame with picture", "objects", 0],
  ["🗂", "card index dividers", "objects", 0],
  ["🗃", "card file box", "objects", 0],
  ["🗄", "file cabinet", "objects", 0],
  ["🗑", "wastebasket", "objects", 0],
  ["🗒", "spiral note pad", "objects", 0],
  ["🗓", "spiral calendar pad", "objects", 0],
  ["🗜", "compression", "objects", 0],
  ["🗝", "old key", "objects", 0],
  ["🗞", "rolled up newspaper", "objects", 0],
  ["🗡", "dagger knife", "objects", 0],
  ["🗳", "ballot box with ballot", "objects", 0],
  ["🚪", "door", "objects", 0],
  ["🚽", "toilet", "objects", 0],
  ["🚿", "shower", "objects", 0],
  ["🛁", "bathtub", "objects", 0],
  ["🛒", "shopping trolley", "objects", 0],
  ["🛗", "elevator", "objects", 0],
  ["🛜", "wireless", "objects", 0],
  ["🥻", "sari", "objects", 0],
  ["🥼", "lab coat", "objects", 0],
  ["🥽", "goggles", "objects", 0],
  ["🥾", "hiking boot", "objects", 0],
  ["🥿", "flat shoe", "objects", 0],
  ["🦯", "probing cane", "objects", 0],
  ["🦼", "motorized wheelchair", "objects", 0],
  ["🦽", "manual wheelchair", "objects", 0],
  ["🧢", "billed cap", "objects", 0],
  ["🧣", "scarf", "objects", 0],
  ["🧤", "gloves", "objects", 0],
  ["🧥", "coat", "objects", 0],
  ["🧦", "socks", "objects", 0],
  ["🧪", "test tube", "objects", 0],
  ["🧫", "petri dish", "objects", 0],
  ["🧬", "dna double helix", "objects", 0],
  ["🧭", "compass", "objects", 0],
  ["🧮", "abacus", "objects", 0],
  ["🧯", "fire extinguisher", "objects", 0],
  ["🧰", "toolbox", "objects", 0],
  ["🧱", "brick", "objects", 0],
  ["🧲", "magnet", "objects", 0],
  ["🧴", "lotion bottle", "objects", 0],
  ["🧵", "spool of thread", "objects", 0],
  ["🧶", "ball of yarn", "objects", 0],
  ["🧷", "safety pin", "objects", 0],
  ["🧸", "teddy bear", "objects", 0],
  ["🧹", "broom", "objects", 0],
  ["🧺", "basket", "objects", 0],
  ["🧻", "roll of paper", "objects", 0],
  ["🧼", "bar of soap", "objects", 0],
  ["🧽", "sponge", "objects", 0],
  ["🧾", "receipt", "objects", 0],
  ["🧿", "nazar amulet", "objects", 0],
  ["🩰", "ballet shoes", "objects", 0],
  ["🩱", "one piece swimsuit", "objects", 0],
  ["🩲", "briefs", "objects", 0],
  ["🩳", "shorts", "objects", 0],
  ["🩴", "thong sandal", "objects", 0],
  ["🩵", "light blue heart", "objects", 0],
  ["🩶", "grey heart", "objects", 0],
  ["🩷", "pink heart", "objects", 0],
  ["🩸", "drop of blood", "objects", 0],
  ["🩹", "adhesive bandage", "objects", 0],
  ["🩺", "stethoscope", "objects", 0],
  ["🩻", "x ray", "objects", 0],
  ["🩼", "crutch", "objects", 0],
  ["🪇", "maracas", "objects", 0],
  ["🪈", "flute", "objects", 0],
  ["🪉", "harp", "objects", 0],
  ["🪑", "chair", "objects", 0],
  ["🪒", "razor", "objects", 0],
  ["🪓", "axe", "objects", 0],
  ["🪔", "diya lamp", "objects", 0],
  ["🪕", "banjo", "objects", 0],
  ["🪖", "military helmet", "objects", 0],
  ["🪗", "accordion", "objects", 0],
  ["🪘", "long drum", "objects", 0],
  ["🪙", "coin", "objects", 0],
  ["🪚", "carpentry saw", "objects", 0],
  ["🪛", "screwdriver", "objects", 0],
  ["🪜", "ladder", "objects", 0],
  ["🪝", "hook", "objects", 0],
  ["🪞", "mirror", "objects", 0],
  ["🪟", "window", "objects", 0],
  ["🪠", "plunger", "objects", 0],
  ["🪡", "sewing needle", "objects", 0],
  ["🪢", "knot", "objects", 0],
  ["🪣", "bucket", "objects", 0],
  ["🪤", "mouse trap", "objects", 0],
  ["🪥", "toothbrush", "objects", 0],
  ["🪦", "headstone", "objects", 0],
  ["🪧", "placard", "objects", 0],
  ["🪩", "mirror ball", "objects", 0],
  ["🪪", "identification card", "objects", 0],
  ["🪫", "low battery", "objects", 0],
  ["🪬", "hamsa", "objects", 0],
  ["🪭", "folding hand fan", "objects", 0],
  ["🪮", "hair pick", "objects", 0],
  ["🪯", "khanda", "objects", 0],
  ["©", "copyright sign", "symbols", 0],
  ["®", "registered sign", "symbols", 0],
  ["‼", "double exclamation mark", "symbols", 0],
  ["⁉", "exclamation question mark", "symbols", 0],
  ["™", "trade mark sign", "symbols", 0],
  ["ℹ", "information source", "symbols", 0],
  ["↔", "left right arrow", "symbols", 0],
  ["↕", "up down arrow", "symbols", 0],
  ["↖", "north west arrow", "symbols", 0],
  ["↗", "north east arrow", "symbols", 0],
  ["↘", "south east arrow", "symbols", 0],
  ["↙", "south west arrow", "symbols", 0],
  ["↩", "leftwards arrow with hook", "symbols", 0],
  ["↪", "rightwards arrow with hook", "symbols", 0],
  ["⏏", "eject symbol", "symbols", 0],
  ["⏩", "black right pointing double triangle", "symbols", 0],
  ["⏪", "black left pointing double triangle", "symbols", 0],
  ["⏫", "black up pointing double triangle", "symbols", 0],
  ["⏬", "black down pointing double triangle", "symbols", 0],
  ["⏭", "black right pointing double triangle with vertical bar", "symbols", 0],
  ["⏮", "black left pointing double triangle with vertical bar", "symbols", 0],
  ["⏯", "black right pointing triangle with double vertical bar", "symbols", 0],
  ["⏸", "double vertical bar", "symbols", 0],
  ["⏹", "black square for stop", "symbols", 0],
  ["⏺", "black circle for record", "symbols", 0],
  ["Ⓜ", "circled latin capital letter m", "symbols", 0],
  ["▪", "black small square", "symbols", 0],
  ["▫", "white small square", "symbols", 0],
  ["▶", "black right pointing triangle", "symbols", 0],
  ["◀", "black left pointing triangle", "symbols", 0],
  ["◻", "white medium square", "symbols", 0],
  ["◼", "black medium square", "symbols", 0],
  ["◽", "white medium small square", "symbols", 0],
  ["◾", "black medium small square", "symbols", 0],
  ["☑", "ballot box with check", "symbols", 0],
  ["☦", "orthodox cross", "symbols", 0],
  ["☪", "star and crescent", "symbols", 0],
  ["☮", "peace symbol", "symbols", 0],
  ["☯", "yin yang", "symbols", 0],
  ["☸", "wheel of dharma", "symbols", 0],
  ["♈", "aries", "symbols", 0],
  ["♉", "taurus", "symbols", 0],
  ["♊", "gemini", "symbols", 0],
  ["♋", "cancer", "symbols", 0],
  ["♌", "leo", "symbols", 0],
  ["♍", "virgo", "symbols", 0],
  ["♎", "libra", "symbols", 0],
  ["♏", "scorpius", "symbols", 0],
  ["♐", "sagittarius", "symbols", 0],
  ["♑", "capricorn", "symbols", 0],
  ["♒", "aquarius", "symbols", 0],
  ["♓", "pisces", "symbols", 0],
  ["♻", "black universal recycling symbol", "symbols", 0],
  ["♾", "permanent paper sign", "symbols", 0],
  ["♿", "wheelchair symbol", "symbols", 0],
  ["⚕", "staff of aesculapius", "symbols", 0],
  ["⚛", "atom symbol", "symbols", 0],
  ["⚜", "fleur de lis", "symbols", 0],
  ["⚠", "warning sign", "symbols", 0],
  ["⚡", "high voltage sign", "symbols", 0],
  ["⚧", "male with stroke and male and female sign", "symbols", 0],
  ["⚪", "medium white circle", "symbols", 0],
  ["⚫", "medium black circle", "symbols", 0],
  ["⛎", "ophiuchus", "symbols", 0],
  ["⛔", "no entry", "symbols", 0],
  ["✅", "white heavy check mark", "symbols", 0],
  ["✔", "heavy check mark", "symbols", 0],
  ["✖", "heavy multiplication x", "symbols", 0],
  ["✝", "latin cross", "symbols", 0],
  ["✡", "star of david", "symbols", 0],
  ["✨", "sparkles", "symbols", 0],
  ["✳", "eight spoked asterisk", "symbols", 0],
  ["✴", "eight pointed black star", "symbols", 0],
  ["❄", "snowflake", "symbols", 0],
  ["❇", "sparkle", "symbols", 0],
  ["❌", "cross mark", "symbols", 0],
  ["❎", "negative squared cross mark", "symbols", 0],
  ["❓", "black question mark ornament", "symbols", 0],
  ["❔", "white question mark ornament", "symbols", 0],
  ["❕", "white exclamation mark ornament", "symbols", 0],
  ["❗", "heavy exclamation mark symbol", "symbols", 0],
  ["➕", "heavy plus sign", "symbols", 0],
  ["➖", "heavy minus sign", "symbols", 0],
  ["➗", "heavy division sign", "symbols", 0],
  ["➡", "black rightwards arrow", "symbols", 0],
  ["➰", "curly loop", "symbols", 0],
  ["➿", "double curly loop", "symbols", 0],
  ["⤴", "arrow pointing rightwards then curving upwards", "symbols", 0],
  ["⤵", "arrow pointing rightwards then curving downwards", "symbols", 0],
  ["⬅", "leftwards black arrow", "symbols", 0],
  ["⬆", "upwards black arrow", "symbols", 0],
  ["⬇", "downwards black arrow", "symbols", 0],
  ["⬛", "black large square", "symbols", 0],
  ["⬜", "white large square", "symbols", 0],
  ["⭐", "white medium star", "symbols", 0],
  ["⭕", "heavy large circle", "symbols", 0],
  ["〰", "wavy dash", "symbols", 0],
  ["〽", "part alternation mark", "symbols", 0],
  ["㊗", "circled ideograph congratulation", "symbols", 0],
  ["㊙", "circled ideograph secret", "symbols", 0],
  ["🅰", "negative squared latin capital letter a", "symbols", 0],
  ["🅱", "negative squared latin capital letter b", "symbols", 0],
  ["🅾", "negative squared latin capital letter o", "symbols", 0],
  ["🅿", "negative squared latin capital letter p", "symbols", 0],
  ["🆎", "negative squared ab", "symbols", 0],
  ["🆑", "squared cl", "symbols", 0],
  ["🆒", "squared cool", "symbols", 0],
  ["🆓", "squared free", "symbols", 0],
  ["🆔", "squared id", "symbols", 0],
  ["🆕", "squared new", "symbols", 0],
  ["🆖", "squared ng", "symbols", 0],
  ["🆗", "squared ok", "symbols", 0],
  ["🆘", "squared sos", "symbols", 0],
  ["🆙", "squared up with exclamation mark", "symbols", 0],
  ["🆚", "squared vs", "symbols", 0],
  ["🈁", "squared katakana koko", "symbols", 0],
  ["🈂", "squared katakana sa", "symbols", 0],
  ["🈚", "squared cjk unified ideograph 7121", "symbols", 0],
  ["🈯", "squared cjk unified ideograph 6307", "symbols", 0],
  ["🈲", "squared cjk unified ideograph 7981", "symbols", 0],
  ["🈳", "squared cjk unified ideograph 7a7a", "symbols", 0],
  ["🈴", "squared cjk unified ideograph 5408", "symbols", 0],
  ["🈵", "squared cjk unified ideograph 6e80", "symbols", 0],
  ["🈶", "squared cjk unified ideograph 6709", "symbols", 0],
  ["🈷", "squared cjk unified ideograph 6708", "symbols", 0],
  ["🈸", "squared cjk unified ideograph 7533", "symbols", 0],
  ["🈹", "squared cjk unified ideograph 5272", "symbols", 0],
  ["🈺", "squared cjk unified ideograph 55b6", "symbols", 0],
  ["🉐", "circled ideograph advantage", "symbols", 0],
  ["🉑", "circled ideograph accept", "symbols", 0],
  ["💠", "diamond shape with a dot inside", "symbols", 0],
  ["💯", "hundred points symbol", "symbols", 0],
  ["🔀", "twisted rightwards arrows", "symbols", 0],
  ["🔁", "clockwise rightwards and leftwards open circle arrows", "symbols", 0],
  ["🔂", "clockwise rightwards and leftwards open circle arrows with circled one overlay", "symbols", 0],
  ["🔃", "clockwise downwards and upwards open circle arrows", "symbols", 0],
  ["🔄", "anticlockwise downwards and upwards open circle arrows", "symbols", 0],
  ["🔅", "low brightness symbol", "symbols", 0],
  ["🔆", "high brightness symbol", "symbols", 0],
  ["🔇", "speaker with cancellation stroke", "symbols", 0],
  ["🔈", "speaker", "symbols", 0],
  ["🔉", "speaker with one sound wave", "symbols", 0],
  ["🔊", "speaker with three sound waves", "symbols", 0],
  ["🔋", "battery", "symbols", 0],
  ["🔌", "electric plug", "symbols", 0],
  ["🔍", "left pointing magnifying glass", "symbols", 0],
  ["🔎", "right pointing magnifying glass", "symbols", 0],
  ["🔏", "lock with ink pen", "symbols", 0],
  ["🔐", "closed lock with key", "symbols", 0],
  ["🔑", "key", "symbols", 0],
  ["🔒", "lock", "symbols", 0],
  ["🔓", "open lock", "symbols", 0],
  ["🔔", "bell", "symbols", 0],
  ["🔕", "bell with cancellation stroke", "symbols", 0],
  ["🔖", "bookmark", "symbols", 0],
  ["🔗", "link symbol", "symbols", 0],
  ["🔘", "radio button", "symbols", 0],
  ["🔙", "back with leftwards arrow above", "symbols", 0],
  ["🔚", "end with leftwards arrow above", "symbols", 0],
  ["🔛", "on with exclamation mark with left right arrow above", "symbols", 0],
  ["🔜", "soon with rightwards arrow above", "symbols", 0],
  ["🔝", "top with upwards arrow above", "symbols", 0],
  ["🔞", "no one under eighteen symbol", "symbols", 0],
  ["🔟", "keycap ten", "symbols", 0],
  ["🔠", "input symbol for latin capital letters", "symbols", 0],
  ["🔡", "input symbol for latin small letters", "symbols", 0],
  ["🔢", "input symbol for numbers", "symbols", 0],
  ["🔣", "input symbol for symbols", "symbols", 0],
  ["🔤", "input symbol for latin letters", "symbols", 0],
  ["🔯", "six pointed star with middle dot", "symbols", 0],
  ["🔰", "japanese symbol for beginner", "symbols", 0],
  ["🔱", "trident emblem", "symbols", 0],
  ["🔲", "black square button", "symbols", 0],
  ["🔳", "white square button", "symbols", 0],
  ["🔴", "large red circle", "symbols", 0],
  ["🔵", "large blue circle", "symbols", 0],
  ["🔶", "large orange diamond", "symbols", 0],
  ["🔷", "large blue diamond", "symbols", 0],
  ["🔸", "small orange diamond", "symbols", 0],
  ["🔹", "small blue diamond", "symbols", 0],
  ["🔺", "up pointing red triangle", "symbols", 0],
  ["🔻", "down pointing red triangle", "symbols", 0],
  ["🔼", "up pointing small red triangle", "symbols", 0],
  ["🔽", "down pointing small red triangle", "symbols", 0],
  ["🚹", "mens symbol", "symbols", 0],
  ["🚺", "womens symbol", "symbols", 0],
  ["🚻", "restroom", "symbols", 0],
  ["🚼", "baby symbol", "symbols", 0],
  ["🚾", "water closet", "symbols", 0],
  ["🛂", "passport control", "symbols", 0],
  ["🛃", "customs", "symbols", 0],
  ["🛄", "baggage claim", "symbols", 0],
  ["🛅", "left luggage", "symbols", 0],
  ["🛐", "place of worship", "symbols", 0],
  ["🟠", "large orange circle", "symbols", 0],
  ["🟡", "large yellow circle", "symbols", 0],
  ["🟢", "large green circle", "symbols", 0],
  ["🟣", "large purple circle", "symbols", 0],
  ["🟤", "large brown circle", "symbols", 0],
  ["🟥", "large red square", "symbols", 0],
  ["🟦", "large blue square", "symbols", 0],
  ["🟧", "large orange square", "symbols", 0],
  ["🟨", "large yellow square", "symbols", 0],
  ["🟩", "large green square", "symbols", 0],
  ["🟪", "large purple square", "symbols", 0],
  ["🟫", "large brown square", "symbols", 0],
  ["🟰", "heavy equals sign", "symbols", 0],
  ["🇦🇩", "andorra flag", "flags", 0],
  ["🇦🇪", "united arab emirates flag", "flags", 0],
  ["🇦🇫", "afghanistan flag", "flags", 0],
  ["🇦🇬", "antigua & barbuda flag", "flags", 0],
  ["🇦🇮", "anguilla flag", "flags", 0],
  ["🇦🇱", "albania flag", "flags", 0],
  ["🇦🇲", "armenia flag", "flags", 0],
  ["🇦🇴", "angola flag", "flags", 0],
  ["🇦🇶", "antarctica flag", "flags", 0],
  ["🇦🇷", "argentina flag", "flags", 0],
  ["🇦🇸", "samoa (american) flag", "flags", 0],
  ["🇦🇹", "austria flag", "flags", 0],
  ["🇦🇺", "australia flag", "flags", 0],
  ["🇦🇼", "aruba flag", "flags", 0],
  ["🇦🇽", "åland islands flag", "flags", 0],
  ["🇦🇿", "azerbaijan flag", "flags", 0],
  ["🇧🇦", "bosnia & herzegovina flag", "flags", 0],
  ["🇧🇧", "barbados flag", "flags", 0],
  ["🇧🇩", "bangladesh flag", "flags", 0],
  ["🇧🇪", "belgium flag", "flags", 0],
  ["🇧🇫", "burkina faso flag", "flags", 0],
  ["🇧🇬", "bulgaria flag", "flags", 0],
  ["🇧🇭", "bahrain flag", "flags", 0],
  ["🇧🇮", "burundi flag", "flags", 0],
  ["🇧🇯", "benin flag", "flags", 0],
  ["🇧🇱", "st barthelemy flag", "flags", 0],
  ["🇧🇲", "bermuda flag", "flags", 0],
  ["🇧🇳", "brunei flag", "flags", 0],
  ["🇧🇴", "bolivia flag", "flags", 0],
  ["🇧🇶", "caribbean nl flag", "flags", 0],
  ["🇧🇷", "brazil flag", "flags", 0],
  ["🇧🇸", "bahamas flag", "flags", 0],
  ["🇧🇹", "bhutan flag", "flags", 0],
  ["🇧🇻", "bouvet island flag", "flags", 0],
  ["🇧🇼", "botswana flag", "flags", 0],
  ["🇧🇾", "belarus flag", "flags", 0],
  ["🇧🇿", "belize flag", "flags", 0],
  ["🇨🇦", "canada flag", "flags", 0],
  ["🇨🇨", "cocos (keeling) islands flag", "flags", 0],
  ["🇨🇩", "congo (dem. rep.) flag", "flags", 0],
  ["🇨🇫", "central african rep. flag", "flags", 0],
  ["🇨🇬", "congo (rep.) flag", "flags", 0],
  ["🇨🇭", "switzerland flag", "flags", 0],
  ["🇨🇮", "côte d’ivoire flag", "flags", 0],
  ["🇨🇰", "cook islands flag", "flags", 0],
  ["🇨🇱", "chile flag", "flags", 0],
  ["🇨🇲", "cameroon flag", "flags", 0],
  ["🇨🇳", "china flag", "flags", 0],
  ["🇨🇴", "colombia flag", "flags", 0],
  ["🇨🇷", "costa rica flag", "flags", 0],
  ["🇨🇺", "cuba flag", "flags", 0],
  ["🇨🇻", "cape verde flag", "flags", 0],
  ["🇨🇼", "curaçao flag", "flags", 0],
  ["🇨🇽", "christmas island flag", "flags", 0],
  ["🇨🇾", "cyprus flag", "flags", 0],
  ["🇨🇿", "czech republic flag", "flags", 0],
  ["🇩🇪", "germany flag", "flags", 0],
  ["🇩🇯", "djibouti flag", "flags", 0],
  ["🇩🇰", "denmark flag", "flags", 0],
  ["🇩🇲", "dominica flag", "flags", 0],
  ["🇩🇴", "dominican republic flag", "flags", 0],
  ["🇩🇿", "algeria flag", "flags", 0],
  ["🇪🇨", "ecuador flag", "flags", 0],
  ["🇪🇪", "estonia flag", "flags", 0],
  ["🇪🇬", "egypt flag", "flags", 0],
  ["🇪🇭", "western sahara flag", "flags", 0],
  ["🇪🇷", "eritrea flag", "flags", 0],
  ["🇪🇸", "spain flag", "flags", 0],
  ["🇪🇹", "ethiopia flag", "flags", 0],
  ["🇫🇮", "finland flag", "flags", 0],
  ["🇫🇯", "fiji flag", "flags", 0],
  ["🇫🇰", "falkland islands flag", "flags", 0],
  ["🇫🇲", "micronesia flag", "flags", 0],
  ["🇫🇴", "faroe islands flag", "flags", 0],
  ["🇫🇷", "france flag", "flags", 0],
  ["🇬🇦", "gabon flag", "flags", 0],
  ["🇬🇧", "britain (uk) flag", "flags", 0],
  ["🇬🇩", "grenada flag", "flags", 0],
  ["🇬🇪", "georgia flag", "flags", 0],
  ["🇬🇫", "french guiana flag", "flags", 0],
  ["🇬🇬", "guernsey flag", "flags", 0],
  ["🇬🇭", "ghana flag", "flags", 0],
  ["🇬🇮", "gibraltar flag", "flags", 0],
  ["🇬🇱", "greenland flag", "flags", 0],
  ["🇬🇲", "gambia flag", "flags", 0],
  ["🇬🇳", "guinea flag", "flags", 0],
  ["🇬🇵", "guadeloupe flag", "flags", 0],
  ["🇬🇶", "equatorial guinea flag", "flags", 0],
  ["🇬🇷", "greece flag", "flags", 0],
  ["🇬🇸", "south georgia & the south sandwich islands flag", "flags", 0],
  ["🇬🇹", "guatemala flag", "flags", 0],
  ["🇬🇺", "guam flag", "flags", 0],
  ["🇬🇼", "guinea-bissau flag", "flags", 0],
  ["🇬🇾", "guyana flag", "flags", 0],
  ["🇭🇰", "hong kong flag", "flags", 0],
  ["🇭🇲", "heard island & mcdonald islands flag", "flags", 0],
  ["🇭🇳", "honduras flag", "flags", 0],
  ["🇭🇷", "croatia flag", "flags", 0],
  ["🇭🇹", "haiti flag", "flags", 0],
  ["🇭🇺", "hungary flag", "flags", 0],
  ["🇮🇩", "indonesia flag", "flags", 0],
  ["🇮🇪", "ireland flag", "flags", 0],
  ["🇮🇱", "israel flag", "flags", 0],
  ["🇮🇲", "isle of man flag", "flags", 0],
  ["🇮🇳", "india flag", "flags", 0],
  ["🇮🇴", "british indian ocean territory flag", "flags", 0],
  ["🇮🇶", "iraq flag", "flags", 0],
  ["🇮🇷", "iran flag", "flags", 0],
  ["🇮🇸", "iceland flag", "flags", 0],
  ["🇮🇹", "italy flag", "flags", 0],
  ["🇯🇪", "jersey flag", "flags", 0],
  ["🇯🇲", "jamaica flag", "flags", 0],
  ["🇯🇴", "jordan flag", "flags", 0],
  ["🇯🇵", "japan flag", "flags", 0],
  ["🇰🇪", "kenya flag", "flags", 0],
  ["🇰🇬", "kyrgyzstan flag", "flags", 0],
  ["🇰🇭", "cambodia flag", "flags", 0],
  ["🇰🇮", "kiribati flag", "flags", 0],
  ["🇰🇲", "comoros flag", "flags", 0],
  ["🇰🇳", "st kitts & nevis flag", "flags", 0],
  ["🇰🇵", "korea (north) flag", "flags", 0],
  ["🇰🇷", "korea (south) flag", "flags", 0],
  ["🇰🇼", "kuwait flag", "flags", 0],
  ["🇰🇾", "cayman islands flag", "flags", 0],
  ["🇰🇿", "kazakhstan flag", "flags", 0],
  ["🇱🇦", "laos flag", "flags", 0],
  ["🇱🇧", "lebanon flag", "flags", 0],
  ["🇱🇨", "st lucia flag", "flags", 0],
  ["🇱🇮", "liechtenstein flag", "flags", 0],
  ["🇱🇰", "sri lanka flag", "flags", 0],
  ["🇱🇷", "liberia flag", "flags", 0],
  ["🇱🇸", "lesotho flag", "flags", 0],
  ["🇱🇹", "lithuania flag", "flags", 0],
  ["🇱🇺", "luxembourg flag", "flags", 0],
  ["🇱🇻", "latvia flag", "flags", 0],
  ["🇱🇾", "libya flag", "flags", 0],
  ["🇲🇦", "morocco flag", "flags", 0],
  ["🇲🇨", "monaco flag", "flags", 0],
  ["🇲🇩", "moldova flag", "flags", 0],
  ["🇲🇪", "montenegro flag", "flags", 0],
  ["🇲🇫", "st martin (french) flag", "flags", 0],
  ["🇲🇬", "madagascar flag", "flags", 0],
  ["🇲🇭", "marshall islands flag", "flags", 0],
  ["🇲🇰", "north macedonia flag", "flags", 0],
  ["🇲🇱", "mali flag", "flags", 0],
  ["🇲🇲", "myanmar (burma) flag", "flags", 0],
  ["🇲🇳", "mongolia flag", "flags", 0],
  ["🇲🇴", "macau flag", "flags", 0],
  ["🇲🇵", "northern mariana islands flag", "flags", 0],
  ["🇲🇶", "martinique flag", "flags", 0],
  ["🇲🇷", "mauritania flag", "flags", 0],
  ["🇲🇸", "montserrat flag", "flags", 0],
  ["🇲🇹", "malta flag", "flags", 0],
  ["🇲🇺", "mauritius flag", "flags", 0],
  ["🇲🇻", "maldives flag", "flags", 0],
  ["🇲🇼", "malawi flag", "flags", 0],
  ["🇲🇽", "mexico flag", "flags", 0],
  ["🇲🇾", "malaysia flag", "flags", 0],
  ["🇲🇿", "mozambique flag", "flags", 0],
  ["🇳🇦", "namibia flag", "flags", 0],
  ["🇳🇨", "new caledonia flag", "flags", 0],
  ["🇳🇪", "niger flag", "flags", 0],
  ["🇳🇫", "norfolk island flag", "flags", 0],
  ["🇳🇬", "nigeria flag", "flags", 0],
  ["🇳🇮", "nicaragua flag", "flags", 0],
  ["🇳🇱", "netherlands flag", "flags", 0],
  ["🇳🇴", "norway flag", "flags", 0],
  ["🇳🇵", "nepal flag", "flags", 0],
  ["🇳🇷", "nauru flag", "flags", 0],
  ["🇳🇺", "niue flag", "flags", 0],
  ["🇳🇿", "new zealand flag", "flags", 0],
  ["🇴🇲", "oman flag", "flags", 0],
  ["🇵🇦", "panama flag", "flags", 0],
  ["🇵🇪", "peru flag", "flags", 0],
  ["🇵🇫", "french polynesia flag", "flags", 0],
  ["🇵🇬", "papua new guinea flag", "flags", 0],
  ["🇵🇭", "philippines flag", "flags", 0],
  ["🇵🇰", "pakistan flag", "flags", 0],
  ["🇵🇱", "poland flag", "flags", 0],
  ["🇵🇲", "st pierre & miquelon flag", "flags", 0],
  ["🇵🇳", "pitcairn flag", "flags", 0],
  ["🇵🇷", "puerto rico flag", "flags", 0],
  ["🇵🇸", "palestine flag", "flags", 0],
  ["🇵🇹", "portugal flag", "flags", 0],
  ["🇵🇼", "palau flag", "flags", 0],
  ["🇵🇾", "paraguay flag", "flags", 0],
  ["🇶🇦", "qatar flag", "flags", 0],
  ["🇷🇪", "réunion flag", "flags", 0],
  ["🇷🇴", "romania flag", "flags", 0],
  ["🇷🇸", "serbia flag", "flags", 0],
  ["🇷🇺", "russia flag", "flags", 0],
  ["🇷🇼", "rwanda flag", "flags", 0],
  ["🇸🇦", "saudi arabia flag", "flags", 0],
  ["🇸🇧", "solomon islands flag", "flags", 0],
  ["🇸🇨", "seychelles flag", "flags", 0],
  ["🇸🇩", "sudan flag", "flags", 0],
  ["🇸🇪", "sweden flag", "flags", 0],
  ["🇸🇬", "singapore flag", "flags", 0],
  ["🇸🇭", "st helena flag", "flags", 0],
  ["🇸🇮", "slovenia flag", "flags", 0],
  ["🇸🇯", "svalbard & jan mayen flag", "flags", 0],
  ["🇸🇰", "slovakia flag", "flags", 0],
  ["🇸🇱", "sierra leone flag", "flags", 0],
  ["🇸🇲", "san marino flag", "flags", 0],
  ["🇸🇳", "senegal flag", "flags", 0],
  ["🇸🇴", "somalia flag", "flags", 0],
  ["🇸🇷", "suriname flag", "flags", 0],
  ["🇸🇸", "south sudan flag", "flags", 0],
  ["🇸🇹", "sao tome & principe flag", "flags", 0],
  ["🇸🇻", "el salvador flag", "flags", 0],
  ["🇸🇽", "st maarten (dutch) flag", "flags", 0],
  ["🇸🇾", "syria flag", "flags", 0],
  ["🇸🇿", "eswatini (swaziland) flag", "flags", 0],
  ["🇹🇨", "turks & caicos is flag", "flags", 0],
  ["🇹🇩", "chad flag", "flags", 0],
  ["🇹🇫", "french s. terr. flag", "flags", 0],
  ["🇹🇬", "togo flag", "flags", 0],
  ["🇹🇭", "thailand flag", "flags", 0],
  ["🇹🇯", "tajikistan flag", "flags", 0],
  ["🇹🇰", "tokelau flag", "flags", 0],
  ["🇹🇱", "east timor flag", "flags", 0],
  ["🇹🇲", "turkmenistan flag", "flags", 0],
  ["🇹🇳", "tunisia flag", "flags", 0],
  ["🇹🇴", "tonga flag", "flags", 0],
  ["🇹🇷", "turkey flag", "flags", 0],
  ["🇹🇹", "trinidad & tobago flag", "flags", 0],
  ["🇹🇻", "tuvalu flag", "flags", 0],
  ["🇹🇼", "taiwan flag", "flags", 0],
  ["🇹🇿", "tanzania flag", "flags", 0],
  ["🇺🇦", "ukraine flag", "flags", 0],
  ["🇺🇬", "uganda flag", "flags", 0],
  ["🇺🇲", "us minor outlying islands flag", "flags", 0],
  ["🇺🇸", "united states flag", "flags", 0],
  ["🇺🇾", "uruguay flag", "flags", 0],
  ["🇺🇿", "uzbekistan flag", "flags", 0],
  ["🇻🇦", "vatican city flag", "flags", 0],
  ["🇻🇨", "st vincent flag", "flags", 0],
  ["🇻🇪", "venezuela flag", "flags", 0],
  ["🇻🇬", "virgin islands (uk) flag", "flags", 0],
  ["🇻🇮", "virgin islands (us) flag", "flags", 0],
  ["🇻🇳", "vietnam flag", "flags", 0],
  ["🇻🇺", "vanuatu flag", "flags", 0],
  ["🇼🇫", "wallis & futuna flag", "flags", 0],
  ["🇼🇸", "samoa (western) flag", "flags", 0],
  ["🇾🇪", "yemen flag", "flags", 0],
  ["🇾🇹", "mayotte flag", "flags", 0],
  ["🇿🇦", "south africa flag", "flags", 0],
  ["🇿🇲", "zambia flag", "flags", 0],
  ["🇿🇼", "zimbabwe flag", "flags", 0],
];

export const STANDARD_EMOJI: readonly StandardEmoji[] = EMOJI_ROWS.map(
  ([char, name, category, tonable]): StandardEmoji => ({
    char,
    name,
    category,
    tonable: tonable === 1,
  }),
);

/**
 * Apply a skin tone index (0 = none) to an emoji, returning the toned character.
 *
 * The modifier is inserted directly after the first codepoint, which is correct
 * for every base in STANDARD_EMOJI because they are all single-codepoint. It is
 * NOT generally correct for ZWJ sequences (families, professions), where each
 * person component takes its own modifier — this dataset contains none of those,
 * so if ZWJ sequences are ever added this function must be revisited.
 */
export function applySkinTone(emoji: StandardEmoji, toneIndex: number): string {
  if (!emoji.tonable || toneIndex <= 0) {
    return emoji.char;
  }
  const tone = SKIN_TONES[toneIndex];
  if (tone === undefined || tone === "") {
    return emoji.char;
  }
  // Split on codepoints, not UTF-16 units, so the surrogate pair stays intact.
  const codepoints = Array.from(emoji.char);
  const first = codepoints[0];
  if (first === undefined) {
    return emoji.char;
  }
  return first + tone + codepoints.slice(1).join("");
}
