// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "pollis-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "PollisNativeSpec.h"

@interface PollisNative : NSObject <NativePollisNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface PollisNative : NSObject <RCTBridgeModule>
#endif

@end