events {}

http {
    server {
        listen 80;
        server_name downpage.xyz;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name downpage.xyz;

        ssl_certificate /etc/letsencrypt/live/downpage.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/downpage.xyz/privkey.pem;

        location / {
            proxy_pass http://livekit:7880;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}