#!/usr/bin/env bash
#
# publish-aur.sh — push one released version's PKGBUILD to the AUR.
#
# Usage:  publish-aur.sh <version> <path-to-linux-deb>
#   e.g.  publish-aur.sh 1.8.5 artifacts/pollis-linux/pollis-v1.8.5-linux.deb
#
# Requires AUR_SSH_KEY in the environment (the AUR maintainer's private key).
#
# TWO callers share this script, and that is the point — the PKGBUILD below is
# the single source of truth for what the AUR serves:
#   * desktop-release.yml, on every stable `v*` tag, with the .deb it just built.
#   * aur-republish.yml, by hand, with the .deb re-downloaded from cdn.pollis.com,
#     to recover a release the AUR was unreachable for.
# Duplicating the PKGBUILD across those two would let them drift, and a stale
# PKGBUILD is exactly the failure this package has already shipped once (see the
# Electron-layout note below).
#
# Exit 0 = the AUR now serves <version>. Exit 1 = it does not, and the reason is
# on stdout as a ::error:: annotation.

set -euo pipefail

VERSION="${1:?usage: publish-aur.sh <version> <path-to-linux-deb>}"
DEB_PATH="${2:?usage: publish-aur.sh <version> <path-to-linux-deb>}"
: "${AUR_SSH_KEY:?AUR_SSH_KEY must be set}"

# Catch-all so no failure here can exit quietly — this script runs under
# continue-on-error in the release pipeline, where a bare non-zero exit is
# indistinguishable from success. Specific failure paths annotate first.
trap 'echo "::error::AUR publish FAILED for v${VERSION} — the AUR still serves the previous version. Re-run once aur.archlinux.org is reachable: gh workflow run aur-republish.yml -f version=${VERSION}"' ERR

if [ ! -f "$DEB_PATH" ]; then
  echo "::error::No .deb at ${DEB_PATH} — cannot compute the sha256sums the PKGBUILD needs."
  exit 1
fi
SHA256=$(sha256sum "$DEB_PATH" | awk '{print $1}')
echo "Publishing v${VERSION} to the AUR (deb sha256 ${SHA256})"

# Configure SSH for AUR access
mkdir -p ~/.ssh
echo "$AUR_SSH_KEY" > ~/.ssh/aur
chmod 600 ~/.ssh/aur
ssh-keyscan -t ed25519 aur.archlinux.org >> ~/.ssh/known_hosts 2>/dev/null
cat >> ~/.ssh/config <<'SSHEOF'
Host aur.archlinux.org
  IdentityFile ~/.ssh/aur
  User aur
SSHEOF

WORKDIR=$(mktemp -d)
cd "$WORKDIR"

# Clone the AUR repo. Two failure modes worth telling apart:
#
#   * Maintenance. aurweb serves "The AUR is down due to maintenance" from
#     git-serve AFTER the ssh key authenticates, and it can sit that way for
#     days — the window that swallowed v1.8.3/v1.8.4/v1.8.5 ran from ~2026-07-30
#     to at least 2026-08-11 and blocked every AUR package, not just ours
#     (google-chrome and visual-studio-code-bin went equally stale). Retrying
#     that is pointless, so bail at once and say plainly it needs a republish.
#   * Anything else (transient network, ssh blip). Worth a few tries.
#
# In the release pipeline the installers are already on R2 and attached to the
# GitHub release by this point, so neither case should fail the release — this
# only decides how loudly we record that the AUR did not get it.
for attempt in 1 2 3; do
  CLONE_LOG=$(mktemp)
  if git clone ssh://aur@aur.archlinux.org/pollis.git aur-pollis 2>&1 | tee "$CLONE_LOG"; then
    break
  fi
  if grep -qF 'down due to maintenance' "$CLONE_LOG"; then
    echo "::error::AUR is in maintenance — v${VERSION} was NOT published. The ssh key authenticated fine; this is AUR-wide, not ours. Republish once aur.archlinux.org accepts pushes again."
    exit 1
  fi
  if [ "$attempt" -eq 3 ]; then
    echo "::error::AUR unreachable after 3 attempts — v${VERSION} was NOT published to the AUR."
    exit 1
  fi
  echo "AUR clone failed (attempt ${attempt}/3) — retrying in $((attempt * 30))s"
  sleep $((attempt * 30))
done
cd aur-pollis

# Regenerate the PKGBUILD from scratch (heredoc) rather than sed-patching it.
# This script is the SOLE writer of the AUR PKGBUILD — nothing else pushes to
# aur/pollis.git. Owning the whole file (instead of patching whatever is checked
# in) is what keeps it correct regardless of what a previous release left
# behind: historically the now-removed Electron pipeline wrote an Electron-layout
# PKGBUILD here (binary at /opt/Pollis, Electron deps), and a sed-only version
# bump inherited that package()/depends on top of a Tauri .deb, producing a
# dangling /usr/bin/pollis symlink that failed to launch. Depends mirror
# tauri.conf.json's deb.depends plus webkit, in Arch package names.
cat > PKGBUILD <<PKGBUILD_EOF
# Maintainer: Pollis <hello@pollis.com>
# Generated by scripts/publish-aur.sh — do not edit by hand; the release
# pipeline overwrites this file on every release.

pkgname=pollis
pkgver=${VERSION}
pkgrel=1
pkgdesc="End-to-end encrypted messaging"
arch=('x86_64')
url="https://pollis.com"
license=('LicenseRef-proprietary')
depends=(
  'webkit2gtk-4.1'
  'gtk3'
  'libayatana-appindicator'
  'alsa-lib'
  'libpulse'
  'dbus'
)
source=("https://cdn.pollis.com/releases/v\${pkgver}/pollis-v\${pkgver}-linux.deb")
sha256sums=('${SHA256}')

package() {
  # The Tauri .deb already lays the app out under /usr (binary at
  # /usr/bin/pollis, capture helper at /usr/bin/pollis-capture-linux,
  # .desktop + icons under /usr/share) — extract it verbatim. No
  # /opt symlink: that is the Electron layout and would clobber the
  # real /usr/bin/pollis with a dangling link.
  bsdtar -xf data.tar.* -C "\${pkgdir}/"

  # Tauri's .desktop template emits a bare \`Exec=pollis\`, which the launcher
  # resolves through \$PATH — so any binary named \`pollis\` ahead of /usr/bin
  # hijacks the menu entry. That is not hypothetical for Arch specifically:
  # website/install.sh picks .deb only when dpkg exists and .rpm only when
  # dnf/yum exists, so on Arch it always falls through to the AppImage branch,
  # which writes a launcher at ~/.local/bin/pollis and tells the user to put
  # that directory on their PATH. Anyone who ran install.sh before switching to
  # this package keeps launching the stale AppImage while pacman upgrades the
  # real binary underneath — and it fails silently, because the AppImage still
  # starts. Pin Exec to the path this package actually owns.
  local desktop pinned=0
  for desktop in "\${pkgdir}"/usr/share/applications/*.desktop; do
    [ -e "\$desktop" ] || continue
    sed -i -E 's|^Exec=pollis([[:space:]].*)?\$|Exec=/usr/bin/pollis\1|' "\$desktop"
    if grep -q '^Exec=/usr/bin/pollis' "\$desktop"; then
      pinned=1
    fi
  done
  # Never ship a launcher that can still be hijacked: if the .deb's layout
  # changed under us, fail the build here rather than reintroduce the bug.
  if [ "\$pinned" -ne 1 ]; then
    echo "No .desktop with an 'Exec=pollis' line under /usr/share/applications — refusing to package a hijackable launcher." >&2
    return 1
  fi
}
PKGBUILD_EOF

# Regenerate .SRCINFO from the updated PKGBUILD
# Copy PKGBUILD to a nobody-owned temp dir to avoid permission issues with makepkg and .git
docker run --rm -v "$PWD:/pkg" archlinux:base-devel bash -c \
  "cp /pkg/PKGBUILD /tmp/ && chown -R nobody:nobody /tmp/PKGBUILD && cd /tmp && sudo -u nobody makepkg --printsrcinfo > /pkg/.SRCINFO"

# Commit and push if there are changes
git config user.name "Pollis Bot"
git config user.email "hello@pollis.com"
git add PKGBUILD .SRCINFO
if git diff --cached --quiet; then
  echo "No AUR changes to commit"
else
  git commit -m "Update to v${VERSION}"
  git push
fi

# Confirm the AUR really has the commit we think we just gave it. A clean exit
# from `git push` is exactly the kind of evidence this step has already been
# wrong about, so check the remote ref directly rather than trusting the local
# exit code. Reads the git remote, not the RPC: the RPC answers from a cache
# that lags a push by minutes.
LOCAL_HEAD=$(git rev-parse HEAD)
REMOTE_HEAD=$(git ls-remote ssh://aur@aur.archlinux.org/pollis.git HEAD | awk '{print $1}')
if [ "$LOCAL_HEAD" != "$REMOTE_HEAD" ]; then
  echo "::error::AUR remote HEAD (${REMOTE_HEAD:-unknown}) does not match the commit for v${VERSION} (${LOCAL_HEAD}) — the AUR did not take the update."
  exit 1
fi
echo "AUR now serves pollis $(grep -oP '^pkgver=\K.*' PKGBUILD) (commit ${LOCAL_HEAD})"
