// Renders the independent-rebuild verdict ledger on /assurance (#877).
//
// Source: website/rebuild-ledger.json, regenerated by scripts/rebuild-ledger.sh
// from the public Actions API and committed. It is a static file on purpose —
// the verdict has to outlive GitHub's 90-day artifact retention, and a
// committed file is the one place that is both durable and diffable.
//
// `website-verify.yml` fails if the ledger stops matching the workflow's real
// run history, so this table cannot quietly under-report.

(function () {
  "use strict";

  var LEDGER_URL = "rebuild-ledger.json";

  // Sort v1.10.0 after v1.9.7 — string compare gets this backwards, and a
  // release table that lists versions in the wrong order reads as careless on
  // exactly the page arguing for care.
  function versionKey(tag) {
    var parts = String(tag).replace(/^v/, "").split(".");
    return (
      (parseInt(parts[0], 10) || 0) * 1e6 +
      (parseInt(parts[1], 10) || 0) * 1e3 +
      (parseInt(parts[2], 10) || 0)
    );
  }

  function esc(s) {
    return String(s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }

  function fmtDate(iso) {
    var d = new Date(iso);
    if (isNaN(d)) {
      return iso;
    }
    return d.toISOString().slice(0, 10);
  }

  // One row per RELEASE, not per run. A tag can have several runs (a re-dispatch
  // after a fix, or the workflow itself being debugged against a real tag); the
  // latest is the standing verdict and the rest are noted as earlier attempts
  // rather than dropped.
  function byRelease(runs) {
    var groups = {};
    runs.forEach(function (r) {
      (groups[r.tag] = groups[r.tag] || []).push(r);
    });
    return Object.keys(groups)
      .map(function (tag) {
        var rs = groups[tag].slice().sort(function (a, b) {
          return new Date(b.created_at) - new Date(a.created_at);
        });
        return { tag: tag, latest: rs[0], attempts: rs.length, all: rs };
      })
      .sort(function (a, b) {
        return versionKey(b.tag) - versionKey(a.tag);
      });
  }

  function verdictCell(rel, fixDate) {
    var c = rel.latest.conclusion;
    if (c === "success") {
      return {
        badge: '<span class="doc-badge doc-badge--pass">reproduced</span>',
        note: "Rebuilt payload is byte-identical to the logged payload.",
      };
    }
    if (c === "skipped") {
      return {
        badge: '<span class="doc-badge doc-badge--info">never checked</span>',
        note:
          "The release workflow did not conclude successfully, so the rebuild " +
          "never ran. No verdict exists for this release.",
      };
    }
    if (c === "failure") {
      // A red predating the false-red fix is not automatically a false alarm —
      // v1.9.3 was both. Where a run has been individually classified against
      // its log, publish that classification and its evidence; otherwise say
      // only what is actually known.
      var cls = rel.latest.classification;
      if (cls === "false_red") {
        return {
          badge: '<span class="doc-badge doc-badge--warn">false alarm</span>',
          note:
            "Reported red by the pre-fix wait-loop bug. " +
            (rel.latest.evidence || ""),
        };
      }
      if (cls === "real") {
        return {
          badge: '<span class="doc-badge doc-badge--fail">did not reproduce</span>',
          note:
            "A genuine reproducibility finding. " + (rel.latest.evidence || ""),
        };
      }
      var preFix = new Date(rel.latest.created_at) < new Date(fixDate);
      return {
        badge: '<span class="doc-badge doc-badge--fail">did not reproduce</span>',
        note: preFix
          ? "Predates the false-red fix and has not been individually " +
            "classified: a red here may mean the release was not yet published " +
            "into the log rather than a byte divergence. Open the run to see which."
          : "The tag was published and the log verified, and the bytes still " +
            "differed.",
      };
    }
    return {
      badge: '<span class="doc-badge doc-badge--info">' + esc(c) + "</span>",
      note: "",
    };
  }

  function render(data) {
    var summaryEl = document.getElementById("ledger-summary");
    var tableEl = document.getElementById("ledger-table");
    if (!summaryEl || !tableEl) {
      return;
    }

    var releases = byRelease(data.runs || []);
    if (!releases.length) {
      summaryEl.innerHTML =
        '<p class="doc-loading">No rebuild verdicts have been published yet.</p>';
      return;
    }

    var fixDate = (data.false_red_fix && data.false_red_fix.date) || "1970-01-01";
    // Count on the CLASSIFICATION, not the raw CI conclusion — a run that CI
    // marked red but which is known to have reproduced is not a failure, and
    // reporting it as one would understate the record as badly as hiding it
    // would overstate it.
    var counts = { success: 0, real: 0, falseRed: 0, skipped: 0, other: 0 };
    releases.forEach(function (r) {
      var c = r.latest.conclusion;
      if (c === "success") {
        counts.success += 1;
      } else if (c === "skipped") {
        counts.skipped += 1;
      } else if (c === "failure") {
        if (r.latest.classification === "false_red") {
          counts.falseRed += 1;
        } else {
          counts.real += 1;
        }
      } else {
        counts.other += 1;
      }
    });

    var parts = [];
    if (counts.real) {
      parts.push(
        counts.real + " did not reproduce and remains a real finding"
      );
    }
    if (counts.falseRed) {
      parts.push(
        counts.falseRed +
          " went red on a since-fixed reporting bug but did reproduce"
      );
    }
    if (counts.skipped) {
      parts.push(counts.skipped + " were never checked at all");
    }

    summaryEl.innerHTML =
      "<p><strong>" +
      counts.success +
      " of " +
      releases.length +
      " releases reproduced bit-for-bit.</strong>" +
      (parts.length ? " Of the rest, " + parts.join("; ") + "." : "") +
      " Each row links to the run that produced the verdict.</p>";

    var rows = releases
      .map(function (rel) {
        var v = verdictCell(rel, fixDate);
        var attempts =
          rel.attempts > 1
            ? '<br /><span class="doc-td-dim">' +
              (rel.attempts - 1) +
              " earlier attempt" +
              (rel.attempts > 2 ? "s" : "") +
              "</span>"
            : "";
        var link =
          rel.latest.conclusion === "skipped"
            ? '<span class="doc-td-dim">no run</span>'
            : '<a href="' +
              esc(rel.latest.run_url) +
              '" target="_blank" rel="noopener noreferrer">run log</a>';
        return (
          "<tr><td><code>" +
          esc(rel.tag) +
          "</code>" +
          attempts +
          '</td><td class="doc-td-dim">' +
          fmtDate(rel.latest.created_at) +
          "</td><td>" +
          v.badge +
          '</td><td class="doc-td-dim">' +
          esc(v.note) +
          "</td><td>" +
          link +
          "</td></tr>"
        );
      })
      .join("");

    tableEl.innerHTML =
      "<caption>Generated from the public Actions API by " +
      "<code>scripts/rebuild-ledger.sh</code>; last updated " +
      esc(fmtDate(data.generated_at)) +
      ".</caption>" +
      "<thead><tr><th>Release</th><th>Checked</th><th>Verdict</th>" +
      "<th>What it means</th><th></th></tr></thead><tbody>" +
      rows +
      "</tbody>";
  }

  fetch(LEDGER_URL, { cache: "no-cache" })
    .then(function (r) {
      if (!r.ok) {
        throw new Error("HTTP " + r.status);
      }
      return r.json();
    })
    .then(render)
    .catch(function (err) {
      var summaryEl = document.getElementById("ledger-summary");
      if (summaryEl) {
        // Say what failed. A blank panel on a page about verifiability is worse
        // than an error message.
        summaryEl.innerHTML =
          '<p class="doc-loading">Could not load the rebuild ledger (' +
          esc(err.message) +
          "). The verdicts are still readable directly in " +
          '<a href="https://github.com/actuallydan/pollis/actions/workflows/rebuild-verify.yml" ' +
          'target="_blank" rel="noopener noreferrer">the workflow run history</a>.</p>';
      }
    });
})();
