// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Produced by `scripts/generate-emoji-data.py`. To regenerate:
//
//     python3 scripts/generate-emoji-data.py
//
// Unicode data version: 16.0.0
// Country names from:   /usr/share/zoneinfo/iso3166.tab
// Shortcodes from:      scripts/emoji-shortcodes.json (v4.1.0)
// Entries:              1581 (people 298, nature 149, food 128, activity 78, travel 214, objects 258, symbols 207, flags 249)
// With shortcodes:      1574 entries, 1608 aliases
//
// Names come straight from `unicodedata.name()`, lowercased, and double as
// the search keywords — there is deliberately no separate keyword field.
// Categories approximate the CLDR groups; see the generator's docstring for
// the exact ranges and the known approximation limits.
//
// `char` is the bare base codepoint with no U+FE0F variation selector. Entries
// drawn from the older BMP symbol blocks default to text presentation, so a
// renderer wanting a colour glyph should append U+FE0F at display time.
//
// `shortcodes` are the `:joy:`-style aliases, vendored from gemoji (MIT) — see
// the generator's "Where the shortcodes come from" section. They may contain
// `+` and `-`, which a CUSTOM emoji shortcode (`[a-z0-9_]{2,32}`) may not.

export type EmojiCategoryId =
  | "people"
  | "nature"
  | "food"
  | "activity"
  | "travel"
  | "objects"
  | "symbols"
  | "flags";

export interface EmojiCategory {
  readonly id: EmojiCategoryId;
  readonly label: string;
}

export interface StandardEmoji {
  /** The emoji character itself. */
  readonly char: string;
  /** Human-readable name, lowercase (e.g. "grinning face"). */
  readonly name: string;
  readonly category: EmojiCategoryId;
  /** True when this base emoji accepts a Fitzpatrick skin-tone modifier. */
  readonly tonable: boolean;
  /**
   * `:shortcode:` aliases, e.g. ["+1", "thumbsup"]. Often empty — only the
   * emoji gemoji names have one. Every alias is unique across the table.
   */
  readonly shortcodes: readonly string[];
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  { id: "people", label: "People" },
  { id: "nature", label: "Nature" },
  { id: "food", label: "Food" },
  { id: "activity", label: "Activities" },
  { id: "travel", label: "Travel" },
  { id: "objects", label: "Objects" },
  { id: "symbols", label: "Symbols" },
  { id: "flags", label: "Flags" },
];

/** The five Fitzpatrick modifiers, in Discord's order (index 0 = default/none). */
export const SKIN_TONES: readonly string[] = ["", "\u{1F3FB}", "\u{1F3FC}", "\u{1F3FD}", "\u{1F3FE}", "\u{1F3FF}"];

// The table is emitted as positional rows rather than object literals: at this
// size a literal array of 1500+ distinct object types makes tsc give up with
// "union type that is too complex to represent" (TS2590). Rows are contextually
// typed against the single EmojiRow tuple type, so there is no union to widen,
// and the file stays one entry per line for readable diffs.
type EmojiRow = readonly [
  char: string,
  name: string,
  category: EmojiCategoryId,
  tonable: 0 | 1,
  // Space-joined rather than a nested array literal: 1500+ inline arrays cost
  // far more bytes than they buy, and no shortcode can contain a space.
  shortcodes: string,
];

const EMOJI_ROWS: readonly EmojiRow[] = [
  ["☝", "white up pointing index", "people", 1, "point_up"],
  ["☹", "white frowning face", "people", 0, "frowning_face"],
  ["☺", "white smiling face", "people", 0, "relaxed"],
  ["⛹", "person with ball", "people", 1, "bouncing_ball_person"],
  ["✊", "raised fist", "people", 1, "fist fist_raised"],
  ["✋", "raised hand", "people", 1, "hand raised_hand"],
  ["✌", "victory hand", "people", 1, "v"],
  ["✍", "writing hand", "people", 1, "writing_hand"],
  ["❣", "heavy heart exclamation mark ornament", "people", 0, "heavy_heart_exclamation"],
  ["❤", "heavy black heart", "people", 0, "heart"],
  ["🎅", "father christmas", "people", 1, "santa"],
  ["🏂", "snowboarder", "people", 1, "snowboarder"],
  ["🏃", "runner", "people", 1, "runner running"],
  ["🏄", "surfer", "people", 1, "surfer"],
  ["🏇", "horse racing", "people", 1, "horse_racing"],
  ["🏊", "swimmer", "people", 1, "swimmer"],
  ["🏋", "weight lifter", "people", 1, "weight_lifting"],
  ["🏌", "golfer", "people", 1, "golfing"],
  ["👀", "eyes", "people", 0, "eyes"],
  ["👁", "eye", "people", 0, "eye"],
  ["👂", "ear", "people", 1, "ear"],
  ["👃", "nose", "people", 1, "nose"],
  ["👄", "mouth", "people", 0, "lips"],
  ["👅", "tongue", "people", 0, "tongue"],
  ["👆", "white up pointing backhand index", "people", 1, "point_up_2"],
  ["👇", "white down pointing backhand index", "people", 1, "point_down"],
  ["👈", "white left pointing backhand index", "people", 1, "point_left"],
  ["👉", "white right pointing backhand index", "people", 1, "point_right"],
  ["👊", "fisted hand sign", "people", 1, "facepunch fist_oncoming punch"],
  ["👋", "waving hand sign", "people", 1, "wave"],
  ["👌", "ok hand sign", "people", 1, "ok_hand"],
  ["👍", "thumbs up sign", "people", 1, "+1 thumbsup"],
  ["👎", "thumbs down sign", "people", 1, "-1 thumbsdown"],
  ["👏", "clapping hands sign", "people", 1, "clap"],
  ["👐", "open hands sign", "people", 1, "open_hands"],
  ["👣", "footprints", "people", 0, "footprints"],
  ["👤", "bust in silhouette", "people", 0, "bust_in_silhouette"],
  ["👥", "busts in silhouette", "people", 0, "busts_in_silhouette"],
  ["👦", "boy", "people", 1, "boy"],
  ["👧", "girl", "people", 1, "girl"],
  ["👨", "man", "people", 1, "man"],
  ["👩", "woman", "people", 1, "woman"],
  ["👪", "family", "people", 1, "family"],
  ["👫", "man and woman holding hands", "people", 1, "couple"],
  ["👬", "two men holding hands", "people", 1, "two_men_holding_hands"],
  ["👭", "two women holding hands", "people", 1, "two_women_holding_hands"],
  ["👮", "police officer", "people", 1, "cop police_officer"],
  ["👯", "woman with bunny ears", "people", 1, "dancers"],
  ["👰", "bride with veil", "people", 1, "person_with_veil"],
  ["👱", "person with blond hair", "people", 1, "blond_haired_person"],
  ["👲", "man with gua pi mao", "people", 1, "man_with_gua_pi_mao"],
  ["👳", "man with turban", "people", 1, "person_with_turban"],
  ["👴", "older man", "people", 1, "older_man"],
  ["👵", "older woman", "people", 1, "older_woman"],
  ["👶", "baby", "people", 1, "baby"],
  ["👷", "construction worker", "people", 1, "construction_worker"],
  ["👸", "princess", "people", 1, "princess"],
  ["👹", "japanese ogre", "people", 0, "japanese_ogre"],
  ["👺", "japanese goblin", "people", 0, "japanese_goblin"],
  ["👻", "ghost", "people", 0, "ghost"],
  ["👼", "baby angel", "people", 1, "angel"],
  ["👽", "extraterrestrial alien", "people", 0, "alien"],
  ["👾", "alien monster", "people", 0, "space_invader"],
  ["👿", "imp", "people", 0, "imp"],
  ["💀", "skull", "people", 0, "skull"],
  ["💁", "information desk person", "people", 1, "information_desk_person tipping_hand_person"],
  ["💂", "guardsman", "people", 1, "guard"],
  ["💃", "dancer", "people", 1, "dancer woman_dancing"],
  ["💄", "lipstick", "people", 0, "lipstick"],
  ["💅", "nail polish", "people", 1, "nail_care"],
  ["💆", "face massage", "people", 1, "massage"],
  ["💇", "haircut", "people", 1, "haircut"],
  ["💋", "kiss mark", "people", 0, "kiss"],
  ["💌", "love letter", "people", 0, "love_letter"],
  ["💏", "kiss", "people", 1, "couplekiss"],
  ["💑", "couple with heart", "people", 1, "couple_with_heart"],
  ["💓", "beating heart", "people", 0, "heartbeat"],
  ["💔", "broken heart", "people", 0, "broken_heart"],
  ["💕", "two hearts", "people", 0, "two_hearts"],
  ["💖", "sparkling heart", "people", 0, "sparkling_heart"],
  ["💗", "growing heart", "people", 0, "heartpulse"],
  ["💘", "heart with arrow", "people", 0, "cupid"],
  ["💙", "blue heart", "people", 0, "blue_heart"],
  ["💚", "green heart", "people", 0, "green_heart"],
  ["💛", "yellow heart", "people", 0, "yellow_heart"],
  ["💜", "purple heart", "people", 0, "purple_heart"],
  ["💝", "heart with ribbon", "people", 0, "gift_heart"],
  ["💞", "revolving hearts", "people", 0, "revolving_hearts"],
  ["💟", "heart decoration", "people", 0, "heart_decoration"],
  ["💢", "anger symbol", "people", 0, "anger"],
  ["💣", "bomb", "people", 0, "bomb"],
  ["💤", "sleeping symbol", "people", 0, "zzz"],
  ["💥", "collision symbol", "people", 0, "boom collision"],
  ["💦", "splashing sweat symbol", "people", 0, "sweat_drops"],
  ["💧", "droplet", "people", 0, "droplet"],
  ["💨", "dash symbol", "people", 0, "dash"],
  ["💩", "pile of poo", "people", 0, "hankey poop shit"],
  ["💪", "flexed biceps", "people", 1, "muscle"],
  ["💫", "dizzy symbol", "people", 0, "dizzy"],
  ["💬", "speech balloon", "people", 0, "speech_balloon"],
  ["💭", "thought balloon", "people", 0, "thought_balloon"],
  ["🕴", "man in business suit levitating", "people", 1, "business_suit_levitating"],
  ["🕵", "sleuth or spy", "people", 1, "detective"],
  ["🕺", "man dancing", "people", 1, "man_dancing"],
  ["🖐", "raised hand with fingers splayed", "people", 1, "raised_hand_with_fingers_splayed"],
  ["🖕", "reversed hand with middle finger extended", "people", 1, "fu middle_finger"],
  ["🖖", "raised hand with part between middle and ring fingers", "people", 1, "vulcan_salute"],
  ["🖤", "black heart", "people", 0, "black_heart"],
  ["🗣", "speaking head in silhouette", "people", 0, "speaking_head"],
  ["🗨", "left speech bubble", "people", 0, "left_speech_bubble"],
  ["🗯", "right anger bubble", "people", 0, "right_anger_bubble"],
  ["😀", "grinning face", "people", 0, "grinning"],
  ["😁", "grinning face with smiling eyes", "people", 0, "grin"],
  ["😂", "face with tears of joy", "people", 0, "joy"],
  ["😃", "smiling face with open mouth", "people", 0, "smiley"],
  ["😄", "smiling face with open mouth and smiling eyes", "people", 0, "smile"],
  ["😅", "smiling face with open mouth and cold sweat", "people", 0, "sweat_smile"],
  ["😆", "smiling face with open mouth and tightly closed eyes", "people", 0, "laughing satisfied"],
  ["😇", "smiling face with halo", "people", 0, "innocent"],
  ["😈", "smiling face with horns", "people", 0, "smiling_imp"],
  ["😉", "winking face", "people", 0, "wink"],
  ["😊", "smiling face with smiling eyes", "people", 0, "blush"],
  ["😋", "face savouring delicious food", "people", 0, "yum"],
  ["😌", "relieved face", "people", 0, "relieved"],
  ["😍", "smiling face with heart shaped eyes", "people", 0, "heart_eyes"],
  ["😎", "smiling face with sunglasses", "people", 0, "sunglasses"],
  ["😏", "smirking face", "people", 0, "smirk"],
  ["😐", "neutral face", "people", 0, "neutral_face"],
  ["😑", "expressionless face", "people", 0, "expressionless"],
  ["😒", "unamused face", "people", 0, "unamused"],
  ["😓", "face with cold sweat", "people", 0, "sweat"],
  ["😔", "pensive face", "people", 0, "pensive"],
  ["😕", "confused face", "people", 0, "confused"],
  ["😖", "confounded face", "people", 0, "confounded"],
  ["😗", "kissing face", "people", 0, "kissing"],
  ["😘", "face throwing a kiss", "people", 0, "kissing_heart"],
  ["😙", "kissing face with smiling eyes", "people", 0, "kissing_smiling_eyes"],
  ["😚", "kissing face with closed eyes", "people", 0, "kissing_closed_eyes"],
  ["😛", "face with stuck out tongue", "people", 0, "stuck_out_tongue"],
  ["😜", "face with stuck out tongue and winking eye", "people", 0, "stuck_out_tongue_winking_eye"],
  ["😝", "face with stuck out tongue and tightly closed eyes", "people", 0, "stuck_out_tongue_closed_eyes"],
  ["😞", "disappointed face", "people", 0, "disappointed"],
  ["😟", "worried face", "people", 0, "worried"],
  ["😠", "angry face", "people", 0, "angry"],
  ["😡", "pouting face", "people", 0, "pout rage"],
  ["😢", "crying face", "people", 0, "cry"],
  ["😣", "persevering face", "people", 0, "persevere"],
  ["😤", "face with look of triumph", "people", 0, "triumph"],
  ["😥", "disappointed but relieved face", "people", 0, "disappointed_relieved"],
  ["😦", "frowning face with open mouth", "people", 0, "frowning"],
  ["😧", "anguished face", "people", 0, "anguished"],
  ["😨", "fearful face", "people", 0, "fearful"],
  ["😩", "weary face", "people", 0, "weary"],
  ["😪", "sleepy face", "people", 0, "sleepy"],
  ["😫", "tired face", "people", 0, "tired_face"],
  ["😬", "grimacing face", "people", 0, "grimacing"],
  ["😭", "loudly crying face", "people", 0, "sob"],
  ["😮", "face with open mouth", "people", 0, "open_mouth"],
  ["😯", "hushed face", "people", 0, "hushed"],
  ["😰", "face with open mouth and cold sweat", "people", 0, "cold_sweat"],
  ["😱", "face screaming in fear", "people", 0, "scream"],
  ["😲", "astonished face", "people", 0, "astonished"],
  ["😳", "flushed face", "people", 0, "flushed"],
  ["😴", "sleeping face", "people", 0, "sleeping"],
  ["😵", "dizzy face", "people", 0, "dizzy_face"],
  ["😶", "face without mouth", "people", 0, "no_mouth"],
  ["😷", "face with medical mask", "people", 0, "mask"],
  ["😸", "grinning cat face with smiling eyes", "people", 0, "smile_cat"],
  ["😹", "cat face with tears of joy", "people", 0, "joy_cat"],
  ["😺", "smiling cat face with open mouth", "people", 0, "smiley_cat"],
  ["😻", "smiling cat face with heart shaped eyes", "people", 0, "heart_eyes_cat"],
  ["😼", "cat face with wry smile", "people", 0, "smirk_cat"],
  ["😽", "kissing cat face with closed eyes", "people", 0, "kissing_cat"],
  ["😾", "pouting cat face", "people", 0, "pouting_cat"],
  ["😿", "crying cat face", "people", 0, "crying_cat_face"],
  ["🙀", "weary cat face", "people", 0, "scream_cat"],
  ["🙁", "slightly frowning face", "people", 0, "slightly_frowning_face"],
  ["🙂", "slightly smiling face", "people", 0, "slightly_smiling_face"],
  ["🙃", "upside down face", "people", 0, "upside_down_face"],
  ["🙄", "face with rolling eyes", "people", 0, "roll_eyes"],
  ["🙅", "face with no good gesture", "people", 1, "no_good"],
  ["🙆", "face with ok gesture", "people", 1, "ok_person"],
  ["🙇", "person bowing deeply", "people", 1, "bow"],
  ["🙈", "see no evil monkey", "people", 0, "see_no_evil"],
  ["🙉", "hear no evil monkey", "people", 0, "hear_no_evil"],
  ["🙊", "speak no evil monkey", "people", 0, "speak_no_evil"],
  ["🙋", "happy person raising one hand", "people", 1, "raising_hand"],
  ["🙌", "person raising both hands in celebration", "people", 1, "raised_hands"],
  ["🙍", "person frowning", "people", 1, "frowning_person"],
  ["🙎", "person with pouting face", "people", 1, "pouting_face"],
  ["🙏", "person with folded hands", "people", 1, "pray"],
  ["🚣", "rowboat", "people", 1, "rowboat"],
  ["🚴", "bicyclist", "people", 1, "bicyclist"],
  ["🚵", "mountain bicyclist", "people", 1, "mountain_bicyclist"],
  ["🚶", "pedestrian", "people", 1, "walking"],
  ["🛀", "bath", "people", 1, "bath"],
  ["🛌", "sleeping accommodation", "people", 1, "sleeping_bed"],
  ["🤌", "pinched fingers", "people", 1, "pinched_fingers"],
  ["🤍", "white heart", "people", 0, "white_heart"],
  ["🤎", "brown heart", "people", 0, "brown_heart"],
  ["🤏", "pinching hand", "people", 1, "pinching_hand"],
  ["🤘", "sign of the horns", "people", 1, "metal"],
  ["🤙", "call me hand", "people", 1, "call_me_hand"],
  ["🤚", "raised back of hand", "people", 1, "raised_back_of_hand"],
  ["🤛", "left facing fist", "people", 1, "fist_left"],
  ["🤜", "right facing fist", "people", 1, "fist_right"],
  ["🤝", "handshake", "people", 1, "handshake"],
  ["🤞", "hand with index and middle fingers crossed", "people", 1, "crossed_fingers"],
  ["🤟", "i love you hand sign", "people", 1, "love_you_gesture"],
  ["🤠", "face with cowboy hat", "people", 0, "cowboy_hat_face"],
  ["🤡", "clown face", "people", 0, "clown_face"],
  ["🤢", "nauseated face", "people", 0, "nauseated_face"],
  ["🤣", "rolling on the floor laughing", "people", 0, "rofl"],
  ["🤤", "drooling face", "people", 0, "drooling_face"],
  ["🤥", "lying face", "people", 0, "lying_face"],
  ["🤦", "face palm", "people", 1, "facepalm"],
  ["🤧", "sneezing face", "people", 0, "sneezing_face"],
  ["🤨", "face with one eyebrow raised", "people", 0, "raised_eyebrow"],
  ["🤩", "grinning face with star eyes", "people", 0, "star_struck"],
  ["🤪", "grinning face with one large and one small eye", "people", 0, "zany_face"],
  ["🤫", "face with finger covering closed lips", "people", 0, "shushing_face"],
  ["🤬", "serious face with symbols covering mouth", "people", 0, "cursing_face"],
  ["🤭", "smiling face with smiling eyes and hand covering mouth", "people", 0, "hand_over_mouth"],
  ["🤮", "face with open mouth vomiting", "people", 0, "vomiting_face"],
  ["🤯", "shocked face with exploding head", "people", 0, "exploding_head"],
  ["🤰", "pregnant woman", "people", 1, "pregnant_woman"],
  ["🤱", "breast feeding", "people", 1, "breast_feeding"],
  ["🤲", "palms up together", "people", 1, "palms_up_together"],
  ["🤳", "selfie", "people", 1, "selfie"],
  ["🤴", "prince", "people", 1, "prince"],
  ["🤵", "man in tuxedo", "people", 1, "person_in_tuxedo"],
  ["🤶", "mother christmas", "people", 1, "mrs_claus"],
  ["🤷", "shrug", "people", 1, "shrug"],
  ["🤸", "person doing cartwheel", "people", 1, "cartwheeling"],
  ["🤹", "juggling", "people", 1, "juggling_person"],
  ["🤼", "wrestlers", "people", 1, "wrestling"],
  ["🤽", "water polo", "people", 1, "water_polo"],
  ["🤾", "handball", "people", 1, "handball_person"],
  ["🥰", "smiling face with smiling eyes and three hearts", "people", 0, "smiling_face_with_three_hearts"],
  ["🥱", "yawning face", "people", 0, "yawning_face"],
  ["🥲", "smiling face with tear", "people", 0, "smiling_face_with_tear"],
  ["🥳", "face with party horn and party hat", "people", 0, "partying_face"],
  ["🥴", "face with uneven eyes and wavy mouth", "people", 0, "woozy_face"],
  ["🥵", "overheated face", "people", 0, "hot_face"],
  ["🥶", "freezing face", "people", 0, "cold_face"],
  ["🥷", "ninja", "people", 1, "ninja"],
  ["🥸", "disguised face", "people", 0, "disguised_face"],
  ["🥹", "face holding back tears", "people", 0, "face_holding_back_tears"],
  ["🥺", "face with pleading eyes", "people", 0, "pleading_face"],
  ["🦰", "emoji component red hair", "people", 0, ""],
  ["🦱", "emoji component curly hair", "people", 0, ""],
  ["🦲", "emoji component bald", "people", 0, ""],
  ["🦳", "emoji component white hair", "people", 0, ""],
  ["🦴", "bone", "people", 0, "bone"],
  ["🦵", "leg", "people", 1, "leg"],
  ["🦶", "foot", "people", 1, "foot"],
  ["🦷", "tooth", "people", 0, "tooth"],
  ["🦸", "superhero", "people", 1, "superhero"],
  ["🦹", "supervillain", "people", 1, "supervillain"],
  ["🦻", "ear with hearing aid", "people", 1, "ear_with_hearing_aid"],
  ["🦾", "mechanical arm", "people", 0, "mechanical_arm"],
  ["🦿", "mechanical leg", "people", 0, "mechanical_leg"],
  ["🧍", "standing person", "people", 1, "standing_person"],
  ["🧎", "kneeling person", "people", 1, "kneeling_person"],
  ["🧏", "deaf person", "people", 1, "deaf_person"],
  ["🧐", "face with monocle", "people", 1, "monocle_face"],
  ["🧑", "adult", "people", 1, "adult"],
  ["🧒", "child", "people", 1, "child"],
  ["🧓", "older adult", "people", 1, "older_adult"],
  ["🧔", "bearded person", "people", 1, "bearded_person"],
  ["🧕", "person with headscarf", "people", 1, "woman_with_headscarf"],
  ["🧖", "person in steamy room", "people", 1, "sauna_person"],
  ["🧗", "person climbing", "people", 1, "climbing"],
  ["🧘", "person in lotus position", "people", 1, "lotus_position"],
  ["🧙", "mage", "people", 1, "mage"],
  ["🧚", "fairy", "people", 1, "fairy"],
  ["🧛", "vampire", "people", 1, "vampire"],
  ["🧜", "merperson", "people", 1, "merperson"],
  ["🧝", "elf", "people", 1, "elf"],
  ["🧞", "genie", "people", 1, "genie"],
  ["🧟", "zombie", "people", 1, "zombie"],
  ["🧠", "brain", "people", 0, "brain"],
  ["🧡", "orange heart", "people", 0, "orange_heart"],
  ["🫀", "anatomical heart", "people", 0, "anatomical_heart"],
  ["🫁", "lungs", "people", 0, "lungs"],
  ["🫂", "people hugging", "people", 0, "people_hugging"],
  ["🫃", "pregnant man", "people", 1, "pregnant_man"],
  ["🫄", "pregnant person", "people", 1, "pregnant_person"],
  ["🫅", "person with crown", "people", 1, "person_with_crown"],
  ["🫰", "hand with index finger and thumb crossed", "people", 1, "hand_with_index_finger_and_thumb_crossed"],
  ["🫱", "rightwards hand", "people", 1, "rightwards_hand"],
  ["🫲", "leftwards hand", "people", 1, "leftwards_hand"],
  ["🫳", "palm down hand", "people", 1, "palm_down_hand"],
  ["🫴", "palm up hand", "people", 1, "palm_up_hand"],
  ["🫵", "index pointing at the viewer", "people", 1, "index_pointing_at_the_viewer"],
  ["🫶", "heart hands", "people", 1, "heart_hands"],
  ["🫷", "leftwards pushing hand", "people", 1, "leftwards_pushing_hand"],
  ["🫸", "rightwards pushing hand", "people", 1, "rightwards_pushing_hand"],
  ["🌱", "seedling", "nature", 0, "seedling"],
  ["🌲", "evergreen tree", "nature", 0, "evergreen_tree"],
  ["🌳", "deciduous tree", "nature", 0, "deciduous_tree"],
  ["🌴", "palm tree", "nature", 0, "palm_tree"],
  ["🌵", "cactus", "nature", 0, "cactus"],
  ["🌷", "tulip", "nature", 0, "tulip"],
  ["🌸", "cherry blossom", "nature", 0, "cherry_blossom"],
  ["🌹", "rose", "nature", 0, "rose"],
  ["🌺", "hibiscus", "nature", 0, "hibiscus"],
  ["🌻", "sunflower", "nature", 0, "sunflower"],
  ["🌼", "blossom", "nature", 0, "blossom"],
  ["🌾", "ear of rice", "nature", 0, "ear_of_rice"],
  ["🌿", "herb", "nature", 0, "herb"],
  ["🍀", "four leaf clover", "nature", 0, "four_leaf_clover"],
  ["🍁", "maple leaf", "nature", 0, "maple_leaf"],
  ["🍂", "fallen leaf", "nature", 0, "fallen_leaf"],
  ["🍃", "leaf fluttering in wind", "nature", 0, "leaves"],
  ["🐀", "rat", "nature", 0, "rat"],
  ["🐁", "mouse", "nature", 0, "mouse2"],
  ["🐂", "ox", "nature", 0, "ox"],
  ["🐃", "water buffalo", "nature", 0, "water_buffalo"],
  ["🐄", "cow", "nature", 0, "cow2"],
  ["🐅", "tiger", "nature", 0, "tiger2"],
  ["🐆", "leopard", "nature", 0, "leopard"],
  ["🐇", "rabbit", "nature", 0, "rabbit2"],
  ["🐈", "cat", "nature", 0, "cat2"],
  ["🐉", "dragon", "nature", 0, "dragon"],
  ["🐊", "crocodile", "nature", 0, "crocodile"],
  ["🐋", "whale", "nature", 0, "whale2"],
  ["🐌", "snail", "nature", 0, "snail"],
  ["🐍", "snake", "nature", 0, "snake"],
  ["🐎", "horse", "nature", 0, "racehorse"],
  ["🐏", "ram", "nature", 0, "ram"],
  ["🐐", "goat", "nature", 0, "goat"],
  ["🐑", "sheep", "nature", 0, "sheep"],
  ["🐒", "monkey", "nature", 0, "monkey"],
  ["🐓", "rooster", "nature", 0, "rooster"],
  ["🐔", "chicken", "nature", 0, "chicken"],
  ["🐕", "dog", "nature", 0, "dog2"],
  ["🐖", "pig", "nature", 0, "pig2"],
  ["🐗", "boar", "nature", 0, "boar"],
  ["🐘", "elephant", "nature", 0, "elephant"],
  ["🐙", "octopus", "nature", 0, "octopus"],
  ["🐚", "spiral shell", "nature", 0, "shell"],
  ["🐛", "bug", "nature", 0, "bug"],
  ["🐜", "ant", "nature", 0, "ant"],
  ["🐝", "honeybee", "nature", 0, "bee honeybee"],
  ["🐞", "lady beetle", "nature", 0, "lady_beetle"],
  ["🐟", "fish", "nature", 0, "fish"],
  ["🐠", "tropical fish", "nature", 0, "tropical_fish"],
  ["🐡", "blowfish", "nature", 0, "blowfish"],
  ["🐢", "turtle", "nature", 0, "turtle"],
  ["🐣", "hatching chick", "nature", 0, "hatching_chick"],
  ["🐤", "baby chick", "nature", 0, "baby_chick"],
  ["🐥", "front facing baby chick", "nature", 0, "hatched_chick"],
  ["🐦", "bird", "nature", 0, "bird"],
  ["🐧", "penguin", "nature", 0, "penguin"],
  ["🐨", "koala", "nature", 0, "koala"],
  ["🐩", "poodle", "nature", 0, "poodle"],
  ["🐪", "dromedary camel", "nature", 0, "dromedary_camel"],
  ["🐫", "bactrian camel", "nature", 0, "camel"],
  ["🐬", "dolphin", "nature", 0, "dolphin flipper"],
  ["🐭", "mouse face", "nature", 0, "mouse"],
  ["🐮", "cow face", "nature", 0, "cow"],
  ["🐯", "tiger face", "nature", 0, "tiger"],
  ["🐰", "rabbit face", "nature", 0, "rabbit"],
  ["🐱", "cat face", "nature", 0, "cat"],
  ["🐲", "dragon face", "nature", 0, "dragon_face"],
  ["🐳", "spouting whale", "nature", 0, "whale"],
  ["🐴", "horse face", "nature", 0, "horse"],
  ["🐵", "monkey face", "nature", 0, "monkey_face"],
  ["🐶", "dog face", "nature", 0, "dog"],
  ["🐷", "pig face", "nature", 0, "pig"],
  ["🐸", "frog face", "nature", 0, "frog"],
  ["🐹", "hamster face", "nature", 0, "hamster"],
  ["🐺", "wolf face", "nature", 0, "wolf"],
  ["🐻", "bear face", "nature", 0, "bear"],
  ["🐼", "panda face", "nature", 0, "panda_face"],
  ["🐽", "pig nose", "nature", 0, "pig_nose"],
  ["🐾", "paw prints", "nature", 0, "feet paw_prints"],
  ["🐿", "chipmunk", "nature", 0, "chipmunk"],
  ["💐", "bouquet", "nature", 0, "bouquet"],
  ["💮", "white flower", "nature", 0, "white_flower"],
  ["🕷", "spider", "nature", 0, "spider"],
  ["🕸", "spider web", "nature", 0, "spider_web"],
  ["🦀", "crab", "nature", 0, "crab"],
  ["🦁", "lion face", "nature", 0, "lion"],
  ["🦂", "scorpion", "nature", 0, "scorpion"],
  ["🦃", "turkey", "nature", 0, "turkey"],
  ["🦄", "unicorn face", "nature", 0, "unicorn"],
  ["🦅", "eagle", "nature", 0, "eagle"],
  ["🦆", "duck", "nature", 0, "duck"],
  ["🦇", "bat", "nature", 0, "bat"],
  ["🦈", "shark", "nature", 0, "shark"],
  ["🦉", "owl", "nature", 0, "owl"],
  ["🦊", "fox face", "nature", 0, "fox_face"],
  ["🦋", "butterfly", "nature", 0, "butterfly"],
  ["🦌", "deer", "nature", 0, "deer"],
  ["🦍", "gorilla", "nature", 0, "gorilla"],
  ["🦎", "lizard", "nature", 0, "lizard"],
  ["🦏", "rhinoceros", "nature", 0, "rhinoceros"],
  ["🦐", "shrimp", "nature", 0, "shrimp"],
  ["🦑", "squid", "nature", 0, "squid"],
  ["🦒", "giraffe face", "nature", 0, "giraffe"],
  ["🦓", "zebra face", "nature", 0, "zebra"],
  ["🦔", "hedgehog", "nature", 0, "hedgehog"],
  ["🦕", "sauropod", "nature", 0, "sauropod"],
  ["🦖", "t rex", "nature", 0, "t-rex"],
  ["🦗", "cricket", "nature", 0, "cricket"],
  ["🦘", "kangaroo", "nature", 0, "kangaroo"],
  ["🦙", "llama", "nature", 0, "llama"],
  ["🦚", "peacock", "nature", 0, "peacock"],
  ["🦛", "hippopotamus", "nature", 0, "hippopotamus"],
  ["🦜", "parrot", "nature", 0, "parrot"],
  ["🦝", "raccoon", "nature", 0, "raccoon"],
  ["🦞", "lobster", "nature", 0, "lobster"],
  ["🦟", "mosquito", "nature", 0, "mosquito"],
  ["🦠", "microbe", "nature", 0, "microbe"],
  ["🦡", "badger", "nature", 0, "badger"],
  ["🦢", "swan", "nature", 0, "swan"],
  ["🦣", "mammoth", "nature", 0, "mammoth"],
  ["🦤", "dodo", "nature", 0, "dodo"],
  ["🦥", "sloth", "nature", 0, "sloth"],
  ["🦦", "otter", "nature", 0, "otter"],
  ["🦧", "orangutan", "nature", 0, "orangutan"],
  ["🦨", "skunk", "nature", 0, "skunk"],
  ["🦩", "flamingo", "nature", 0, "flamingo"],
  ["🦪", "oyster", "nature", 0, "oyster"],
  ["🦫", "beaver", "nature", 0, "beaver"],
  ["🦬", "bison", "nature", 0, "bison"],
  ["🦭", "seal", "nature", 0, "seal"],
  ["🦮", "guide dog", "nature", 0, "guide_dog"],
  ["🪨", "rock", "nature", 0, "rock"],
  ["🪰", "fly", "nature", 0, "fly"],
  ["🪱", "worm", "nature", 0, "worm"],
  ["🪲", "beetle", "nature", 0, "beetle"],
  ["🪳", "cockroach", "nature", 0, "cockroach"],
  ["🪴", "potted plant", "nature", 0, "potted_plant"],
  ["🪵", "wood", "nature", 0, "wood"],
  ["🪶", "feather", "nature", 0, "feather"],
  ["🪷", "lotus", "nature", 0, "lotus"],
  ["🪸", "coral", "nature", 0, "coral"],
  ["🪹", "empty nest", "nature", 0, "empty_nest"],
  ["🪺", "nest with eggs", "nature", 0, "nest_with_eggs"],
  ["🪻", "hyacinth", "nature", 0, "hyacinth"],
  ["🪼", "jellyfish", "nature", 0, "jellyfish"],
  ["🪽", "wing", "nature", 0, "wing"],
  ["🪾", "leafless tree", "nature", 0, ""],
  ["🪿", "goose", "nature", 0, "goose"],
  ["☕", "hot beverage", "food", 0, "coffee"],
  ["🌭", "hot dog", "food", 0, "hotdog"],
  ["🌮", "taco", "food", 0, "taco"],
  ["🌯", "burrito", "food", 0, "burrito"],
  ["🌰", "chestnut", "food", 0, "chestnut"],
  ["🌶", "hot pepper", "food", 0, "hot_pepper"],
  ["🌽", "ear of maize", "food", 0, "corn"],
  ["🍄", "mushroom", "food", 0, "mushroom"],
  ["🍅", "tomato", "food", 0, "tomato"],
  ["🍆", "aubergine", "food", 0, "eggplant"],
  ["🍇", "grapes", "food", 0, "grapes"],
  ["🍈", "melon", "food", 0, "melon"],
  ["🍉", "watermelon", "food", 0, "watermelon"],
  ["🍊", "tangerine", "food", 0, "mandarin orange tangerine"],
  ["🍋", "lemon", "food", 0, "lemon"],
  ["🍌", "banana", "food", 0, "banana"],
  ["🍍", "pineapple", "food", 0, "pineapple"],
  ["🍎", "red apple", "food", 0, "apple"],
  ["🍏", "green apple", "food", 0, "green_apple"],
  ["🍐", "pear", "food", 0, "pear"],
  ["🍑", "peach", "food", 0, "peach"],
  ["🍒", "cherries", "food", 0, "cherries"],
  ["🍓", "strawberry", "food", 0, "strawberry"],
  ["🍔", "hamburger", "food", 0, "hamburger"],
  ["🍕", "slice of pizza", "food", 0, "pizza"],
  ["🍖", "meat on bone", "food", 0, "meat_on_bone"],
  ["🍗", "poultry leg", "food", 0, "poultry_leg"],
  ["🍘", "rice cracker", "food", 0, "rice_cracker"],
  ["🍙", "rice ball", "food", 0, "rice_ball"],
  ["🍚", "cooked rice", "food", 0, "rice"],
  ["🍛", "curry and rice", "food", 0, "curry"],
  ["🍜", "steaming bowl", "food", 0, "ramen"],
  ["🍝", "spaghetti", "food", 0, "spaghetti"],
  ["🍞", "bread", "food", 0, "bread"],
  ["🍟", "french fries", "food", 0, "fries"],
  ["🍠", "roasted sweet potato", "food", 0, "sweet_potato"],
  ["🍡", "dango", "food", 0, "dango"],
  ["🍢", "oden", "food", 0, "oden"],
  ["🍣", "sushi", "food", 0, "sushi"],
  ["🍤", "fried shrimp", "food", 0, "fried_shrimp"],
  ["🍥", "fish cake with swirl design", "food", 0, "fish_cake"],
  ["🍦", "soft ice cream", "food", 0, "icecream"],
  ["🍧", "shaved ice", "food", 0, "shaved_ice"],
  ["🍨", "ice cream", "food", 0, "ice_cream"],
  ["🍩", "doughnut", "food", 0, "doughnut"],
  ["🍪", "cookie", "food", 0, "cookie"],
  ["🍫", "chocolate bar", "food", 0, "chocolate_bar"],
  ["🍬", "candy", "food", 0, "candy"],
  ["🍭", "lollipop", "food", 0, "lollipop"],
  ["🍮", "custard", "food", 0, "custard"],
  ["🍯", "honey pot", "food", 0, "honey_pot"],
  ["🍰", "shortcake", "food", 0, "cake"],
  ["🍱", "bento box", "food", 0, "bento"],
  ["🍲", "pot of food", "food", 0, "stew"],
  ["🍳", "cooking", "food", 0, "fried_egg"],
  ["🍴", "fork and knife", "food", 0, "fork_and_knife"],
  ["🍵", "teacup without handle", "food", 0, "tea"],
  ["🍶", "sake bottle and cup", "food", 0, "sake"],
  ["🍷", "wine glass", "food", 0, "wine_glass"],
  ["🍸", "cocktail glass", "food", 0, "cocktail"],
  ["🍹", "tropical drink", "food", 0, "tropical_drink"],
  ["🍺", "beer mug", "food", 0, "beer"],
  ["🍻", "clinking beer mugs", "food", 0, "beers"],
  ["🍼", "baby bottle", "food", 0, "baby_bottle"],
  ["🍽", "fork and knife with plate", "food", 0, "plate_with_cutlery"],
  ["🍾", "bottle with popping cork", "food", 0, "champagne"],
  ["🍿", "popcorn", "food", 0, "popcorn"],
  ["🎂", "birthday cake", "food", 0, "birthday"],
  ["🥂", "clinking glasses", "food", 0, "clinking_glasses"],
  ["🥃", "tumbler glass", "food", 0, "tumbler_glass"],
  ["🥄", "spoon", "food", 0, "spoon"],
  ["🥐", "croissant", "food", 0, "croissant"],
  ["🥑", "avocado", "food", 0, "avocado"],
  ["🥒", "cucumber", "food", 0, "cucumber"],
  ["🥓", "bacon", "food", 0, "bacon"],
  ["🥔", "potato", "food", 0, "potato"],
  ["🥕", "carrot", "food", 0, "carrot"],
  ["🥖", "baguette bread", "food", 0, "baguette_bread"],
  ["🥗", "green salad", "food", 0, "green_salad"],
  ["🥘", "shallow pan of food", "food", 0, "shallow_pan_of_food"],
  ["🥙", "stuffed flatbread", "food", 0, "stuffed_flatbread"],
  ["🥚", "egg", "food", 0, "egg"],
  ["🥛", "glass of milk", "food", 0, "milk_glass"],
  ["🥜", "peanuts", "food", 0, "peanuts"],
  ["🥝", "kiwifruit", "food", 0, "kiwi_fruit"],
  ["🥞", "pancakes", "food", 0, "pancakes"],
  ["🥟", "dumpling", "food", 0, "dumpling"],
  ["🥠", "fortune cookie", "food", 0, "fortune_cookie"],
  ["🥡", "takeout box", "food", 0, "takeout_box"],
  ["🥢", "chopsticks", "food", 0, "chopsticks"],
  ["🥣", "bowl with spoon", "food", 0, "bowl_with_spoon"],
  ["🥤", "cup with straw", "food", 0, "cup_with_straw"],
  ["🥥", "coconut", "food", 0, "coconut"],
  ["🥦", "broccoli", "food", 0, "broccoli"],
  ["🥧", "pie", "food", 0, "pie"],
  ["🥨", "pretzel", "food", 0, "pretzel"],
  ["🥩", "cut of meat", "food", 0, "cut_of_meat"],
  ["🥪", "sandwich", "food", 0, "sandwich"],
  ["🥫", "canned food", "food", 0, "canned_food"],
  ["🥬", "leafy green", "food", 0, "leafy_green"],
  ["🥭", "mango", "food", 0, "mango"],
  ["🥮", "moon cake", "food", 0, "moon_cake"],
  ["🥯", "bagel", "food", 0, "bagel"],
  ["🧀", "cheese wedge", "food", 0, "cheese"],
  ["🧁", "cupcake", "food", 0, "cupcake"],
  ["🧂", "salt shaker", "food", 0, "salt"],
  ["🧃", "beverage box", "food", 0, "beverage_box"],
  ["🧄", "garlic", "food", 0, "garlic"],
  ["🧅", "onion", "food", 0, "onion"],
  ["🧆", "falafel", "food", 0, "falafel"],
  ["🧇", "waffle", "food", 0, "waffle"],
  ["🧈", "butter", "food", 0, "butter"],
  ["🧉", "mate drink", "food", 0, "mate"],
  ["🧊", "ice cube", "food", 0, "ice_cube"],
  ["🧋", "bubble tea", "food", 0, "bubble_tea"],
  ["🫐", "blueberries", "food", 0, "blueberries"],
  ["🫑", "bell pepper", "food", 0, "bell_pepper"],
  ["🫒", "olive", "food", 0, "olive"],
  ["🫓", "flatbread", "food", 0, "flatbread"],
  ["🫔", "tamale", "food", 0, "tamale"],
  ["🫕", "fondue", "food", 0, "fondue"],
  ["🫖", "teapot", "food", 0, "teapot"],
  ["🫗", "pouring liquid", "food", 0, "pouring_liquid"],
  ["🫘", "beans", "food", 0, "beans"],
  ["🫙", "jar", "food", 0, "jar"],
  ["🫚", "ginger root", "food", 0, "ginger_root"],
  ["🫛", "pea pod", "food", 0, "pea_pod"],
  ["🫜", "root vegetable", "food", 0, ""],
  ["♟", "black chess pawn", "activity", 0, "chess_pawn"],
  ["⚽", "soccer ball", "activity", 0, "soccer"],
  ["⚾", "baseball", "activity", 0, "baseball"],
  ["⛳", "flag in hole", "activity", 0, "golf"],
  ["⛷", "skier", "activity", 0, "skier"],
  ["⛸", "ice skate", "activity", 0, "ice_skate"],
  ["🀄", "mahjong tile red dragon", "activity", 0, "mahjong"],
  ["🃏", "playing card black joker", "activity", 0, "black_joker"],
  ["🎀", "ribbon", "activity", 0, "ribbon"],
  ["🎁", "wrapped present", "activity", 0, "gift"],
  ["🎃", "jack o lantern", "activity", 0, "jack_o_lantern"],
  ["🎄", "christmas tree", "activity", 0, "christmas_tree"],
  ["🎆", "fireworks", "activity", 0, "fireworks"],
  ["🎇", "firework sparkler", "activity", 0, "sparkler"],
  ["🎈", "balloon", "activity", 0, "balloon"],
  ["🎉", "party popper", "activity", 0, "tada"],
  ["🎊", "confetti ball", "activity", 0, "confetti_ball"],
  ["🎋", "tanabata tree", "activity", 0, "tanabata_tree"],
  ["🎌", "crossed flags", "activity", 0, "crossed_flags"],
  ["🎍", "pine decoration", "activity", 0, "bamboo"],
  ["🎎", "japanese dolls", "activity", 0, "dolls"],
  ["🎏", "carp streamer", "activity", 0, "flags"],
  ["🎐", "wind chime", "activity", 0, "wind_chime"],
  ["🎑", "moon viewing ceremony", "activity", 0, "rice_scene"],
  ["🎒", "school satchel", "activity", 0, "school_satchel"],
  ["🎓", "graduation cap", "activity", 0, "mortar_board"],
  ["🎖", "military medal", "activity", 0, "medal_military"],
  ["🎗", "reminder ribbon", "activity", 0, "reminder_ribbon"],
  ["🎣", "fishing pole and fish", "activity", 0, "fishing_pole_and_fish"],
  ["🎨", "artist palette", "activity", 0, "art"],
  ["🎪", "circus tent", "activity", 0, "circus_tent"],
  ["🎫", "ticket", "activity", 0, "ticket"],
  ["🎭", "performing arts", "activity", 0, "performing_arts"],
  ["🎮", "video game", "activity", 0, "video_game"],
  ["🎯", "direct hit", "activity", 0, "dart"],
  ["🎰", "slot machine", "activity", 0, "slot_machine"],
  ["🎱", "billiards", "activity", 0, "8ball"],
  ["🎲", "game die", "activity", 0, "game_die"],
  ["🎳", "bowling", "activity", 0, "bowling"],
  ["🎴", "flower playing cards", "activity", 0, "flower_playing_cards"],
  ["🎽", "running shirt with sash", "activity", 0, "running_shirt_with_sash"],
  ["🎾", "tennis racquet and ball", "activity", 0, "tennis"],
  ["🎿", "ski and ski boot", "activity", 0, "ski"],
  ["🏀", "basketball and hoop", "activity", 0, "basketball"],
  ["🏁", "chequered flag", "activity", 0, "checkered_flag"],
  ["🏅", "sports medal", "activity", 0, "medal_sports"],
  ["🏆", "trophy", "activity", 0, "trophy"],
  ["🏈", "american football", "activity", 0, "football"],
  ["🏉", "rugby football", "activity", 0, "rugby_football"],
  ["🏏", "cricket bat and ball", "activity", 0, "cricket_game"],
  ["🏐", "volleyball", "activity", 0, "volleyball"],
  ["🏑", "field hockey stick and ball", "activity", 0, "field_hockey"],
  ["🏒", "ice hockey stick and puck", "activity", 0, "ice_hockey"],
  ["🏓", "table tennis paddle and ball", "activity", 0, "ping_pong"],
  ["🏵", "rosette", "activity", 0, "rosette"],
  ["🏸", "badminton racquet and shuttlecock", "activity", 0, "badminton"],
  ["🏹", "bow and arrow", "activity", 0, "bow_and_arrow"],
  ["🔮", "crystal ball", "activity", 0, "crystal_ball"],
  ["🕹", "joystick", "activity", 0, "joystick"],
  ["🛝", "playground slide", "activity", 0, "playground_slide"],
  ["🤺", "fencer", "activity", 0, "person_fencing"],
  ["🥅", "goal net", "activity", 0, "goal_net"],
  ["🥇", "first place medal", "activity", 0, "1st_place_medal"],
  ["🥈", "second place medal", "activity", 0, "2nd_place_medal"],
  ["🥉", "third place medal", "activity", 0, "3rd_place_medal"],
  ["🥊", "boxing glove", "activity", 0, "boxing_glove"],
  ["🥋", "martial arts uniform", "activity", 0, "martial_arts_uniform"],
  ["🥌", "curling stone", "activity", 0, "curling_stone"],
  ["🧧", "red gift envelope", "activity", 0, "red_envelope"],
  ["🧨", "firecracker", "activity", 0, "firecracker"],
  ["🧩", "jigsaw puzzle piece", "activity", 0, "jigsaw"],
  ["🪀", "yo yo", "activity", 0, "yo_yo"],
  ["🪁", "kite", "activity", 0, "kite"],
  ["🪂", "parachute", "activity", 0, "parachute"],
  ["🪃", "boomerang", "activity", 0, "boomerang"],
  ["🪄", "magic wand", "activity", 0, "magic_wand"],
  ["🪅", "pinata", "activity", 0, "pinata"],
  ["🪆", "nesting dolls", "activity", 0, "nesting_dolls"],
  ["⌚", "watch", "travel", 0, "watch"],
  ["⌛", "hourglass", "travel", 0, "hourglass"],
  ["⏰", "alarm clock", "travel", 0, "alarm_clock"],
  ["⏱", "stopwatch", "travel", 0, "stopwatch"],
  ["⏲", "timer clock", "travel", 0, "timer_clock"],
  ["⏳", "hourglass with flowing sand", "travel", 0, "hourglass_flowing_sand"],
  ["☀", "black sun with rays", "travel", 0, "sunny"],
  ["☁", "cloud", "travel", 0, "cloud"],
  ["☂", "umbrella", "travel", 0, "open_umbrella"],
  ["☃", "snowman", "travel", 0, "snowman_with_snow"],
  ["☄", "comet", "travel", 0, "comet"],
  ["☔", "umbrella with rain drops", "travel", 0, "umbrella"],
  ["⛄", "snowman without snow", "travel", 0, "snowman"],
  ["⛅", "sun behind cloud", "travel", 0, "partly_sunny"],
  ["⛈", "thunder cloud and rain", "travel", 0, "cloud_with_lightning_and_rain"],
  ["⛩", "shinto shrine", "travel", 0, "shinto_shrine"],
  ["⛪", "church", "travel", 0, "church"],
  ["⛰", "mountain", "travel", 0, "mountain"],
  ["⛱", "umbrella on ground", "travel", 0, "parasol_on_ground"],
  ["⛲", "fountain", "travel", 0, "fountain"],
  ["⛴", "ferry", "travel", 0, "ferry"],
  ["⛵", "sailboat", "travel", 0, "boat sailboat"],
  ["⛺", "tent", "travel", 0, "tent"],
  ["⛽", "fuel pump", "travel", 0, "fuelpump"],
  ["✈", "airplane", "travel", 0, "airplane"],
  ["🌀", "cyclone", "travel", 0, "cyclone"],
  ["🌁", "foggy", "travel", 0, "foggy"],
  ["🌂", "closed umbrella", "travel", 0, "closed_umbrella"],
  ["🌃", "night with stars", "travel", 0, "night_with_stars"],
  ["🌄", "sunrise over mountains", "travel", 0, "sunrise_over_mountains"],
  ["🌅", "sunrise", "travel", 0, "sunrise"],
  ["🌆", "cityscape at dusk", "travel", 0, "city_sunset"],
  ["🌇", "sunset over buildings", "travel", 0, "city_sunrise"],
  ["🌈", "rainbow", "travel", 0, "rainbow"],
  ["🌉", "bridge at night", "travel", 0, "bridge_at_night"],
  ["🌊", "water wave", "travel", 0, "ocean"],
  ["🌋", "volcano", "travel", 0, "volcano"],
  ["🌌", "milky way", "travel", 0, "milky_way"],
  ["🌍", "earth globe europe africa", "travel", 0, "earth_africa"],
  ["🌎", "earth globe americas", "travel", 0, "earth_americas"],
  ["🌏", "earth globe asia australia", "travel", 0, "earth_asia"],
  ["🌐", "globe with meridians", "travel", 0, "globe_with_meridians"],
  ["🌑", "new moon symbol", "travel", 0, "new_moon"],
  ["🌒", "waxing crescent moon symbol", "travel", 0, "waxing_crescent_moon"],
  ["🌓", "first quarter moon symbol", "travel", 0, "first_quarter_moon"],
  ["🌔", "waxing gibbous moon symbol", "travel", 0, "moon waxing_gibbous_moon"],
  ["🌕", "full moon symbol", "travel", 0, "full_moon"],
  ["🌖", "waning gibbous moon symbol", "travel", 0, "waning_gibbous_moon"],
  ["🌗", "last quarter moon symbol", "travel", 0, "last_quarter_moon"],
  ["🌘", "waning crescent moon symbol", "travel", 0, "waning_crescent_moon"],
  ["🌙", "crescent moon", "travel", 0, "crescent_moon"],
  ["🌚", "new moon with face", "travel", 0, "new_moon_with_face"],
  ["🌛", "first quarter moon with face", "travel", 0, "first_quarter_moon_with_face"],
  ["🌜", "last quarter moon with face", "travel", 0, "last_quarter_moon_with_face"],
  ["🌝", "full moon with face", "travel", 0, "full_moon_with_face"],
  ["🌞", "sun with face", "travel", 0, "sun_with_face"],
  ["🌟", "glowing star", "travel", 0, "star2"],
  ["🌠", "shooting star", "travel", 0, "stars"],
  ["🌡", "thermometer", "travel", 0, "thermometer"],
  ["🌤", "white sun with small cloud", "travel", 0, "sun_behind_small_cloud"],
  ["🌥", "white sun behind cloud", "travel", 0, "sun_behind_large_cloud"],
  ["🌦", "white sun behind cloud with rain", "travel", 0, "sun_behind_rain_cloud"],
  ["🌧", "cloud with rain", "travel", 0, "cloud_with_rain"],
  ["🌨", "cloud with snow", "travel", 0, "cloud_with_snow"],
  ["🌩", "cloud with lightning", "travel", 0, "cloud_with_lightning"],
  ["🌪", "cloud with tornado", "travel", 0, "tornado"],
  ["🌫", "fog", "travel", 0, "fog"],
  ["🌬", "wind blowing face", "travel", 0, "wind_face"],
  ["🎠", "carousel horse", "travel", 0, "carousel_horse"],
  ["🎡", "ferris wheel", "travel", 0, "ferris_wheel"],
  ["🎢", "roller coaster", "travel", 0, "roller_coaster"],
  ["🏍", "racing motorcycle", "travel", 0, "motorcycle"],
  ["🏎", "racing car", "travel", 0, "racing_car"],
  ["🏔", "snow capped mountain", "travel", 0, "mountain_snow"],
  ["🏕", "camping", "travel", 0, "camping"],
  ["🏖", "beach with umbrella", "travel", 0, "beach_umbrella"],
  ["🏗", "building construction", "travel", 0, "building_construction"],
  ["🏘", "house buildings", "travel", 0, "houses"],
  ["🏙", "cityscape", "travel", 0, "cityscape"],
  ["🏚", "derelict house building", "travel", 0, "derelict_house"],
  ["🏛", "classical building", "travel", 0, "classical_building"],
  ["🏜", "desert", "travel", 0, "desert"],
  ["🏝", "desert island", "travel", 0, "desert_island"],
  ["🏞", "national park", "travel", 0, "national_park"],
  ["🏟", "stadium", "travel", 0, "stadium"],
  ["🏠", "house building", "travel", 0, "house"],
  ["🏡", "house with garden", "travel", 0, "house_with_garden"],
  ["🏢", "office building", "travel", 0, "office"],
  ["🏣", "japanese post office", "travel", 0, "post_office"],
  ["🏤", "european post office", "travel", 0, "european_post_office"],
  ["🏥", "hospital", "travel", 0, "hospital"],
  ["🏦", "bank", "travel", 0, "bank"],
  ["🏧", "automated teller machine", "travel", 0, "atm"],
  ["🏨", "hotel", "travel", 0, "hotel"],
  ["🏩", "love hotel", "travel", 0, "love_hotel"],
  ["🏪", "convenience store", "travel", 0, "convenience_store"],
  ["🏫", "school", "travel", 0, "school"],
  ["🏬", "department store", "travel", 0, "department_store"],
  ["🏭", "factory", "travel", 0, "factory"],
  ["🏮", "izakaya lantern", "travel", 0, "izakaya_lantern lantern"],
  ["🏯", "japanese castle", "travel", 0, "japanese_castle"],
  ["🏰", "european castle", "travel", 0, "european_castle"],
  ["💒", "wedding", "travel", 0, "wedding"],
  ["💺", "seat", "travel", 0, "seat"],
  ["🕐", "clock face one oclock", "travel", 0, "clock1"],
  ["🕑", "clock face two oclock", "travel", 0, "clock2"],
  ["🕒", "clock face three oclock", "travel", 0, "clock3"],
  ["🕓", "clock face four oclock", "travel", 0, "clock4"],
  ["🕔", "clock face five oclock", "travel", 0, "clock5"],
  ["🕕", "clock face six oclock", "travel", 0, "clock6"],
  ["🕖", "clock face seven oclock", "travel", 0, "clock7"],
  ["🕗", "clock face eight oclock", "travel", 0, "clock8"],
  ["🕘", "clock face nine oclock", "travel", 0, "clock9"],
  ["🕙", "clock face ten oclock", "travel", 0, "clock10"],
  ["🕚", "clock face eleven oclock", "travel", 0, "clock11"],
  ["🕛", "clock face twelve oclock", "travel", 0, "clock12"],
  ["🕜", "clock face one thirty", "travel", 0, "clock130"],
  ["🕝", "clock face two thirty", "travel", 0, "clock230"],
  ["🕞", "clock face three thirty", "travel", 0, "clock330"],
  ["🕟", "clock face four thirty", "travel", 0, "clock430"],
  ["🕠", "clock face five thirty", "travel", 0, "clock530"],
  ["🕡", "clock face six thirty", "travel", 0, "clock630"],
  ["🕢", "clock face seven thirty", "travel", 0, "clock730"],
  ["🕣", "clock face eight thirty", "travel", 0, "clock830"],
  ["🕤", "clock face nine thirty", "travel", 0, "clock930"],
  ["🕥", "clock face ten thirty", "travel", 0, "clock1030"],
  ["🕦", "clock face eleven thirty", "travel", 0, "clock1130"],
  ["🕧", "clock face twelve thirty", "travel", 0, "clock1230"],
  ["🕰", "mantelpiece clock", "travel", 0, "mantelpiece_clock"],
  ["🗺", "world map", "travel", 0, "world_map"],
  ["🗻", "mount fuji", "travel", 0, "mount_fuji"],
  ["🗼", "tokyo tower", "travel", 0, "tokyo_tower"],
  ["🗽", "statue of liberty", "travel", 0, "statue_of_liberty"],
  ["🗾", "silhouette of japan", "travel", 0, "japan"],
  ["🗿", "moyai", "travel", 0, "moyai"],
  ["🚀", "rocket", "travel", 0, "rocket"],
  ["🚁", "helicopter", "travel", 0, "helicopter"],
  ["🚂", "steam locomotive", "travel", 0, "steam_locomotive"],
  ["🚃", "railway car", "travel", 0, "railway_car"],
  ["🚄", "high speed train", "travel", 0, "bullettrain_side"],
  ["🚅", "high speed train with bullet nose", "travel", 0, "bullettrain_front"],
  ["🚆", "train", "travel", 0, "train2"],
  ["🚇", "metro", "travel", 0, "metro"],
  ["🚈", "light rail", "travel", 0, "light_rail"],
  ["🚉", "station", "travel", 0, "station"],
  ["🚊", "tram", "travel", 0, "tram"],
  ["🚋", "tram car", "travel", 0, "train"],
  ["🚌", "bus", "travel", 0, "bus"],
  ["🚍", "oncoming bus", "travel", 0, "oncoming_bus"],
  ["🚎", "trolleybus", "travel", 0, "trolleybus"],
  ["🚏", "bus stop", "travel", 0, "busstop"],
  ["🚐", "minibus", "travel", 0, "minibus"],
  ["🚑", "ambulance", "travel", 0, "ambulance"],
  ["🚒", "fire engine", "travel", 0, "fire_engine"],
  ["🚓", "police car", "travel", 0, "police_car"],
  ["🚔", "oncoming police car", "travel", 0, "oncoming_police_car"],
  ["🚕", "taxi", "travel", 0, "taxi"],
  ["🚖", "oncoming taxi", "travel", 0, "oncoming_taxi"],
  ["🚗", "automobile", "travel", 0, "car red_car"],
  ["🚘", "oncoming automobile", "travel", 0, "oncoming_automobile"],
  ["🚙", "recreational vehicle", "travel", 0, "blue_car"],
  ["🚚", "delivery truck", "travel", 0, "truck"],
  ["🚛", "articulated lorry", "travel", 0, "articulated_lorry"],
  ["🚜", "tractor", "travel", 0, "tractor"],
  ["🚝", "monorail", "travel", 0, "monorail"],
  ["🚞", "mountain railway", "travel", 0, "mountain_railway"],
  ["🚟", "suspension railway", "travel", 0, "suspension_railway"],
  ["🚠", "mountain cableway", "travel", 0, "mountain_cableway"],
  ["🚡", "aerial tramway", "travel", 0, "aerial_tramway"],
  ["🚢", "ship", "travel", 0, "ship"],
  ["🚤", "speedboat", "travel", 0, "speedboat"],
  ["🚥", "horizontal traffic light", "travel", 0, "traffic_light"],
  ["🚦", "vertical traffic light", "travel", 0, "vertical_traffic_light"],
  ["🚧", "construction sign", "travel", 0, "construction"],
  ["🚨", "police cars revolving light", "travel", 0, "rotating_light"],
  ["🚩", "triangular flag on post", "travel", 0, "triangular_flag_on_post"],
  ["🚫", "no entry sign", "travel", 0, "no_entry_sign"],
  ["🚬", "smoking symbol", "travel", 0, "smoking"],
  ["🚭", "no smoking symbol", "travel", 0, "no_smoking"],
  ["🚮", "put litter in its place symbol", "travel", 0, "put_litter_in_its_place"],
  ["🚯", "do not litter symbol", "travel", 0, "do_not_litter"],
  ["🚰", "potable water symbol", "travel", 0, "potable_water"],
  ["🚱", "non potable water symbol", "travel", 0, "non-potable_water"],
  ["🚲", "bicycle", "travel", 0, "bike"],
  ["🚳", "no bicycles", "travel", 0, "no_bicycles"],
  ["🚷", "no pedestrians", "travel", 0, "no_pedestrians"],
  ["🚸", "children crossing", "travel", 0, "children_crossing"],
  ["🛑", "octagonal sign", "travel", 0, "stop_sign"],
  ["🛕", "hindu temple", "travel", 0, "hindu_temple"],
  ["🛖", "hut", "travel", 0, "hut"],
  ["🛞", "wheel", "travel", 0, "wheel"],
  ["🛟", "ring buoy", "travel", 0, "ring_buoy"],
  ["🛠", "hammer and wrench", "travel", 0, "hammer_and_wrench"],
  ["🛡", "shield", "travel", 0, "shield"],
  ["🛢", "oil drum", "travel", 0, "oil_drum"],
  ["🛣", "motorway", "travel", 0, "motorway"],
  ["🛤", "railway track", "travel", 0, "railway_track"],
  ["🛥", "motor boat", "travel", 0, "motor_boat"],
  ["🛩", "small airplane", "travel", 0, "small_airplane"],
  ["🛫", "airplane departure", "travel", 0, "flight_departure"],
  ["🛬", "airplane arriving", "travel", 0, "flight_arrival"],
  ["🛰", "satellite", "travel", 0, "artificial_satellite"],
  ["🛳", "passenger ship", "travel", 0, "passenger_ship"],
  ["🛴", "scooter", "travel", 0, "kick_scooter"],
  ["🛵", "motor scooter", "travel", 0, "motor_scooter"],
  ["🛶", "canoe", "travel", 0, "canoe"],
  ["🛷", "sled", "travel", 0, "sled"],
  ["🛸", "flying saucer", "travel", 0, "flying_saucer"],
  ["🛹", "skateboard", "travel", 0, "skateboard"],
  ["🛺", "auto rickshaw", "travel", 0, "auto_rickshaw"],
  ["🛻", "pickup truck", "travel", 0, "pickup_truck"],
  ["🛼", "roller skate", "travel", 0, "roller_skate"],
  ["🧳", "luggage", "travel", 0, "luggage"],
  ["🪐", "ringed planet", "travel", 0, "ringed_planet"],
  ["⌨", "keyboard", "objects", 0, "keyboard"],
  ["☎", "black telephone", "objects", 0, "phone telephone"],
  ["⚒", "hammer and pick", "objects", 0, "hammer_and_pick"],
  ["⚔", "crossed swords", "objects", 0, "crossed_swords"],
  ["⚖", "scales", "objects", 0, "balance_scale"],
  ["⚗", "alembic", "objects", 0, "alembic"],
  ["⚙", "gear", "objects", 0, "gear"],
  ["⚰", "coffin", "objects", 0, "coffin"],
  ["⚱", "funeral urn", "objects", 0, "funeral_urn"],
  ["⛏", "pick", "objects", 0, "pick"],
  ["⛑", "helmet with white cross", "objects", 0, "rescue_worker_helmet"],
  ["⛓", "chains", "objects", 0, "chains"],
  ["✂", "black scissors", "objects", 0, "scissors"],
  ["✉", "envelope", "objects", 0, "envelope"],
  ["✏", "pencil", "objects", 0, "pencil2"],
  ["✒", "black nib", "objects", 0, "black_nib"],
  ["🎙", "studio microphone", "objects", 0, "studio_microphone"],
  ["🎚", "level slider", "objects", 0, "level_slider"],
  ["🎛", "control knobs", "objects", 0, "control_knobs"],
  ["🎞", "film frames", "objects", 0, "film_strip"],
  ["🎟", "admission tickets", "objects", 0, "tickets"],
  ["🎤", "microphone", "objects", 0, "microphone"],
  ["🎥", "movie camera", "objects", 0, "movie_camera"],
  ["🎦", "cinema", "objects", 0, "cinema"],
  ["🎧", "headphone", "objects", 0, "headphones"],
  ["🎩", "top hat", "objects", 0, "tophat"],
  ["🎬", "clapper board", "objects", 0, "clapper"],
  ["🎵", "musical note", "objects", 0, "musical_note"],
  ["🎶", "multiple musical notes", "objects", 0, "notes"],
  ["🎷", "saxophone", "objects", 0, "saxophone"],
  ["🎸", "guitar", "objects", 0, "guitar"],
  ["🎹", "musical keyboard", "objects", 0, "musical_keyboard"],
  ["🎺", "trumpet", "objects", 0, "trumpet"],
  ["🎻", "violin", "objects", 0, "violin"],
  ["🎼", "musical score", "objects", 0, "musical_score"],
  ["🏷", "label", "objects", 0, "label"],
  ["🏺", "amphora", "objects", 0, "amphora"],
  ["👑", "crown", "objects", 0, "crown"],
  ["👒", "womans hat", "objects", 0, "womans_hat"],
  ["👓", "eyeglasses", "objects", 0, "eyeglasses"],
  ["👔", "necktie", "objects", 0, "necktie"],
  ["👕", "t shirt", "objects", 0, "shirt tshirt"],
  ["👖", "jeans", "objects", 0, "jeans"],
  ["👗", "dress", "objects", 0, "dress"],
  ["👘", "kimono", "objects", 0, "kimono"],
  ["👙", "bikini", "objects", 0, "bikini"],
  ["👚", "womans clothes", "objects", 0, "womans_clothes"],
  ["👛", "purse", "objects", 0, "purse"],
  ["👜", "handbag", "objects", 0, "handbag"],
  ["👝", "pouch", "objects", 0, "pouch"],
  ["👞", "mans shoe", "objects", 0, "mans_shoe shoe"],
  ["👟", "athletic shoe", "objects", 0, "athletic_shoe"],
  ["👠", "high heeled shoe", "objects", 0, "high_heel"],
  ["👡", "womans sandal", "objects", 0, "sandal"],
  ["👢", "womans boots", "objects", 0, "boot"],
  ["💈", "barber pole", "objects", 0, "barber"],
  ["💉", "syringe", "objects", 0, "syringe"],
  ["💊", "pill", "objects", 0, "pill"],
  ["💍", "ring", "objects", 0, "ring"],
  ["💎", "gem stone", "objects", 0, "gem"],
  ["💡", "electric light bulb", "objects", 0, "bulb"],
  ["💰", "money bag", "objects", 0, "moneybag"],
  ["💱", "currency exchange", "objects", 0, "currency_exchange"],
  ["💲", "heavy dollar sign", "objects", 0, "heavy_dollar_sign"],
  ["💳", "credit card", "objects", 0, "credit_card"],
  ["💴", "banknote with yen sign", "objects", 0, "yen"],
  ["💵", "banknote with dollar sign", "objects", 0, "dollar"],
  ["💶", "banknote with euro sign", "objects", 0, "euro"],
  ["💷", "banknote with pound sign", "objects", 0, "pound"],
  ["💸", "money with wings", "objects", 0, "money_with_wings"],
  ["💹", "chart with upwards trend and yen sign", "objects", 0, "chart"],
  ["💻", "personal computer", "objects", 0, "computer"],
  ["💼", "briefcase", "objects", 0, "briefcase"],
  ["💽", "minidisc", "objects", 0, "minidisc"],
  ["💾", "floppy disk", "objects", 0, "floppy_disk"],
  ["💿", "optical disc", "objects", 0, "cd"],
  ["📀", "dvd", "objects", 0, "dvd"],
  ["📁", "file folder", "objects", 0, "file_folder"],
  ["📂", "open file folder", "objects", 0, "open_file_folder"],
  ["📃", "page with curl", "objects", 0, "page_with_curl"],
  ["📄", "page facing up", "objects", 0, "page_facing_up"],
  ["📅", "calendar", "objects", 0, "date"],
  ["📆", "tear off calendar", "objects", 0, "calendar"],
  ["📇", "card index", "objects", 0, "card_index"],
  ["📈", "chart with upwards trend", "objects", 0, "chart_with_upwards_trend"],
  ["📉", "chart with downwards trend", "objects", 0, "chart_with_downwards_trend"],
  ["📊", "bar chart", "objects", 0, "bar_chart"],
  ["📋", "clipboard", "objects", 0, "clipboard"],
  ["📌", "pushpin", "objects", 0, "pushpin"],
  ["📍", "round pushpin", "objects", 0, "round_pushpin"],
  ["📎", "paperclip", "objects", 0, "paperclip"],
  ["📏", "straight ruler", "objects", 0, "straight_ruler"],
  ["📐", "triangular ruler", "objects", 0, "triangular_ruler"],
  ["📑", "bookmark tabs", "objects", 0, "bookmark_tabs"],
  ["📒", "ledger", "objects", 0, "ledger"],
  ["📓", "notebook", "objects", 0, "notebook"],
  ["📔", "notebook with decorative cover", "objects", 0, "notebook_with_decorative_cover"],
  ["📕", "closed book", "objects", 0, "closed_book"],
  ["📖", "open book", "objects", 0, "book open_book"],
  ["📗", "green book", "objects", 0, "green_book"],
  ["📘", "blue book", "objects", 0, "blue_book"],
  ["📙", "orange book", "objects", 0, "orange_book"],
  ["📚", "books", "objects", 0, "books"],
  ["📛", "name badge", "objects", 0, "name_badge"],
  ["📜", "scroll", "objects", 0, "scroll"],
  ["📝", "memo", "objects", 0, "memo pencil"],
  ["📞", "telephone receiver", "objects", 0, "telephone_receiver"],
  ["📟", "pager", "objects", 0, "pager"],
  ["📠", "fax machine", "objects", 0, "fax"],
  ["📡", "satellite antenna", "objects", 0, "satellite"],
  ["📢", "public address loudspeaker", "objects", 0, "loudspeaker"],
  ["📣", "cheering megaphone", "objects", 0, "mega"],
  ["📤", "outbox tray", "objects", 0, "outbox_tray"],
  ["📥", "inbox tray", "objects", 0, "inbox_tray"],
  ["📦", "package", "objects", 0, "package"],
  ["📧", "e mail symbol", "objects", 0, "e-mail email"],
  ["📨", "incoming envelope", "objects", 0, "incoming_envelope"],
  ["📩", "envelope with downwards arrow above", "objects", 0, "envelope_with_arrow"],
  ["📪", "closed mailbox with lowered flag", "objects", 0, "mailbox_closed"],
  ["📫", "closed mailbox with raised flag", "objects", 0, "mailbox"],
  ["📬", "open mailbox with raised flag", "objects", 0, "mailbox_with_mail"],
  ["📭", "open mailbox with lowered flag", "objects", 0, "mailbox_with_no_mail"],
  ["📮", "postbox", "objects", 0, "postbox"],
  ["📯", "postal horn", "objects", 0, "postal_horn"],
  ["📰", "newspaper", "objects", 0, "newspaper"],
  ["📱", "mobile phone", "objects", 0, "iphone"],
  ["📲", "mobile phone with rightwards arrow at left", "objects", 0, "calling"],
  ["📳", "vibration mode", "objects", 0, "vibration_mode"],
  ["📴", "mobile phone off", "objects", 0, "mobile_phone_off"],
  ["📵", "no mobile phones", "objects", 0, "no_mobile_phones"],
  ["📶", "antenna with bars", "objects", 0, "signal_strength"],
  ["📷", "camera", "objects", 0, "camera"],
  ["📸", "camera with flash", "objects", 0, "camera_flash"],
  ["📹", "video camera", "objects", 0, "video_camera"],
  ["📺", "television", "objects", 0, "tv"],
  ["📻", "radio", "objects", 0, "radio"],
  ["📼", "videocassette", "objects", 0, "vhs"],
  ["📽", "film projector", "objects", 0, "film_projector"],
  ["📿", "prayer beads", "objects", 0, "prayer_beads"],
  ["🔥", "fire", "objects", 0, "fire"],
  ["🔦", "electric torch", "objects", 0, "flashlight"],
  ["🔧", "wrench", "objects", 0, "wrench"],
  ["🔨", "hammer", "objects", 0, "hammer"],
  ["🔩", "nut and bolt", "objects", 0, "nut_and_bolt"],
  ["🔪", "hocho", "objects", 0, "hocho knife"],
  ["🔫", "pistol", "objects", 0, "gun"],
  ["🔬", "microscope", "objects", 0, "microscope"],
  ["🔭", "telescope", "objects", 0, "telescope"],
  ["🕯", "candle", "objects", 0, "candle"],
  ["🕶", "dark sunglasses", "objects", 0, "dark_sunglasses"],
  ["🖇", "linked paperclips", "objects", 0, "paperclips"],
  ["🖊", "lower left ballpoint pen", "objects", 0, "pen"],
  ["🖋", "lower left fountain pen", "objects", 0, "fountain_pen"],
  ["🖌", "lower left paintbrush", "objects", 0, "paintbrush"],
  ["🖍", "lower left crayon", "objects", 0, "crayon"],
  ["🖥", "desktop computer", "objects", 0, "desktop_computer"],
  ["🖨", "printer", "objects", 0, "printer"],
  ["🖱", "three button mouse", "objects", 0, "computer_mouse"],
  ["🖲", "trackball", "objects", 0, "trackball"],
  ["🖼", "frame with picture", "objects", 0, "framed_picture"],
  ["🗂", "card index dividers", "objects", 0, "card_index_dividers"],
  ["🗃", "card file box", "objects", 0, "card_file_box"],
  ["🗄", "file cabinet", "objects", 0, "file_cabinet"],
  ["🗑", "wastebasket", "objects", 0, "wastebasket"],
  ["🗒", "spiral note pad", "objects", 0, "spiral_notepad"],
  ["🗓", "spiral calendar pad", "objects", 0, "spiral_calendar"],
  ["🗜", "compression", "objects", 0, "clamp"],
  ["🗝", "old key", "objects", 0, "old_key"],
  ["🗞", "rolled up newspaper", "objects", 0, "newspaper_roll"],
  ["🗡", "dagger knife", "objects", 0, "dagger"],
  ["🗳", "ballot box with ballot", "objects", 0, "ballot_box"],
  ["🚪", "door", "objects", 0, "door"],
  ["🚽", "toilet", "objects", 0, "toilet"],
  ["🚿", "shower", "objects", 0, "shower"],
  ["🛁", "bathtub", "objects", 0, "bathtub"],
  ["🛒", "shopping trolley", "objects", 0, "shopping_cart"],
  ["🛗", "elevator", "objects", 0, "elevator"],
  ["🛜", "wireless", "objects", 0, "wireless"],
  ["🥻", "sari", "objects", 0, "sari"],
  ["🥼", "lab coat", "objects", 0, "lab_coat"],
  ["🥽", "goggles", "objects", 0, "goggles"],
  ["🥾", "hiking boot", "objects", 0, "hiking_boot"],
  ["🥿", "flat shoe", "objects", 0, "flat_shoe"],
  ["🦯", "probing cane", "objects", 0, "probing_cane"],
  ["🦼", "motorized wheelchair", "objects", 0, "motorized_wheelchair"],
  ["🦽", "manual wheelchair", "objects", 0, "manual_wheelchair"],
  ["🧢", "billed cap", "objects", 0, "billed_cap"],
  ["🧣", "scarf", "objects", 0, "scarf"],
  ["🧤", "gloves", "objects", 0, "gloves"],
  ["🧥", "coat", "objects", 0, "coat"],
  ["🧦", "socks", "objects", 0, "socks"],
  ["🧪", "test tube", "objects", 0, "test_tube"],
  ["🧫", "petri dish", "objects", 0, "petri_dish"],
  ["🧬", "dna double helix", "objects", 0, "dna"],
  ["🧭", "compass", "objects", 0, "compass"],
  ["🧮", "abacus", "objects", 0, "abacus"],
  ["🧯", "fire extinguisher", "objects", 0, "fire_extinguisher"],
  ["🧰", "toolbox", "objects", 0, "toolbox"],
  ["🧱", "brick", "objects", 0, "bricks"],
  ["🧲", "magnet", "objects", 0, "magnet"],
  ["🧴", "lotion bottle", "objects", 0, "lotion_bottle"],
  ["🧵", "spool of thread", "objects", 0, "thread"],
  ["🧶", "ball of yarn", "objects", 0, "yarn"],
  ["🧷", "safety pin", "objects", 0, "safety_pin"],
  ["🧸", "teddy bear", "objects", 0, "teddy_bear"],
  ["🧹", "broom", "objects", 0, "broom"],
  ["🧺", "basket", "objects", 0, "basket"],
  ["🧻", "roll of paper", "objects", 0, "roll_of_paper"],
  ["🧼", "bar of soap", "objects", 0, "soap"],
  ["🧽", "sponge", "objects", 0, "sponge"],
  ["🧾", "receipt", "objects", 0, "receipt"],
  ["🧿", "nazar amulet", "objects", 0, "nazar_amulet"],
  ["🩰", "ballet shoes", "objects", 0, "ballet_shoes"],
  ["🩱", "one piece swimsuit", "objects", 0, "one_piece_swimsuit"],
  ["🩲", "briefs", "objects", 0, "swim_brief"],
  ["🩳", "shorts", "objects", 0, "shorts"],
  ["🩴", "thong sandal", "objects", 0, "thong_sandal"],
  ["🩵", "light blue heart", "objects", 0, "light_blue_heart"],
  ["🩶", "grey heart", "objects", 0, "grey_heart"],
  ["🩷", "pink heart", "objects", 0, "pink_heart"],
  ["🩸", "drop of blood", "objects", 0, "drop_of_blood"],
  ["🩹", "adhesive bandage", "objects", 0, "adhesive_bandage"],
  ["🩺", "stethoscope", "objects", 0, "stethoscope"],
  ["🩻", "x ray", "objects", 0, "x_ray"],
  ["🩼", "crutch", "objects", 0, "crutch"],
  ["🪇", "maracas", "objects", 0, "maracas"],
  ["🪈", "flute", "objects", 0, "flute"],
  ["🪉", "harp", "objects", 0, ""],
  ["🪑", "chair", "objects", 0, "chair"],
  ["🪒", "razor", "objects", 0, "razor"],
  ["🪓", "axe", "objects", 0, "axe"],
  ["🪔", "diya lamp", "objects", 0, "diya_lamp"],
  ["🪕", "banjo", "objects", 0, "banjo"],
  ["🪖", "military helmet", "objects", 0, "military_helmet"],
  ["🪗", "accordion", "objects", 0, "accordion"],
  ["🪘", "long drum", "objects", 0, "long_drum"],
  ["🪙", "coin", "objects", 0, "coin"],
  ["🪚", "carpentry saw", "objects", 0, "carpentry_saw"],
  ["🪛", "screwdriver", "objects", 0, "screwdriver"],
  ["🪜", "ladder", "objects", 0, "ladder"],
  ["🪝", "hook", "objects", 0, "hook"],
  ["🪞", "mirror", "objects", 0, "mirror"],
  ["🪟", "window", "objects", 0, "window"],
  ["🪠", "plunger", "objects", 0, "plunger"],
  ["🪡", "sewing needle", "objects", 0, "sewing_needle"],
  ["🪢", "knot", "objects", 0, "knot"],
  ["🪣", "bucket", "objects", 0, "bucket"],
  ["🪤", "mouse trap", "objects", 0, "mouse_trap"],
  ["🪥", "toothbrush", "objects", 0, "toothbrush"],
  ["🪦", "headstone", "objects", 0, "headstone"],
  ["🪧", "placard", "objects", 0, "placard"],
  ["🪩", "mirror ball", "objects", 0, "mirror_ball"],
  ["🪪", "identification card", "objects", 0, "identification_card"],
  ["🪫", "low battery", "objects", 0, "low_battery"],
  ["🪬", "hamsa", "objects", 0, "hamsa"],
  ["🪭", "folding hand fan", "objects", 0, "folding_hand_fan"],
  ["🪮", "hair pick", "objects", 0, "hair_pick"],
  ["🪯", "khanda", "objects", 0, "khanda"],
  ["©", "copyright sign", "symbols", 0, "copyright"],
  ["®", "registered sign", "symbols", 0, "registered"],
  ["‼", "double exclamation mark", "symbols", 0, "bangbang"],
  ["⁉", "exclamation question mark", "symbols", 0, "interrobang"],
  ["™", "trade mark sign", "symbols", 0, "tm"],
  ["ℹ", "information source", "symbols", 0, "information_source"],
  ["↔", "left right arrow", "symbols", 0, "left_right_arrow"],
  ["↕", "up down arrow", "symbols", 0, "arrow_up_down"],
  ["↖", "north west arrow", "symbols", 0, "arrow_upper_left"],
  ["↗", "north east arrow", "symbols", 0, "arrow_upper_right"],
  ["↘", "south east arrow", "symbols", 0, "arrow_lower_right"],
  ["↙", "south west arrow", "symbols", 0, "arrow_lower_left"],
  ["↩", "leftwards arrow with hook", "symbols", 0, "leftwards_arrow_with_hook"],
  ["↪", "rightwards arrow with hook", "symbols", 0, "arrow_right_hook"],
  ["⏏", "eject symbol", "symbols", 0, "eject_button"],
  ["⏩", "black right pointing double triangle", "symbols", 0, "fast_forward"],
  ["⏪", "black left pointing double triangle", "symbols", 0, "rewind"],
  ["⏫", "black up pointing double triangle", "symbols", 0, "arrow_double_up"],
  ["⏬", "black down pointing double triangle", "symbols", 0, "arrow_double_down"],
  ["⏭", "black right pointing double triangle with vertical bar", "symbols", 0, "next_track_button"],
  ["⏮", "black left pointing double triangle with vertical bar", "symbols", 0, "previous_track_button"],
  ["⏯", "black right pointing triangle with double vertical bar", "symbols", 0, "play_or_pause_button"],
  ["⏸", "double vertical bar", "symbols", 0, "pause_button"],
  ["⏹", "black square for stop", "symbols", 0, "stop_button"],
  ["⏺", "black circle for record", "symbols", 0, "record_button"],
  ["Ⓜ", "circled latin capital letter m", "symbols", 0, "m"],
  ["▪", "black small square", "symbols", 0, "black_small_square"],
  ["▫", "white small square", "symbols", 0, "white_small_square"],
  ["▶", "black right pointing triangle", "symbols", 0, "arrow_forward"],
  ["◀", "black left pointing triangle", "symbols", 0, "arrow_backward"],
  ["◻", "white medium square", "symbols", 0, "white_medium_square"],
  ["◼", "black medium square", "symbols", 0, "black_medium_square"],
  ["◽", "white medium small square", "symbols", 0, "white_medium_small_square"],
  ["◾", "black medium small square", "symbols", 0, "black_medium_small_square"],
  ["☑", "ballot box with check", "symbols", 0, "ballot_box_with_check"],
  ["☦", "orthodox cross", "symbols", 0, "orthodox_cross"],
  ["☪", "star and crescent", "symbols", 0, "star_and_crescent"],
  ["☮", "peace symbol", "symbols", 0, "peace_symbol"],
  ["☯", "yin yang", "symbols", 0, "yin_yang"],
  ["☸", "wheel of dharma", "symbols", 0, "wheel_of_dharma"],
  ["♈", "aries", "symbols", 0, "aries"],
  ["♉", "taurus", "symbols", 0, "taurus"],
  ["♊", "gemini", "symbols", 0, "gemini"],
  ["♋", "cancer", "symbols", 0, "cancer"],
  ["♌", "leo", "symbols", 0, "leo"],
  ["♍", "virgo", "symbols", 0, "virgo"],
  ["♎", "libra", "symbols", 0, "libra"],
  ["♏", "scorpius", "symbols", 0, "scorpius"],
  ["♐", "sagittarius", "symbols", 0, "sagittarius"],
  ["♑", "capricorn", "symbols", 0, "capricorn"],
  ["♒", "aquarius", "symbols", 0, "aquarius"],
  ["♓", "pisces", "symbols", 0, "pisces"],
  ["♻", "black universal recycling symbol", "symbols", 0, "recycle"],
  ["♾", "permanent paper sign", "symbols", 0, "infinity"],
  ["♿", "wheelchair symbol", "symbols", 0, "wheelchair"],
  ["⚕", "staff of aesculapius", "symbols", 0, "medical_symbol"],
  ["⚛", "atom symbol", "symbols", 0, "atom_symbol"],
  ["⚜", "fleur de lis", "symbols", 0, "fleur_de_lis"],
  ["⚠", "warning sign", "symbols", 0, "warning"],
  ["⚡", "high voltage sign", "symbols", 0, "zap"],
  ["⚧", "male with stroke and male and female sign", "symbols", 0, "transgender_symbol"],
  ["⚪", "medium white circle", "symbols", 0, "white_circle"],
  ["⚫", "medium black circle", "symbols", 0, "black_circle"],
  ["⛎", "ophiuchus", "symbols", 0, "ophiuchus"],
  ["⛔", "no entry", "symbols", 0, "no_entry"],
  ["✅", "white heavy check mark", "symbols", 0, "white_check_mark"],
  ["✔", "heavy check mark", "symbols", 0, "heavy_check_mark"],
  ["✖", "heavy multiplication x", "symbols", 0, "heavy_multiplication_x"],
  ["✝", "latin cross", "symbols", 0, "latin_cross"],
  ["✡", "star of david", "symbols", 0, "star_of_david"],
  ["✨", "sparkles", "symbols", 0, "sparkles"],
  ["✳", "eight spoked asterisk", "symbols", 0, "eight_spoked_asterisk"],
  ["✴", "eight pointed black star", "symbols", 0, "eight_pointed_black_star"],
  ["❄", "snowflake", "symbols", 0, "snowflake"],
  ["❇", "sparkle", "symbols", 0, "sparkle"],
  ["❌", "cross mark", "symbols", 0, "x"],
  ["❎", "negative squared cross mark", "symbols", 0, "negative_squared_cross_mark"],
  ["❓", "black question mark ornament", "symbols", 0, "question"],
  ["❔", "white question mark ornament", "symbols", 0, "grey_question"],
  ["❕", "white exclamation mark ornament", "symbols", 0, "grey_exclamation"],
  ["❗", "heavy exclamation mark symbol", "symbols", 0, "exclamation heavy_exclamation_mark"],
  ["➕", "heavy plus sign", "symbols", 0, "heavy_plus_sign"],
  ["➖", "heavy minus sign", "symbols", 0, "heavy_minus_sign"],
  ["➗", "heavy division sign", "symbols", 0, "heavy_division_sign"],
  ["➡", "black rightwards arrow", "symbols", 0, "arrow_right"],
  ["➰", "curly loop", "symbols", 0, "curly_loop"],
  ["➿", "double curly loop", "symbols", 0, "loop"],
  ["⤴", "arrow pointing rightwards then curving upwards", "symbols", 0, "arrow_heading_up"],
  ["⤵", "arrow pointing rightwards then curving downwards", "symbols", 0, "arrow_heading_down"],
  ["⬅", "leftwards black arrow", "symbols", 0, "arrow_left"],
  ["⬆", "upwards black arrow", "symbols", 0, "arrow_up"],
  ["⬇", "downwards black arrow", "symbols", 0, "arrow_down"],
  ["⬛", "black large square", "symbols", 0, "black_large_square"],
  ["⬜", "white large square", "symbols", 0, "white_large_square"],
  ["⭐", "white medium star", "symbols", 0, "star"],
  ["⭕", "heavy large circle", "symbols", 0, "o"],
  ["〰", "wavy dash", "symbols", 0, "wavy_dash"],
  ["〽", "part alternation mark", "symbols", 0, "part_alternation_mark"],
  ["㊗", "circled ideograph congratulation", "symbols", 0, "congratulations"],
  ["㊙", "circled ideograph secret", "symbols", 0, "secret"],
  ["🅰", "negative squared latin capital letter a", "symbols", 0, "a"],
  ["🅱", "negative squared latin capital letter b", "symbols", 0, "b"],
  ["🅾", "negative squared latin capital letter o", "symbols", 0, "o2"],
  ["🅿", "negative squared latin capital letter p", "symbols", 0, "parking"],
  ["🆎", "negative squared ab", "symbols", 0, "ab"],
  ["🆑", "squared cl", "symbols", 0, "cl"],
  ["🆒", "squared cool", "symbols", 0, "cool"],
  ["🆓", "squared free", "symbols", 0, "free"],
  ["🆔", "squared id", "symbols", 0, "id"],
  ["🆕", "squared new", "symbols", 0, "new"],
  ["🆖", "squared ng", "symbols", 0, "ng"],
  ["🆗", "squared ok", "symbols", 0, "ok"],
  ["🆘", "squared sos", "symbols", 0, "sos"],
  ["🆙", "squared up with exclamation mark", "symbols", 0, "up"],
  ["🆚", "squared vs", "symbols", 0, "vs"],
  ["🈁", "squared katakana koko", "symbols", 0, "koko"],
  ["🈂", "squared katakana sa", "symbols", 0, "sa"],
  ["🈚", "squared cjk unified ideograph 7121", "symbols", 0, "u7121"],
  ["🈯", "squared cjk unified ideograph 6307", "symbols", 0, "u6307"],
  ["🈲", "squared cjk unified ideograph 7981", "symbols", 0, "u7981"],
  ["🈳", "squared cjk unified ideograph 7a7a", "symbols", 0, "u7a7a"],
  ["🈴", "squared cjk unified ideograph 5408", "symbols", 0, "u5408"],
  ["🈵", "squared cjk unified ideograph 6e80", "symbols", 0, "u6e80"],
  ["🈶", "squared cjk unified ideograph 6709", "symbols", 0, "u6709"],
  ["🈷", "squared cjk unified ideograph 6708", "symbols", 0, "u6708"],
  ["🈸", "squared cjk unified ideograph 7533", "symbols", 0, "u7533"],
  ["🈹", "squared cjk unified ideograph 5272", "symbols", 0, "u5272"],
  ["🈺", "squared cjk unified ideograph 55b6", "symbols", 0, "u55b6"],
  ["🉐", "circled ideograph advantage", "symbols", 0, "ideograph_advantage"],
  ["🉑", "circled ideograph accept", "symbols", 0, "accept"],
  ["💠", "diamond shape with a dot inside", "symbols", 0, "diamond_shape_with_a_dot_inside"],
  ["💯", "hundred points symbol", "symbols", 0, "100"],
  ["🔀", "twisted rightwards arrows", "symbols", 0, "twisted_rightwards_arrows"],
  ["🔁", "clockwise rightwards and leftwards open circle arrows", "symbols", 0, "repeat"],
  ["🔂", "clockwise rightwards and leftwards open circle arrows with circled one overlay", "symbols", 0, "repeat_one"],
  ["🔃", "clockwise downwards and upwards open circle arrows", "symbols", 0, "arrows_clockwise"],
  ["🔄", "anticlockwise downwards and upwards open circle arrows", "symbols", 0, "arrows_counterclockwise"],
  ["🔅", "low brightness symbol", "symbols", 0, "low_brightness"],
  ["🔆", "high brightness symbol", "symbols", 0, "high_brightness"],
  ["🔇", "speaker with cancellation stroke", "symbols", 0, "mute"],
  ["🔈", "speaker", "symbols", 0, "speaker"],
  ["🔉", "speaker with one sound wave", "symbols", 0, "sound"],
  ["🔊", "speaker with three sound waves", "symbols", 0, "loud_sound"],
  ["🔋", "battery", "symbols", 0, "battery"],
  ["🔌", "electric plug", "symbols", 0, "electric_plug"],
  ["🔍", "left pointing magnifying glass", "symbols", 0, "mag"],
  ["🔎", "right pointing magnifying glass", "symbols", 0, "mag_right"],
  ["🔏", "lock with ink pen", "symbols", 0, "lock_with_ink_pen"],
  ["🔐", "closed lock with key", "symbols", 0, "closed_lock_with_key"],
  ["🔑", "key", "symbols", 0, "key"],
  ["🔒", "lock", "symbols", 0, "lock"],
  ["🔓", "open lock", "symbols", 0, "unlock"],
  ["🔔", "bell", "symbols", 0, "bell"],
  ["🔕", "bell with cancellation stroke", "symbols", 0, "no_bell"],
  ["🔖", "bookmark", "symbols", 0, "bookmark"],
  ["🔗", "link symbol", "symbols", 0, "link"],
  ["🔘", "radio button", "symbols", 0, "radio_button"],
  ["🔙", "back with leftwards arrow above", "symbols", 0, "back"],
  ["🔚", "end with leftwards arrow above", "symbols", 0, "end"],
  ["🔛", "on with exclamation mark with left right arrow above", "symbols", 0, "on"],
  ["🔜", "soon with rightwards arrow above", "symbols", 0, "soon"],
  ["🔝", "top with upwards arrow above", "symbols", 0, "top"],
  ["🔞", "no one under eighteen symbol", "symbols", 0, "underage"],
  ["🔟", "keycap ten", "symbols", 0, "keycap_ten"],
  ["🔠", "input symbol for latin capital letters", "symbols", 0, "capital_abcd"],
  ["🔡", "input symbol for latin small letters", "symbols", 0, "abcd"],
  ["🔢", "input symbol for numbers", "symbols", 0, "1234"],
  ["🔣", "input symbol for symbols", "symbols", 0, "symbols"],
  ["🔤", "input symbol for latin letters", "symbols", 0, "abc"],
  ["🔯", "six pointed star with middle dot", "symbols", 0, "six_pointed_star"],
  ["🔰", "japanese symbol for beginner", "symbols", 0, "beginner"],
  ["🔱", "trident emblem", "symbols", 0, "trident"],
  ["🔲", "black square button", "symbols", 0, "black_square_button"],
  ["🔳", "white square button", "symbols", 0, "white_square_button"],
  ["🔴", "large red circle", "symbols", 0, "red_circle"],
  ["🔵", "large blue circle", "symbols", 0, "large_blue_circle"],
  ["🔶", "large orange diamond", "symbols", 0, "large_orange_diamond"],
  ["🔷", "large blue diamond", "symbols", 0, "large_blue_diamond"],
  ["🔸", "small orange diamond", "symbols", 0, "small_orange_diamond"],
  ["🔹", "small blue diamond", "symbols", 0, "small_blue_diamond"],
  ["🔺", "up pointing red triangle", "symbols", 0, "small_red_triangle"],
  ["🔻", "down pointing red triangle", "symbols", 0, "small_red_triangle_down"],
  ["🔼", "up pointing small red triangle", "symbols", 0, "arrow_up_small"],
  ["🔽", "down pointing small red triangle", "symbols", 0, "arrow_down_small"],
  ["🚹", "mens symbol", "symbols", 0, "mens"],
  ["🚺", "womens symbol", "symbols", 0, "womens"],
  ["🚻", "restroom", "symbols", 0, "restroom"],
  ["🚼", "baby symbol", "symbols", 0, "baby_symbol"],
  ["🚾", "water closet", "symbols", 0, "wc"],
  ["🛂", "passport control", "symbols", 0, "passport_control"],
  ["🛃", "customs", "symbols", 0, "customs"],
  ["🛄", "baggage claim", "symbols", 0, "baggage_claim"],
  ["🛅", "left luggage", "symbols", 0, "left_luggage"],
  ["🛐", "place of worship", "symbols", 0, "place_of_worship"],
  ["🟠", "large orange circle", "symbols", 0, "orange_circle"],
  ["🟡", "large yellow circle", "symbols", 0, "yellow_circle"],
  ["🟢", "large green circle", "symbols", 0, "green_circle"],
  ["🟣", "large purple circle", "symbols", 0, "purple_circle"],
  ["🟤", "large brown circle", "symbols", 0, "brown_circle"],
  ["🟥", "large red square", "symbols", 0, "red_square"],
  ["🟦", "large blue square", "symbols", 0, "blue_square"],
  ["🟧", "large orange square", "symbols", 0, "orange_square"],
  ["🟨", "large yellow square", "symbols", 0, "yellow_square"],
  ["🟩", "large green square", "symbols", 0, "green_square"],
  ["🟪", "large purple square", "symbols", 0, "purple_square"],
  ["🟫", "large brown square", "symbols", 0, "brown_square"],
  ["🟰", "heavy equals sign", "symbols", 0, "heavy_equals_sign"],
  ["🇦🇩", "andorra flag", "flags", 0, "andorra"],
  ["🇦🇪", "united arab emirates flag", "flags", 0, "united_arab_emirates"],
  ["🇦🇫", "afghanistan flag", "flags", 0, "afghanistan"],
  ["🇦🇬", "antigua & barbuda flag", "flags", 0, "antigua_barbuda"],
  ["🇦🇮", "anguilla flag", "flags", 0, "anguilla"],
  ["🇦🇱", "albania flag", "flags", 0, "albania"],
  ["🇦🇲", "armenia flag", "flags", 0, "armenia"],
  ["🇦🇴", "angola flag", "flags", 0, "angola"],
  ["🇦🇶", "antarctica flag", "flags", 0, "antarctica"],
  ["🇦🇷", "argentina flag", "flags", 0, "argentina"],
  ["🇦🇸", "samoa (american) flag", "flags", 0, "american_samoa"],
  ["🇦🇹", "austria flag", "flags", 0, "austria"],
  ["🇦🇺", "australia flag", "flags", 0, "australia"],
  ["🇦🇼", "aruba flag", "flags", 0, "aruba"],
  ["🇦🇽", "åland islands flag", "flags", 0, "aland_islands"],
  ["🇦🇿", "azerbaijan flag", "flags", 0, "azerbaijan"],
  ["🇧🇦", "bosnia & herzegovina flag", "flags", 0, "bosnia_herzegovina"],
  ["🇧🇧", "barbados flag", "flags", 0, "barbados"],
  ["🇧🇩", "bangladesh flag", "flags", 0, "bangladesh"],
  ["🇧🇪", "belgium flag", "flags", 0, "belgium"],
  ["🇧🇫", "burkina faso flag", "flags", 0, "burkina_faso"],
  ["🇧🇬", "bulgaria flag", "flags", 0, "bulgaria"],
  ["🇧🇭", "bahrain flag", "flags", 0, "bahrain"],
  ["🇧🇮", "burundi flag", "flags", 0, "burundi"],
  ["🇧🇯", "benin flag", "flags", 0, "benin"],
  ["🇧🇱", "st barthelemy flag", "flags", 0, "st_barthelemy"],
  ["🇧🇲", "bermuda flag", "flags", 0, "bermuda"],
  ["🇧🇳", "brunei flag", "flags", 0, "brunei"],
  ["🇧🇴", "bolivia flag", "flags", 0, "bolivia"],
  ["🇧🇶", "caribbean nl flag", "flags", 0, "caribbean_netherlands"],
  ["🇧🇷", "brazil flag", "flags", 0, "brazil"],
  ["🇧🇸", "bahamas flag", "flags", 0, "bahamas"],
  ["🇧🇹", "bhutan flag", "flags", 0, "bhutan"],
  ["🇧🇻", "bouvet island flag", "flags", 0, "bouvet_island"],
  ["🇧🇼", "botswana flag", "flags", 0, "botswana"],
  ["🇧🇾", "belarus flag", "flags", 0, "belarus"],
  ["🇧🇿", "belize flag", "flags", 0, "belize"],
  ["🇨🇦", "canada flag", "flags", 0, "canada"],
  ["🇨🇨", "cocos (keeling) islands flag", "flags", 0, "cocos_islands"],
  ["🇨🇩", "congo (dem. rep.) flag", "flags", 0, "congo_kinshasa"],
  ["🇨🇫", "central african rep. flag", "flags", 0, "central_african_republic"],
  ["🇨🇬", "congo (rep.) flag", "flags", 0, "congo_brazzaville"],
  ["🇨🇭", "switzerland flag", "flags", 0, "switzerland"],
  ["🇨🇮", "côte d’ivoire flag", "flags", 0, "cote_divoire"],
  ["🇨🇰", "cook islands flag", "flags", 0, "cook_islands"],
  ["🇨🇱", "chile flag", "flags", 0, "chile"],
  ["🇨🇲", "cameroon flag", "flags", 0, "cameroon"],
  ["🇨🇳", "china flag", "flags", 0, "cn"],
  ["🇨🇴", "colombia flag", "flags", 0, "colombia"],
  ["🇨🇷", "costa rica flag", "flags", 0, "costa_rica"],
  ["🇨🇺", "cuba flag", "flags", 0, "cuba"],
  ["🇨🇻", "cape verde flag", "flags", 0, "cape_verde"],
  ["🇨🇼", "curaçao flag", "flags", 0, "curacao"],
  ["🇨🇽", "christmas island flag", "flags", 0, "christmas_island"],
  ["🇨🇾", "cyprus flag", "flags", 0, "cyprus"],
  ["🇨🇿", "czech republic flag", "flags", 0, "czech_republic"],
  ["🇩🇪", "germany flag", "flags", 0, "de"],
  ["🇩🇯", "djibouti flag", "flags", 0, "djibouti"],
  ["🇩🇰", "denmark flag", "flags", 0, "denmark"],
  ["🇩🇲", "dominica flag", "flags", 0, "dominica"],
  ["🇩🇴", "dominican republic flag", "flags", 0, "dominican_republic"],
  ["🇩🇿", "algeria flag", "flags", 0, "algeria"],
  ["🇪🇨", "ecuador flag", "flags", 0, "ecuador"],
  ["🇪🇪", "estonia flag", "flags", 0, "estonia"],
  ["🇪🇬", "egypt flag", "flags", 0, "egypt"],
  ["🇪🇭", "western sahara flag", "flags", 0, "western_sahara"],
  ["🇪🇷", "eritrea flag", "flags", 0, "eritrea"],
  ["🇪🇸", "spain flag", "flags", 0, "es"],
  ["🇪🇹", "ethiopia flag", "flags", 0, "ethiopia"],
  ["🇫🇮", "finland flag", "flags", 0, "finland"],
  ["🇫🇯", "fiji flag", "flags", 0, "fiji"],
  ["🇫🇰", "falkland islands flag", "flags", 0, "falkland_islands"],
  ["🇫🇲", "micronesia flag", "flags", 0, "micronesia"],
  ["🇫🇴", "faroe islands flag", "flags", 0, "faroe_islands"],
  ["🇫🇷", "france flag", "flags", 0, "fr"],
  ["🇬🇦", "gabon flag", "flags", 0, "gabon"],
  ["🇬🇧", "britain (uk) flag", "flags", 0, "gb uk"],
  ["🇬🇩", "grenada flag", "flags", 0, "grenada"],
  ["🇬🇪", "georgia flag", "flags", 0, "georgia"],
  ["🇬🇫", "french guiana flag", "flags", 0, "french_guiana"],
  ["🇬🇬", "guernsey flag", "flags", 0, "guernsey"],
  ["🇬🇭", "ghana flag", "flags", 0, "ghana"],
  ["🇬🇮", "gibraltar flag", "flags", 0, "gibraltar"],
  ["🇬🇱", "greenland flag", "flags", 0, "greenland"],
  ["🇬🇲", "gambia flag", "flags", 0, "gambia"],
  ["🇬🇳", "guinea flag", "flags", 0, "guinea"],
  ["🇬🇵", "guadeloupe flag", "flags", 0, "guadeloupe"],
  ["🇬🇶", "equatorial guinea flag", "flags", 0, "equatorial_guinea"],
  ["🇬🇷", "greece flag", "flags", 0, "greece"],
  ["🇬🇸", "south georgia & the south sandwich islands flag", "flags", 0, "south_georgia_south_sandwich_islands"],
  ["🇬🇹", "guatemala flag", "flags", 0, "guatemala"],
  ["🇬🇺", "guam flag", "flags", 0, "guam"],
  ["🇬🇼", "guinea-bissau flag", "flags", 0, "guinea_bissau"],
  ["🇬🇾", "guyana flag", "flags", 0, "guyana"],
  ["🇭🇰", "hong kong flag", "flags", 0, "hong_kong"],
  ["🇭🇲", "heard island & mcdonald islands flag", "flags", 0, "heard_mcdonald_islands"],
  ["🇭🇳", "honduras flag", "flags", 0, "honduras"],
  ["🇭🇷", "croatia flag", "flags", 0, "croatia"],
  ["🇭🇹", "haiti flag", "flags", 0, "haiti"],
  ["🇭🇺", "hungary flag", "flags", 0, "hungary"],
  ["🇮🇩", "indonesia flag", "flags", 0, "indonesia"],
  ["🇮🇪", "ireland flag", "flags", 0, "ireland"],
  ["🇮🇱", "israel flag", "flags", 0, "israel"],
  ["🇮🇲", "isle of man flag", "flags", 0, "isle_of_man"],
  ["🇮🇳", "india flag", "flags", 0, "india"],
  ["🇮🇴", "british indian ocean territory flag", "flags", 0, "british_indian_ocean_territory"],
  ["🇮🇶", "iraq flag", "flags", 0, "iraq"],
  ["🇮🇷", "iran flag", "flags", 0, "iran"],
  ["🇮🇸", "iceland flag", "flags", 0, "iceland"],
  ["🇮🇹", "italy flag", "flags", 0, "it"],
  ["🇯🇪", "jersey flag", "flags", 0, "jersey"],
  ["🇯🇲", "jamaica flag", "flags", 0, "jamaica"],
  ["🇯🇴", "jordan flag", "flags", 0, "jordan"],
  ["🇯🇵", "japan flag", "flags", 0, "jp"],
  ["🇰🇪", "kenya flag", "flags", 0, "kenya"],
  ["🇰🇬", "kyrgyzstan flag", "flags", 0, "kyrgyzstan"],
  ["🇰🇭", "cambodia flag", "flags", 0, "cambodia"],
  ["🇰🇮", "kiribati flag", "flags", 0, "kiribati"],
  ["🇰🇲", "comoros flag", "flags", 0, "comoros"],
  ["🇰🇳", "st kitts & nevis flag", "flags", 0, "st_kitts_nevis"],
  ["🇰🇵", "korea (north) flag", "flags", 0, "north_korea"],
  ["🇰🇷", "korea (south) flag", "flags", 0, "kr"],
  ["🇰🇼", "kuwait flag", "flags", 0, "kuwait"],
  ["🇰🇾", "cayman islands flag", "flags", 0, "cayman_islands"],
  ["🇰🇿", "kazakhstan flag", "flags", 0, "kazakhstan"],
  ["🇱🇦", "laos flag", "flags", 0, "laos"],
  ["🇱🇧", "lebanon flag", "flags", 0, "lebanon"],
  ["🇱🇨", "st lucia flag", "flags", 0, "st_lucia"],
  ["🇱🇮", "liechtenstein flag", "flags", 0, "liechtenstein"],
  ["🇱🇰", "sri lanka flag", "flags", 0, "sri_lanka"],
  ["🇱🇷", "liberia flag", "flags", 0, "liberia"],
  ["🇱🇸", "lesotho flag", "flags", 0, "lesotho"],
  ["🇱🇹", "lithuania flag", "flags", 0, "lithuania"],
  ["🇱🇺", "luxembourg flag", "flags", 0, "luxembourg"],
  ["🇱🇻", "latvia flag", "flags", 0, "latvia"],
  ["🇱🇾", "libya flag", "flags", 0, "libya"],
  ["🇲🇦", "morocco flag", "flags", 0, "morocco"],
  ["🇲🇨", "monaco flag", "flags", 0, "monaco"],
  ["🇲🇩", "moldova flag", "flags", 0, "moldova"],
  ["🇲🇪", "montenegro flag", "flags", 0, "montenegro"],
  ["🇲🇫", "st martin (french) flag", "flags", 0, "st_martin"],
  ["🇲🇬", "madagascar flag", "flags", 0, "madagascar"],
  ["🇲🇭", "marshall islands flag", "flags", 0, "marshall_islands"],
  ["🇲🇰", "north macedonia flag", "flags", 0, "macedonia"],
  ["🇲🇱", "mali flag", "flags", 0, "mali"],
  ["🇲🇲", "myanmar (burma) flag", "flags", 0, "myanmar"],
  ["🇲🇳", "mongolia flag", "flags", 0, "mongolia"],
  ["🇲🇴", "macau flag", "flags", 0, "macau"],
  ["🇲🇵", "northern mariana islands flag", "flags", 0, "northern_mariana_islands"],
  ["🇲🇶", "martinique flag", "flags", 0, "martinique"],
  ["🇲🇷", "mauritania flag", "flags", 0, "mauritania"],
  ["🇲🇸", "montserrat flag", "flags", 0, "montserrat"],
  ["🇲🇹", "malta flag", "flags", 0, "malta"],
  ["🇲🇺", "mauritius flag", "flags", 0, "mauritius"],
  ["🇲🇻", "maldives flag", "flags", 0, "maldives"],
  ["🇲🇼", "malawi flag", "flags", 0, "malawi"],
  ["🇲🇽", "mexico flag", "flags", 0, "mexico"],
  ["🇲🇾", "malaysia flag", "flags", 0, "malaysia"],
  ["🇲🇿", "mozambique flag", "flags", 0, "mozambique"],
  ["🇳🇦", "namibia flag", "flags", 0, "namibia"],
  ["🇳🇨", "new caledonia flag", "flags", 0, "new_caledonia"],
  ["🇳🇪", "niger flag", "flags", 0, "niger"],
  ["🇳🇫", "norfolk island flag", "flags", 0, "norfolk_island"],
  ["🇳🇬", "nigeria flag", "flags", 0, "nigeria"],
  ["🇳🇮", "nicaragua flag", "flags", 0, "nicaragua"],
  ["🇳🇱", "netherlands flag", "flags", 0, "netherlands"],
  ["🇳🇴", "norway flag", "flags", 0, "norway"],
  ["🇳🇵", "nepal flag", "flags", 0, "nepal"],
  ["🇳🇷", "nauru flag", "flags", 0, "nauru"],
  ["🇳🇺", "niue flag", "flags", 0, "niue"],
  ["🇳🇿", "new zealand flag", "flags", 0, "new_zealand"],
  ["🇴🇲", "oman flag", "flags", 0, "oman"],
  ["🇵🇦", "panama flag", "flags", 0, "panama"],
  ["🇵🇪", "peru flag", "flags", 0, "peru"],
  ["🇵🇫", "french polynesia flag", "flags", 0, "french_polynesia"],
  ["🇵🇬", "papua new guinea flag", "flags", 0, "papua_new_guinea"],
  ["🇵🇭", "philippines flag", "flags", 0, "philippines"],
  ["🇵🇰", "pakistan flag", "flags", 0, "pakistan"],
  ["🇵🇱", "poland flag", "flags", 0, "poland"],
  ["🇵🇲", "st pierre & miquelon flag", "flags", 0, "st_pierre_miquelon"],
  ["🇵🇳", "pitcairn flag", "flags", 0, "pitcairn_islands"],
  ["🇵🇷", "puerto rico flag", "flags", 0, "puerto_rico"],
  ["🇵🇸", "palestine flag", "flags", 0, "palestinian_territories"],
  ["🇵🇹", "portugal flag", "flags", 0, "portugal"],
  ["🇵🇼", "palau flag", "flags", 0, "palau"],
  ["🇵🇾", "paraguay flag", "flags", 0, "paraguay"],
  ["🇶🇦", "qatar flag", "flags", 0, "qatar"],
  ["🇷🇪", "réunion flag", "flags", 0, "reunion"],
  ["🇷🇴", "romania flag", "flags", 0, "romania"],
  ["🇷🇸", "serbia flag", "flags", 0, "serbia"],
  ["🇷🇺", "russia flag", "flags", 0, "ru"],
  ["🇷🇼", "rwanda flag", "flags", 0, "rwanda"],
  ["🇸🇦", "saudi arabia flag", "flags", 0, "saudi_arabia"],
  ["🇸🇧", "solomon islands flag", "flags", 0, "solomon_islands"],
  ["🇸🇨", "seychelles flag", "flags", 0, "seychelles"],
  ["🇸🇩", "sudan flag", "flags", 0, "sudan"],
  ["🇸🇪", "sweden flag", "flags", 0, "sweden"],
  ["🇸🇬", "singapore flag", "flags", 0, "singapore"],
  ["🇸🇭", "st helena flag", "flags", 0, "st_helena"],
  ["🇸🇮", "slovenia flag", "flags", 0, "slovenia"],
  ["🇸🇯", "svalbard & jan mayen flag", "flags", 0, "svalbard_jan_mayen"],
  ["🇸🇰", "slovakia flag", "flags", 0, "slovakia"],
  ["🇸🇱", "sierra leone flag", "flags", 0, "sierra_leone"],
  ["🇸🇲", "san marino flag", "flags", 0, "san_marino"],
  ["🇸🇳", "senegal flag", "flags", 0, "senegal"],
  ["🇸🇴", "somalia flag", "flags", 0, "somalia"],
  ["🇸🇷", "suriname flag", "flags", 0, "suriname"],
  ["🇸🇸", "south sudan flag", "flags", 0, "south_sudan"],
  ["🇸🇹", "sao tome & principe flag", "flags", 0, "sao_tome_principe"],
  ["🇸🇻", "el salvador flag", "flags", 0, "el_salvador"],
  ["🇸🇽", "st maarten (dutch) flag", "flags", 0, "sint_maarten"],
  ["🇸🇾", "syria flag", "flags", 0, "syria"],
  ["🇸🇿", "eswatini (swaziland) flag", "flags", 0, "swaziland"],
  ["🇹🇨", "turks & caicos is flag", "flags", 0, "turks_caicos_islands"],
  ["🇹🇩", "chad flag", "flags", 0, "chad"],
  ["🇹🇫", "french s. terr. flag", "flags", 0, "french_southern_territories"],
  ["🇹🇬", "togo flag", "flags", 0, "togo"],
  ["🇹🇭", "thailand flag", "flags", 0, "thailand"],
  ["🇹🇯", "tajikistan flag", "flags", 0, "tajikistan"],
  ["🇹🇰", "tokelau flag", "flags", 0, "tokelau"],
  ["🇹🇱", "east timor flag", "flags", 0, "timor_leste"],
  ["🇹🇲", "turkmenistan flag", "flags", 0, "turkmenistan"],
  ["🇹🇳", "tunisia flag", "flags", 0, "tunisia"],
  ["🇹🇴", "tonga flag", "flags", 0, "tonga"],
  ["🇹🇷", "turkey flag", "flags", 0, "tr"],
  ["🇹🇹", "trinidad & tobago flag", "flags", 0, "trinidad_tobago"],
  ["🇹🇻", "tuvalu flag", "flags", 0, "tuvalu"],
  ["🇹🇼", "taiwan flag", "flags", 0, "taiwan"],
  ["🇹🇿", "tanzania flag", "flags", 0, "tanzania"],
  ["🇺🇦", "ukraine flag", "flags", 0, "ukraine"],
  ["🇺🇬", "uganda flag", "flags", 0, "uganda"],
  ["🇺🇲", "us minor outlying islands flag", "flags", 0, "us_outlying_islands"],
  ["🇺🇸", "united states flag", "flags", 0, "us"],
  ["🇺🇾", "uruguay flag", "flags", 0, "uruguay"],
  ["🇺🇿", "uzbekistan flag", "flags", 0, "uzbekistan"],
  ["🇻🇦", "vatican city flag", "flags", 0, "vatican_city"],
  ["🇻🇨", "st vincent flag", "flags", 0, "st_vincent_grenadines"],
  ["🇻🇪", "venezuela flag", "flags", 0, "venezuela"],
  ["🇻🇬", "virgin islands (uk) flag", "flags", 0, "british_virgin_islands"],
  ["🇻🇮", "virgin islands (us) flag", "flags", 0, "us_virgin_islands"],
  ["🇻🇳", "vietnam flag", "flags", 0, "vietnam"],
  ["🇻🇺", "vanuatu flag", "flags", 0, "vanuatu"],
  ["🇼🇫", "wallis & futuna flag", "flags", 0, "wallis_futuna"],
  ["🇼🇸", "samoa (western) flag", "flags", 0, "samoa"],
  ["🇾🇪", "yemen flag", "flags", 0, "yemen"],
  ["🇾🇹", "mayotte flag", "flags", 0, "mayotte"],
  ["🇿🇦", "south africa flag", "flags", 0, "south_africa"],
  ["🇿🇲", "zambia flag", "flags", 0, "zambia"],
  ["🇿🇼", "zimbabwe flag", "flags", 0, "zimbabwe"],
];

export const STANDARD_EMOJI: readonly StandardEmoji[] = EMOJI_ROWS.map(
  ([char, name, category, tonable, shortcodes]): StandardEmoji => ({
    char,
    name,
    category,
    tonable: tonable === 1,
    shortcodes: shortcodes === "" ? [] : shortcodes.split(" "),
  }),
);

/**
 * Apply a skin tone index (0 = none) to an emoji, returning the toned character.
 *
 * The modifier is inserted directly after the first codepoint, which is correct
 * for every base in STANDARD_EMOJI because they are all single-codepoint. It is
 * NOT generally correct for ZWJ sequences (families, professions), where each
 * person component takes its own modifier — this dataset contains none of those,
 * so if ZWJ sequences are ever added this function must be revisited.
 */
export function applySkinTone(emoji: StandardEmoji, toneIndex: number): string {
  if (!emoji.tonable || toneIndex <= 0) {
    return emoji.char;
  }
  const tone = SKIN_TONES[toneIndex];
  if (tone === undefined || tone === "") {
    return emoji.char;
  }
  // Split on codepoints, not UTF-16 units, so the surrogate pair stays intact.
  const codepoints = Array.from(emoji.char);
  const first = codepoints[0];
  if (first === undefined) {
    return emoji.char;
  }
  return first + tone + codepoints.slice(1).join("");
}
