// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pollis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pre-Key / Identity Messages
type RegisterPreKeysRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdentityKey     []byte                 `protobuf:"bytes,2,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`                 // Ed25519 public key
	SignedPreKey    []byte                 `protobuf:"bytes,3,opt,name=signed_pre_key,json=signedPreKey,proto3" json:"signed_pre_key,omitempty"`            // X25519 public key
	SignedPreKeySig []byte                 `protobuf:"bytes,4,opt,name=signed_pre_key_sig,json=signedPreKeySig,proto3" json:"signed_pre_key_sig,omitempty"` // Ed25519 signature over signed_pre_key
	OneTimePreKeys  [][]byte               `protobuf:"bytes,5,rep,name=one_time_pre_keys,json=oneTimePreKeys,proto3" json:"one_time_pre_keys,omitempty"`    // X25519 public keys
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterPreKeysRequest) Reset() {
	*x = RegisterPreKeysRequest{}
	mi := &file_pollis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPreKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPreKeysRequest) ProtoMessage() {}

func (x *RegisterPreKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPreKeysRequest.ProtoReflect.Descriptor instead.
func (*RegisterPreKeysRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterPreKeysRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterPreKeysRequest) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *RegisterPreKeysRequest) GetSignedPreKey() []byte {
	if x != nil {
		return x.SignedPreKey
	}
	return nil
}

func (x *RegisterPreKeysRequest) GetSignedPreKeySig() []byte {
	if x != nil {
		return x.SignedPreKeySig
	}
	return nil
}

func (x *RegisterPreKeysRequest) GetOneTimePreKeys() [][]byte {
	if x != nil {
		return x.OneTimePreKeys
	}
	return nil
}

type RegisterPreKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPreKeysResponse) Reset() {
	*x = RegisterPreKeysResponse{}
	mi := &file_pollis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPreKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPreKeysResponse) ProtoMessage() {}

func (x *RegisterPreKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPreKeysResponse.ProtoReflect.Descriptor instead.
func (*RegisterPreKeysResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPreKeysResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterPreKeysResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPreKeyBundleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserIdentifier string                 `protobuf:"bytes,1,opt,name=user_identifier,json=userIdentifier,proto3" json:"user_identifier,omitempty"` // username/email/phone
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPreKeyBundleRequest) Reset() {
	*x = GetPreKeyBundleRequest{}
	mi := &file_pollis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreKeyBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreKeyBundleRequest) ProtoMessage() {}

func (x *GetPreKeyBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreKeyBundleRequest.ProtoReflect.Descriptor instead.
func (*GetPreKeyBundleRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{2}
}

func (x *GetPreKeyBundleRequest) GetUserIdentifier() string {
	if x != nil {
		return x.UserIdentifier
	}
	return ""
}

type GetPreKeyBundleResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdentityKey     []byte                 `protobuf:"bytes,2,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`                 // Ed25519 public key
	SignedPreKey    []byte                 `protobuf:"bytes,3,opt,name=signed_pre_key,json=signedPreKey,proto3" json:"signed_pre_key,omitempty"`            // X25519 public key
	SignedPreKeySig []byte                 `protobuf:"bytes,4,opt,name=signed_pre_key_sig,json=signedPreKeySig,proto3" json:"signed_pre_key_sig,omitempty"` // Ed25519 signature
	OneTimePreKey   []byte                 `protobuf:"bytes,5,opt,name=one_time_pre_key,json=oneTimePreKey,proto3" json:"one_time_pre_key,omitempty"`       // Optional X25519 public key
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPreKeyBundleResponse) Reset() {
	*x = GetPreKeyBundleResponse{}
	mi := &file_pollis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreKeyBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreKeyBundleResponse) ProtoMessage() {}

func (x *GetPreKeyBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreKeyBundleResponse.ProtoReflect.Descriptor instead.
func (*GetPreKeyBundleResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{3}
}

func (x *GetPreKeyBundleResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPreKeyBundleResponse) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *GetPreKeyBundleResponse) GetSignedPreKey() []byte {
	if x != nil {
		return x.SignedPreKey
	}
	return nil
}

func (x *GetPreKeyBundleResponse) GetSignedPreKeySig() []byte {
	if x != nil {
		return x.SignedPreKeySig
	}
	return nil
}

func (x *GetPreKeyBundleResponse) GetOneTimePreKey() []byte {
	if x != nil {
		return x.OneTimePreKey
	}
	return nil
}

type RotateSignedPreKeyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SignedPreKey    []byte                 `protobuf:"bytes,2,opt,name=signed_pre_key,json=signedPreKey,proto3" json:"signed_pre_key,omitempty"`            // New X25519 public key
	SignedPreKeySig []byte                 `protobuf:"bytes,3,opt,name=signed_pre_key_sig,json=signedPreKeySig,proto3" json:"signed_pre_key_sig,omitempty"` // Ed25519 signature
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RotateSignedPreKeyRequest) Reset() {
	*x = RotateSignedPreKeyRequest{}
	mi := &file_pollis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSignedPreKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSignedPreKeyRequest) ProtoMessage() {}

func (x *RotateSignedPreKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSignedPreKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateSignedPreKeyRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{4}
}

func (x *RotateSignedPreKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RotateSignedPreKeyRequest) GetSignedPreKey() []byte {
	if x != nil {
		return x.SignedPreKey
	}
	return nil
}

func (x *RotateSignedPreKeyRequest) GetSignedPreKeySig() []byte {
	if x != nil {
		return x.SignedPreKeySig
	}
	return nil
}

type RotateSignedPreKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSignedPreKeyResponse) Reset() {
	*x = RotateSignedPreKeyResponse{}
	mi := &file_pollis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSignedPreKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSignedPreKeyResponse) ProtoMessage() {}

func (x *RotateSignedPreKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSignedPreKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateSignedPreKeyResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{5}
}

func (x *RotateSignedPreKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RotateSignedPreKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Sender Key Messages
type GetSenderKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSenderKeyRequest) Reset() {
	*x = GetSenderKeyRequest{}
	mi := &file_pollis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSenderKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSenderKeyRequest) ProtoMessage() {}

func (x *GetSenderKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSenderKeyRequest.ProtoReflect.Descriptor instead.
func (*GetSenderKeyRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{6}
}

func (x *GetSenderKeyRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetSenderKeyRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetSenderKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SenderKey     []byte                 `protobuf:"bytes,2,opt,name=sender_key,json=senderKey,proto3" json:"sender_key,omitempty"` // AES-256 key material
	KeyVersion    int32                  `protobuf:"varint,3,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSenderKeyResponse) Reset() {
	*x = GetSenderKeyResponse{}
	mi := &file_pollis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSenderKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSenderKeyResponse) ProtoMessage() {}

func (x *GetSenderKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSenderKeyResponse.ProtoReflect.Descriptor instead.
func (*GetSenderKeyResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{7}
}

func (x *GetSenderKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSenderKeyResponse) GetSenderKey() []byte {
	if x != nil {
		return x.SenderKey
	}
	return nil
}

func (x *GetSenderKeyResponse) GetKeyVersion() int32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *GetSenderKeyResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DistributeSenderKeyRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	GroupId              string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ChannelId            string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SenderKey            []byte                 `protobuf:"bytes,3,opt,name=sender_key,json=senderKey,proto3" json:"sender_key,omitempty"`
	KeyVersion           int32                  `protobuf:"varint,4,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	RecipientIdentifiers []string               `protobuf:"bytes,5,rep,name=recipient_identifiers,json=recipientIdentifiers,proto3" json:"recipient_identifiers,omitempty"` // usernames/emails/phones
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DistributeSenderKeyRequest) Reset() {
	*x = DistributeSenderKeyRequest{}
	mi := &file_pollis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributeSenderKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributeSenderKeyRequest) ProtoMessage() {}

func (x *DistributeSenderKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributeSenderKeyRequest.ProtoReflect.Descriptor instead.
func (*DistributeSenderKeyRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{8}
}

func (x *DistributeSenderKeyRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *DistributeSenderKeyRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *DistributeSenderKeyRequest) GetSenderKey() []byte {
	if x != nil {
		return x.SenderKey
	}
	return nil
}

func (x *DistributeSenderKeyRequest) GetKeyVersion() int32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *DistributeSenderKeyRequest) GetRecipientIdentifiers() []string {
	if x != nil {
		return x.RecipientIdentifiers
	}
	return nil
}

type DistributeSenderKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributeSenderKeyResponse) Reset() {
	*x = DistributeSenderKeyResponse{}
	mi := &file_pollis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributeSenderKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributeSenderKeyResponse) ProtoMessage() {}

func (x *DistributeSenderKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributeSenderKeyResponse.ProtoReflect.Descriptor instead.
func (*DistributeSenderKeyResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{9}
}

func (x *DistributeSenderKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DistributeSenderKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Key Exchange Messages
type SendKeyExchangeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromUserId       string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserIdentifier string                 `protobuf:"bytes,2,opt,name=to_user_identifier,json=toUserIdentifier,proto3" json:"to_user_identifier,omitempty"`
	MessageType      string                 `protobuf:"bytes,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // 'prekey_bundle', 'key_exchange', etc.
	EncryptedData    []byte                 `protobuf:"bytes,4,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	ExpiresInSeconds int64                  `protobuf:"varint,5,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendKeyExchangeRequest) Reset() {
	*x = SendKeyExchangeRequest{}
	mi := &file_pollis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendKeyExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyExchangeRequest) ProtoMessage() {}

func (x *SendKeyExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyExchangeRequest.ProtoReflect.Descriptor instead.
func (*SendKeyExchangeRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{10}
}

func (x *SendKeyExchangeRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *SendKeyExchangeRequest) GetToUserIdentifier() string {
	if x != nil {
		return x.ToUserIdentifier
	}
	return ""
}

func (x *SendKeyExchangeRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *SendKeyExchangeRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *SendKeyExchangeRequest) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type SendKeyExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendKeyExchangeResponse) Reset() {
	*x = SendKeyExchangeResponse{}
	mi := &file_pollis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendKeyExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyExchangeResponse) ProtoMessage() {}

func (x *SendKeyExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyExchangeResponse.ProtoReflect.Descriptor instead.
func (*SendKeyExchangeResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{11}
}

func (x *SendKeyExchangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendKeyExchangeResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendKeyExchangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetKeyExchangeMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserIdentifier string                 `protobuf:"bytes,1,opt,name=user_identifier,json=userIdentifier,proto3" json:"user_identifier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetKeyExchangeMessagesRequest) Reset() {
	*x = GetKeyExchangeMessagesRequest{}
	mi := &file_pollis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyExchangeMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyExchangeMessagesRequest) ProtoMessage() {}

func (x *GetKeyExchangeMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyExchangeMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetKeyExchangeMessagesRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{12}
}

func (x *GetKeyExchangeMessagesRequest) GetUserIdentifier() string {
	if x != nil {
		return x.UserIdentifier
	}
	return ""
}

type GetKeyExchangeMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*KeyExchangeMessage  `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyExchangeMessagesResponse) Reset() {
	*x = GetKeyExchangeMessagesResponse{}
	mi := &file_pollis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyExchangeMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyExchangeMessagesResponse) ProtoMessage() {}

func (x *GetKeyExchangeMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyExchangeMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetKeyExchangeMessagesResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{13}
}

func (x *GetKeyExchangeMessagesResponse) GetMessages() []*KeyExchangeMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type KeyExchangeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	MessageType   string                 `protobuf:"bytes,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	EncryptedData []byte                 `protobuf:"bytes,4,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyExchangeMessage) Reset() {
	*x = KeyExchangeMessage{}
	mi := &file_pollis_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyExchangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchangeMessage) ProtoMessage() {}

func (x *KeyExchangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchangeMessage.ProtoReflect.Descriptor instead.
func (*KeyExchangeMessage) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{14}
}

func (x *KeyExchangeMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *KeyExchangeMessage) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *KeyExchangeMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *KeyExchangeMessage) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *KeyExchangeMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type MarkKeyExchangeReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageIds    []string               `protobuf:"bytes,1,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkKeyExchangeReadRequest) Reset() {
	*x = MarkKeyExchangeReadRequest{}
	mi := &file_pollis_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkKeyExchangeReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkKeyExchangeReadRequest) ProtoMessage() {}

func (x *MarkKeyExchangeReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkKeyExchangeReadRequest.ProtoReflect.Descriptor instead.
func (*MarkKeyExchangeReadRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{15}
}

func (x *MarkKeyExchangeReadRequest) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type MarkKeyExchangeReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkKeyExchangeReadResponse) Reset() {
	*x = MarkKeyExchangeReadResponse{}
	mi := &file_pollis_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkKeyExchangeReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkKeyExchangeReadResponse) ProtoMessage() {}

func (x *MarkKeyExchangeReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkKeyExchangeReadResponse.ProtoReflect.Descriptor instead.
func (*MarkKeyExchangeReadResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{16}
}

func (x *MarkKeyExchangeReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// WebRTC Signaling Messages
type SendWebRTCSignalRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromUserId       string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId         string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	SignalType       string                 `protobuf:"bytes,3,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"` // 'offer', 'answer', 'ice_candidate'
	SignalData       string                 `protobuf:"bytes,4,opt,name=signal_data,json=signalData,proto3" json:"signal_data,omitempty"` // JSON string
	ExpiresInSeconds int64                  `protobuf:"varint,5,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendWebRTCSignalRequest) Reset() {
	*x = SendWebRTCSignalRequest{}
	mi := &file_pollis_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWebRTCSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWebRTCSignalRequest) ProtoMessage() {}

func (x *SendWebRTCSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWebRTCSignalRequest.ProtoReflect.Descriptor instead.
func (*SendWebRTCSignalRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{17}
}

func (x *SendWebRTCSignalRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *SendWebRTCSignalRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *SendWebRTCSignalRequest) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *SendWebRTCSignalRequest) GetSignalData() string {
	if x != nil {
		return x.SignalData
	}
	return ""
}

func (x *SendWebRTCSignalRequest) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type SendWebRTCSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SignalId      string                 `protobuf:"bytes,2,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWebRTCSignalResponse) Reset() {
	*x = SendWebRTCSignalResponse{}
	mi := &file_pollis_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWebRTCSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWebRTCSignalResponse) ProtoMessage() {}

func (x *SendWebRTCSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWebRTCSignalResponse.ProtoReflect.Descriptor instead.
func (*SendWebRTCSignalResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{18}
}

func (x *SendWebRTCSignalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendWebRTCSignalResponse) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

type GetWebRTCSignalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebRTCSignalsRequest) Reset() {
	*x = GetWebRTCSignalsRequest{}
	mi := &file_pollis_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebRTCSignalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebRTCSignalsRequest) ProtoMessage() {}

func (x *GetWebRTCSignalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebRTCSignalsRequest.ProtoReflect.Descriptor instead.
func (*GetWebRTCSignalsRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{19}
}

func (x *GetWebRTCSignalsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetWebRTCSignalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*WebRTCSignal        `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebRTCSignalsResponse) Reset() {
	*x = GetWebRTCSignalsResponse{}
	mi := &file_pollis_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebRTCSignalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebRTCSignalsResponse) ProtoMessage() {}

func (x *GetWebRTCSignalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebRTCSignalsResponse.ProtoReflect.Descriptor instead.
func (*GetWebRTCSignalsResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{20}
}

func (x *GetWebRTCSignalsResponse) GetSignals() []*WebRTCSignal {
	if x != nil {
		return x.Signals
	}
	return nil
}

type WebRTCSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	SignalType    string                 `protobuf:"bytes,3,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"`
	SignalData    string                 `protobuf:"bytes,4,opt,name=signal_data,json=signalData,proto3" json:"signal_data,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRTCSignal) Reset() {
	*x = WebRTCSignal{}
	mi := &file_pollis_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRTCSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRTCSignal) ProtoMessage() {}

func (x *WebRTCSignal) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRTCSignal.ProtoReflect.Descriptor instead.
func (*WebRTCSignal) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{21}
}

func (x *WebRTCSignal) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *WebRTCSignal) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *WebRTCSignal) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *WebRTCSignal) GetSignalData() string {
	if x != nil {
		return x.SignalData
	}
	return ""
}

func (x *WebRTCSignal) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Key Backup Messages (for recovery with Clerk)
type StoreKeyBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EncryptedKey  []byte                 `protobuf:"bytes,2,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"` // Encrypted with Clerk token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreKeyBackupRequest) Reset() {
	*x = StoreKeyBackupRequest{}
	mi := &file_pollis_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreKeyBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKeyBackupRequest) ProtoMessage() {}

func (x *StoreKeyBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKeyBackupRequest.ProtoReflect.Descriptor instead.
func (*StoreKeyBackupRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{22}
}

func (x *StoreKeyBackupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreKeyBackupRequest) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

type StoreKeyBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreKeyBackupResponse) Reset() {
	*x = StoreKeyBackupResponse{}
	mi := &file_pollis_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreKeyBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKeyBackupResponse) ProtoMessage() {}

func (x *StoreKeyBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKeyBackupResponse.ProtoReflect.Descriptor instead.
func (*StoreKeyBackupResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{23}
}

func (x *StoreKeyBackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreKeyBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetKeyBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyBackupRequest) Reset() {
	*x = GetKeyBackupRequest{}
	mi := &file_pollis_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyBackupRequest) ProtoMessage() {}

func (x *GetKeyBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyBackupRequest.ProtoReflect.Descriptor instead.
func (*GetKeyBackupRequest) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{24}
}

func (x *GetKeyBackupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetKeyBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedKey  []byte                 `protobuf:"bytes,1,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyBackupResponse) Reset() {
	*x = GetKeyBackupResponse{}
	mi := &file_pollis_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyBackupResponse) ProtoMessage() {}

func (x *GetKeyBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollis_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyBackupResponse.ProtoReflect.Descriptor instead.
func (*GetKeyBackupResponse) Descriptor() ([]byte, []int) {
	return file_pollis_proto_rawDescGZIP(), []int{25}
}

func (x *GetKeyBackupResponse) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

var File_pollis_proto protoreflect.FileDescriptor

const file_pollis_proto_rawDesc = "" +
	"\n" +
	"\fpollis.proto\x12\x06pollis\"\xd2\x01\n" +
	"\x16RegisterPreKeysRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fidentity_key\x18\x02 \x01(\fR\videntityKey\x12$\n" +
	"\x0esigned_pre_key\x18\x03 \x01(\fR\fsignedPreKey\x12+\n" +
	"\x12signed_pre_key_sig\x18\x04 \x01(\fR\x0fsignedPreKeySig\x12)\n" +
	"\x11one_time_pre_keys\x18\x05 \x03(\fR\x0eoneTimePreKeys\"M\n" +
	"\x17RegisterPreKeysResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x16GetPreKeyBundleRequest\x12'\n" +
	"\x0fuser_identifier\x18\x01 \x01(\tR\x0euserIdentifier\"\xd1\x01\n" +
	"\x17GetPreKeyBundleResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fidentity_key\x18\x02 \x01(\fR\videntityKey\x12$\n" +
	"\x0esigned_pre_key\x18\x03 \x01(\fR\fsignedPreKey\x12+\n" +
	"\x12signed_pre_key_sig\x18\x04 \x01(\fR\x0fsignedPreKeySig\x12'\n" +
	"\x10one_time_pre_key\x18\x05 \x01(\fR\roneTimePreKey\"\x87\x01\n" +
	"\x19RotateSignedPreKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0esigned_pre_key\x18\x02 \x01(\fR\fsignedPreKey\x12+\n" +
	"\x12signed_pre_key_sig\x18\x03 \x01(\fR\x0fsignedPreKeySig\"P\n" +
	"\x1aRotateSignedPreKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x13GetSenderKeyRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\x8f\x01\n" +
	"\x14GetSenderKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"sender_key\x18\x02 \x01(\fR\tsenderKey\x12\x1f\n" +
	"\vkey_version\x18\x03 \x01(\x05R\n" +
	"keyVersion\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\xcb\x01\n" +
	"\x1aDistributeSenderKeyRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1d\n" +
	"\n" +
	"sender_key\x18\x03 \x01(\fR\tsenderKey\x12\x1f\n" +
	"\vkey_version\x18\x04 \x01(\x05R\n" +
	"keyVersion\x123\n" +
	"\x15recipient_identifiers\x18\x05 \x03(\tR\x14recipientIdentifiers\"Q\n" +
	"\x1bDistributeSenderKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe0\x01\n" +
	"\x16SendKeyExchangeRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12,\n" +
	"\x12to_user_identifier\x18\x02 \x01(\tR\x10toUserIdentifier\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\tR\vmessageType\x12%\n" +
	"\x0eencrypted_data\x18\x04 \x01(\fR\rencryptedData\x12,\n" +
	"\x12expires_in_seconds\x18\x05 \x01(\x03R\x10expiresInSeconds\"l\n" +
	"\x17SendKeyExchangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"H\n" +
	"\x1dGetKeyExchangeMessagesRequest\x12'\n" +
	"\x0fuser_identifier\x18\x01 \x01(\tR\x0euserIdentifier\"X\n" +
	"\x1eGetKeyExchangeMessagesResponse\x126\n" +
	"\bmessages\x18\x01 \x03(\v2\x1a.pollis.KeyExchangeMessageR\bmessages\"\xbe\x01\n" +
	"\x12KeyExchangeMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\tR\vmessageType\x12%\n" +
	"\x0eencrypted_data\x18\x04 \x01(\fR\rencryptedData\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"=\n" +
	"\x1aMarkKeyExchangeReadRequest\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\tR\n" +
	"messageIds\"7\n" +
	"\x1bMarkKeyExchangeReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc9\x01\n" +
	"\x17SendWebRTCSignalRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12\x1f\n" +
	"\vsignal_type\x18\x03 \x01(\tR\n" +
	"signalType\x12\x1f\n" +
	"\vsignal_data\x18\x04 \x01(\tR\n" +
	"signalData\x12,\n" +
	"\x12expires_in_seconds\x18\x05 \x01(\x03R\x10expiresInSeconds\"Q\n" +
	"\x18SendWebRTCSignalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tsignal_id\x18\x02 \x01(\tR\bsignalId\"2\n" +
	"\x17GetWebRTCSignalsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"J\n" +
	"\x18GetWebRTCSignalsResponse\x12.\n" +
	"\asignals\x18\x01 \x03(\v2\x14.pollis.WebRTCSignalR\asignals\"\xae\x01\n" +
	"\fWebRTCSignal\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12\x1f\n" +
	"\vsignal_type\x18\x03 \x01(\tR\n" +
	"signalType\x12\x1f\n" +
	"\vsignal_data\x18\x04 \x01(\tR\n" +
	"signalData\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"U\n" +
	"\x15StoreKeyBackupRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rencrypted_key\x18\x02 \x01(\fR\fencryptedKey\"L\n" +
	"\x16StoreKeyBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x13GetKeyBackupRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x14GetKeyBackupResponse\x12#\n" +
	"\rencrypted_key\x18\x01 \x01(\fR\fencryptedKey2\xa6\b\n" +
	"\rPollisService\x12R\n" +
	"\x0fRegisterPreKeys\x12\x1e.pollis.RegisterPreKeysRequest\x1a\x1f.pollis.RegisterPreKeysResponse\x12R\n" +
	"\x0fGetPreKeyBundle\x12\x1e.pollis.GetPreKeyBundleRequest\x1a\x1f.pollis.GetPreKeyBundleResponse\x12[\n" +
	"\x12RotateSignedPreKey\x12!.pollis.RotateSignedPreKeyRequest\x1a\".pollis.RotateSignedPreKeyResponse\x12I\n" +
	"\fGetSenderKey\x12\x1b.pollis.GetSenderKeyRequest\x1a\x1c.pollis.GetSenderKeyResponse\x12^\n" +
	"\x13DistributeSenderKey\x12\".pollis.DistributeSenderKeyRequest\x1a#.pollis.DistributeSenderKeyResponse\x12R\n" +
	"\x0fSendKeyExchange\x12\x1e.pollis.SendKeyExchangeRequest\x1a\x1f.pollis.SendKeyExchangeResponse\x12g\n" +
	"\x16GetKeyExchangeMessages\x12%.pollis.GetKeyExchangeMessagesRequest\x1a&.pollis.GetKeyExchangeMessagesResponse\x12^\n" +
	"\x13MarkKeyExchangeRead\x12\".pollis.MarkKeyExchangeReadRequest\x1a#.pollis.MarkKeyExchangeReadResponse\x12U\n" +
	"\x10SendWebRTCSignal\x12\x1f.pollis.SendWebRTCSignalRequest\x1a .pollis.SendWebRTCSignalResponse\x12U\n" +
	"\x10GetWebRTCSignals\x12\x1f.pollis.GetWebRTCSignalsRequest\x1a .pollis.GetWebRTCSignalsResponse\x12O\n" +
	"\x0eStoreKeyBackup\x12\x1d.pollis.StoreKeyBackupRequest\x1a\x1e.pollis.StoreKeyBackupResponse\x12I\n" +
	"\fGetKeyBackup\x12\x1b.pollis.GetKeyBackupRequest\x1a\x1c.pollis.GetKeyBackupResponseB\x12Z\x10pollis/pkg/protob\x06proto3"

var (
	file_pollis_proto_rawDescOnce sync.Once
	file_pollis_proto_rawDescData []byte
)

func file_pollis_proto_rawDescGZIP() []byte {
	file_pollis_proto_rawDescOnce.Do(func() {
		file_pollis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pollis_proto_rawDesc), len(file_pollis_proto_rawDesc)))
	})
	return file_pollis_proto_rawDescData
}

var file_pollis_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_pollis_proto_goTypes = []any{
	(*RegisterPreKeysRequest)(nil),         // 0: pollis.RegisterPreKeysRequest
	(*RegisterPreKeysResponse)(nil),        // 1: pollis.RegisterPreKeysResponse
	(*GetPreKeyBundleRequest)(nil),         // 2: pollis.GetPreKeyBundleRequest
	(*GetPreKeyBundleResponse)(nil),        // 3: pollis.GetPreKeyBundleResponse
	(*RotateSignedPreKeyRequest)(nil),      // 4: pollis.RotateSignedPreKeyRequest
	(*RotateSignedPreKeyResponse)(nil),     // 5: pollis.RotateSignedPreKeyResponse
	(*GetSenderKeyRequest)(nil),            // 6: pollis.GetSenderKeyRequest
	(*GetSenderKeyResponse)(nil),           // 7: pollis.GetSenderKeyResponse
	(*DistributeSenderKeyRequest)(nil),     // 8: pollis.DistributeSenderKeyRequest
	(*DistributeSenderKeyResponse)(nil),    // 9: pollis.DistributeSenderKeyResponse
	(*SendKeyExchangeRequest)(nil),         // 10: pollis.SendKeyExchangeRequest
	(*SendKeyExchangeResponse)(nil),        // 11: pollis.SendKeyExchangeResponse
	(*GetKeyExchangeMessagesRequest)(nil),  // 12: pollis.GetKeyExchangeMessagesRequest
	(*GetKeyExchangeMessagesResponse)(nil), // 13: pollis.GetKeyExchangeMessagesResponse
	(*KeyExchangeMessage)(nil),             // 14: pollis.KeyExchangeMessage
	(*MarkKeyExchangeReadRequest)(nil),     // 15: pollis.MarkKeyExchangeReadRequest
	(*MarkKeyExchangeReadResponse)(nil),    // 16: pollis.MarkKeyExchangeReadResponse
	(*SendWebRTCSignalRequest)(nil),        // 17: pollis.SendWebRTCSignalRequest
	(*SendWebRTCSignalResponse)(nil),       // 18: pollis.SendWebRTCSignalResponse
	(*GetWebRTCSignalsRequest)(nil),        // 19: pollis.GetWebRTCSignalsRequest
	(*GetWebRTCSignalsResponse)(nil),       // 20: pollis.GetWebRTCSignalsResponse
	(*WebRTCSignal)(nil),                   // 21: pollis.WebRTCSignal
	(*StoreKeyBackupRequest)(nil),          // 22: pollis.StoreKeyBackupRequest
	(*StoreKeyBackupResponse)(nil),         // 23: pollis.StoreKeyBackupResponse
	(*GetKeyBackupRequest)(nil),            // 24: pollis.GetKeyBackupRequest
	(*GetKeyBackupResponse)(nil),           // 25: pollis.GetKeyBackupResponse
}
var file_pollis_proto_depIdxs = []int32{
	14, // 0: pollis.GetKeyExchangeMessagesResponse.messages:type_name -> pollis.KeyExchangeMessage
	21, // 1: pollis.GetWebRTCSignalsResponse.signals:type_name -> pollis.WebRTCSignal
	0,  // 2: pollis.PollisService.RegisterPreKeys:input_type -> pollis.RegisterPreKeysRequest
	2,  // 3: pollis.PollisService.GetPreKeyBundle:input_type -> pollis.GetPreKeyBundleRequest
	4,  // 4: pollis.PollisService.RotateSignedPreKey:input_type -> pollis.RotateSignedPreKeyRequest
	6,  // 5: pollis.PollisService.GetSenderKey:input_type -> pollis.GetSenderKeyRequest
	8,  // 6: pollis.PollisService.DistributeSenderKey:input_type -> pollis.DistributeSenderKeyRequest
	10, // 7: pollis.PollisService.SendKeyExchange:input_type -> pollis.SendKeyExchangeRequest
	12, // 8: pollis.PollisService.GetKeyExchangeMessages:input_type -> pollis.GetKeyExchangeMessagesRequest
	15, // 9: pollis.PollisService.MarkKeyExchangeRead:input_type -> pollis.MarkKeyExchangeReadRequest
	17, // 10: pollis.PollisService.SendWebRTCSignal:input_type -> pollis.SendWebRTCSignalRequest
	19, // 11: pollis.PollisService.GetWebRTCSignals:input_type -> pollis.GetWebRTCSignalsRequest
	22, // 12: pollis.PollisService.StoreKeyBackup:input_type -> pollis.StoreKeyBackupRequest
	24, // 13: pollis.PollisService.GetKeyBackup:input_type -> pollis.GetKeyBackupRequest
	1,  // 14: pollis.PollisService.RegisterPreKeys:output_type -> pollis.RegisterPreKeysResponse
	3,  // 15: pollis.PollisService.GetPreKeyBundle:output_type -> pollis.GetPreKeyBundleResponse
	5,  // 16: pollis.PollisService.RotateSignedPreKey:output_type -> pollis.RotateSignedPreKeyResponse
	7,  // 17: pollis.PollisService.GetSenderKey:output_type -> pollis.GetSenderKeyResponse
	9,  // 18: pollis.PollisService.DistributeSenderKey:output_type -> pollis.DistributeSenderKeyResponse
	11, // 19: pollis.PollisService.SendKeyExchange:output_type -> pollis.SendKeyExchangeResponse
	13, // 20: pollis.PollisService.GetKeyExchangeMessages:output_type -> pollis.GetKeyExchangeMessagesResponse
	16, // 21: pollis.PollisService.MarkKeyExchangeRead:output_type -> pollis.MarkKeyExchangeReadResponse
	18, // 22: pollis.PollisService.SendWebRTCSignal:output_type -> pollis.SendWebRTCSignalResponse
	20, // 23: pollis.PollisService.GetWebRTCSignals:output_type -> pollis.GetWebRTCSignalsResponse
	23, // 24: pollis.PollisService.StoreKeyBackup:output_type -> pollis.StoreKeyBackupResponse
	25, // 25: pollis.PollisService.GetKeyBackup:output_type -> pollis.GetKeyBackupResponse
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pollis_proto_init() }
func file_pollis_proto_init() {
	if File_pollis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pollis_proto_rawDesc), len(file_pollis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pollis_proto_goTypes,
		DependencyIndexes: file_pollis_proto_depIdxs,
		MessageInfos:      file_pollis_proto_msgTypes,
	}.Build()
	File_pollis_proto = out.File
	file_pollis_proto_goTypes = nil
	file_pollis_proto_depIdxs = nil
}
