// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pollis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PollisService_RegisterPreKeys_FullMethodName        = "/pollis.PollisService/RegisterPreKeys"
	PollisService_GetPreKeyBundle_FullMethodName        = "/pollis.PollisService/GetPreKeyBundle"
	PollisService_RotateSignedPreKey_FullMethodName     = "/pollis.PollisService/RotateSignedPreKey"
	PollisService_GetSenderKey_FullMethodName           = "/pollis.PollisService/GetSenderKey"
	PollisService_DistributeSenderKey_FullMethodName    = "/pollis.PollisService/DistributeSenderKey"
	PollisService_SendKeyExchange_FullMethodName        = "/pollis.PollisService/SendKeyExchange"
	PollisService_GetKeyExchangeMessages_FullMethodName = "/pollis.PollisService/GetKeyExchangeMessages"
	PollisService_MarkKeyExchangeRead_FullMethodName    = "/pollis.PollisService/MarkKeyExchangeRead"
	PollisService_SendWebRTCSignal_FullMethodName       = "/pollis.PollisService/SendWebRTCSignal"
	PollisService_GetWebRTCSignals_FullMethodName       = "/pollis.PollisService/GetWebRTCSignals"
	PollisService_StoreKeyBackup_FullMethodName         = "/pollis.PollisService/StoreKeyBackup"
	PollisService_GetKeyBackup_FullMethodName           = "/pollis.PollisService/GetKeyBackup"
)

// PollisServiceClient is the client API for PollisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PollisServiceClient interface {
	// Pre-Key / Identity - Server coordinates atomic pre-key consumption
	RegisterPreKeys(ctx context.Context, in *RegisterPreKeysRequest, opts ...grpc.CallOption) (*RegisterPreKeysResponse, error)
	GetPreKeyBundle(ctx context.Context, in *GetPreKeyBundleRequest, opts ...grpc.CallOption) (*GetPreKeyBundleResponse, error)
	RotateSignedPreKey(ctx context.Context, in *RotateSignedPreKeyRequest, opts ...grpc.CallOption) (*RotateSignedPreKeyResponse, error)
	// Sender Key Distribution - Server coordinates group channel encryption
	GetSenderKey(ctx context.Context, in *GetSenderKeyRequest, opts ...grpc.CallOption) (*GetSenderKeyResponse, error)
	DistributeSenderKey(ctx context.Context, in *DistributeSenderKeyRequest, opts ...grpc.CallOption) (*DistributeSenderKeyResponse, error)
	// Key Exchange - Server relays encrypted key exchange messages between users
	SendKeyExchange(ctx context.Context, in *SendKeyExchangeRequest, opts ...grpc.CallOption) (*SendKeyExchangeResponse, error)
	GetKeyExchangeMessages(ctx context.Context, in *GetKeyExchangeMessagesRequest, opts ...grpc.CallOption) (*GetKeyExchangeMessagesResponse, error)
	MarkKeyExchangeRead(ctx context.Context, in *MarkKeyExchangeReadRequest, opts ...grpc.CallOption) (*MarkKeyExchangeReadResponse, error)
	// WebRTC Signaling - Server relays signaling for voice/video
	SendWebRTCSignal(ctx context.Context, in *SendWebRTCSignalRequest, opts ...grpc.CallOption) (*SendWebRTCSignalResponse, error)
	GetWebRTCSignals(ctx context.Context, in *GetWebRTCSignalsRequest, opts ...grpc.CallOption) (*GetWebRTCSignalsResponse, error)
	// Key Backup - Server stores encrypted key backups for recovery
	StoreKeyBackup(ctx context.Context, in *StoreKeyBackupRequest, opts ...grpc.CallOption) (*StoreKeyBackupResponse, error)
	GetKeyBackup(ctx context.Context, in *GetKeyBackupRequest, opts ...grpc.CallOption) (*GetKeyBackupResponse, error)
}

type pollisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPollisServiceClient(cc grpc.ClientConnInterface) PollisServiceClient {
	return &pollisServiceClient{cc}
}

func (c *pollisServiceClient) RegisterPreKeys(ctx context.Context, in *RegisterPreKeysRequest, opts ...grpc.CallOption) (*RegisterPreKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPreKeysResponse)
	err := c.cc.Invoke(ctx, PollisService_RegisterPreKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollisServiceClient) GetPreKeyBundle(ctx context.Context, in *GetPreKeyBundleRequest, opts ...grpc.CallOption) (*GetPreKeyBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPreKeyBundleResponse)
	err := c.cc.Invoke(ctx, PollisService_GetPreKeyBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollisServiceClient) RotateSignedPreKey(ctx context.Context, in *RotateSignedPreKeyRequest, opts ...grpc.CallOption) (*RotateSignedPreKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateSignedPreKeyResponse)
	err := c.cc.Invoke(ctx, PollisService_RotateSignedPreKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollisServiceClient) GetSenderKey(ctx context.Context, in *GetSenderKeyRequest, opts ...grpc.CallOption) (*GetSenderKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSenderKeyResponse)
	err := c.cc.Invoke(ctx, PollisService_GetSenderKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollisServiceClient) DistributeSenderKey(ctx context.Context, in *DistributeSenderKeyRequest, opts ...grpc.CallOption) (*DistributeSenderKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DistributeSenderKeyResponse)
	err := c.cc.Invoke(ctx, PollisService_DistributeSenderKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollisServiceClient) SendKeyExchange(ctx context.Context, in *SendKeyExchangeRequest, opts ...grpc.CallOption) (*SendKeyExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendKeyExchangeResponse)
	err := c.cc.Invoke(ctx, PollisService_SendKeyExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollisServiceClient) GetKeyExchangeMessages(ctx context.Context, in *GetKeyExchangeMessagesRequest, opts ...grpc.CallOption) (*GetKeyExchangeMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyExchangeMessagesResponse)
	err := c.cc.Invoke(ctx, PollisService_GetKeyExchangeMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollisServiceClient) MarkKeyExchangeRead(ctx context.Context, in *MarkKeyExchangeReadRequest, opts ...grpc.CallOption) (*MarkKeyExchangeReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkKeyExchangeReadResponse)
	err := c.cc.Invoke(ctx, PollisService_MarkKeyExchangeRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollisServiceClient) SendWebRTCSignal(ctx context.Context, in *SendWebRTCSignalRequest, opts ...grpc.CallOption) (*SendWebRTCSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendWebRTCSignalResponse)
	err := c.cc.Invoke(ctx, PollisService_SendWebRTCSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollisServiceClient) GetWebRTCSignals(ctx context.Context, in *GetWebRTCSignalsRequest, opts ...grpc.CallOption) (*GetWebRTCSignalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebRTCSignalsResponse)
	err := c.cc.Invoke(ctx, PollisService_GetWebRTCSignals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollisServiceClient) StoreKeyBackup(ctx context.Context, in *StoreKeyBackupRequest, opts ...grpc.CallOption) (*StoreKeyBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreKeyBackupResponse)
	err := c.cc.Invoke(ctx, PollisService_StoreKeyBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollisServiceClient) GetKeyBackup(ctx context.Context, in *GetKeyBackupRequest, opts ...grpc.CallOption) (*GetKeyBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyBackupResponse)
	err := c.cc.Invoke(ctx, PollisService_GetKeyBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PollisServiceServer is the server API for PollisService service.
// All implementations must embed UnimplementedPollisServiceServer
// for forward compatibility.
type PollisServiceServer interface {
	// Pre-Key / Identity - Server coordinates atomic pre-key consumption
	RegisterPreKeys(context.Context, *RegisterPreKeysRequest) (*RegisterPreKeysResponse, error)
	GetPreKeyBundle(context.Context, *GetPreKeyBundleRequest) (*GetPreKeyBundleResponse, error)
	RotateSignedPreKey(context.Context, *RotateSignedPreKeyRequest) (*RotateSignedPreKeyResponse, error)
	// Sender Key Distribution - Server coordinates group channel encryption
	GetSenderKey(context.Context, *GetSenderKeyRequest) (*GetSenderKeyResponse, error)
	DistributeSenderKey(context.Context, *DistributeSenderKeyRequest) (*DistributeSenderKeyResponse, error)
	// Key Exchange - Server relays encrypted key exchange messages between users
	SendKeyExchange(context.Context, *SendKeyExchangeRequest) (*SendKeyExchangeResponse, error)
	GetKeyExchangeMessages(context.Context, *GetKeyExchangeMessagesRequest) (*GetKeyExchangeMessagesResponse, error)
	MarkKeyExchangeRead(context.Context, *MarkKeyExchangeReadRequest) (*MarkKeyExchangeReadResponse, error)
	// WebRTC Signaling - Server relays signaling for voice/video
	SendWebRTCSignal(context.Context, *SendWebRTCSignalRequest) (*SendWebRTCSignalResponse, error)
	GetWebRTCSignals(context.Context, *GetWebRTCSignalsRequest) (*GetWebRTCSignalsResponse, error)
	// Key Backup - Server stores encrypted key backups for recovery
	StoreKeyBackup(context.Context, *StoreKeyBackupRequest) (*StoreKeyBackupResponse, error)
	GetKeyBackup(context.Context, *GetKeyBackupRequest) (*GetKeyBackupResponse, error)
	mustEmbedUnimplementedPollisServiceServer()
}

// UnimplementedPollisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPollisServiceServer struct{}

func (UnimplementedPollisServiceServer) RegisterPreKeys(context.Context, *RegisterPreKeysRequest) (*RegisterPreKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPreKeys not implemented")
}
func (UnimplementedPollisServiceServer) GetPreKeyBundle(context.Context, *GetPreKeyBundleRequest) (*GetPreKeyBundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPreKeyBundle not implemented")
}
func (UnimplementedPollisServiceServer) RotateSignedPreKey(context.Context, *RotateSignedPreKeyRequest) (*RotateSignedPreKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateSignedPreKey not implemented")
}
func (UnimplementedPollisServiceServer) GetSenderKey(context.Context, *GetSenderKeyRequest) (*GetSenderKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSenderKey not implemented")
}
func (UnimplementedPollisServiceServer) DistributeSenderKey(context.Context, *DistributeSenderKeyRequest) (*DistributeSenderKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DistributeSenderKey not implemented")
}
func (UnimplementedPollisServiceServer) SendKeyExchange(context.Context, *SendKeyExchangeRequest) (*SendKeyExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendKeyExchange not implemented")
}
func (UnimplementedPollisServiceServer) GetKeyExchangeMessages(context.Context, *GetKeyExchangeMessagesRequest) (*GetKeyExchangeMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeyExchangeMessages not implemented")
}
func (UnimplementedPollisServiceServer) MarkKeyExchangeRead(context.Context, *MarkKeyExchangeReadRequest) (*MarkKeyExchangeReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkKeyExchangeRead not implemented")
}
func (UnimplementedPollisServiceServer) SendWebRTCSignal(context.Context, *SendWebRTCSignalRequest) (*SendWebRTCSignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendWebRTCSignal not implemented")
}
func (UnimplementedPollisServiceServer) GetWebRTCSignals(context.Context, *GetWebRTCSignalsRequest) (*GetWebRTCSignalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebRTCSignals not implemented")
}
func (UnimplementedPollisServiceServer) StoreKeyBackup(context.Context, *StoreKeyBackupRequest) (*StoreKeyBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreKeyBackup not implemented")
}
func (UnimplementedPollisServiceServer) GetKeyBackup(context.Context, *GetKeyBackupRequest) (*GetKeyBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeyBackup not implemented")
}
func (UnimplementedPollisServiceServer) mustEmbedUnimplementedPollisServiceServer() {}
func (UnimplementedPollisServiceServer) testEmbeddedByValue()                       {}

// UnsafePollisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PollisServiceServer will
// result in compilation errors.
type UnsafePollisServiceServer interface {
	mustEmbedUnimplementedPollisServiceServer()
}

func RegisterPollisServiceServer(s grpc.ServiceRegistrar, srv PollisServiceServer) {
	// If the following call panics, it indicates UnimplementedPollisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PollisService_ServiceDesc, srv)
}

func _PollisService_RegisterPreKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPreKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).RegisterPreKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_RegisterPreKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).RegisterPreKeys(ctx, req.(*RegisterPreKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollisService_GetPreKeyBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreKeyBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).GetPreKeyBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_GetPreKeyBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).GetPreKeyBundle(ctx, req.(*GetPreKeyBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollisService_RotateSignedPreKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSignedPreKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).RotateSignedPreKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_RotateSignedPreKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).RotateSignedPreKey(ctx, req.(*RotateSignedPreKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollisService_GetSenderKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSenderKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).GetSenderKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_GetSenderKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).GetSenderKey(ctx, req.(*GetSenderKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollisService_DistributeSenderKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistributeSenderKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).DistributeSenderKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_DistributeSenderKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).DistributeSenderKey(ctx, req.(*DistributeSenderKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollisService_SendKeyExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendKeyExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).SendKeyExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_SendKeyExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).SendKeyExchange(ctx, req.(*SendKeyExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollisService_GetKeyExchangeMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyExchangeMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).GetKeyExchangeMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_GetKeyExchangeMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).GetKeyExchangeMessages(ctx, req.(*GetKeyExchangeMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollisService_MarkKeyExchangeRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkKeyExchangeReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).MarkKeyExchangeRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_MarkKeyExchangeRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).MarkKeyExchangeRead(ctx, req.(*MarkKeyExchangeReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollisService_SendWebRTCSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWebRTCSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).SendWebRTCSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_SendWebRTCSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).SendWebRTCSignal(ctx, req.(*SendWebRTCSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollisService_GetWebRTCSignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebRTCSignalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).GetWebRTCSignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_GetWebRTCSignals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).GetWebRTCSignals(ctx, req.(*GetWebRTCSignalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollisService_StoreKeyBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreKeyBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).StoreKeyBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_StoreKeyBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).StoreKeyBackup(ctx, req.(*StoreKeyBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollisService_GetKeyBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollisServiceServer).GetKeyBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollisService_GetKeyBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollisServiceServer).GetKeyBackup(ctx, req.(*GetKeyBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PollisService_ServiceDesc is the grpc.ServiceDesc for PollisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PollisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pollis.PollisService",
	HandlerType: (*PollisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPreKeys",
			Handler:    _PollisService_RegisterPreKeys_Handler,
		},
		{
			MethodName: "GetPreKeyBundle",
			Handler:    _PollisService_GetPreKeyBundle_Handler,
		},
		{
			MethodName: "RotateSignedPreKey",
			Handler:    _PollisService_RotateSignedPreKey_Handler,
		},
		{
			MethodName: "GetSenderKey",
			Handler:    _PollisService_GetSenderKey_Handler,
		},
		{
			MethodName: "DistributeSenderKey",
			Handler:    _PollisService_DistributeSenderKey_Handler,
		},
		{
			MethodName: "SendKeyExchange",
			Handler:    _PollisService_SendKeyExchange_Handler,
		},
		{
			MethodName: "GetKeyExchangeMessages",
			Handler:    _PollisService_GetKeyExchangeMessages_Handler,
		},
		{
			MethodName: "MarkKeyExchangeRead",
			Handler:    _PollisService_MarkKeyExchangeRead_Handler,
		},
		{
			MethodName: "SendWebRTCSignal",
			Handler:    _PollisService_SendWebRTCSignal_Handler,
		},
		{
			MethodName: "GetWebRTCSignals",
			Handler:    _PollisService_GetWebRTCSignals_Handler,
		},
		{
			MethodName: "StoreKeyBackup",
			Handler:    _PollisService_StoreKeyBackup_Handler,
		},
		{
			MethodName: "GetKeyBackup",
			Handler:    _PollisService_GetKeyBackup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pollis.proto",
}
