// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGroupMember(arg1, arg2) {
  return window['go']['main']['App']['AddGroupMember'](arg1, arg2);
}

export function AuthenticateAndLoadUser(arg1) {
  return window['go']['main']['App']['AuthenticateAndLoadUser'](arg1);
}

export function AuthenticateWithClerk() {
  return window['go']['main']['App']['AuthenticateWithClerk']();
}

export function CancelAuth() {
  return window['go']['main']['App']['CancelAuth']();
}

export function CancelQueuedMessage(arg1) {
  return window['go']['main']['App']['CancelQueuedMessage'](arg1);
}

export function ChannelExistsBySlug(arg1, arg2) {
  return window['go']['main']['App']['ChannelExistsBySlug'](arg1, arg2);
}

export function CheckIdentity() {
  return window['go']['main']['App']['CheckIdentity']();
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function CreateChannel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateChannel'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateGroup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2, arg3, arg4);
}

export function CreateOrGetDMConversation(arg1, arg2) {
  return window['go']['main']['App']['CreateOrGetDMConversation'](arg1, arg2);
}

export function CreateUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetChannel(arg1) {
  return window['go']['main']['App']['GetChannel'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetGroup(arg1) {
  return window['go']['main']['App']['GetGroup'](arg1);
}

export function GetGroupBySlug(arg1) {
  return window['go']['main']['App']['GetGroupBySlug'](arg1);
}

export function GetMessages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2, arg3, arg4);
}

export function GetNetworkStatus() {
  return window['go']['main']['App']['GetNetworkStatus']();
}

export function GetPendingMessages() {
  return window['go']['main']['App']['GetPendingMessages']();
}

export function GetPinnedMessages(arg1, arg2) {
  return window['go']['main']['App']['GetPinnedMessages'](arg1, arg2);
}

export function GetPresignedAvatarUploadURL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPresignedAvatarUploadURL'](arg1, arg2, arg3, arg4);
}

export function GetPresignedFileDownloadURL(arg1) {
  return window['go']['main']['App']['GetPresignedFileDownloadURL'](arg1);
}

export function GetPresignedFileUploadURL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetPresignedFileUploadURL'](arg1, arg2, arg3, arg4, arg5);
}

export function GetServiceUserData() {
  return window['go']['main']['App']['GetServiceUserData']();
}

export function GetStoredSession() {
  return window['go']['main']['App']['GetStoredSession']();
}

export function GetUserByIdentifier(arg1) {
  return window['go']['main']['App']['GetUserByIdentifier'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function GroupExistsBySlug(arg1) {
  return window['go']['main']['App']['GroupExistsBySlug'](arg1);
}

export function IsAblyReady() {
  return window['go']['main']['App']['IsAblyReady']();
}

export function ListChannels(arg1) {
  return window['go']['main']['App']['ListChannels'](arg1);
}

export function ListDMConversations(arg1) {
  return window['go']['main']['App']['ListDMConversations'](arg1);
}

export function ListGroupMembers(arg1) {
  return window['go']['main']['App']['ListGroupMembers'](arg1);
}

export function ListUserGroups(arg1) {
  return window['go']['main']['App']['ListUserGroups'](arg1);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function PinMessage(arg1, arg2) {
  return window['go']['main']['App']['PinMessage'](arg1, arg2);
}

export function ProcessQueue() {
  return window['go']['main']['App']['ProcessQueue']();
}

export function SearchGroup(arg1) {
  return window['go']['main']['App']['SearchGroup'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function SetKillSwitch(arg1) {
  return window['go']['main']['App']['SetKillSwitch'](arg1);
}

export function SetServiceURL(arg1) {
  return window['go']['main']['App']['SetServiceURL'](arg1);
}

export function StoreSession(arg1, arg2) {
  return window['go']['main']['App']['StoreSession'](arg1, arg2);
}

export function SubscribeToChannel(arg1) {
  return window['go']['main']['App']['SubscribeToChannel'](arg1);
}

export function UnpinMessage(arg1) {
  return window['go']['main']['App']['UnpinMessage'](arg1);
}

export function UnsubscribeFromChannel(arg1) {
  return window['go']['main']['App']['UnsubscribeFromChannel'](arg1);
}

export function UpdateGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2, arg3);
}

export function UpdateServiceUserAvatar(arg1) {
  return window['go']['main']['App']['UpdateServiceUserAvatar'](arg1);
}

export function UpdateServiceUserData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateServiceUserData'](arg1, arg2, arg3, arg4);
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}
