// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddGroupMember(arg1:string,arg2:string):Promise<void>;

export function AuthenticateAndLoadUser(arg1:string):Promise<models.User>;

export function AuthenticateWithClerk():Promise<string>;

export function CancelAuth():Promise<void>;

export function CancelQueuedMessage(arg1:string):Promise<void>;

export function ChannelExistsBySlug(arg1:string,arg2:string):Promise<boolean>;

export function CheckIdentity():Promise<boolean>;

export function ClearSession():Promise<void>;

export function CreateChannel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Channel>;

export function CreateGroup(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Group>;

export function CreateOrGetDMConversation(arg1:string,arg2:string):Promise<models.DMConversation>;

export function CreateUser(arg1:string,arg2:string,arg3:string):Promise<models.User>;

export function GetChannel(arg1:string):Promise<models.Channel>;

export function GetCurrentUser():Promise<models.User>;

export function GetGroup(arg1:string):Promise<models.Group>;

export function GetGroupBySlug(arg1:string):Promise<models.Group>;

export function GetMessages(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<models.Message>>;

export function GetNetworkStatus():Promise<string>;

export function GetPendingMessages():Promise<Array<models.MessageQueue>>;

export function GetPinnedMessages(arg1:string,arg2:string):Promise<Array<models.Message>>;

export function GetPresignedAvatarUploadURL(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.PresignedUploadResponse>;

export function GetPresignedFileDownloadURL(arg1:string):Promise<string>;

export function GetPresignedFileUploadURL(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.PresignedUploadResponse>;

export function GetServiceUserData():Promise<Record<string, any>>;

export function GetStoredSession():Promise<Record<string, string>>;

export function GetUserByIdentifier(arg1:string):Promise<models.User>;

export function Greet(arg1:string):Promise<string>;

export function GroupExistsBySlug(arg1:string):Promise<boolean>;

export function IsAblyReady():Promise<boolean>;

export function ListChannels(arg1:string):Promise<Array<models.Channel>>;

export function ListDMConversations(arg1:string):Promise<Array<models.DMConversation>>;

export function ListGroupMembers(arg1:string):Promise<Array<models.GroupMember>>;

export function ListUserGroups(arg1:string):Promise<Array<models.Group>>;

export function Logout(arg1:boolean):Promise<void>;

export function PinMessage(arg1:string,arg2:string):Promise<void>;

export function ProcessQueue():Promise<void>;

export function SearchGroup(arg1:string):Promise<models.Group>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Message>;

export function SetKillSwitch(arg1:boolean):Promise<void>;

export function SetServiceURL(arg1:string):Promise<void>;

export function StoreSession(arg1:string,arg2:string):Promise<void>;

export function SubscribeToChannel(arg1:string):Promise<void>;

export function UnpinMessage(arg1:string):Promise<void>;

export function UnsubscribeFromChannel(arg1:string):Promise<void>;

export function UpdateGroup(arg1:string,arg2:string,arg3:string):Promise<models.Group>;

export function UpdateServiceUserAvatar(arg1:string):Promise<void>;

export function UpdateServiceUserData(arg1:string,arg2:any,arg3:any,arg4:any):Promise<void>;

export function UpdateUser(arg1:models.User):Promise<void>;
