use std::collections::HashMap;
use std::sync::atomic::AtomicBool;
use std::sync::Arc;
use tokio::sync::Mutex;

use crate::config::Config;
use crate::db::{local::LocalDb, remote::RemoteDb};
use crate::keystore::{self, Keystore};
use crate::commands::pin::UnlockState;
use crate::commands::voice::VoiceState;
use crate::commands::voice_test::VoiceTestState;
use crate::realtime::LiveKitState;

#[derive(Clone)]
pub struct OtpEntry {
    pub hash: String,
    pub expires_at: u64,
}

pub struct AppState {
    pub config: Config,
    /// None until a user logs in. Opened per-user as pollis_{user_id}.db.
    pub local_db: Arc<Mutex<Option<LocalDb>>>,
    pub remote_db: Arc<RemoteDb>,
    /// Pluggable secret store. Production wires an [`OsKeystore`]; integration
    /// tests inject an [`InMemoryKeystore`] per simulated client so multiple
    /// users coexist in one test process without sharing session tokens or
    /// account identity keys.
    pub keystore: Arc<dyn Keystore>,
    pub otp_store: Arc<Mutex<HashMap<String, OtpEntry>>>,
    pub livekit: Arc<Mutex<LiveKitState>>,
    pub voice: Arc<Mutex<VoiceState>>,
    pub voice_test: Arc<Mutex<VoiceTestState>>,
    pub update_required: Arc<AtomicBool>,
    /// Per-device ULID, set during login. Each physical device gets a stable ID
    /// stored in the OS keystore so it survives local DB wipes.
    pub device_id: Arc<Mutex<Option<String>>>,
    /// In-memory ephemeral X25519 private keys for pending device-enrollment
    /// requests. Keyed by enrollment request id. Populated by
    /// `start_device_enrollment` and consumed by `poll_enrollment_status`
    /// when the approver has written back the wrapped account key.
    ///
    /// Stored in memory only — if the app restarts mid-enrollment the user
    /// starts over. The 10-minute request TTL bounds the exposure.
    pub enrollment_ephemeral_keys: Arc<Mutex<HashMap<String, Vec<u8>>>>,
    /// In-memory PIN unlock state. `Some` once the user has entered a
    /// valid PIN (or just set one via `set_pin`); dropped by `lock`.
    /// Not yet load-bearing — stage 6 flips the app over to reading the
    /// unwrapped keys from here instead of the legacy keystore slots.
    pub unlock: Arc<Mutex<Option<UnlockState>>>,
}

impl AppState {
    pub async fn new(config: Config) -> crate::error::Result<Self> {
        let remote_db = RemoteDb::connect(&config.turso_url, &config.turso_token).await?;
        Ok(Self::new_with_parts(
            config,
            Arc::new(remote_db),
            keystore::default_os_keystore(),
        ))
    }

    /// Build AppState from pre-constructed parts. Production should use
    /// [`AppState::new`]; tests use this to inject an [`InMemoryKeystore`] and
    /// a RemoteDb pointed at the disposable test Turso.
    pub fn new_with_parts(
        config: Config,
        remote_db: Arc<RemoteDb>,
        keystore: Arc<dyn Keystore>,
    ) -> Self {
        Self {
            config,
            local_db: Arc::new(Mutex::new(None)),
            remote_db,
            keystore,
            otp_store: Arc::new(Mutex::new(HashMap::new())),
            livekit: Arc::new(Mutex::new(LiveKitState::new())),
            voice: Arc::new(Mutex::new(VoiceState::new())),
            voice_test: Arc::new(Mutex::new(VoiceTestState::new())),
            update_required: Arc::new(AtomicBool::new(false)),
            device_id: Arc::new(Mutex::new(None)),
            enrollment_ephemeral_keys: Arc::new(Mutex::new(HashMap::new())),
            unlock: Arc::new(Mutex::new(None)),
        }
    }

    /// Open the per-user database under a caller-supplied DB key.
    ///
    /// Used by `set_pin` (after wrapping freshly generated bytes) and
    /// `unlock` (after unwrapping the PIN-protected blob). Does not touch
    /// the keystore — the caller is responsible for sourcing `db_key`
    /// from `AppState.unlock`. Keeps the `mls_kv` empty-check + welcome-
    /// reset logic so a wiped local DB still recovers group memberships.
    pub async fn load_user_db_with_key(
        &self,
        user_id: &str,
        db_key: &[u8],
    ) -> crate::error::Result<()> {
        let db = LocalDb::open_for_user(user_id, db_key)?;

        // If mls_kv is empty the local DB was freshly created or wiped (e.g. a
        // schema-version bump deleted and recreated the file).  Reset welcome
        // delivery markers so poll_mls_welcomes (called from initialize_identity)
        // will re-process them and restore all MLS group memberships.
        let mls_empty: bool = db.conn()
            .query_row("SELECT COUNT(*) FROM mls_kv", [], |r| r.get::<_, i64>(0))
            .map(|c| c == 0)
            .unwrap_or(true);

        if mls_empty {
            // Load the device_id from keystore (if it exists yet) to scope the
            // reset to THIS device only.  Without scoping, resetting all of a
            // user's welcomes would cause other devices to re-process welcomes
            // and destroy their working MLS group state.
            let maybe_device_id = self.keystore.load_for_user("device_id", user_id).await
                .ok()
                .flatten()
                .and_then(|b| String::from_utf8(b).ok());

            match self.remote_db.conn().await {
                Ok(conn) => {
                    if let Some(ref did) = maybe_device_id {
                        let _ = conn.execute(
                            "UPDATE mls_welcome SET delivered = 0 \
                             WHERE recipient_id = ?1 AND (recipient_device_id = ?2 OR recipient_device_id IS NULL)",
                            libsql::params![user_id, did.clone()],
                        ).await;
                    } else {
                        // First login ever (no device_id yet) — safe to reset all
                        // since no other device can exist for this user yet.
                        let _ = conn.execute(
                            "UPDATE mls_welcome SET delivered = 0 WHERE recipient_id = ?1",
                            libsql::params![user_id],
                        ).await;
                    }
                }
                Err(e) => {
                    eprintln!("[state] load_user_db: failed to reset mls_welcome (non-fatal): {e}");
                }
            }
        }

        *self.local_db.lock().await = Some(db);
        Ok(())
    }

    /// Close the current user's database (called on logout).
    pub async fn unload_user_db(&self) {
        *self.local_db.lock().await = None;
    }

    pub fn check_not_outdated(&self) -> crate::error::Result<()> {
        if self.update_required.load(std::sync::atomic::Ordering::Relaxed) {
            return Err(crate::error::Error::ClientOutdated);
        }
        Ok(())
    }
}
